### ISSUE TITLE
Link para a central de ventiladores está incorreto

### ISSUE THREAD

**Issue by ItaloRod** [EscolaDeSaudePublica/isus-app#1]
verificar com o Uirá qual o link correto e corrigir no Aplicativo
link atual:
https://gestao-ventiladores.dev.org.br/
link candidato:
https://coronavirus.ceara.gov.br/centraldeventiladores/

- [x] Testado no Android
- [x] Testado no iOS

**Comment by camilaccolares** [comment]
O link correto é https://coronavirus.ceara.gov.br/centraldeventiladores/

**Comment by ItaloRod** [comment]
O link foi testado em ambas as plataformas
