### ISSUE TITLE
Anexar imagem ao feedback

### ISSUE THREAD

**Issue by caetanooliveira** [EscolaDeSaudePublica/isus-app#100]
Objetivo:
Permitir usuário anexar imagem ao Feedback

Contexto:
No menu de sugestões e suporte o usuário hoje só tem três campos: email, tipo e texto. Devemos adicionar a opção de anexar imagem. Esse campo não é obrigatório.

Escopo: 
    - Manter 3 campos antigos como obrigatório
    - Adicionar campo de upload de imagem
    - Anexar imagem ao email enviado 
Nota:
Ver telas no figma
Corrigir um erro de texto na tela em que se pede para "espeficar" seu feedback.

Fora de Escopo:
- Anexar imagem

Alcance:
Sistemas: Android e IOS
Menus de Feedback

Critério de Aceite:

Dado que o usuário preencheu tipo, email e texto
Quando ele clica botão enviar
Feedback é enviado com sucesso à ESP

Dado que o usuário está na tela de feedback
Quando clica no adicionar imagem
O app pede permissão de acesso à galeria
E abre sua galeria de fotos

Dado que o usuário não preencheu tipo, email ou texto
Quando ele clica botão enviar
Surge a snackbar explicando que falta algum campo obrigatório  Dado que o usuário preencheu tipo, email, texto e imagem
Quando ele clica botão enviar
Feedback é enviado com sucesso à ESP

Dado que abro a caixa de entrada da ESP
Quando o feedback tem imagem
Posso fazer download e abri-la.

**Comment by matheuscpl** [comment]
**Interface e comportamento**
Um text button adicionado abaixo da caixa de texto acionará a galeria de fotos. A imagem, após selecionada, será exibida com seu nome de arquivo em um chip, onde o mesmo permite retirar a imagem escolhida através do clique no 'x'.

![Screenshot_70](https://user-images.githubusercontent.com/64148308/83549256-6a833c00-a4db-11ea-903d-45c86e044507.png)
