### ISSUE TITLE
Ajustar banner de Manejo Clínico na Home

### ISSUE THREAD

**Issue by matheuscpl** [EscolaDeSaudePublica/isus-app#103]
**Objetivo:**
Ajustar banner de Manejo Clínico na Home

**Contexto:**
Alterações no layout da Home do app trouxeram complicações para o banner de manejo clínico:
![photo5062485318120351831](https://user-images.githubusercontent.com/64148308/82692222-b27da580-9c35-11ea-9f87-f8146534c9d8.jpg)

**Escopo:**
A solução do problema está a ser decidida, mas pode ser abordada de 03 formas:
- Deixa o tamanho dos boxes flexível
- Transformar banner em imagem PNG redimensinável
- Implementar diferentes tamanhos no reactnative

**Nota:**
Caso seja decidido o uso do banner em PNG, eis as imagens na pasta: 
https://drive.google.com/open?id=1gtgt5WTey5clSyDYYMlHyQJwJBbsgSsb

**Comment by ItaloRod** [comment]
coloquei a altura do box flexível. Eis os resultados de como se comportou nos celulares:
Pixel 2
![Screenshot_1590169815](https://user-images.githubusercontent.com/20058085/82695974-7f8ae000-9c3c-11ea-8559-b08f4c031aa4.png)
Nexus One (O celular de menor resolução que eu encontrei)
![Screenshot_1590169802](https://user-images.githubusercontent.com/20058085/82695920-641fd500-9c3c-11ea-9190-599cdf2af695.png)
