### ISSUE TITLE
Criar paginação para busca

### ISSUE THREAD

**Issue by Junior-Shyko** [EscolaDeSaudePublica/isus-app#109]
**Objetivo**
Criar paginação para exibição de lista de resultados

**Contexto**
As listas de resultados exibem um limite de 10 resultados por pesquisa atualmente, limitando o controle do usuário.

**Escopo**
Incluir paginação para exibir todos os resultados de uma determinada lista
Tipo: scroll infinito

**Alcance**
Sistemas: Android e IOS
‘Busca’ e ‘Alertas’

**Critérios**
Dado que eu realize scroll vertical em uma lista de resultados
Ao chegar no fim dos 10 resultados
São carregados e exibidos novos 10 (ou o restante) resultados

**Comment by matheuscpl** [comment]
No momento não vejo necessidade de paginação Junin, podemos adotar o scroll infinito, já é um comportamento comum pra visualização de resultado de busca em apps como Facebook, Google, Instagram, Twitter...

**Comment by Junior-Shyko** [comment]
Pois é, isso mesmo. O Scroll infinito é uma paginação. Era essa mesmo que eu estava me referindo. :)

**Comment by matheuscpl** [comment]
Ahh entendi, estávamos falando a msm coisa então haha

**Comment by Junior-Shyko** [comment]
Iniciado e desenvolvendo para usar no atributo **onEndReached** do FlastList
