### ISSUE TITLE
Conteúdo vindo da API com código DIVI

### ISSUE THREAD

**Issue by uira** [EscolaDeSaudePublica/isus-app#110]
## Contexto
O wordpress do coronavirus.ceara.gov.br está utilizando o [Divi Buider](https://www.elegantthemes.com/documentation/developers/) para sua construção e criação de algumas páginas de conteúdo específicas.

O Divi utiliza "_code snippets_" do WP pra montar o layout, e no banco de dados ficam gravados esses snipets, e não o código HTML.

## Problema
Na nossa abordagem atual, a API do iSUS está indo buscar o conteúdo do item no banco de dados do WP, e está trazendo os snippets, que não são renderizados pelo APP:
![image](https://user-images.githubusercontent.com/89998/82817485-76d01f00-9e73-11ea-8b54-bb320de70800.png)

## Solução
- [ ] Fazer verificação e retirar Divi das páginas publicadas pela API
- [ ] Criar condição na API, para identificar quando a página for do tipo Divi Builder, e assim fazer com que no APP ela seja aberta como webview, e não como componente de conteúdo vindo da API.
- [ ] Trazer pra API o HTML já renderizado pelo WP/Divi

**Comment by jacsonp** [comment]
os shortcodes do WordPress precisam de parse antes de serem exibidos, isso vai rolar com os builders que os usam e um série de plugin. é possivel puxar da api do wordpress, onde tem o content.redered, que já vem como html completo, basta passar o id do post. É possível?
