### ISSUE TITLE
Atualizar conteúdo do Manejo Clínico

### ISSUE THREAD

**Issue by matheuscpl** [EscolaDeSaudePublica/isus-app#112]
**Objetivo:**
Ajustar texto e botões do Manejo Clínico de acordo com as atualização

**Contexto:**
Novas regras foram implantadas no Manejo e devem ser atualizadas no app, seguindo as informações abaixo.

**Página inicial**
O que muda: Texto abaixo do título, label dos botões e texto abaixo dos botões;
Link do botão "confira orientações de paramentação" muda para https://coronavirus.ceara.gov.br/profissional/medidas-de-protecao/
![Screenshot_55](https://user-images.githubusercontent.com/64148308/82900210-90846b80-9f32-11ea-8a3a-a9df55b86616.png)

**Card Estágio 01**
O que muda: Título e subtítulo do card.
![Screenshot_57](https://user-images.githubusercontent.com/64148308/82900620-320bbd00-9f33-11ea-9402-6a7710ae3d02.png)

**Estágio 01**
O que muda:  A ilustração de termômetro PNG deve ser retirada e substituída pelo texto atual, assim como os outros estágios; Os kinks no fim do estágio viram botões; O Título muda.
![Screenshot_56](https://user-images.githubusercontent.com/64148308/82900510-0b4d8680-9f33-11ea-85e8-dd8f2f59945a.png)

**Estágio 02**
O que muda: Todo o texto deve ser retirado e substituído pelo atual.
![Screenshot_58](https://user-images.githubusercontent.com/64148308/82900747-5ebfd480-9f33-11ea-9ccd-a6baef8fb408.png)

Para acesso aos textos completos, visualizar no protótipo: https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/mockup?node-id=0%3A1

**Comment by matheuscpl** [comment]
**Estágio 03**
Alterações no texto e links 
![Screenshot_59](https://user-images.githubusercontent.com/64148308/82941436-b9c1ed80-9f6c-11ea-910d-ec5382d6fa2b.png)

**Comment by matheuscpl** [comment]
**Atualização**
Substituir banner no início do manejo clínico por nova imagem:
[bannerEPI.zip](https://github.com/EscolaDeSaudePublica/isus-app/files/4697927/bannerEPI.zip)

![Screenshot_61](https://user-images.githubusercontent.com/64148308/83187637-da24b000-a104-11ea-9ba8-68268f6ea013.png)

**Comment by matheuscpl** [comment]
- [ ] Atualizar link do utilmo 'conforme o protocolo' no Estágio 03 para https://www.google.com/url?q=https://coronavirus.ceara.gov.br/project/nota-tecnica-esclarece-sobre-usos-da-de-hidroxicloroquina-e-cloroquina-em-pacientes-hospitalizados/&sa=D&ust=1590515770584000&usg=AFQjCNGJuLDPHT4exXQ47IMfNZl2dooN1w

Repositório de links: https://docs.google.com/spreadsheets/d/1CqqiVEWH-YchqFSTlx3NN5zG7RBpvPRUkGo_CCyLThw/edit#gid=1390311126

**Comment by matheuscpl** [comment]
- [ ] Atualizar ilustração do Estágio 01
![Screenshot_65](https://user-images.githubusercontent.com/64148308/83297236-96937a00-a1c8-11ea-88fe-518b26a2053d.png)

**Comment by ItaloRod** [comment]
> 
> 
>     * [x]  Atualizar link do utilmo 'conforme o protocolo' no Estágio 03 para https://www.google.com/url?q=https://coronavirus.ceara.gov.br/project/nota-tecnica-esclarece-sobre-usos-da-de-hidroxicloroquina-e-cloroquina-em-pacientes-hospitalizados/&sa=D&ust=1590515770584000&usg=AFQjCNGJuLDPHT4exXQ47IMfNZl2dooN1w
> 
> 
> Repositório de links: https://docs.google.com/spreadsheets/d/1CqqiVEWH-YchqFSTlx3NN5zG7RBpvPRUkGo_CCyLThw/edit#gid=1390311126

Alterado, porém os links restantes do estágio 03.

**Comment by ItaloRod** [comment]
> 
> 
>     * [x]  Atualizar ilustração do Estágio 01
>       ![Screenshot_65](https://user-images.githubusercontent.com/64148308/83297236-96937a00-a1c8-11ea-88fe-518b26a2053d.png)

Alterado e está conforme o protótipo do figma

**Comment by ItaloRod** [comment]
> 
> 
> **Atualização**
> Substituir banner no início do manejo clínico por nova imagem:
> [bannerEPI.zip](https://github.com/EscolaDeSaudePublica/isus-app/files/4697927/bannerEPI.zip)
> 
> ![Screenshot_61](https://user-images.githubusercontent.com/64148308/83187637-da24b000-a104-11ea-9ba8-68268f6ea013.png)

substituida conforme o protótipo
