### ISSUE TITLE
Ajustar tela do Manejo Clínico

### ISSUE THREAD

**Issue by matheuscpl** [EscolaDeSaudePublica/isus-app#123]
**Objetivo**
Consertar os cortes visuais de conteúdo que estão acontecendo na tela do Manejo

**Contexto**
O banner de paramentação aparece incompleto:
![WhatsApp Image 2020-05-31 at 17 13 38](https://user-images.githubusercontent.com/64148308/83361862-eefe7f00-a362-11ea-878b-93eb23645786.jpeg)

Os cards aparecem incompletos nas bordas, perdendo o efeito de sombra:
![WhatsApp Image 2020-05-31 at 17 13 38 (1)](https://user-images.githubusercontent.com/64148308/83361863-f160d900-a362-11ea-8226-d26c01dd6860.jpeg)

**Escopo**
- [x] O banner de paramentação deve aparecer por completo em qualquer resolução de tela.

- [x] Os cards e suas propriedades de estilo devem aparecer por completo em qualquer resolução de tela.

**Comment by ItaloRod** [comment]
> **Objetivo**
> Consertar os cortes visuais de conteúdo que estão acontecendo na tela do Manejo
> 
> **Contexto**
> O banner de paramentação aparece incompleto:
> ![WhatsApp Image 2020-05-31 at 17 13 38](https://user-images.githubusercontent.com/64148308/83361862-eefe7f00-a362-11ea-878b-93eb23645786.jpeg)
> 
> Os cards aparecem incompletos nas bordas, perdendo o efeito de sombra:
> ![WhatsApp Image 2020-05-31 at 17 13 38 (1)](https://user-images.githubusercontent.com/64148308/83361863-f160d900-a362-11ea-8226-d26c01dd6860.jpeg)
> 
> **Escopo**
> 
>     * [x]  O banner de paramentação deve aparecer por completo em qualquer resolução de tela.
> 
>     * [x]  Os cards e suas propriedades de estilo devem aparecer por completo em qualquer resolução de tela.

Resolução de 4.7"
![Screenshot_1590961022](https://user-images.githubusercontent.com/20058085/83363198-e1022b80-a36d-11ea-9beb-b85eb7506e72.png)
![Screenshot_1590961027](https://user-images.githubusercontent.com/20058085/83363200-e2335880-a36d-11ea-9646-4e3fc1f10eec.png)

resolução de 6.2

![photo_2020-05-31_18-39-42](https://user-images.githubusercontent.com/20058085/83363236-24f53080-a36e-11ea-9aa2-9f4468080616.jpg)
![photo_2020-05-31_18-39-54](https://user-images.githubusercontent.com/20058085/83363237-258dc700-a36e-11ea-832e-7fbf2390afe0.jpg)

**Comment by wforte88** [comment]
@ItaloRod 
Atualizar link em Estágio 03 > A prescrição rotineira (...) não é recomendada, **conforme protocolo** para:

https://coronavirus.ceara.gov.br/project/nota-tecnica-esclarece-sobre-usos-da-de-hidroxicloroquina-e-cloroquina-em-pacientes-hospitalizados/

![Estagio_03](https://user-images.githubusercontent.com/21333612/83365950-70193e80-a382-11ea-8dc5-1c212bf9d5d5.jpg)
