### ISSUE TITLE
Ajuste de links no Manejo Clínico

### ISSUE THREAD

**Issue by wforte88** [EscolaDeSaudePublica/isus-app#124]
**Estágio 02 > Critérios de internação**
- [x] Retirar link de "Marcadores laboratoriais prognósticos alterados associados à piora clínica". O texto segue no app, apenas sem o link.

**Estágio 02 > Notas técnicas para o manejo ambulatorial**
- [x] Inserir link no próprio título "Notas técnicas para o manejo ambulatorial":
https://coronavirus.ceara.gov.br/project/nt-tratamento-farmaco-amb/
- [x] Aplicar neste link a mesma cor (#87BA25) dos demais links do Estágio 02.

**Comment by ItaloRod** [comment]
>     * #87BA25
Retirado o link de marcadores laboratoriais e colocado o notas técnicas na cor informada.
![image](https://user-images.githubusercontent.com/20058085/83367604-c8a10980-a38b-11ea-9372-9861f7508afc.png)
