### ISSUE TITLE
Alterar ícone de educação

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/isus-app#13]

**Comment by rodrigoplimafreire** [comment]
Qual é o ícone que deve ser? Você tem alguma sugestão?

**Comment by ItaloRod** [comment]
@rodrigoplimafreire  deixa eu te contextualizar:
Acontece que no menu de baixo  o ícone de educação está com o ícone antigo
![image_2020-05-04_16-32-07](https://user-images.githubusercontent.com/20058085/81006390-d499ba00-8e25-11ea-97fa-e4485796e2d5.png)
Gostaria de saber se continua esse ou o chapéu.
![image_2020-05-04_16-32-39](https://user-images.githubusercontent.com/20058085/81006501-090d7600-8e26-11ea-9171-0e112391b27d.png)
