### ISSUE TITLE
Mostrar versão do App na Interface

### ISSUE THREAD

**Issue by uira** [EscolaDeSaudePublica/isus-app#135]
Pode ser no rodapé do Menu Lateral?

**Comment by caetanooliveira** [comment]
Objetivo:
Informar ao usuário versão e última atualização do app 

Contexto:
Hoje em dia um usuário não consegue acessar quando foi atualizado o aplicativo de forma direta. Esse card contempla implementar a visualização do versionamento do app nos menus iniciais.

Nota:
o versionamento contempla: versao/data/hora
ver figma (@matheuscpl incluir aqui)

AC:
Dado que foi publicada uma nova versao na loja apple
Quando abro o app
Encontro o mesmo versionamento que vejo na loja
