### ISSUE TITLE
Atualizar texto do Sobre

### ISSUE THREAD

**Issue by uira** [EscolaDeSaudePublica/isus-app#136]
Atualizar de acordo com a [Narrativa do Projeto](https://docs.google.com/document/d/18PdSmaQUChULPDODuU_XmutTJjRQb_Towz_5ob_26jc/edit#)

- [x] Melhorar layout da página: logo e slogan em cima, titulos de sesões, links no texto e tamanhos maiores de imagem das logos)

- [x] Implementar

**Comment by matheuscpl** [comment]
Seguir layou do Figma https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/mockup?node-id=1333%3A35122

Links necessários: https://docs.google.com/spreadsheets/d/1CqqiVEWH-YchqFSTlx3NN5zG7RBpvPRUkGo_CCyLThw/edit#gid=618587046

![Sobre](https://user-images.githubusercontent.com/64148308/83647119-edaf9b00-a58a-11ea-8111-f7bebfd12aa9.png)

**Comment by uira** [comment]
@matheuscpl @ClarisCaval por favor, faz uma verificação ortográfica só pra ver se não deixamos passar nada?

**Comment by uira** [comment]
@uira Já achei um erro no texto, mas tô esperando a validação do pessoal da TW pra gente avançar.
