### ISSUE TITLE
Pop-up de Avaliação e Feedback do app na loja

### ISSUE THREAD

**Issue by uira** [EscolaDeSaudePublica/isus-app#137]
### **Objetivo**
**Eu como** pessoa responsável pela evolução do produto
**gostaria que** o app solicitasse para a usuária que ela realizasse avaliação e feedback do app na loja após algum tempo de uso 
**para que** eu consiga avaliar e obter uma métrica de nível de satisfação que nosso app está tendo com seu público alvo para me auxiliar a identificar evoluções possíveis para o iSUS

### **Contexto**
As medidas de avaliação e feedback que os usuários costumam realizar nas lojas de aplicativos fornecem dados valiosos para que possamos ter conhecimento do que está faltando no app e que precisa ser melhorado e evoluído. Com base nisso, surge a necessidade de implementarmos um lembrete para que nossa usuária realize a avaliação de nosso app nas lojas. 

### **Pendências**
- [x] Definir os gatilhos para que a mensagem seja disparada para a usuária realizar a avaliação - 5 dias de uso
- [x] A mensagem solicitando avaliação deve aparecer independente se a pessoa já fez a avaliação na loja ou não? - Se já fez não precisa, ver como filtrar isso
- [x] Se a usuária não quiser realizar a avaliação no momento da mensagem, daremos a opção de lembra-la mais tarde ou depois? Se sim, quanto tempo depois? - Três opções: sim, não, depois, não desejo jamais

### **UX**
- [x] Criar modal/popup que aparece no app solicitando avaliação do app na loja após 5 dias desde o download do iSUS
- [x] Criar opções de resposta da usuária para o modal de: Sim, Agora não, Não perturbe com essa mensagem novamente

### **Escopo**
- Implementar função que solicita feedback do app para a usuária após 5 dias desde o download do iSUS
- Implementar tela modal/popup solicitando o feedback 
- Ao clicar para prosseguir para o feedback, direcionar a usuária para a avaliação do app na loja de aplicativos conforme o dispositivo que ela estiver utilizando
- Ao clicar em Agora não, registrar que a solicitação de feedback deve aparecer para a usuária novamente em 10 dias
- Ao clicar para Não perturbe novamente, registrar que a solicitação de avaliação não deve aparecer novamente para a usuária em questão

### **Critérios de Aceitação**
- Solicitação de feedback para usuária Android
**Dado** que estou utilizando o app
**Quando** atingir um tempo de utilização de 5 dias
**Então** devo receber uma mensagem para avaliar o aplicativo na loja 

- Solicitação de feedback para usuária iOS
**Dado** que estou utilizando o app
**Quando** atingir um tempo de utilização de 5 dias
**Então** devo receber uma mensagem para avaliar o aplicativo na loja 

- Prosseguir para feedback Android
**Dado** que recebi a mensagem solicitando feedback para a loja
**Quando** eu clicar para prosseguir com a avaliação 
**Então** serei direcionada para a loja já no app iSUS para realizar a avaliação 

- Prosseguir para feedback iOS
**Dado** que recebi a mensagem solicitando feedback para a loja
**Quando** eu clicar para prosseguir com a avaliação 
**Então** serei direcionada para a loja já no app iSUS para realizar a avaliação 

- Escolher não realizar feedback Android
**Dado** que recebi a mensagem solicitando feedback para a loja
**Quando** eu optar por não realizar a avaliação agora
**Então** a mensagem deve ser removida do meu campo de visão e deve aparecer novamente em 10 dias

- Escolher não realizar feedback iOS
**Dado** que recebi a mensagem solicitando feedback para a loja
**Quando** eu optar por não realizar a avaliação agora 
**Então** a mensagem deve ser removida do meu campo de visão e deve aparecer novamente em 10 dias

- Escolher não realizar feedback Android
**Dado** que recebi a mensagem solicitando feedback para a loja
**Quando** eu optar por não perturbe novamente
**Então** a mensagem deve ser removida do meu campo de visão e a solicitação de avaliação não deve aparecer novamente

- Escolher não realizar feedback iOS
**Dado** que recebi a mensagem solicitando feedback para a loja
**Quando** eu optar por não perturbe novamente
**Então** a mensagem deve ser removida do meu campo de visão e a solicitação de avaliação não deve aparecer novamente

### **Observações**

_Sugestão de gatilhos: após realizar um quiz e o download de X conteúdos para offline_
Isso a gente vai pensar no futuro por experiências, tipo realização do cadastro

**Comment by caetanooliveira** [comment]
https://github.com/pankod/react-native-store-rating

**Comment by kurjes** [comment]
Priorizar com @uira

**Comment by MayaraMonte** [comment]
Protótipo atualizado: https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/?node-id=5417%3A0

**Comment by ericsonmoreira** [comment]
Devido ao tempo em que essa tarefa está como não priorizada, faz-se necessário uma nova pesquisa de libs para serem usadas. Vimos que a lib sugerida está a muito tempo desatualizada e ainda está usando o paradigma de orientação a objetos e não o funcional (o que é mais recomendado atualmente).

**Comment by ericsonmoreira** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/iSUS---Refinamento-61672dbc32f1ce0015aa7eca/issues/EscolaDeSaudePublica/isus-app/137?planning-poker) with ZenHub @fpontef @Laysacunha
