### ISSUE TITLE
Bug - Aplicativo não abre (ícone não aparece)

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/isus-app#145]

**Comment by ItaloRod** [comment]
correção referente a issue #88

**Comment by ItaloRod** [comment]
Conseguimos resolver o código. Separamos em dois intent-filter e colocamos o launchMode como SingleTask. Testamos e está funcionando normalmente tanto as notificações como também o aplicativo. sem nenhum problema ao abri-lo
