### ISSUE TITLE
Ajustes no Manejo Clínico

### ISSUE THREAD

**Issue by matheuscpl** [EscolaDeSaudePublica/isus-app#155]
**Contexto**

- [x] Substituir os links do Estágio 02, conforme a planilha https://docs.google.com/spreadsheets/d/1CqqiVEWH-YchqFSTlx3NN5zG7RBpvPRUkGo_CCyLThw/edit#gid=1390311126

- [x] Trocar "SaO₂" por "SpO₂", apontado na imagem abaixo

- [x] Adicionar link no texto marcado na imagem abaixo 

![Screenshot_71](https://user-images.githubusercontent.com/64148308/84200636-88254800-aa7d-11ea-94f8-85e48eb6e8cc.png)

**Comment by uira** [comment]
@matheuscpl URGENTE
