### ISSUE TITLE
Adicionar Descrição de uso para as permissões do iOS

### ISSUE THREAD

**Issue by ItaloRod** [EscolaDeSaudePublica/isus-app#159]
A versão 3.1.0 foi rejeitada até na AppleStoreConnect devido a ausência de certos elementos que compõe as permissões de acesso dentro do iOS

ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a **NSPhotoLibraryUsageDescription** key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy). 

 ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a **NSLocationAlwaysUsageDescription** key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a **NSLocationWhenInUseUsageDescription** key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

**Comment by matheusbernardes19** [comment]
A key NSPhotoLibraryUsageDescription tem relação com a issue #100 então coloquei uma mensagem que faça sentido pro usuário quando pedir permissão. Porém não sei bem como o acesso à localização é usado dentro do app, então deixei uma mensagem padrão pra quando o app pedir permissão de uso.
