### ISSUE TITLE
Aumentar tempo de exibição da splash screen

### ISSUE THREAD

**Issue by camilaccolares** [EscolaDeSaudePublica/isus-app#16]
Splash screen aparece muito rápido na hora do carregamento do app. Mal dá pra ver. Acrescentar algum tipo de delay?

**Comment by ItaloRod** [comment]
Verifiquei com o Carlo Irano a viabilidade do tempo de exibição da Splash screen. Ele me informou que não há uma opção para poder aumentar a exibição e a velocidade de exibição está relacionada com a carga dos elementos do aplicativo.

**Comment by uira** [comment]
Entendido. Então, é a velha máxima: "não é um bug, é uma feature"

Existe outra demanda para incluir atividades na abertura do app, que podem impactar nessa experiência, mas por ora estou fechando essa issue.

https://github.com/EscolaDeSaudePublica/isus-app/issues/99
