### ISSUE TITLE
Ajustes no Manejo Clínico

### ISSUE THREAD

**Issue by matheuscpl** [EscolaDeSaudePublica/isus-app#165]
**Objetivo**
Correções de texto no Estágio 02 do Manejo

**Escopo**
- [x] "PaO2/FiO2" para "PaO₂/FIO₂"

- [x] separar "corticoide + azitromicinaeoseltamivir" em "corticoide + azitromicina e oseltamivir"

- [x] Adicionar o link em 'oseltamivir', conforme o link https://docs.google.com/spreadsheets/d/1CqqiVEWH-YchqFSTlx3NN5zG7RBpvPRUkGo_CCyLThw/edit#gid=1390311126

**Nota**
![Screenshot_74](https://user-images.githubusercontent.com/64148308/84692832-dc687600-af1c-11ea-9dc4-020419460380.png)

**Comment by uira** [comment]
@matheuscpl Aqui tem que conferir no original, mas achei que era pra RETIRAR o oseltamivir, não?
