### ISSUE TITLE
Destacar atualizações do novo protocolo visando dinamizar a leitura do usuário.

### ISSUE THREAD

**Issue by caetanooliveira** [EscolaDeSaudePublica/isus-app#166]
Objetivo:
Destacar atualizações do novo protocolo visando dinamizar a leitura do usuário.

Contexto:
Os profissionais da saúde tem rotinas aceleradas durante seus plantões e atendimentos de pacientes. Hoje em dia sabemos que eles recebem protocolos em grupos de WhatsApp diariamente, e além de fazer uma curadoria, os profissionais leem os protocolos e passam a implementá-las na sua rotina.

Processo:
Hoje recebemos o manejo do Dr Fabrício, mas ainda não sabemos quais são as mudanças. Devemos pedir a ESP esses detalhes.

Cards relacionados:

#184 Gerar notificações no banner para novas atualizações do manejo
#180 Sinalizar o usuário onde houveram atualizações no manejo
#177 Visualizar versionamento do manejo clinico
#204 Template para Atualização do manejo no One Signal
#187 Gerar Notificações para novas atualizações do manejo

Dúvidas:
- Quais conteúdos são mais importantes na atualização?
- Como os profissionais descobrem o que mudou de uma versão para outra hoje em dia?
- Como podemos apresentá-los? 
- Devemos apresentar o antes/depois? Ou só o depois? (Pensar em exemplos)

Notas Técnicas (como a ESP organiza o manejo):
- Paramentação
- Pacientes em Orientações iniciais
- Pacientes em UAPS/UPA/Emergência
- Pacientes em Internação Hospitalar
- Pacientes em UTI
- Exames Laboratoriais
- Diretriz de Diagnóstico  
Métricas de sucesso:
- Número de usuários que abrem manejo 
- Tempo em tela
- Numero de downloads do app

AC:
Dado que há uma atualização do protocolo
O profissional da saúde consegue entender rapidamente as suas mudanças

**Comment by uira** [comment]
@caetanooliveira Sugestões:
- Adotar versionamento e incluir versão do protocolo na interface, de forma clicável, para ver mais informações sobre a versão e ter acesso ao histórico de versões;

- Adotar ChangeLog, sistematizando, a cada versão, as alterações realizadas, de forma detalhada.

- Permitir que Notas do Change log funcionem como Sumário, ao clicar, o usuário é levado para a sessão alterada, e a alteração fica destacada com marcação/ícone "NOVO".

- Implementar notificações para alterações do Manejo. Ao clicar na notificação, o usuário é direcionado para a tela do Manejo com Modal com as Notas da Versão / ChangeLog;

- Implementar camada de interface para destacar mudanças no Protocolo. As mudanças ficam destacadas até o usuário abrir a sessão, quando são "marcadas como lidas" e deixam de ter a tar NOVA.
