### ISSUE TITLE
Permitir compartilhar conteúdos específicos para o perfil de cada usuário.

### ISSUE THREAD

**Issue by caetanooliveira** [EscolaDeSaudePublica/isus-app#168]
Objetivo:
Ter dados de contatos dos usuários em troca de cadastrá-los em eventos da ESP

Contexto:
Hoje em dia os conteúdos do iSUS são generalistas para todas pessoas profissionais da saúde em busca de educação, e informação, principalmente em relação ao enfrentamento da pandemia. Do ponto de vista do negócio, é importante pra nós termos essa informação pois hoje não há um cadastro de profissional da saúde único no Ceará. Existe o CNES (Cadastro Nacional de Estabelecimentos de Saúde) que permite cadastrar profissionais linhadas a um ou outro estabelecimento, mas esse registro é feito pelas gerências, pouco atualizado e confiável. Esse registro tem cerca de 105 mil profissionais de uma estimativa total de 360 mil (facebook), esse cadastro não tem contato de email/telefone ou qualquer contato pessoal do profissional, sabemos que existem os dados de CPF e CNS. Queremos ao longo da progressão do iSUS ter esses usuários cadastrados no app para conseguir seus dados e um contato mais próximo entre governo-profissional. Em troca disso, hoje em dia, há uma demanda por um local de visualização da agenda e inscrição de profissionais em eventos organizados pela ESP. No contexto de pandemia, a ESP organiza Webinars e Treinamentos para seus profissionais, hoje a inscrição é descentralizada e via formulário do Google. O caminho proposto nesse épico é de reunirmos no iSUS a agenda da ESP (já disponível no site e permitir aos usuários que se inscrevem nesses treinamentos a partir dos seus cadastros feitos no aplicativo. Dessa forma poderemos pedir dados mais "sensíveis" como o CPF, email e telefone habilitando uma futura integração com CNES.

Escopo:
- Propor cadastro do usuário (Quais dados, como cadastrar, acesso a esse perfil)
- Propor inscrição em Webinars via perfil (Agenda da ESP e inscrição nos cursos disponível apenas para usuários cadastrados)

Nota:
Dados que PRECISAMOS dos usuários: CPF, telefone, email.
Dados que GOSTARÍAMOS: CNS, profissão.

AC:
Dado que sou um fisioterapeuta do Ceará
Quando quero descobrir eventos da ESP
Posso acessar o app e ver função de agenda

Dado que tento acessar a agenda
Quando não tenho um perfil
Não posso visualizá-la

Dado que tento acessar a agenda
Quando tenho um perfil
Posso visualizá-la
E me inscrever em Webinars

Dado que quero me inscrever
Quando preciso criar um perfil
Posso enviar meus dados ao iSUS

**Comment by Clarisse1983** [comment]
O cadastro no ID Saúde já está operando em seu MVP e atualmente já solicita dados que eram desejáveis segundo esse card: CPF e email. A partir do apeamento do sequenciador da última inception, realizada em outubro de 2020, identificamos demandas com caráter semelhante às expectativas desse card, que se relacionam ao desenvolvimento de uma home personalizada, e de um espaço para a formação/avaliação do profissional de saúde, a partir de um conjunto de estratégias que o deixem atualizado sobre cursos, quizes, notas, etc. Assim, esse card será desdobrado em dois outros épicos: home personalizada e cursos esp. Além disso, o épico do ID saúde seguirá melhorando a experiência da usuária com o cadastro.
