### ISSUE TITLE
Refatorar os estágios na tela de manejo clínico

### ISSUE THREAD

**Issue by stratow** [EscolaDeSaudePublica/isus-app#169]
O index.js do manejo clínico está um monolito. Seria melhor termos cada estágio em um arquivo para manutenção mais fácil.

**Comment by mbernardes19** [comment]
Objetivo:
Facilitar a manutenção e atualização constante do Manejo Clínico

Contexto:
A tela de Manejo Clínico no momento é basicamente um arquivo enorme com que renderiza textos vindos de um JSON e linka para conteúdos através de webview ou acesso a pdf. Achamos que facilitaria manutenção do Manejo se pudéssemos separá-lo em partes menores.

Exemplo:
- Separar estágios em arquivos diferentes
- Ter componentes responsáveis de fazer tarefas que acontecem muito (renderizar texto, renderizar parágrafo, renderizar link etc)
