### ISSUE TITLE
Alterar link de download do Manejo Clínico

### ISSUE THREAD

**Issue by matheuscpl** [EscolaDeSaudePublica/isus-app#173]
**Objetivo**
Substituir link que permite o download do arquivo PDF do Manejo Clínico no app

**Escopo**
O link deve ser substituído por este: https://coronavirus.ceara.gov.br/wp-content/uploads/2020/06/Manejo-Cl%C3%ADnico-dos-pacientes-com-Covid-19.pdf

![Screenshot_78](https://user-images.githubusercontent.com/64148308/85133248-bc80cd00-b210-11ea-9c6c-d7ec9bb62812.png)

**Comment by uira** [comment]
@matheuscpl Ideal seria já deixar isso dinâmico via API, @victormagpacheco e @jacsonp 

Precisava mapear um endpoint com o anexo dessa página:
https://coronavirus.ceara.gov.br/profissional/manejoclinico/

- Talvez colocar um postMeta específico pra isso, @jacsonp, e bater com o @wforte de sempre atualizarem esse meta, e aí já atualiza no app, dinamicamente.

Faz sentido?
