### ISSUE TITLE
Solicitar feedback via OneSignal

### ISSUE THREAD

**Issue by caetanooliveira** [EscolaDeSaudePublica/isus-app#175]
Objetivo:
Permitir gerenciamento de pop-up de feedback via One Signal

Contexto:
Lançamos a funcionalidade de feedback, mas a maioria ainda chega pelos grupos de whatsapp. A ideia desse card é que incentivemos o uso da função de feedback do app através de uma pop-up.  Queremos que, via One Signal, o adm da conta do One Signal possa solicitar envio de pop-up aos usuários para que quando eles abram o aplicativo, apareça o pedido de feedback. O horário de envio, a frequência e público alvo será definido via One Signal. Nesse card queremos habilitar só o tipo de pop-up para ser disparado quando solicitado.

<img width="356" alt="Captura de Tela 2020-06-19 às 16 26 54" src="https://user-images.githubusercontent.com/65370398/85174028-e3f48b80-b24a-11ea-8e74-c3c253c702e4.png">

AC:
Dado que sou adm da conta do One Signal
Quando eu solicito envio de pop-up
Os usuários recebem lembrete para receber feedback

Dado que sou usuário 
Quando disparam a pop-up e eu abro o aplicativo
Visualizo a pop-up e posso aceitar ou rejeitar.

Dado que sou usuario
Quando aparece a pop-up
e eu digo: tudo bem
sou direcionado à tela de feedback

Dado que sou usuario
Quando aparece a pop-up
e eu digo: mais tarde
volto a tela que eu estava antes de surgir a pop-up

**Comment by mbernardes19** [comment]
Eu, @laurapmelo e @ItaloRod descobrimos nessa tarefa que a funcionalidade de mensagem in-app do OneSignal está na versão beta e que ela permanecerá gratuita enquanto estiver na beta. Além disso, também descobrimos que a funcionalidade de segmentação de usuário para envio de mensagem in-app só está disponível na versão paga do OneSignal. Por isso no momento não conseguimos enviar mensagens in-app pra um grupo específico, é sempre pra todos os usuários.

Então, enquanto usarmos essa versão gratuita não vamos poder enviar mensagens in-app específicas pra usuários baseado no botão que clicaram na mensagem, mas podemos enviar notificações push específicas pra cada um.

Existem outros serviços que nos dão essa funcionalidade de mensagem in-app de forma gratuita, como o Firebase (https://firebase.google.com/products/in-app-messaging), porém precisamos estudá-los.
