### ISSUE TITLE
Visualizar versionamento do Manejo Clínico

### ISSUE THREAD

**Issue by matheuscpl** [EscolaDeSaudePublica/isus-app#177]
# Objetivo

**Eu como** profissional da saúde  
**Quero** saber qual ultima atualização do protocolo que visualizo
**Para que** possa me manter atento as atualizações 

# Contexto

## O que originou

É essencial que o profissional da saúde esteja sempre atualizado ou buscando atualizações sobre informações cruciais para o sucesso de suas atividades

## Solução proposta

Adição de **appbar** contendo as informações de versionamento do Manejo Clínico, como também o agrupamento de funcionalidades extras, como o download do Manejo.

# Escopo

## Appbar

- [x] Uma barra de ferramentas deve ser inserida no inferior da página de Manejo Clínico, onde serão inseridos os botões com a funcionalidade de 'download' e as informações de versionamento

![Screenshot_89](https://user-images.githubusercontent.com/64148308/85401771-f57eb180-b530-11ea-8700-f156542b4caf.png)

- [x] A barra deve **desaparecer** ao fazer **scroll para baixo** na página e **aparecer** novamente ao fazer **scroll para cima**

![ezgif com-crop](https://user-images.githubusercontent.com/64148308/85321572-3e842680-b49b-11ea-89a6-a65f0d2c6240.gif)

Elemento React no Framework: https://callstack.github.io/react-native-paper/appbar.html
Usar como referência o elemento criado na issue #57 

## Botão de download

- [x] Inserir botão de download para salvar o arquivo em PDF no telefone do usuário, a partir do link: https://coronavirus.ceara.gov.br/wp-content/uploads/2020/07/Manejo-Cl%C3%ADnico-dos-pacientes-com-Covid-19.pdf

# Fora de escopo

## Nota técnica

O appbar continua sendo exibido na página webview de uma nota técnica, com a mesma informação de versão do Manejo e download, entretanto, será adicionado o **botão de compartilhar** 

![notatecnica](https://user-images.githubusercontent.com/64148308/85402228-b309a480-b531-11ea-9f68-fe5dd5d16adb.png)

- [ ] Permitir o download dos arquivos contidos naquela nota técnica

- [ ] Permitir o compartilhamento externo daquela nota técnica, assim como ocorre em conteúdos de Educação e Pesquisa

# Critérios de aceitação

- [x] **Dado que** queira fazer download do arquivo PDF  
**Quando** clicar no botão de download  
**Então** o arquivo deve estar disponível no meu telefone  

- [ ] **Dado que** queira compartilhar uma nota técnica  
**Quando** clicar no botão de compartilhar  
**Então** visualizo as opções de compartilhamento do meu sistema  

- [x] **Dado que** leio um conteúdo  
**Quando** realize scroll para baixo  
**Então** a appbar desaparece da tela  

- [x] **Dado que** leio um conteúdo  
**Quando** realize scroll para cima  
**Então** a appbar reaparece na tela

# Observações
Figma: https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=1553%3A0

Referências: https://material.io/components/app-bars-bottom#behavior
https://developer.apple.com/design/human-interface-guidelines/ios/bars/toolbars/

**Comment by ItaloRod** [comment]
A Ascom me informou que a última versão do manejo 2.4 no site com data 09/07/20 e não com 05/06/20
