### ISSUE TITLE
Ajustar itens do Drawer

### ISSUE THREAD

**Issue by Junior-Shyko** [EscolaDeSaudePublica/isus-app#178]
# Objetivo
**Eu como** pessoa responsável pela UX do projeto
**gostaria que** não houvesse diferenças de layout ao acessar o app em dispositivos Androids ou dispositivos iOS
**para que** possamos proporcionar a mesma experiência e entregar o mesmo valor e layout independente de plataformas para as nossas usuárias 

# Contexto
Foi identificado que existe uma diferença de espaçamento no menu lateral do app iSUS entre dispositivos Android e iOS. 

Dessa forma, é necessário deixar os itens do menu lateral todos alinhados para não haver diferenças entre plataformas para os usuários profissionais da saúde.

**Observações técnicas:** O uso da safe area para dispositivos iOS com notch causou complicação na disposição dos botões no menu lateral, como também na visualização da versão do app.

Pelo que foi entendido a safe area está sendo aplicada para todos os dispositivos, mesmos os que não possuem notch.

### **Resultado Esperado para Iphone**

- Imagem do Android Asus (como deve ser):

![Webp net-resizeimage](https://user-images.githubusercontent.com/7341117/85450679-647afb00-b56f-11ea-8ed1-c0fb5ecdaee1.png)

### **Resultado Atual em Iphone**

- Imagem do iphone 11 (com notch):

![Screen Shot 2020-06-15 at 15 14 20](https://user-images.githubusercontent.com/7341117/85448457-15cc6180-b56d-11ea-9c91-95de3c187031.png)

- Imagem do iphone 8 (sem notch):

![Screen Shot 2020-06-15 at 15 34 42](https://user-images.githubusercontent.com/7341117/85448094-b8d0ab80-b56c-11ea-81a3-269fc13c60bb.png)

# Escopo
- [x] Implementar a safe area nos dispositivos iOS de maneira correta, a fim de que todos os dispositivos e plataformas apresentem o mesmo layout no menu lateral conforme [figma](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=1550%3A7603).

# Observações

Figma: https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=1550%3A7603

- No menu lateral tem uma diferença em dispositivos que tem o notch, foi testado no iphone8, android Pixel 2, e Nexus S e não ocorreu a diferença, porém, no simulador Iphone 11 foi percebido esse problema.

- Esse recurso já foi aplicado com sucesso no header, buscar entender como isso foi feito lá.

**Comment by Junior-Shyko** [comment]
@matheuscpl da uma olhada.

**Comment by matheuscpl** [comment]
Uirá: "Jogar o Sobre o iSUS lá pra baixo, e tirar esse Aleta de EPI daí também. Ficaria:

- Home
- Meu Perfil (ID Saúde) <—pode ser uma tag
- Sus no Ceará
- Fale Conosco


- Sobre o iSUS
- Compartilhe o iSUS
- Versão X.X.X"

**Comment by kurjes** [comment]
@Junior-Shyko verificar se esse comportamento ainda ocorre, e caso ocorra @uira priorizar dentro no nosso backlog juntamente com @rodrigoplimafreire criando uma nova experiência.

**Comment by Wanderley97** [comment]
![75b19ee1-59e8-4c4c-8e80-f6d539dbd092](https://user-images.githubusercontent.com/74379182/104320299-e6595400-54c0-11eb-9c60-1e82763febec.jpg)

**Comment by Wanderley97** [comment]
Visão de tela para Iphone X.
