### ISSUE TITLE
Gerar notificação no banner para novas atualizações de Manejo

### ISSUE THREAD

**Issue by laurapmelo** [EscolaDeSaudePublica/isus-app#184]
# **Objetivo**
Eu como profissional de saúde
Quero saber quando houveram atualizações nos protocolos de manejo ao acessar o aplicativo
Para que possa ver o que mudou

# Contexto:

Parte do épico de versionamento de protocolos é mostrar ao usuário em quais notas técnicas o manejo foi atualizado, por exemplo, se foi na paramentação, nas orientações iniciais, triagem, etc.
Esse card tem como objetivo apenas a criação dessa tag que sinaliza onde houve atualização, estão contemplados: o banner de manejo na tela inicial (conforme imagens). Essa sinalização ocorre toda vez que alguma parte da nota técnica é modificada, alterada ou excluída e deve seguir o mesmo padrão para todo manejo. Ou seja, se na próxima versão do manejo tivermos atualizações na paramentação e nas orientações para pacientes internados, essas são as duas seções sinalizadas.

# **Dentro do escopo:**
- Gerar sinalização no banner de manejo a cada atualização de protocolo
- Retirar sinalização uma vez que a usuária clica no banner

**Protótipo:**
![image](https://user-images.githubusercontent.com/67436275/86277160-9a8e2f80-bbac-11ea-91fb-abb862b7b05e.png)

# Critérios de aceite

(surge tag no banner)
Dado que há uma nova atualização na nota de orientações iniciais
Quando eu abro o app
Posso ver o banner do manejo sinalizado
Quando abro o manejo
Vejo a tag apenas em “Orientações iniciais”

(some tag no banner) - comportamento de notificação
Dado que há uma atualização no manejo
Quando estou na Home
há uma tag no banner do manejo
Até que eu clique nele pela primeira vez.

**Comment by ItaloRod** [comment]
foi adicionado instruções de como atualizar a versão do manejo clínico e se encontra no ReadMe da Aplicação
