### ISSUE TITLE
Gerar notificação para novas atualizações de Manejo

### ISSUE THREAD

**Issue by laurapmelo** [EscolaDeSaudePublica/isus-app#187]
**Objetivo**
Como um usuário 
Quando receber uma notificação de atualização  do manejo
Então quero ser redirecionada para a tela de manejo

**Contexto**
Todas as notificações  atualmente são redirecionadas para a tela de webview utilizando a url de parâmetro. Devemos criar uma nova url que ira nos informar qual tela acessar, mas sem alterar o comportamento de uma notificação que deve ir para a webview. Sugestão: "isusapp://manejo" ou "isusapp://webview:https://www.esp.ce.gov.br/2020/07/15/esp-ce-lanca-curso-prevencao-e-controle-de-infeccoes-em-parceria-com-opas-e-oms/"

**Critérios de aceitação**

- [x] Dado que uma notificação push é recebida
       Quando eu clico na notificação 
       Então a tela informada no url deve ser aberta 
- [x] Dado que uma notificação push que envia para webview é recebida
       Quando eu clico na notificação 
       Então a tela de webview deve ser aberta com a url carregada
- [ ] Dado que não seja encontrado a tela dentro da notificação (notificação  mal construída)
       Quando eu clico na notificação 
       Então a tela de home deve ser aberta

**Comment by amaurymeireles** [comment]
Exemplo de url:
isusapp://webview|https://google.com
isusapp://clinical management

**Comment by amaurymeireles** [comment]
IMPORTANTE MUDAR O WORDPRESS ANTES DE SUBIR

**Comment by uira** [comment]
@amaurymeireles @jacsonp vc captou essa aqui?

**Comment by jacsonp** [comment]
Preciso entender primeiro o que mudou, já que havíamos configurado o app para fazer handler de todas as urls https://coronavirus.ceara.gov.br o que mudou? Lembrando que usamos um serviço de 3º para fazer o push (onesignal), e que esse não nos permite mudar o formato da url apenas para o app, sendo assim, "estragaria" as notificações de navegador, como já tínhamos vistos anteriormente.

**Comment by jacsonp** [comment]
Uma sugestão de workaround para evitar refatoração de todo o sistema de push: criar uma configuração no app, que será alimentada via api, onde certas urls serão marcadas como visualizadas no app, sendo assim, quando o app as recebe, ao invés de abrir o webview, abriria a tela específica.

**Comment by amaurymeireles** [comment]
Opa jacson tu ta no slack ne? vamos marcar um call pra discutir isso
