### ISSUE TITLE
Permitir que a usuária faça um Alerta de Falta de EPI na sua Unidade de Saúde

### ISSUE THREAD

**Issue by laurapmelo** [EscolaDeSaudePublica/isus-app#188]
# Objetivo

**Eu como** profissional da saúde  
**Quero** alertar quanto a falta de EPI na unidade de saúde na qual trabalho 
**Para que** para que possa dar visibilidade do problema para as autoridades competentes

# Contexto
## O que originou
Atualmente não existe um local centralizado para que as profissionais de saúde possam alertar sobre a falta de EPIs nas unidades em que trabalham. 

## Qual solução proposta
Para este problema, a solução é criação de um local que esta profissional possa alertar sobre o problema. Será adicionado um botão no menu lateral que deve direcionar para uma nova aba da área de feedback. O formulário terá os campos de descrição, Unidade de saúde e email. O envio da solicitação deve gerar um email com as informações preenchidas.

# Escopo
## Botão no menu lateral

- [x] Adicionar um botão de "Fale conosco" no menu lateral que direciona para a página correspondente, que irá agregar o "Alerta de EPI" e a funcionalidade já existente "Feedback", separados por abas

## Aba com formulário de alerta de EPI

- [x] Adicionar aba de Alerta de EPI 

- [x] Formulário com campos "Descrição" (obrigatório), Unidade de Saúde (Obrigatório) e email (opcional)

## Enviar email ao submeter formulário

- [x] Um email deve ser enviado quando a usuária submeter o feedback. O assunto deverá ser ISUS APP - ALERTA DE EPI - UNIDADE DE SAÚDE. DD/MM/AAAA HH:MM:SS e o remetente o email informado pelo usuário

# Fora de contexto

- **Alterar página de feedback**

# Critérios de aceitação

## Botões 

- [x] **Dado que** eu queira Alertar sobre a falta de EPI na minha unidade de saúde
**Quando** clicar acessar o menu lateral **e** clicar no botão de "Fale conosco"  
**Então** devo ir para a página/aba de Alerta de EPI
**E** ver os campos de descrição, unidade de saude e email

- [x] **Dado que** eu queira fazer uma sugestão ou reclamação sobre o iSUS
**Quando** clicar acessar o menu lateral **e** clicar no botão de "Fale conosco"  
**Então** devo ir para a página/aba de feedback 
**E** ver os campos de feedback

## Formulário de Alerta de EPI

- [x] **Dado que** esteja na página de "Alerta de EPI" 
**Quando** eu tentar submeter o formulário sem preencher o campo de "Descrição"
**Então** o botão fica cinza
**E** o formulário não é enviado

- [x] **Dado que** eu esteja na página de "Alerta de EPI" 
**Quando** eu tentar submeter o formulário sem preencher o campo de "Unidade de Saúde"
**Então** o botão fica cinza
**E** o formulário não é enviado

- [x] **Dado que** eu esteja na página de "Alerta de EPI" 
**Quando** preencher todos os campos obrigatórios
**Então** o botão fica ativo
**E** eu posso clicar para submeter o formulário

## Email
- [x] **Dado que** preenchi todos os dados necessário para realizar um "Alerta de EPI"
**Quando** eu submeter o formulário
**Então** um email com o assunto "ISUS APP - ALERTA DE EPI - UNIDADE DE SAÚDE. DD/MM/AAAA HH:MM:SS" deve ser enviado
**E** o remetente deve ser o email enviado pelo usuário
**E** surge uma snack bar com mensagem de sucesso.

- [x] **Dado que** abro a caixa de entrada do feedback.isus@esp.ce.gov.br 
**Quando** pesquiso "alerta de EPI"
**Então** Posso ver os alertas enviados pelos usuários

# Observações
Figma: https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=1550%3A7607
Protótipo: https://www.figma.com/proto/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=1701%3A161&viewport=416%2C251%2C0.15615564584732056&scaling=scale-down

**Comment by matheuscpl** [comment]
@lemenezes @mbernardes19  O label "Alerta de EPI" localizado dentro do menu foi trocado por "Alerta de falta de EPI"

![Screenshot_135](https://user-images.githubusercontent.com/64148308/87814811-cf4fe700-c83a-11ea-9096-32173a3f00e0.png)
