### ISSUE TITLE
Adicionar rodapé de versão nas notas técnicas e permitir download

### ISSUE THREAD

**Issue by laurapmelo** [EscolaDeSaudePublica/isus-app#194]
### **OBS**
Tarefa criada a partir da recusa da apple de publicar o app em função de conteúdo médico. Tarefa está desenvolvida em branch separa e pode ser usada caso seja necessário.

# Objetivo

**Eu como** profissional da saúde  
**Quero** saber qual ultima atualização do protocolo que visualizo
**Para que** possa me manter atento as atualizações 

# Contexto

## O que originou

É essencial que o profissional da saúde esteja sempre atualizado ou buscando atualizações sobre informações cruciais para o sucesso de suas atividades

## Solução proposta

Adição de **appbar** contendo as informações de versionamento do Manejo Clínico, como também o agrupamento de funcionalidades extras, como o download do Manejo.

# Escopo

** Referência: Issue #177 

## Nota técnica

O appbar continua sendo exibido na página webview de uma nota técnica, com a mesma informação de versão do Manejo e download, entretanto, será adicionado o **botão de compartilhar** 

![notatecnica](https://user-images.githubusercontent.com/64148308/85402228-b309a480-b531-11ea-9f68-fe5dd5d16adb.png)

- [ ] Permitir o download dos arquivos contidos naquela nota técnica

- [ ] Permitir o compartilhamento externo daquela nota técnica, assim como ocorre em conteúdos de Educação e Pesquisa

# Critérios de aceitação

- [ ] **Dado que** queira fazer download do arquivo PDF  
**Quando** clicar no botão de download  
**Então** o arquivo deve estar disponível no meu telefone  

- [ ] **Dado que** queira compartilhar uma nota técnica  
**Quando** clicar no botão de compartilhar  
**Então** visualizo as opções de compartilhamento do meu sistema  

- [ ] **Dado que** leio um conteúdo  
**Quando** realize scroll para baixo  
**Então** a appbar desaparece da tela  

- [ ] **Dado que** leio um conteúdo  
**Quando** realize scroll para cima  
**Então** a appbar reaparece na tela

# Observações
Figma: https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=1553%3A0

Referências: https://material.io/components/app-bars-bottom#behavior
https://developer.apple.com/design/human-interface-guidelines/ios/bars/toolbars/

Épico #45 conteúdo disponível offline

**Comment by laurapmelo** [comment]
Necessitamos que o parser do manejo seja implementado para facilitação desta tarefa.

**Comment by kurjes** [comment]
Necessária entender prioridade com @uira 

pareando @daianefreira

**Comment by Clarisse1983** [comment]
Estamos fechando essa issue porque esses conteúdos referidos são exibidos na webview do coronavirus.ceara.gov.br, e lá já temos a opção de download, então essa tarefa perde o sentido. Além disso, o download e versionamento do manejo, que motivou essa tarefa, são funcionalidades a serem previstas pelo novo manejo, em produção.
