### ISSUE TITLE
Implementar integração com idSaúde (keycloak) - Login

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/isus-app#196]
# Objetivo:

conseguir fazer o login e retornar os dados do usuário autenticado

# Contexto:

Demanda de conseguir integrar com sistema de usuários dentro do App iSUS

# Escopo:

- [x] Adicionar um botão de login no menu lateral do aplicativo
- [x] Realizar o processo de redirecionamento do aplicativo para a tela do iDSaúde
- [x] Após o Login permitir que o usuário retorne para o app.
- [x] Ao retornar mostrar o nome do usuário Logado e mostrar botão de sair.
- [x] Ao sair do aplicativo, fazer com que o usuário ainda esteja logado.

**Comment by ItaloRod** [comment]
Botão adicionado de login. Adicionado a biblioteca para o react-native e serviço de autenticação com o keycloak
Problemas somente no redirecionamento

**Comment by ItaloRod** [comment]
Implementação realizada com sucesso. O Sistema de login está operando através de um estado em conteúdo do Drawer. Para fazer com que o usuário seja visto em todo o projeto (se necessário) é preciso coloca-lo num contexto.
