### ISSUE TITLE
Trocar Telemedicina por Feedback

### ISSUE THREAD

**Issue by laurapmelo** [EscolaDeSaudePublica/isus-app#200]
## Objetivo ##

Alterar ícone "Telemedicina" da home para "Feedback"

## Contexto ##

Os dados informados na página de telemedicina não estão mais válidos. Por estarem na primeira tela acessada pelo usuário quando acessa o APP podem causar desinformação e uma má experiência no app.

## Escopo ##

[ ] Substituir o ícone da home de "Telemedicina" com "Feedback""

[ ] Linkar ao ícone a página de feedback

Ícone a ser usado: 
[feedback_icon.zip](https://github.com/EscolaDeSaudePublica/isus-app/files/4931739/feedback_icon.zip)

## Critérios de Aceitação ##

Dado que acesso o iSUS
Quando estou na Home do app
Então vejo o ícone de "Feedback" abaixo do "IntegraSUS"

Dado que estou na home do iSUS
Quando clico no ícone de "feedback"
Então sou redirecionada para a página de feedback

Figma: https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=1550%3A7603

**Comment by laurapmelo** [comment]
##Objetivo

Alterar ícone "Telemedicina" da home para "Feedback"

##Contexto

Os dados informados na página de telemedicina não estão mais válidos. Por estarem na primeira tela acessada pelo usuário quando acessa o APP podem causar desinformação e uma má experiência no app.

##Escopo

[ ] Substituir o ícone da home de "Telemedicina" com "Feedback""

[ ] Linkar ao ícone a página de feedback

##Critérios de Aceitação

*Dado que* acesso o iSUS
*Quando* estou na Home do app
*Então* vejo o ícone de "Feedback" abaixo do "IntegraSUS"

*Dado que* estou na home do iSUS
*Quando* clico no ícone de "feedback"
*Então* sou redirecionada para a página de feedback

Figma: https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=1550%3A7603

**Comment by uira** [comment]
@laurapmelo A gente  tinha falado de trocar "Feedback" por "Fale Consco", não?

**Comment by laurapmelo** [comment]
> @laurapmelo A gente tinha falado de trocar "Feedback" por "Fale Consco", não?

Siiim!! @amaurymeireles tu pode trocar os textos do menu lateral e do ícone na home para "Fale Conosco"?!
