### ISSUE TITLE
Adicionar dotEnv para diferenciar os ambientes de homologação e produção durante o desenvolvimento do keycloack.

### ISSUE THREAD

**Issue by ItaloRod** [EscolaDeSaudePublica/isus-app#209]
### **Contexto**
Algumas credenciais do keycloack estão expostas dentro do projeto, sendo que são variáveis que devem estar disponíveis somente no repositório local do usuário e não deve ser versionado junto com o código fonte do projeto. Por outro lado, esses dados são referentes a homologação e que podem ser alteradas no futuro quando o ID Saúde estiver em produção.

### **Objetivo**

* Adicionar uma biblioteca que possibilite o acesso das variáveis de ambiente dentro do código:
Ex.: https://github.com/motdotla/dotenv
* Adicionar um arquivo ```.env``` contento as credenciais que estão declaradas em:
https://github.com/EscolaDeSaudePublica/isus-app/blob/%23196-integracao-keycloak/src/services/autenticacao.js
* Esse arquivo ```.env``` deve conter os seguintes campos:

````.env
KEYCLOAK_URL=
KEYCLOAK_REALM=
KEYCLOAK_CLIENT_ID=
KEYCLOAK_REDIRECT_URI=
KEYCLOAK_APPSITE_URI= 
````

* Adicionar no ```.env.example``` esses campos de exemplo
* Substituir os dados em https://github.com/EscolaDeSaudePublica/isus-app/blob/%23196-integracao-keycloak/src/services/autenticacao.js pelos declarados no usuário.

Épico #232 habilitadores gerais

**Comment by mbernardes19** [comment]
Já existe uma biblioteca de configuração de dotEnv instalada no projeto: [react-native-config](https://github.com/luggit/react-native-config)

Com ela as variáveis inseridas no `.env` ficam acessíveis pra configuração do projeto RN, Android e iOS.

Ela já está instalada e funcionando. Ao meu entender, seria necessário agora só analisar como fazer pra mudar as variáveis dependendo do ambiente em que está.
