### ISSUE TITLE
Permitir compartilhar um link de acesso através do aplicativo

### ISSUE THREAD

**Issue by laurapmelo** [EscolaDeSaudePublica/isus-app#218]
# Objetivo

Permitir que os usuários do iSUS convidem colegas de trabalho através de compartilhamento um link de compartilhamento através do menu lateral.

# Escopo

- [x] Adicionar ao menu lateral do app, na parte inferior, logo acima a versão, um item na lista que permitirá o compartilhamento do site do iSUS em redes sociais.

![menu lateral](https://user-images.githubusercontent.com/64148308/88296370-fa23ba80-ccd4-11ea-9994-0407c5a02701.png)

- [x] Fazer link com: https://coronavirus.ceara.gov.br/isus/

# Nota

Protótipo: https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=1937%3A318

**Comment by ItaloRod** [comment]
o texto que acompanha o link é: "Em tempos de crise, a informação correta deve ser sua principal aliada. Aqui você encontra todo o conteúdo Oficial sobre o CoronaVírus, preparado pelo Governo do Estado do Ceará. - https://coronavirus.ceara.gov.br/isus/"
