### ISSUE TITLE
Adicionar referências de conteúdo médico nos rodapés dos estágios do Manejo Clínico

### ISSUE THREAD

**Issue by mbernardes19** [EscolaDeSaudePublica/isus-app#219]
# Contexto
Houve 2 rejeições no App Store devido a falta de referências aos conteúdos médicos o app. Tentamos com a tarefa #211 atribuir os sites da Secretaria Estadual da Saúde e da Escola de Saúde Pública do Ceará como referência de todos os conteúdos do Manejo Clínico, porém tivemos a resposta de que faltavam referências em outras partes do app (sem especificação de quais).

Esta tarefa foi proposta como uma forma de tentar sinalizar de uma forma diferente que todos os conteúdos do Manejo Clínico têm esses sites como referência. Caso a versão publicada hoje (23/07/2020) falhe, tentaremos lançar outra versão com as alterações desta tarefa.

# Objetivo

Devido a uma solicitação da App Store, surgiu a necessidade de fazer referência às instituições médicas que fornecem as informações ao iSUS

# Escopo

Adicionar, ao final da cada estágio do Manejo Clínico, um pequeno texto referenciando a SESA e a ESP, com links para seus respectivos sites.

![Screenshot_10](https://user-images.githubusercontent.com/64148308/88215232-b75cd680-cc31-11ea-946f-9429b28628a7.png)

## Texto: 
"Todas as informações disponíveis neste aplicativo foram cuidadosamente selecionadas e verificadas pela Secretaria Estadual da Saúde e Escola de Saúde Pública do Ceará."

## Links:

Secretaria Estadual da Saúde: https://www.saude.ce.gov.br/

Escola de Saúde Pública do Ceará: https://www.esp.ce.gov.br/

**Comment by mbernardes19** [comment]
# Objetivo

Devido a uma solicitação da App Store, surgiu a necessidade de fazer referência às instituições médicas que fornecem as informações ao iSUS

# Escopo

Adicionar, ao final da cada estágio do Manejo Clínico, um pequeno texto referenciando a SESA e a ESP, com links para seus respectivos sites.

![Screenshot_10](https://user-images.githubusercontent.com/64148308/88215232-b75cd680-cc31-11ea-946f-9429b28628a7.png)

## Texto: 
"Todas as informações disponíveis neste aplicativo foram cuidadosamente selecionadas e verificadas pela Secretaria Estadual da Saúde e Escola de Saúde Pública do Ceará."

## Links:

Secretaria Estadual da Saúde: https://www.saude.ce.gov.br/

Escola de Saúde Pública do Ceará: https://www.esp.ce.gov.br/

**Comment by laurapmelo** [comment]
outra versão foi submetida e aceita na apple. essa tarefa está feita e, caso seja necessária, pode ser colocada em produção.

**Comment by ericsonmoreira** [comment]
Não encontramos mais esse impedimento pela Apple, então decidimos fechar essa `issue`.

**Comment by uira** [comment]
@ericsonmoreira Isso aqui pode taguear como Backlog do projeto iNova Saúde, a ser priorizado quando o projeto estiver em execução.
