### ISSUE TITLE
Adicionar telas de manejo clínico

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/isus-app#22]
- [x] Entender o requisito
- [x] PDF ou adicionar realmente o conteúdo do PDF diretamente no APP (telas)
- [x] https://coronavirus.ceara.gov.br/profissional/manejoclinico/

**Comment by matheuscpl** [comment]
Galera tá aqui os links do Manejo COVID-19, no msm arquivo do iSUS, lá em baixo tem a página específica dele:
https://docs.google.com/spreadsheets/d/1CqqiVEWH-YchqFSTlx3NN5zG7RBpvPRUkGo_CCyLThw/edit#gid=1390311126

Juntei todos os PDFs e eles somam 20,5mb

**Comment by ItaloRod** [comment]
só uma pergunta. Então como os PDF's pesam 20,5MB colocamos eles junto ao App? Gostaria de saber também se já tem algum esquema de qual pdf vai em qual link

**Comment by ItaloRod** [comment]
Em uma conversa com o Victor. ficou decidido que:
Os PDF's serão disponibilizados de forma offline, onde cada link será atribuído ao pdf **principal** de cada link disponibilizado.  Amanhã de manhã farei uma planilha para mapear os links para PDF's para poder a tarde parear com o Leandro

**Comment by victorMagalhaesPacheco** [comment]
> só uma pergunta. Então como os PDF's pesam 20,5MB colocamos eles junto ao App? Gostaria de saber também se já tem algum esquema de qual pdf vai em qual link

Vamos tentar diminuie o tamanho desses pdf comprimindo os mesmos com esse site: https://pdfcompressor.com/pt/

**Comment by ItaloRod** [comment]
Tarefa em espera para definir se deve ou não ser realizada

**Comment by uira** [comment]
Gente, isso não é prioridade para a MVP.

Existe uma outra tarefa, de configurar os conteúdos offline, que resolve essa tarefa.
