### ISSUE TITLE
Realizar ajustes no Fale Conosco

### ISSUE THREAD

**Issue by matheuscpl** [EscolaDeSaudePublica/isus-app#221]
# Contexto

- Os feedbacks (snack bar) da função Fale Conosco exibem mensagens que corresponde a apenas uma das três funcionalidade. 

![photo4958895938210998495](https://user-images.githubusercontent.com/64148308/88388989-f868fe00-cd8b-11ea-8eee-78821442d1c3.jpg)

- O header da página de Fale Conosco não corresponde ao que exibe o sistema, continha com a label da home

![WhatsApp Image 2020-07-24 at 08 40 24](https://user-images.githubusercontent.com/64148308/88388994-fc951b80-cd8b-11ea-90b2-bb15f017c925.jpeg)

# Escopo

- [x] Substituir a mensagem de feedback por: "Seu relato foi enviado, obrigado!"

![Screenshot_12](https://user-images.githubusercontent.com/64148308/88389013-04ed5680-cd8c-11ea-9d99-b80fccc77c64.png)

- [x] Ajustar o label do header para exibir "Fale Conosco" ao acessar a seção

![Screenshot_13](https://user-images.githubusercontent.com/64148308/88389034-0f0f5500-cd8c-11ea-9f71-66262e97a703.png)

**Comment by ItaloRod** [comment]
o Comportamento que nós fizemos durante o processo de desenvolvimento dessa atividade foi diferente do solicitado. Ao invés de uma mensagem genérica, o header e o retorno do envio da requisição do fale conosco é referente ao que o usuário escolheu (Alerta de falta de EPI, Sugestão ou problema)
