### ISSUE TITLE
Alterações para Permitir compartilhar um link através de um aplicativo.

### ISSUE THREAD

**Issue by ItaloRod** [EscolaDeSaudePublica/isus-app#231]
Essas são demandas vindas da Ascom sobre a tarefa #218:

- [x] mudar o texto do convite para: "Conhece o app iSUS? Um produto digital do governo do Ceará de apoio a profissionais de saúde, com informações, serviços e oportunidades na palma da mão! Saiba mais: https://coronavirus.ceara.gov.br/isus/"
- [x] Alterar texto no menu lateral para "Compartilhe o iSUS"

**Comment by uira** [comment]
@ItaloRod Fiquei na dúvida entre:

- Indique o iSUS
- Compartilhe o iSUS
- Convidar Contatos

**Comment by ItaloRod** [comment]
> 
> 
> eu gosto de
> 
>     * Indique o iSUS
>       ou
> 
>     * Compartilhe o iSUS

Achei bacana o compartilhe o iSUS. Bem mais objetivo e padronizado. Com relação ao texto que acompanha o link? Alguma alteração em relação ao que a Ariane nos passou?
