### ISSUE TITLE
Integração com a página do Observatório

### ISSUE THREAD

**Issue by laurapmelo** [EscolaDeSaudePublica/isus-app#233]
### **Contexto**
Observatório gostaria de criar um link do app iSUS para redirecionar para a página deles.

**Dúvidas**
Colocar um link dentro do app, webview dentro do app ou vai pra fora? _Visualização com webview_

**Contato**
Jadson

**Comment by kurjes** [comment]
Necessário uma priorização dentro do nosso backlog @uira

**Comment by Clarisse1983** [comment]
Como está a página do Observatório? Pensar se essa tarefa faz sentido, e qual a melhor jornada para a usuária.

**Comment by MayaraMonte** [comment]
Protótipo atualizado: https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/?node-id=5613%3A489

**Comment by Laysacunha** [comment]
deprecated.

**Comment by uira** [comment]
@ericsonmoreira Essa aqui precisa passar pelo refinamento de UX, tem uma dependência que é a definição de onde entra, na arquitetura, @RaniGub

**Comment by RaniGub** [comment]
@ericsonmoreira hj tenho disponível de 13h30 às 14h, tb podemos conversar na segunda 11h ou 14h.
