### ISSUE TITLE
Adicionar Plano de Modernização da Saúde no menu lateral

### ISSUE THREAD

**Issue by laurapmelo** [EscolaDeSaudePublica/isus-app#234]
Adicionar página com plano de modernização da Saúde.

**Comment by uira** [comment]
@laurapmelo Será que isso não poderia ser um dos links dentro do Sobre o SUS?

**Comment by laurapmelo** [comment]
@uira pensamos nisso ontem, acredito que poderia sim. Não tenho muito contexto sobre as informações que seriam colocadas nessa parte, mas se faz sentido, acredito que seja um bom lugar.

**Comment by Laysacunha** [comment]
Conteúdo já incluído na seção SUS no Ceará. Portanto, tarefa será fechada.
Seguem imagens:
![image](https://user-images.githubusercontent.com/20958122/164368032-5e121003-cb4b-4ee9-9aec-40967c70c926.png)
![image](https://user-images.githubusercontent.com/20958122/164368062-be39b819-c9b8-4678-8c4b-58db896d317c.png)
