### ISSUE TITLE
Implementar a tela de perfil de usuário

### ISSUE THREAD

**Issue by laurapmelo** [EscolaDeSaudePublica/isus-app#240]
**### Objetivo**
**Como** uma usuária logada
**Quero** acessar meu perfil
**Para** verificar e mudar meus dados

### **Contexto**
Após realizar o login, a usuária deve poder verificar dados inseridos, editá-los e acessar documentos relacionadas ao cadastro. Esta página deve implementar os acessos a estas funcionalidades.

### **Escopo**
- [x] botão no menu lateral que redireciona para a página do perfil
![image](https://user-images.githubusercontent.com/67436275/89340478-31e81600-d676-11ea-9e52-8c0064a246c9.png)

- [x] Criar página de perfil da usuária (não haverá foto)
![image](https://user-images.githubusercontent.com/67436275/89323356-f2143500-d65b-11ea-9433-07cb0118b142.png)

- [x] Botão para deslogar

**Fora do escopo**
- [x] Acesso a página com dados cadastrados (outro card)

- [x] Acesso a Política de Privacidade - será uma página com texto (#267 )

- [x] Acesso a Termos de Uso - será um pagina com texto ()

- [x] Acesso à webview com ID Saúde - deverá redirecionar para uma webview do keycloack

### **Critérios de Aceitação**
- [x] acessar página
**Dado que** sou uma usuária e estou logada
**Quando** clico no no menu lateral em "Meu perfil"
**Então** sou redirecionada para a página do perfil
 
- [x] logout
**Dado que** estou logada no id saúde 
**Quando** clico em sair
**Então**  sou deslogada do ID e redirecionada para  a home do app

**Comment by lemenezes** [comment]
Status do cartão: Bloqueado
Motivo: Dependente do cartão de tela de login (card 56 - api)

**Comment by laurapmelo** [comment]
Pessoal, por algumas limitações, a seção de minha conta não vai ser implementada para essa entrega, então deve ficar oculta ou ser retirada!

**Comment by uira** [comment]
Não vai rolar a minha conta, mas vai exibir os dados cadastrados de alguma forma?

**Comment by mbernardes19** [comment]
Eu e @kurjes estamos mergeando a branch desta tarefa com a da tarefa #242 para deixar a funcionalidade de Login completamente integrada com a API.

**Comment by drmarcos** [comment]
Apesar de exibir os dados não encontrei como modificar (editar)
O "Botão" preferência não funciona e não parece desabilitado.

**Comment by nicoledbianchin** [comment]
No dispositovo Android aparecem os dados cadastrados ao logar. Depois que logo, não consigo clicar em nenhum item do meu drawer (não sou redirecionada para os links)

**Comment by nicoledbianchin** [comment]
[Link do vídeo](https://drive.google.com/file/d/12RbTGsk7UaWEMJKmbYeBp1zRN8fgVBHE/view)

- Quando estou na tela de perfil, o menu lateral não funciona, apenas o link para os termos de uso e para compartilhar
- O aviso de email inválido continua mesmo após eu colocar um email válido, mas mesmo assim consigo logar

@daianefreira quando sai e fui logar de novo, os dados não estavam salvos, talvez seja alguma configuração do iOS
