### ISSUE TITLE
[BUG- QA] Implementar tela de login

### ISSUE THREAD

**Issue by ItaloRod** [EscolaDeSaudePublica/isus-app#242]
## **Objetivo**
**Eu como** Profissional de saúde
**Eu Quero** realizar o login no aplicativo
**Para que** eu possa ter acesso às informações registradas e conteúdo personalizado

### **Contexto**
Queremos que os profissionais com cadastro no ID Saúde possam acessar uma área personalizada, que no futuro agregará outras funcionalidades específicas para eles.

### **Escopo**

- [x] botão no menu lateral que direciona para a página de login caso eu não esteja logada. se eu estiver logada, devo ser redirecionada para a página de perfil (outro card)
![image](https://user-images.githubusercontent.com/67436275/89295918-1100d000-d638-11ea-861b-c3f4c8963087.png)

- [x] tela que redireciona para o login
![image](https://user-images.githubusercontent.com/67436275/89296564-e400ed00-d638-11ea-83a8-f601cd3eefb2.png)

- [x] Tela de login dentro do app (não em webview) com campos de email e senha
* O campo de email deve possuir validação e conter um feedback visual para o usuário quando houver problemas.
![image](https://user-images.githubusercontent.com/67436275/89296639-fd099e00-d638-11ea-9bec-22ec96eee233.png)

- [x] botão de esqueci a senha que redireciona para tela de webview onde ele poderá recuperar a senha.

- [x] botão de login que redireciona para apágina de perfil #240 

- [x] criar resposta mockada para endpoints acessados na tela de login

### **Fora do Escopo**
- Criar página home personalizada
- Criar perfil da usuária
- Fazer requisições aos endpoints da API

### **Critérios de Aceitação**

- [x] botão de login
**Dado que** clico no botão do ID saúde
**Quando** não estou logada
**Então** sou redirecionada para a página de login

- [x] Login com sucesso
**Dado que** tenho uma conta **e** inseri meus dados corretamente
**Quando** clico em "Fazer login"
**Então** sou redirecionada para a minha página de perfil

- [x] Email com formato incorreto
**Dado que** inseri um email com formato incorreto
**Quando** saio do campo de email
**Então** vejo uma indicação de que o formato está incorreto @matheuscpl 

- [x] Login sem cadastro ou com dados incorretos
**Dado que** inseri dados que não correspondem a uma usuária cadastrada
**Quando** tento fazer login
**Então** vejo uma indicação que este usuário não existe ou os dados estão incorretos @matheuscpl  

- [x] recuperação de senha
**Dado que** quero fazer login
**Quando** clico em recuperar senha
**Então** uma webview é aberta na página de recuperação de senha

- [x] manter conectado - encerrar
**Dado que** estou logada
**Quando** encerro o app e abro novamente
**Então** sigo logada no meu perfil

- [x] manter conectado - minimizar
**Dado que** estou logada
**Quando** abro outro app e depois volto ao iSUS
**Então** sigo logada logada no meu perfil

**Protótipo**
https://www.figma.com/proto/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=2061%3A0&scaling=scale-down

Épico #134 perfil do usuário

### **BUGS-QA**

**Todas as correções foram feitas na branch `feature/#260-implementar-tela-de-informacoes`**

- [x] usuário ser capaz de preencher o campo de email com autocomplete do teclado nativo e ter esse email reconhecido como válido caso seja **(IOS e Android)**

Na tela de login, ao preencher o email com o autocomplete do teclado nativo
**Comportamento atual:** mesmo que o email seja um email válido, ele não é reconhecido como tal pelo input e a mensagem de "email inválido" continua alí
**Comportamento esperado:** ao inserir email com autocomplete do teclado, sendo esse email válido, será validado corretamente

- [x] usuários ser capaz de entender que o login está sendo processado e o app não deu erro **(iOS e Android)**

Na tela de login, ao clicar em "Fazer login"
**Comportamento atual:** há uma demora para realizá-lo mas não existe nenhuma sinalização de que o login está sendo processado.
**Comportamento esperado:** seria mostrada uma animação de carregamento para indicar que um processamento está sendo feito e que o app ainda está funcionando (recomenda-se usar o mesmo carregamento que acontece no botão da tela de Fale Conosco).

- [x] ser possível acessar links de menu lateral **(iOS e Android)**

Após realizar o login (e em momentos inesperados) no app, ao abrir o menu lateral e clicar em um dos primeiros 6 botões de navegação
**Comportamento atual:** não é exibida nenhuma animação de clique e nem a navegação para a tela desejada é realizada. A navegação e o clique só acontecem de fato nos dois últimos botões do menu. 
**Comportamento esperado:** a animação de clique é exibida e a navegação ocorre para todos os botões de navegação

- [ ] logar com apenas um click no botão de login **(Android)**

Quando preencho meu e-mail e senha na página de login
**Comportamento atual:** só consigo logar com um duplo click no botão "login" 
**Comportamento esperado:** conseguir realizar o login com o click simples no botão "login"

**Comment by ItaloRod** [comment]
![image](https://user-images.githubusercontent.com/20058085/89561450-e1e08f00-d7ee-11ea-9dc5-4f1af59c4c39.png)
os links para os termos de uso e de política de privacidade estão apontando para a tela de sobre. Quando essas telas estiverem prontas, basta substitui-las pela sua respectiva tela.

**Comment by ItaloRod** [comment]
Para simular o login correto, colocamos um email e senha de teste ("teste@teste.com", "12345678"). Qualquer usuário fora esse, ele estará incorreto no sistema.

**Comment by ItaloRod** [comment]
estamos em dúvida quando o usuário errar a senha. Seria interessante limpar os campos quando isso acontecer. Impactaria positivamente ou negativamente na experiência do usuário?

**Comment by laurapmelo** [comment]
> estamos em dúvida quando o usuário errar a senha. Seria interessante limpar os campos quando isso acontecer. Impactaria positivamente ou negativamente na experiência do usuário?

acho que faz sentido, se não aumentar muito a complexidade!

-> podemos mudar o redirecionamento da página quando o login é efetivado? para ir para a página de perfil (card #240)?

**Comment by mbernardes19** [comment]
Tarefa aprovada em desk check, porém falta (para próxima sprint):
- Loading ao logar e ao deslogar;

**Comment by matheuscpl** [comment]
Encontrei esse erro no estado ativo dos campos de preenchimento, a label está indo pra trás da linha do componente e a descrição não some de dentro do campo:

![WhatsApp Image 2020-08-18 at 10 27 53](https://user-images.githubusercontent.com/64148308/90518786-965aa900-e13d-11ea-91d5-5dbdb2c790a7.jpeg)

O comportamento comum seria (Fale Conosco):

![WhatsApp Image 2020-08-18 at 10 27 53 (1)](https://user-images.githubusercontent.com/64148308/90518966-ce61ec00-e13d-11ea-80f7-6d489e4d5bb0.jpeg)

**Comment by laurapmelo** [comment]
>>>>>>Encontrei esse erro no estado ativo dos campos de preenchimento, a label está indo pra trás da linha do componente e a descrição não some de dentro do campo:

#272

**Comment by KelmaSouto** [comment]
Informo que fiz o cadastro completo sem nenhum impedimento e ao tentar fazer o login recebi a msg que não é possível acessar.

**Comment by mbernardes19** [comment]
Quando insiro meu email no campo de login usando o autocomplete do teclado, continua aparecendo a mensagem de que é um email inválido. Porém, mesmo assim, ele me permite tentar realizar o login depois de preencher a senha (comportamento verificado em celular físico Android).

![qa-login](https://user-images.githubusercontent.com/26047592/91719054-010eda00-eb6b-11ea-817d-29119dc482b2.gif)

**Comment by mbernardes19** [comment]
Demora na finalização do login após o clique no botão "Fazer login" dá a impressão de que o app parou por alguns instantes. Ter um indicador de loading como o do botão da tela de Fale Conosco resolveria o problema.

Testado em: dispositivo físico Android
Versão do app: 3.10.0

![loading-login](https://user-images.githubusercontent.com/26047592/92000471-e9268a00-ed13-11ea-9337-42bde9b67d94.gif)

**Comment by mbernardes19** [comment]
Percebi ao testar tanto no emulador quanto no dispositivo físico no Android que depois de um tempo usando o app, ao clicar nos links do menu lateral, meus clicks não são reconhecidos e não acontece a navegação. Porém, os últimos dois links (Termos de Uso e Compartilhe o iSUS) continuam clicáveis e navegáveis mesmo assim.

Testado em: emulador e dispositivo físico Android
Versão do app: 3.10.0

![erro-navegacao-lateral](https://user-images.githubusercontent.com/26047592/92026118-e9844c80-ed36-11ea-9e42-f78bd682966a.gif)

**Comment by mbernardes19** [comment]
**Todas as correções foram feitas na branch `#260-feature/#260-implementar-tela-de-informacoes`**

**Comment by KelmaSouto** [comment]
Dado abro o App "sem estar logada" 
Quando clico no botão "Meu Perfil"
Então sou direccionada para a página do "ID Saúde", opções: Realizar Meu cadastro ou JáPossuo ID Saúde

Quando clico em "Já Possuo ID Saúde"
Então sou direcionada para o slide "ID Saúde" opção: Fazer Login

Quando preencho meu "e-mail e senha" (o app já tem os dados salvos)
Então clico em "Fazer Login"
sou direcionada o slide "perfil" 

Comportamento atual: quando clico em "Fazer Login", necessito de dois cliques para a operação ser concluída. 
Comportamento esperado: quando eu clicar em "Fazer Login", apenas com hum clique, a operação seja concluída.

**Comment by KelmaSouto** [comment]
Ready for QA em Android 9, dispositivo LG K40S por Kelma Souto - Versão 3.10.3 - [BUG- QA] Implementar tela de login #242
Bug Dev

Dado abro o App "sem estar logada"
Quando clico no botão "Meu Perfil"
Então sou direccionada para a página do "ID Saúde", opções: Realizar Meu cadastro ou JáPossuo ID Saúde

Quando clico em "Já Possuo ID Saúde"
Então sou direcionada para o slide "ID Saúde" opção: Fazer Login

Quando preencho meu "e-mail e senha" (o app já tem os dados salvos)
Então clico em "Fazer Login"
sou direcionada o slide "perfil"

Comportamento atual: quando clico em "Fazer Login", necessito de dois cliques para a operação ser concluída.
Comportamento esperado: quando eu clicar em "Fazer Login", apenas com hum clique, a operação seja concluída.

Parecer final: Informo que refiz o teste a fim de revalidar a resultado posterior, no entanto o resultado não modificou. 
Convido qualquer colega do Time iSUS para que possamos parearmos e refazermos juntos, tks.

**Comment by ItaloRod** [comment]
Observamos que o Duplo click na verdade é uma ausência de resposta ao usuário de que a requisição de cadastro está sendo realizada. Por isso, foi  adicionado um loading no botão de finalização do cadastro.

**Comment by KelmaSouto** [comment]
Ready for QA em Android 9, dispositivo LG K40S por Kelma Souto - Versão 3.10.5 
Atividade/Card: [BUG- QA] Implementar tela de login #242


                          **Escopo: logar com apenas um click no botão de login (Android)**


**Quando preencho meu e-mail e senha na página de login**
**Comportamento atual:** conseguir realizar o login com um click simples no botão "login"

**Comportamento esperado:** conseguir realizar o login com um click simples no botão "login"
