### ISSUE TITLE
[BUG- QA] Criar Tela de cadastro de dados profissionais - front

### ISSUE THREAD

**Issue by ItaloRod** [EscolaDeSaudePublica/isus-app#243]
### **Objetivo** 
**Eu como** Profissional de saúde
**Eu Quero** me cadastrar
**Para que** eu possa ter acesso a conteúdo personalizado

### **Contexto**
Queremos saber quem são os usuários do iSUS para melhor direcionar conteúdos e propiciar um acesso único a diversos serviços. Inicialmente vamos focar o cadastro em profissionais de terapia intensiva. Essa tela tem como objetivo saber os dados profissionais da usuária.

**Dependência**
A tarefa #260  cria uma estrutura da qual este cadastro é dependente. Antes da implementação, verificar implementação.

### **Escopo**
- [x] página de cadastro - redirecionar para está página quando for clicado em próximo na página de informações pessoais (#260 )
![image](https://user-images.githubusercontent.com/67436275/89838063-aae8e100-db40-11ea-9cbc-f66cddee1385.png)

- [x] Campo de categoria profissional: dropdown com opções
*Categoria profissional
- Medicina
- Fisioterapia
- Enfermagem
- Terapia Ocupacional
- Farmácia
- Coordenação Clínica
- Coordenação de Enfermagem
- Outra

![image](https://user-images.githubusercontent.com/67436275/89838077-b6d4a300-db40-11ea-98ec-1ba031132e37.png)

- [x] Serviços em que atua: acordeon com select que permite múltiplas respostas. 
![image](https://user-images.githubusercontent.com/67436275/89838085-bdfbb100-db40-11ea-8478-37b0846b22da.png)

- [x] botão de próximo que está sempre habilitado

- [x] dados salvos em cache quando a usuária clica em próximo

### **Critérios de Aceitação**
- [x] redirecionamento
**Dado que** preenchi meus dados corretamente na página de informações pessoais
**Quando** clico em próximo
**Então** sou redirecionada para a página de cadastro de infos profissionais

- [ ] serviço
**Dado que** quero preencher o serviço em que atuo
**Quando** clico no acordeon 
**Então** o topo dele fica fixado no topo da tela

- [x] serviço
**Dado que** o acordeon de serviço está aberto
**Quando** clico no topo dele
**Então** volto para a tela de dados profissionais e o acordeon é fechado

- [x] serviço
**Dado que** o acordeon de serviço está aberto
**Quando** clico escolho um serviço
**Então** o acordeon segue aberto e posso selecionar outras opções

- [x] dados não selecionados
**Dado que** não selecionei uma categoria profissional ou pelo menos um serviço
**Quando** tento clicar em próximo
**Então** o botão está habilitado

- [x] botão habilitado
**Dado que** selecionei uma categoria profissional **e** um ou mais serviços
**Quando** finalizo
**Então** o botão está habilitado

- [x] cache
**Dado que** preenchi os dados corretamente 
**Quando** clico em próximo
**Então** os dados que inseri são salvos na memória local

Protótipo:
https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=1550%3A7606
Dados: 
https://docs.google.com/presentation/d/1-AbnLgRmKIoGcKUoEriFnUFY2-OWkc_pspQcN_kOPt4/edit#slide=id.g86a325bfdc_0_20

### **BUGS-QA**
- [ ] usuários ser capaz de selecionar quantos itens quiser no campos Serviços em que atua **(IOS e Android)**
Dentro da tela de cadastro de dados profissionais, ao selecionar no campo Serviços em que atua 
**Comportamento atual:** se o usuário selecionar muitas opções no campo Serviços em que atua ele não é capaz de realizar seu cadastro, ao clicar no botão de Finalizar na tela de criação de senha.
**Comportamento esperado:** usuário deve ser capaz de selecionar quantos itens quiser no campo de Serviços em que atua e o cadastro ser criado.

Épico: #134 -

**Comment by laurapmelo** [comment]
Pessoal, o campo de Serviços em que atua tem uns 30 itens, talvez seja interessante acessar uma dialog ao check box pra fica mais amigável, ou alguma outra solução nesse estilo. Podem me procurar se precisar.

**Comment by ItaloRod** [comment]
Tarefa bloqueada esperando integração com outras tarefas

**Comment by laurapmelo** [comment]
agora já podemos integrar, certo?

**Comment by ItaloRod** [comment]
Integrado com a #260

**Comment by KelmaSouto** [comment]
blob:https://web.telegram.org/e39ef58d-0321-424b-b078-5a6dc05ff27e

Aparece uma traja cinza sem nenhuma imagem.

**Comment by kurjes** [comment]
BUG IOS e Android: No campo "serviços em que atua" quando o usuário seleciona muitas opções(a partir de 7) não é possível realizar o cadastro. Não aparece nenhuma mensagem de erro, apensar uma snackbar vazia quando clicamos em finalizar na tela de senha. 

pareando com @daianefreira

**Comment by KelmaSouto** [comment]
![Fazer Login ID Saúde](https://user-images.githubusercontent.com/65924048/91860901-9761ff00-ec42-11ea-8fc3-d40c43693a37.jpg)

**Comment by KelmaSouto** [comment]
![Tela_ID Saúde_Recuperar senha_Voltar para o aplicativo](https://user-images.githubusercontent.com/65924048/91861292-050e2b00-ec43-11ea-9649-478a9d3f2c5a.jpg)

**Comment by KelmaSouto** [comment]
![Tela_Inicial_Bem-vindo ao ID Saúde_Acessar](https://user-images.githubusercontent.com/65924048/91861701-7fd74600-ec43-11ea-8f32-bb627ac195ae.jpg)

**Comment by KelmaSouto** [comment]
![Tela_ID Saúde_Meno_Inicial_Conta](https://user-images.githubusercontent.com/65924048/91862102-eb211800-ec43-11ea-8bfd-bd8e4c46cb2a.jpg)

**Comment by KelmaSouto** [comment]
![Tela_ID Saúde_Meno_Inicial_Conta_Endereço](https://user-images.githubusercontent.com/65924048/91862246-14da3f00-ec44-11ea-8407-24d41a44a51d.jpg)

**Comment by KelmaSouto** [comment]
![Tela_ID Saúde_após salvar novamente dos dados de endereço residencial e quando tento salvar](https://user-images.githubusercontent.com/65924048/91862728-b792bd80-ec44-11ea-9ea9-d55a3ef2c59a.jpg)

**Comment by mbernardes19** [comment]
Descobri que a causa do problema de não conseguir adicionar mais de 6 opções no campo de Unidades de Serviço no cadastro é que os atributos de usuário do Keycloak, que são os campos onde guardamos os dados dos usuários que criamos, não aceitam strings com tamanho maior que 255 caracteres.

<img width="1372" alt="Screen Shot 2020-09-03 at 16 21 26" src="https://user-images.githubusercontent.com/26047592/92157952-90cdb600-ee01-11ea-81f5-75515ea915b0.png">

**Comment by mbernardes19** [comment]
Conclusão: Para resolver este bug, ao cadastrar o usuário, vamos fazer com que:
1 - Seja criado um usuário no Keycloak apenas os dados obrigatórios do usuário (ou seja, os dados pessoais);
2 - Seja criado um usuário no banco de dados da API do iSUS com todos os dados;

E depois vamos fornecer esses dados completos do usuário da API do iSUS para o app através de um endpoint.

**Comment by KelmaSouto** [comment]
Comportamento atual: selecionei 14 categorias profissionais e os dados que inseri ficaram salvos na memória local. 

Comportamento esperado: selecionei 14 categorias profissionais e os dados que inseri ficaram salvos na memória local.                       Parabéns, login realizado com sucesso!

Observação: conta utilizada -> kelma.souto@esp.ce.gov.br
                                              senha: 12345678
