### ISSUE TITLE
[BUGS QA] Adicionar a versão do app às mensagens

### ISSUE THREAD

**Issue by drmarcos** [EscolaDeSaudePublica/isus-app#249]
### **Objetivo**
Devemos criar nas mensagens de feedbacks,  quer seja nas versões teste,  ou em produção, uma forma de que junto com a mensagem seja enviada a informação da versão  do app usado.
Acredito que como seja algo fácil de ser resolver, podemos usar esse formato em toda e qualquer interação feita no App, isto é sempre que o usuário enviar uma mensagem para a equipe

### **Escopo**
- [x] adicionar informação de versão de app no corpo do email de feedback (nos três tipos)
- [x] informar se o sistema é IOS ou Android

### BUGS- QA
Feedbacks e alertas de EPI estão sendo enviados sem a versão do app e a plataforma (Android ou iOS) de onde foram enviadas. É necessário verificar por que esta funcionalidade não está mais funcionando na versão 3.10.1.

**Comment by drmarcos** [comment]
Uma curiosidade:
Os números das versões são diferenciadas para os dispositivos?
Pelo que pude ver não são.
Dessa forma acho que seria de grande valor acrescentarmos no envio de tickets qual o dispositivo usado para o envio de feedback.
IOS, Androide, Tablet.....
Importante lembrar que como estamos elaborando termos de uso e políticas de privacidade isso deverá constar no(s) texto(s)

**Comment by drmarcos** [comment]
Versão não aparece nas mensagens
Ainda não temos como identificar de onde vem o feedback e nem a versão:
Um exemplo de como chega ao freshdesk:
"Esp.coronavirus relatado por e-mail
há 2 horas (Qua, 2 Set 2020 na (o) 11:31 AM)
 
Para:feedback.isus@esp.ce.gov.br
ISUS APP - FEEDBACK 02/09/2020 14:31:40
Categoria: Alerta
Texto: Realizando teste de feedback
E-mail usuário: victor.magalhaesp@gmail.com"

**Comment by kurjes** [comment]
> Versão não aparece nas mensagens
> Ainda não temos como identificar de onde vem o feedback e nem a versão:
> Um exemplo de como chega ao freshdesk:
> "Esp.coronavirus relatado por e-mail
> há 2 horas (Qua, 2 Set 2020 na (o) 11:31 AM)
> 
> Para:[feedback.isus@esp.ce.gov.br](mailto:feedback.isus@esp.ce.gov.br)
> ISUS APP - FEEDBACK 02/09/2020 14:31:40
> Categoria: Alerta
> Texto: Realizando teste de feedback
> E-mail usuário: [victor.magalhaesp@gmail.com](mailto:victor.magalhaesp@gmail.com)"

Marcos eu acabei de mandar uma mensagem de feedback utilizando a versão 3.10.1, gostaria de que o senhor postasse aqui como ela está chegando. Estou utilizando IOS.

**Comment by mbernardes19** [comment]
Acessando o email, vi o email que chegou do feedback que a @kurjes enviou e também enviei 2 feedbacks (problema e sugestão) e 1 alerta de um dispositivo físico Android usando o app na versão 3.10.1. Todos eles foram sem versão e plataforma.

Vou voltar este card para To Do para que possam verificar o que houve com este.

**Comment by ItaloRod** [comment]
![image](https://user-images.githubusercontent.com/20058085/92749674-b8ba9d80-f35c-11ea-81ad-c27db379f612.png)
![image](https://user-images.githubusercontent.com/20058085/92749962-fe776600-f35c-11ea-8a51-38ca4b79ae80.png)
Realizamos os teste da branch #249 no isus-api. Todos os testes deram certo e enviaram corretamente a plataforma e a versão do

**Comment by drmarcos** [comment]
Que tal incluir de qual Aplicativo está sendo enviado?
Tipo : Produção, Teste BETA, Teste Fechado e por ai vai.
Um pequeno detalhes que pode fazer uma boa diferença no final
Vi na Imagem do @ItaloRod que já temos os seguintes  parâmetros sendo passados:

*Tipo de feedback
*Texto
*Email
*Versão do aplicativo
*Plataforma

º Sugiro algo como *Categoria (Produção/Testes: Tipo Beta/Testes:Tipo Fechado)

**Comment by KelmaSouto** [comment]
![Ready for QA for iSUS - Kelma Souto - Card 249 - Imagem 1](https://user-images.githubusercontent.com/65924048/93077877-dee38480-f65f-11ea-974f-64f0e83e0f9d.jpg)

**Comment by KelmaSouto** [comment]
![Ready for QA for iSUS - Kelma Souto - Card 249 - Imagem 2](https://user-images.githubusercontent.com/65924048/93077919-f15dbe00-f65f-11ea-88f8-4fd931c10dee.jpg)

**Comment by KelmaSouto** [comment]
Comportamento atual:  preenchi os campos: Tipo de ocorrência, Reporte o erro ..., Anexar imagem, Email (chamo atenção que o email fica com a primeira letra em maiúscula).  


Comportamento esperado: que apresentasse os campos: Tipo de ocorrência (sugiro que continue e que já está ok), Reporte o erro ... (sugiro que continue e que já está ok), Email (falta, sugiro que a fonte da letra fique sempre toda minúscula); Versão do aplicativo (falta implementar); Plataforma (falta implementar).
