### ISSUE TITLE
Criar Política de Privacidade do ID Saúde

### ISSUE THREAD

**Issue by laurapmelo** [EscolaDeSaudePublica/isus-app#250]
### **Contexto**
Com a implementação de um perfil dos usuários, precisamos de uma política de privacidade explicando sobre os dados coletados e como eles serão utilizados pelo iSUS/SESA/ESP.

Inspiração
https://login.sabia.ufrn.br/politica_de_privacidade/

Arquivo para edição
https://docs.google.com/document/d/1e_z0J--fAdXkivAYqNKXrIcAC9SBxxofI1HhBjIJIoQ/edit#heading=h.xd1gqyruw92b

**Comment by uira** [comment]
@laurapmelo Una dúvida: 
precisamos de dois termos de uso? 

Um do ID Saúde e outro do ISUS?

**Comment by laurapmelo** [comment]
Pois então, eu pensei nisso escrevendo esses cards. Talvez faça sentido..
