### ISSUE TITLE
Adicionar ícone de 'Alerta de EPI' na home

### ISSUE THREAD

**Issue by matheuscpl** [EscolaDeSaudePublica/isus-app#252]
# Objetivo
Adicionar ícone de Alerta de EPI na home, como um botão

# Escopo

- [x] Adicionar novo botão na home, no grupo de Força-tarefa Anticorona, como atalho para o Alerta de EPI

![Screenshot_22](https://user-images.githubusercontent.com/64148308/89411897-90f06e00-d6fc-11ea-841c-47549f115f07.png)

ícone: [icon_epi.zip](https://github.com/EscolaDeSaudePublica/isus-app/files/5028271/icon_epi.zip)

# Critério de aceite

- [ ] **Dado que** faça scroll na home
**Quando** eu clico em "Alerta de EPI"
**Então** sou direcionado ao "Fale Conosco" com o tipo de ocorrência "Alerta de falta de EPI" já selecionado

**Comment by kurjes** [comment]
Dado que foi retirado o alerta API do nosso menu e houveram discursões sobre a efetividade desse atalho. Faz sentido esse card? @uira
