### ISSUE TITLE
Meus Conteúdos-Mais cursos e artigos  específicos para cada área.

### ISSUE THREAD

**Issue by drmarcos** [EscolaDeSaudePublica/isus-app#255]
Ter mais cursos e artigos que seja mais específico para cada área.

https://felicilab.freshdesk.com/a/tickets/37

integrar novas fontes???

**Comment by laurapmelo** [comment]
Acho que aqui faz sentido respondermos que estamos trabalhando para que o usuário possa informar qual a sua área de atuação e que assim o conteúdo oferecido seja mais personalizado para cada perfil.
@uira o que acha?

**Comment by uira** [comment]
@laurapmelo Perfeição em forma de réplica de feedback... 

😍😍

**Comment by ericsonmoreira** [comment]
@uira qual o contexto dessa atividade? Ela faz parte do desenvolvimento ou da geração de conteúdos?

**Comment by Laysacunha** [comment]
@Clarisse1983 e @ericabpinho em alinhamento com Washington percebemos que se trata de tarefa de narrativas. A implementação técnica será tratada na #369. Fechando a issue.
