### ISSUE TITLE
Na seção Educação, Tutoriais, os vídeos e PDFs....

### ISSUE THREAD

**Issue by drmarcos** [EscolaDeSaudePublica/isus-app#256]
##**Contexto**
Os vídeos da seção de educação ficam cortados na tela pq não são ajustados à tela. Precisamos verificar se esse problema de responsividade está no nosso app ou no wordpress, de onde o conteúdo vem.

**Escopo**
- Caso a responsividade esteja dentro do nosso escopo, corrigir
- Caso não esteja, informar o usuário (pessoal do helpdesk deve fazer)

Como verificar o problema:
home do app -> educação -> tutoriais -> "entenda como funciona o uso de dispositivos inalatórios.."
![image](https://user-images.githubusercontent.com/67436275/91358651-8a1fbd00-e7c9-11ea-9ecd-460aa0f1af98.png)

**Conteúdo** do feedback:
Categoria: Problemas
Texto: tarso.leite@cb.ce.gov.br
E-mail usuário: Na seção Educação, Tutoriais, os vídeos e PDFs não estão ajustados para a largura do dispositivo, dificultando a visualização.

https://felicilab.freshdesk.com/a/tickets/22

**Comment by nicoledbianchin** [comment]
O problema está no iframe da tag <p> em que o link do vídeo vem. Atualmente ele está com `width=\"1080\" height=\"608\"`. É preciso apagar esses parâmetros no Wordpress, e o conteúdo ficará responsívo :)
