### ISSUE TITLE
Mensagens de feedbacks com valores em posição trocada

### ISSUE THREAD

**Issue by drmarcos** [EscolaDeSaudePublica/isus-app#257]
Percebi que as mensagens tem um pequeno erro na exibição dentro do freshdesk.
Será na ferramenta ou nos campos do form?
Categoria: Problemas

-----> (Texto): email@enviado

-----> (E-mail usuário): Texto explicando...........

**Comment by ItaloRod** [comment]
foi feito testes na issue #249 e não conseguimos reproduzir o erro apresentado.

**Comment by ItaloRod** [comment]
Realizamos os testes tanto no android (3.10.0) quanto no iOS (3.8.2) e não foi apresentado nenhum problema relacionado ao reportado. Verificamos também que os emails enviados conforme apresentado são datados do inicio de junho. Logo, esse erro já foi resolvido.

**Comment by drmarcos** [comment]
Verdade, percebi que foi realmente resolvido.
Infelizmente essas coisa aconteceram por que começamos a gerenciar os feeds agora e haviam muitas mensagens acumuladas.
Com as mensagens não carregam a versão do App na ocasião do envio, não tínhamos como saber o que estava resolvido ou não.
Aproveito para reforçar a ideia de que devemos obter esses dados (versão/produção/testes abertos/testes/privados) nos envios das mensagens para que possamos reportar corretamente, tornando o processo mais ágil
