### ISSUE TITLE
[BUG- QA] Implementar tela de Informações pessoais do cadastro - front

### ISSUE THREAD

**Issue by laurapmelo** [EscolaDeSaudePublica/isus-app#260]
### **Objetivo**
**Como** uma usuária
**Quero** inserir meus dados pessoais
**Para** realizar meu cadastro no ID Saúde

### **Contexto**
Estamos realizando a integração com o keycloack através de dados fixos no backend. Este card tem como objetivo permitir que os dados pessoais do cadastro possam ser inseridos pela usuária ao realizar o cadastro.
 
### **Escopo**
- [x] acesso a esta página através do botão "realizar meu cadastro" #242 
![image](https://user-images.githubusercontent.com/67436275/89585671-a658bb80-d814-11ea-93d6-31a626d42a6b.png)

- [x] Criar tela para cadastro de dados pessoais
![image](https://user-images.githubusercontent.com/67436275/89581569-9e494d80-d80d-11ea-9142-c5f8c7e5d847.png)

- [x] Campo nome: permite apenas letras

- [x] Campo email: verificação de formato ao sair do campo

- [x] Telefone: campo com máscara que aceita os formatos (XX)XXXXX-XXXX e (XX)XXXX-XXXX

- [x] Município: lista de municípios do ceará, autocomplete

- [x] CPF, campo com máscara 

- [x] botão "próximo" é habilitado quando todos os campos são preenchidos

- [x] salvar dados em cache quando o usuário clica em próximo

### **Critérios de Aceitação**
- [x] Acessa página
**Dado que** quero fazer meu cadastro
**Quando** clico em "Realizar meu cadastro"
**Então** sou redirecionada para a página de informações pessoais

- [x] Dados preenchidos corretamente
**Dado que** estou na página de infos pessoais
**Quando** preencho todos os campos corretamente
**Então** o botão de próxima página se habilita

- [x] campo nome - caracteres especiais ou números
**Dado que** estou na página de infos pessoais
**Quando** adiciono algum número ou caractere especial no campo "nome"
**Então** vejo uma mensagem de erro

- [x] campo em branco
**Dado que** deixei algum campo em branco
**Quando** tento clicar em próxima página
**Então** o botão está desabilitado

- [x] email com erro no formato
**Dado que** insiro um email com formato incorreto (por ex: laura.com ou  laura@com)
**Quando** vou para o próximo campo
**Então** vejo uma sinalização de que os dados estão incorretos

- [x] telefone com erro 
**Dado que** inseri um número menor de dígitos que o obrigatório
**Quando** saio do campo
**Então** vejo uma sinalização que os dados estão incorretos

- [x] cpf com erro
**Dado que** inseri um número menor de dígitos que o obrigatório
**Quando** saio do campo
**Então** vejo uma sinalização que os dados estão incorretos
 
- [x] autocomplete municípios - digitação
**Dado que** estou na página de infos pessoais
**Quando** digito algo no autocomplete
**Então** os municípios são filtrados de acordo com o que inseri no campo

- [x] autocomplete municípios
**Dado que** estou no campo de municípios
**Quando** insiro caracteres que não correspondem a nenhum município da base
**Então** vejo uma mensagem de erro 

- [x] dados salvos na memória local (por x horas)
 **Dado que** inseri os dados corretamente
**Quando** clico em próximo
**Então** os dados são salvos em memória local

### **BUGS-QA**
- [x] digitar/apagar caracteres no campo Nome Completo sem caracteres engasgarem **(IOS e Android)**
Dentro da tela de cadastro de dados pessoais, ao digitar/apagar no campo Nome Completo 
**Comportamento atual:** se o usuário deixa para preencher o campo Nome Completo por último os caracteres engasgam ao serem digitados, o mesmo comportamento ocorre quando os caracteres são apagados.
**Comportamento esperado:** usuário ser capaz de preencher o campo de Nome Completo sem engasgar os caracteres, independente da ordem que os campos da tela sejam preenchidos.

- [x] apagar DDD no campo telefone  **(IOS e Android)**
Dentro da tela de cadastro de dados pessoais, ao apagar os dados no campo de telefone
**Comportamento atual:** a parte do DDD não é apagada. O usuário só consegue apagar se selecionar todos os dados do campo.
**Comportamento esperado:** que todos os dados sejam apagados apensa utilizando o botão de apagar do teclado.

OBS.: @mbernardes19 e @nicoledbianchin verificamos que o comportamento inesperado só acontece no emulador de iOS, mas nos dispositivos não.

- [x] apagar máscara do campo de telefone com um clique simples **(IOS e Android)**
Dentro da tela de cadastro de dados pessoais, ao apagar os dados do campo de telefone 
**Comportamento atual:** os caracteres da máscara são apagados apenas com um duplo clique
**Comportamento esperado:** que os caracteres da máscara sejam apagados com um clique simples

OBS.: @mbernardes19 e @nicoledbianchin verificamos que o comportamento inesperado só acontece no emulador de iOS, mas nos dispositivos não.

- [x] apagar máscara do campo de CPF com um clique simples **(IOS e Android)**
Dentro da tela de cadastro de dados pessoais, ao apagar os dados do campo de CPF 
**Comportamento atual:** os caracteres da máscara são apagados apenas com um duplo clique
**Comportamento esperado:** que os caracteres da máscara sejam apagados com um clique simples

OBS.: @mbernardes19 e @nicoledbianchin verificamos que o comportamento inesperado só acontece no emulador de iOS, mas nos dispositivos não.

- [x] mostrar lista no campo de município mesmo quando ela for de 1 item **(Android)**
Dentro da tela de cadastro de dados pessoais, ao digitar no campo município 
**Comportamento atual:** se a lista de cidades for pequena (1 cidade. Ex: Farias Brito), a lista não aparece para o usuário
**Comportamento esperado:** que a lista seja mostrada para o usuário independente do número de itens

- [x] mostrar caracteres digitados  no campo município **(IOS)**
Dentro da tela de cadastro de dados pessoais, ao digitar no campo município 
**Comportamento atual:** ao digitar no campo de município os caracteres não são mostrados para o usuário
**Comportamento esperado:** ao digitar o usuário consiga ver o que o que esta no campo

- [x] mostrar placeholder dentro do campo de município **(IOS)**
Dentro da tela de cadastro de dados pessoais, no campo município 
**Comportamento atual:** não é possível enxergar a placeholder dentro do campo município 
**Comportamento esperado:** o usuário consiga  enxergar a placeholder dentro do campo de município

- [x] placeholder centralizada dentro do campo de município **(Android)**
Dentro da tela de cadastro de dados pessoais, no campo município 
**Comportamento atual:** a placeholder dentro do campo de município não está centralizada
**Comportamento esperado:** a placeholder dentro do campo município esteja centralizada

- [x] teclado não cobrir a lista de municípios **(IOS e Android)**
Dentro da tela de cadastro de dados pessoais, ao digitar no campo município 
**Comportamento atual:** a lista de municípios é encoberta pelo teclado e o usuário não consegue entender que existe uma lista. (Esse comportamento ocorre nos dois ambientes mas é pior no Android)
**Comportamento esperado:** itens da lista de município não fiquem por  trás do teclado quando o usuário estiver digitando

- [x] selecionar o item da lista de municípios com o clique simples **(IOS e Android)**
Dentro da tela de cadastro de dados pessoais, no campo município 
**Comportamento atual:** o  usuário precisa de um duplo clique para que o item da lista de município seja selecionado
**Comportamento esperado:** item da lista de municípios seja selecionado com um clique simples

- [x] usuário conseguir visualizar toda a lista de cidades no campo Município  **(Android)**
Dentro da tela de cadastro de dados pessoais, ao digitar no campo município 
**Comportamento atual:** ao digitar o usuário não consegue visualizar toda a lista de cidades (Ex: T)
**Comportamento esperado:** usuário conseguir visualizar todos os itens da lista de cidades que forem match dos caracteres digitados. 

Épico: #134 Perfil

**Comment by uira** [comment]
Importante que a label seja 'Município de Residência', pra deixar claro que trata-se do município da moradia principal daquele profissional.

**Comment by kurjes** [comment]
Para resolver o bug do telefone e no cpf temos que remover o js da máscara e usar algo do react. pareando com @mbernardes19

**Comment by kurjes** [comment]
Bug Android: Quando digitado o número de telefone e o usuário apaga, ao sair do campo o app adiciona o parêntese novamente, mesmo o campo estando vazio e não selecionado. 

pareando com @daianefreira

**Comment by kurjes** [comment]
Questão para depois: modo de divisão de tela no android é para funcionar? 

pareando com @daianefreira

**Comment by kurjes** [comment]
Bug de Android: No campo de telefone ao apagar o número quando chegamos nos caracteres da mascara não conseguimos apagar com o único toque, temos que clicar em apagar 2 vezes para o caractere suma. 

pareando com @daianefreira

**Comment by kurjes** [comment]
Bug IOS: No campo de telefone quando vou apagar o número e chego na parte do DDD eu não consigo apagar, tenho que clicar em selecionar os caracteres e apago, mas mesmo assim ainda fica o parêntese inicial. Para que esse parênteses inicial suma tenho que dar um duplo toque em apagar. 

pareando com @daianefreira

**Comment by kurjes** [comment]
Bug IOS e Android: No campo de CPF os caracteres da máscara não são apagados com um único top, apenas com um duplo

pareando com @daianefreira

**Comment by kurjes** [comment]
Bug Android: No campo de município se a lista for pequena(uma cidade) não aparece as opções para o usuário clicar. Ex: Farias Brito

pareando com @daianefreira

**Comment by kurjes** [comment]
Bug IOS: Ao digitar no campo de município os caracteres não são mostrados para o usuário. Mas a lista de municípios aparece para ser selecionada. 

pareando com @daianefreira

**Comment by kurjes** [comment]
Bug IOS: A lable dentro do campo município não aparece. 

pareando com @daianefreira

**Comment by kurjes** [comment]
Bug Android: A lable dentro do campo município não esta centralizada. 

pareando com @daianefreira

**Comment by kurjes** [comment]
Bug Android e IOS: Ao digitar no campo de município a lista aparece por trás do teclado e o usuário não entende que ela existe a não ser que ele dê scroll na tela. 

pareando com @daianefreira

**Comment by kurjes** [comment]
Bug IOS e Android: Ao clicar na lista no campo município não seleciona de primeira, tem que clicar duas vezes.

Melhoria para usuário de Android: A lista de municípios está com os itens muito próximos e o usuário pode ter dificuldade de clicar

pareando com @daianefreira

**Comment by ilizakoski** [comment]
Encontramos o componente [searchBar](https://callstack.github.io/react-native-paper/searchbar.html). Que se comporta parecido com o autocomplete.  Mas é mais intuitivo e seria mais fácil de implementar.
Como é da biblioteca do **paper** também o estilo ficaria igual.
Pensamos em fazer alguns testes e se tudo tiver ok implementar no lugar do autocomplete

**Comment by victorMagalhaesPacheco** [comment]
> Encontramos o componente [searchBar](https://callstack.github.io/react-native-paper/searchbar.html). Que se comporta parecido com o autocomplete.  Mas é mais intuitivo e seria mais fácil de implementar.
> Como é da biblioteca do **paper** também o estilo ficaria igual.
> Pensamos em fazer alguns testes e se tudo tiver ok implementar no lugar do autocomplete

Essa lib pode ajudar? https://www.npmjs.com/package/react-native-dropdown-picker

**Comment by kurjes** [comment]
Bug IOS e Android: Se o campo de Nome Completo for deixado para ser preenchido por último os caracteres ficam engasgando. 

[link com o vídeo IOS](https://drive.google.com/file/d/1Hhs1orqzc_7vgmLhZNwuo8DiK2ZAbiIc/view?usp=sharing)

feedback de @drmarcos

**Comment by kurjes** [comment]
Bug Android: Ao preencher o campo de Municípios o usuário não é consegue enxergar todos os itens da lista, também não é possível dar scroll dentro da lista.

![lista](https://user-images.githubusercontent.com/69155423/91611927-b7e43d80-e952-11ea-941e-6c040b1ac6af.png)

feedback de @drmarcos

**Comment by KelmaSouto** [comment]
![Ready for QA em Android por Kelma Souto - Versão 3 10 3 - front #260](https://user-images.githubusercontent.com/65924048/93133408-8d61e680-f6ad-11ea-9a34-8111a241266d.jpg)

**Comment by KelmaSouto** [comment]
Ready for QA em Android por Kelma Souto

Versão 3.10.3

Comportamento atual: cadastro realizado com sucesso.  
Comportamento esperado: cadastro realizado com sucesso.
