### ISSUE TITLE
Melhoria na seção 'SUS no Ceará' (texto e links)

### ISSUE THREAD

**Issue by matheuscpl** [EscolaDeSaudePublica/isus-app#262]
# Objetivo
**Eu como** profissional da saúde do Ceará
**Quero** ter acesso a informações dos órgãos responsáveis pela saúde pública no meu estado
**Para que** possa me manter informado e atualizado sobre suas iniciativas

# Contexto
Uma nova narrativa na seção 'SUS no Ceará' foi criada para tornar a informação mais fácil de ser consumida. Alterações nos labels e texto, além da adição de links para redes sociais.

# Escopo

- [x] Retirar o texto explicativo e alterar as labels do acordeon

![Screenshot_32](https://user-images.githubusercontent.com/64148308/89896594-161fcb00-dbb4-11ea-93ab-128de2dc47fe.png)

- [x] Alterar textos dentro de cada seção, adicionando os links nos mesmos

![Screenshot_33](https://user-images.githubusercontent.com/64148308/89898320-e1614300-dbb6-11ea-9782-427296c0ce5d.png)

- [x] Adicionar lista com ícones com links para redes sociais

![Screenshot_34](https://user-images.githubusercontent.com/64148308/89898419-153c6880-dbb7-11ea-9139-6b4574148df0.png)

- [x] números de telefone devem ser clicáveis e redirecionarem para o discador do telefone

# Critérios de aceite

- [x] **Dado que** acesse a tela SUS no CE
**Quando** clico em O iSUS é ESP
**Então** o acordeon expande exibindo o texto a que refere

- [x] **Dado que** esteja lendo o texto
**Quando** clico em um link no texto
**Então** abre o webview com o respectivo url

- [x] **Dado que** esteja lendo o texto
**Quando** clico em um item da lista de redes sociais
**Então** abre o webview com o respectivo url

- [x] **Dado que** esteja lendo o texto de A ESP É SESA
**Quando** faço um scroll até o fim da página
**Então** há uma margem entre o fim texto e a parte inferior da tela do meu smartphone

- [x] **dado que** esteja lendo o texto
**quando** clico em um dos telefones
**então** sou redirecionado para o discador do telefone e o número selecionado está digitado

# Notas 
Protótipo: https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=1691%3A6044

Texto: https://docs.google.com/document/d/1svbOm46TsX8d2ZgOGO-ste79JAZv4WCt1KHPl4wtquY/edit

Links: https://docs.google.com/spreadsheets/d/1CqqiVEWH-YchqFSTlx3NN5zG7RBpvPRUkGo_CCyLThw/edit#gid=250852473

**Comment by uira** [comment]
@matheuscpl @MatheusCpl aqui faltou um detalhe, que é o telefone e endereço da ESP e da SESA serem clicáveis

**Comment by laurapmelo** [comment]
@uira e redirecionar pro app de ligações do telefone?

**Comment by uira** [comment]
@laurapmelo Exato. Ao clicar no número, a ação esperada é realizar uma chamada.

**Comment by laurapmelo** [comment]
@uira feito

**Comment by ItaloRod** [comment]
## Alguns HyperLinks ainda não estão funcionando
![image](https://user-images.githubusercontent.com/20058085/90187996-1aeda600-dd91-11ea-9bd6-8476bc53f269.png)
![image](https://user-images.githubusercontent.com/20058085/90188003-1f19c380-dd91-11ea-9fd9-52f60e20c1e0.png)
![image](https://user-images.githubusercontent.com/20058085/90188009-22ad4a80-dd91-11ea-841a-1ebe16f1937c.png)
![image](https://user-images.githubusercontent.com/20058085/90188019-250fa480-dd91-11ea-83e8-71420529fd25.png)

## Nas redes sociais da ESP, tem um erro de digitação, todos estão como ...do ESP, tem que alterar para ...da ESP.
![image](https://user-images.githubusercontent.com/20058085/90188079-3bb5fb80-dd91-11ea-9866-efda6e3f9498.png)
![image](https://user-images.githubusercontent.com/20058085/90188090-3e185580-dd91-11ea-862b-cbf1d52b60b4.png)

**Comment by uira** [comment]
@ItaloRod Aproveitando:

O links pras redes sociais é melhor que sejam direcionados pro navegador padrão ou, melhor ainda, pras urls dos aplicativos. Tipo o youtube:// e fb://, pra abrir com o aplicativo mesmo.

Isso pq abrindo em webview ele vem sem login e aí perde o sentido que seria o usuário interagir (curtir/seguir) as redes da ESP e Sesa

**Comment by ItaloRod** [comment]
Há 3 links problemáticos no SUS no Ceará que estão somente sem o HTTPS e isso impacta na abertura do app. Há a tarefa de retirar os 3 links problemáticos.

**Comment by laurapmelo** [comment]
@uirá, vamos fazer essas atualizações como melhoria, certo? daí pelo menos por agora subimos os textos corretos.

**Comment by uira** [comment]
sim sim.

go go go

**Comment by laurapmelo** [comment]
Melhorias que devem virar novos cards:
- links nao seguros (http) devem ser redirecionados pro navegador do celular
http://www.cesau.ce.gov.br/#recadastramento
uece.br   http://www.planalto.gov.br/ccivil_03/leis/l8080.htm#:~:text=LEI%20N%C2%BA%208.080%2C%20DE%2019%20DE%20SETEMBRO%20DE%201990.&text=Disp%C3%B5e%20sobre%20as%20condi%C3%A7%C3%B5es%20para

- redes sociais devem ser direcionadas para o app (deep link)

**Comment by ItaloRod** [comment]
Bloqueado aguardando aprovação do time de teste da ESP.
