### ISSUE TITLE
Criar tela de cadastro de informações complementares

### ISSUE THREAD

**Issue by laurapmelo** [EscolaDeSaudePublica/isus-app#263]
### **Objetivo** 
**Eu como** Profissional de saúde
**Quero** me cadastrar
**Para que** eu possa ter acesso a conteúdo personalizado

### **Contexto**
Queremos saber quem são os usuários do iSUS para melhor direcionar conteúdos e propiciar um acesso único a diversos serviços. Inicialmente vamos focar o cadastro em profissionais de terapia intensiva. Essa tela tem como objetivo saber dados complementares da usuária.

**Dependência**
A tarefa #260  cria uma estrutura da qual este cadastro é dependente. Antes da implementação, verificar implementação.

### **Escopo**
- [ ] página de cadastro - redirecionar para está página quando for clicado em próximo na página de informações profissionais (#243  )
![image](https://user-images.githubusercontent.com/67436275/89930367-07034200-dbe1-11ea-880c-b278d0e48724.png)

- [ ] Campo de titulação acadêmica: select que permite múltiplas respostas com dropdown para a residência
![image](https://user-images.githubusercontent.com/67436275/89930183-b7bd1180-dbe0-11ea-8c64-f5ad71e8aa0d.png)

- [ ] tipo de contratação: select que permite múltiplas respostas, caso seja selecionado outro, um campo aberto é habilitado
![image](https://user-images.githubusercontent.com/67436275/89945998-9bc56a00-dbf8-11ea-8b93-98354fc3e49e.png)

- [ ] campo Instituição: dropdown com autocomplete
componente: https://github.com/dumbre-prasad/react-native-dropdown-autocomplete-textinput
![image](https://user-images.githubusercontent.com/67436275/89947752-5a828980-dbfb-11ea-90da-d77821c1cc14.png)

- [ ] botão que permite e adição de nova instituição

- [ ] campo "Docente" conforme protótipo

- [ ] botão de próximo sempre habilitado

- [ ] dados salvos em cache quando a usuária clica em próximo

### **Critérios de Aceitação**
- [ ] redirecionamento
**Dado que** estou na página de infos profissionais
**Quando** clico em próximo
**Então** sou redirecionada para a página de cadastro de infos adicionais

- [ ] titulação acadêmica - múltiplos campos
**Dado que** quero preencher minha titulação acadêmica
**Quando** seleciono "graduado"
**Então** as demais opções de titulação acadêmica seguem habilitadas

- [ ] titulação acadêmica
**Dado que** não selecionei o campo "residência em"
**Quando** tento clicar no dropdown de residência
**Então** ele está desabilitado

- [ ] titulação acadêmica
**Dado que** selecionei o campo "residência em" **mas não selecionei** uma opção no dropdown
**Quando** tento ir para a próxima página
**Então** vejo uma mensagem de erro e não consigo mudar de página

- [ ] residência
**Dado que** quero preencher a titulação acadêmica
**Quando** seleciono "residência em"
**Então** o campo dropdown deve ficar habilitado

- [ ] tipo de contratação - múltiplos campos
**Dado que** quero preencher o tipo de contratação
**Quando** seleciono "estatutário"
**Então** as demais opções de tipo de contratação seguem habilitadas

- [ ] tipo de contratação
**Dado que** não selecionei o campo "outro"
**Quando** tento clicar no campo de input(?)
**Então** ele está desabilitado

- [ ] tipo de contratação: outro
**Dado que** quero preencher o tipo de contratação
**Quando** seleciono "outro"
**Então** o campo de input deve ficar habilitado

- [ ] instituição
**Dado que** cliquei no dropdown de instituição
**Quando** digito alguma letra
**Então** as opções são filtradas

- [ ] adicionar instituição
**Dado que** quero preencher uma segunda instituição
**Quando** clico em adicionar instituição
**Então** um novo dropdown aparece

- [ ] atuação como docente - dropdown??
**Dado que** não atuo como docente
**Quando** seleciono a check box "não possuo atuação como docente"
**Então** dropdown fica desabilitado

- [ ] atuação como docente????
dropdown??

- 

- [ ] cache
**Dado que** preenchi algum dado nesta página
**Quando** clico em próximo 
**Então** os dados que inseri são salvos na memória local

## **UX**
- [ ] Desenhar tela de cadastro com as informações de unidade (Confirmar com @uira que campos entram) 
- [ ] Reestruturar a experiência de cadastro

- [ ] Pensar em como tratar quando a pessoa já possui cadastro (pop up pedindo para adicionar novas informações?)
- [ ] Opções Sim e cancelar ou Sim e Não
- [ ] Como a tela de perfil será exibida para o usuário que ainda não tem algumas informação (Aparecera mensagens informando que falta dados?)

- [ ] Cenário de sucesso
- [ ] Cenário de senha falhando
- [ ] Cenário de falta de internet
  
Protótipo:
https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=1550%3A7606
Dados: 
https://docs.google.com/presentation/d/1-AbnLgRmKIoGcKUoEriFnUFY2-OWkc_pspQcN_kOPt4/edit#slide=id.g86a325bfdc_0_20 
Épico: #134

**Comment by kurjes** [comment]
Esse card altera o fluxo de usuário, adicionando novos campos. É preciso entender com @uira se ainda faz sentido para o momento atual.

pareando com @daianefreira

**Comment by jessica-salmazzo** [comment]
Essa atividade é Mapa da Saúde ou Home Personalizada?

**Comment by Clarisse1983** [comment]
Movendo para o entendimento para ver com Fabrício se essas informações se encaixam na expectativa sobre o Cadastro.

**Comment by uira** [comment]
@Clarisse1983 Isso será substituído pelo Cadastro no Mapa da Saúde

**Comment by Clarisse1983** [comment]
Posso fechar essa issue como concluída então? Uma vez que "a parte do iSUS"
já está implementada?

Em sex, 11 de dez de 2020 11:02, Uirá Porã <notifications@github.com>
escreveu:

**Comment by uira** [comment]
@Clarisse1983 Pode fechar essa, mas precisa conferir se tem outra pra Integração de Cadastro do iSUS com Mapa da Saúde

**Comment by Clarisse1983** [comment]
Estamos fechando essa issue porque grande parte dela já foi implementada no cadastro no iSUS (ID Saúde, na verdade), e o que ainda não foi será resultado da integração do cadastro do ID Saúde com o Mapa da Saúde. Temos uma tarefa pra isso: #370
