### ISSUE TITLE
[BUG- QA] Criar página com Termos de Uso do iSUS

### ISSUE THREAD

**Issue by laurapmelo** [EscolaDeSaudePublica/isus-app#266]
### **Objetivo**
**Como** usuária me cadastrando no ID Saúde
**Quero** saber quais são os Termos de Uso
**Para** entender meus direitos e deveres
 
### **Contexto**
Com a criação do ID Saúde, precisamos deixar claro para o usuário quais dados são exigidos dele e o que faremos com estes dados. Esta tarefa implementa a página que mostrará o termo de Uso.

### **Escopo**
- [x] Criar página com Termo de Uso
Texto provisório: https://docs.google.com/document/d/13bKnLE_dOJVmSIb97KKmXeWLVNZZiTQUWxw0GjqNRXM/edit#
![image](https://user-images.githubusercontent.com/67436275/90030807-dd0a5800-dc92-11ea-8c9e-b3f77fa02e1c.png)

- [x] Colocar primeira versão do texto do Termo de Uso criado

- [x] botão de voltar (setinha) no cabeçalho

- [x] navegação - deve ser possível acessar esta tela quando a usuária está logada e clica no botão na página de perfil
![image](https://user-images.githubusercontent.com/67436275/90048731-48abef80-dcaa-11ea-858b-f227af3f1679.png)

- [x ] navegação - também é possível chegar na nesta página através das telas abaixo (tela inicial do ID saúde e de login), quando se clica no link
![image](https://user-images.githubusercontent.com/67436275/90191049-88e89c00-dd96-11ea-951c-001abff67033.png)
 

- [x ] navegação - esta página deve ser acessível do menu lateral na home

### **Critérios de Aceitação**
- [x] acesso pelo menu lateral home
**Dado que** estou na home do app
**Quando** acesso o menu lateral e clico em "Termos de Uso"
**Então** sou redirecionada para a página correta

- [x] Voltar - menu lateral
**Dado que** acessei os termos de uso pelo menu lateral da home
**Quando** clico na seta de voltar no cabeçalho
**Então** sou redirecionada para a home do app

- [x] acesso pelo perfil
**Dado que** estou logado no ID Saúde
**Quando** acesso o meu perfil e clico em "Termos de Uso"
**Então** sou redirecionada para a página correta

- [x] Voltar - perfil
**Dado que** acessei os termos de uso pelo meu perfil
**Quando** clico na seta de voltar no cabeçalho
**Então** sou redirecionada para a página de perfil

- [x] acesso - ID Saúde
**Dado que** cliquei no link de termos de uso da página inicial do ID Saúde
**Quando** sou redirecionada para a página de Termo de Uso 
**Então** vejo o texto do termo 

- [x] Voltar - ID Saúde
**Dado que** acessei os termos de uso através da página inicial do ID Saúde
**Quando** clico na seta de voltar no cabeçalho
**Então** sou redirecionada para a página inicial do ID Saúde

- [x] acesso - login
**Dado que** cliquei no link de termos de uso da página de login
**Quando** sou redirecionada para a página de Termo de Uso 
**Então** vejo o texto do termo 

- [x] Voltar - login
**Dado que** acessei os termos de uso através da página de login
**Quando** clico na seta de voltar no cabeçalho
**Então** sou redirecionada para a de login

Protótipo:
https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=1550%3A7606

### **BUGS-QA**
- [x] Exibição Termos de uso **(IOS e Android)**

Na tela de termos de uso, 
**Comportamento atual:** Título da tela de Termos de Uso (TERMOS E CONDIÇÕES DE USO) muito colado com a margem direita da tela.
**Comportamento esperado:** Ter uma margem a direita similar ao corpo do texto.

- [x] voltar para tela de perfil **(IOS e Android)**

Na tela de termos de uso, 
**Comportamento atual:** quando acesso a tela de termos de uso através da tela de login e clico na seta de voltar, ela me leva para perfil.
**Comportamento esperado:** quando acessar a tela de termos de uso  através da tela de login e clico na seta de voltar, ela deve me levar para a tela de login

- [x] erros de escrita **(IOS e Android)**

Na tela de termos de uso, 
**Comportamento atual:** Dado que acessei o "Termos de Uso" através da página de "Login"
Quando rolo a barra para fazer a leitura no item "OBRIGAÇÕES E RESPONSABILIDADES DO USUÁRIO" 2º paragrafo, 4ª linha consta "iSU"
**Comportamento esperado:** Dado que acessei o "Termos de Uso" através da página de "Login"
Quando rolo a barra para fazer a leitura no item "OBRIGAÇÕES E RESPONSABILIDADES DO USUÁRIO" 2º paragrafo, 4ª linha consta "iSUS"

**Comment by ItaloRod** [comment]
Branch integrada com a #260

**Comment by mbernardes19** [comment]
Título da tela de Termos de Uso (TERMOS E CONDIÇÕES DE USO) muito colado com a margem direita da tela.
Testado em dispositivo físico Android Samsung Galaxy J6


<img width="411" alt="Captura de Tela 2020-08-31 às 09 25 59" src="https://user-images.githubusercontent.com/26047592/91719709-349e3400-eb6c-11ea-9254-ffa246262f59.png">

**Comment by drmarcos** [comment]
Página criada e acessada sem problemas

**Comment by KelmaSouto** [comment]
![Ready for QA em Android por Kelma Souto - Versão 3 10 3 - front #266 - Bug Dev](https://user-images.githubusercontent.com/65924048/93137633-2bf14600-f6b4-11ea-8407-02d63d38e1b1.jpg)

**Comment by KelmaSouto** [comment]
Ready for QA em Android 9, dispositivo LG K40S por Kelma Souto 
Versão 3.10.3 - front #266

Comportamento atual: 
Dado que acessei o "Termos de Uso" através da página de "Login" 
Quando clico na "seta de voltar no cabeçalho"
Então sou redirecionada para a tela de "Perfil"

Comportamento esperado:  
Dado que acessei o 'Termos de Uso" através da página de "Login" 
Quando clico na "seta de voltar no cabeçalho"
Então sou redirecionada para a tela de "Login"

**Comment by KelmaSouto** [comment]
![Ready for QA em Android por Kelma Souto - Versão 3 10 3 - front #266 - Bug Narrativas](https://user-images.githubusercontent.com/65924048/93138337-3a8c2d00-f6b5-11ea-9527-6ee10b3d45c1.jpg)

**Comment by KelmaSouto** [comment]
Ready for QA em Android 9, dispositivo LG K40S por Kelma Souto - Versão 3.10.3 - front #266 
Bug Narrativas

Comportamento atual: 
Dado que acessei o "Termos de Uso" através da página de "Login" 
Quando rolo a barra para fazer a leitura no item "OBRIGAÇÕES E RESPONSABILIDADES DO USUÁRIO" 2º paragrafo, 4ª linha consta "iSU"

Comportamento esperado:  
Dado que acessei o "Termos de Uso" através da página de "Login" 
Quando rolo a barra para fazer a leitura no item "OBRIGAÇÕES E RESPONSABILIDADES DO USUÁRIO" 2º paragrafo, 4ª linha consta "iSUS"

**Comment by KelmaSouto** [comment]
Ready for QA em Android 9, dispositivo LG K40S por Kelma Souto - Versão 3.10.5 
Atividade/Card: [BUG- QA] Criar página com Termos de Uso do iSUS #266

                                                             **Escopo: Exibição Termos de uso**


**Na tela de termos de uso**
**Comportamento atual:** Título da tela de Termos de Uso com apresentação de margem a direita similar ao corpo do texto.

**Comportamento esperado:** Título da tela de Termos de Uso com apresentação de margem a direita similar ao corpo do texto.



**Voltar para tela de perfil (Android)**

**Comportamento atual:** quando acesso a tela de termos de uso através da tela de login e clico na seta de voltar, ela me leva para perfil.

**Comportamento esperado:** quando acesso a tela de termos de uso através da tela de login e clico na seta de voltar, ela me leva para perfil.



**Erros de escrita (Android)**

**Comportamento atual:** 
Dado que acessei o "Termos de Uso" através da página de "Login"
Quando rolo a barra para fazer a leitura no item "OBRIGAÇÕES E RESPONSABILIDADES DO USUÁRIO" 2º paragrafo, 4ª linha consta "iSU"

**Comportamento esperado:** 
Dado que acessei o "Termos de Uso" através da página de "Login"
Quando rolo a barra para fazer a leitura no item "OBRIGAÇÕES E RESPONSABILIDADES DO USUÁRIO" 2º paragrafo, 4ª linha consta "iSUS"

**Comment by KelmaSouto** [comment]
Ready for QA em Android 9, dispositivo LG K40S por Kelma Souto - Versão 3.10.5 
Atividade/Card: [BUG- QA] Criar página com Termos de Uso do iSUS #266

           **Escopo: Exibição Termos de uso**


**Comportamento atual:**
Visualizar Termos de uso
Dado que acessei o "Termos de Uso" através da página de "Login"
Quando rolo a barra para fazer a leitura no item "OBRIGAÇÕES E RESPONSABILIDADES DO USUÁRIO" 2º paragrafo, 4ª linha consta "iSUS"


**Comportamento esperado:**
Visualizar Termos de uso
Dado que acessei o "Termos de Uso" através da página de "Login"
Quando rolo a barra para fazer a leitura no item "OBRIGAÇÕES E RESPONSABILIDADES DO USUÁRIO" 2º paragrafo, 4ª linha consta "iSUS"
