### ISSUE TITLE
Cadastro de nova senha

### ISSUE THREAD

**Issue by laurapmelo** [EscolaDeSaudePublica/isus-app#268]
## **Objetivo**
**Como** um usuário fazendo cadastro
**Quero** criar uma senha 
**Para** que meus dados fiquem seguros

**Contexto**
Através do ID Saúde, os usuários vão poder inserir seus dados e futuramente acessar serviços personalizados. Para proteger as informações e permitir que a usuária adicione, exclua e edite estas infos, precisamos que seja cadastrada uma senha de acesso.

**Escopo**
- [x] tela de definição de senha 
![image](https://user-images.githubusercontent.com/67436275/90056055-a9402a00-dcb4-11ea-8f4f-32266f8d6688.png)

- [ ] navegação - essa página deve ser acessada quando a usuária clica em "Li e Aceito" na página de Política de Privacidade
![image](https://user-images.githubusercontent.com/67436275/90057525-e2799980-dcb6-11ea-8d63-cd30cada3b24.png)

- [x] validação do formato da senha quando sai do primeiro campo
 - "A sua senha deve ter pelo menos 8 caracteres."

- [x] botão de cadastro - integração com API para efetivação do cadastro. deve ser habilitado quando as duas senhas são iguais
![image](https://user-images.githubusercontent.com/67436275/90057665-18b71900-dcb7-11ea-8f5e-1f49019ee21f.png)

- [x] snackbar de confirmação - quando a usuária clica em finalizar e o cadastro é efetivado, deve aparecer uma snackbar dizendo "Parabéns! Você finalizou seu cadastro do ID Saúde. Conheça seu perfil no iSUS."
![image](https://user-images.githubusercontent.com/67436275/90188135-50928f00-dd91-11ea-8ba3-7e2eb5327268.png)

- [ ] redirecionar para página de login quando o cadastro é efetivado
![image](https://user-images.githubusercontent.com/67436275/90057576-f6250000-dcb6-11ea-9680-485d7edfe7be.png)

**Critérios de Aceitação**
- [ ] navegação 
**Dado que** estou na página de Política de Privacidade
**Quando** clico em li e aceito
**Então** sou redirecionada para a página de criação de senha

- [ ] senha fora do formato
**Dado que** a inseri uma senha que não se encaixa no padrão definido
**Quando** saio do primeiro campo de senha
**Então** vejo uma sinalização de que a senha precisa ter o formato determinado

- [ ] senhas diferentes
**Dado que** inseri senhas diferentes nos dois campos
**Quando** saio do campo de confirmação de senha
**Então** vejo uma sinalização de que as senhas estão diferentes e o botão de "finalizar" está desabilitado

- [ ] campo em branco
**Dado que** não preenchi um dos campos de senha
**Quando** tento finalizar o cadastro
**Então** o botão está desabilitado

- [ ] botão habilitado
**Dado que** informei senhas iguais nos dois campos
**Quando** saio do campo de confirmação de senha
**Então** o botão de finalizar é habilitado

- [ ] integração com API
**Dado que** preenchi as senhas corretamente
**Quando** clico em finalizar
**Então** o meu cadastro é efetivado no keycloack

- [ ] snackbar
**Dado que** cliquei em "finalizar"
**Quando** meu cadastro é efetivado no keycloack
**Então** e uma snackbar aparece confirmando o cadastro

- [ ] redirecionamento
**Dado que** finalizei meu cadastro
**Quando** clico em ok na snackbar
**Então** sou redirecionada para a página de login

**Comment by ItaloRod** [comment]
integrado com a #260

**Comment by daianefreira** [comment]
Aguardando retorno do funcionamento do serviço referente a cadastro dos dados cadastrais para retomar teste.
