### ISSUE TITLE
Adicionar dados cadastrados na página do perfil

### ISSUE THREAD

**Issue by laurapmelo** [EscolaDeSaudePublica/isus-app#270]
# Objetivo
**Como** uma usuária logada
**Quero** acessar meu perfil
**Para** verificar meus dados pessoais

# Contexto
Após realizar o login, a usuária deve poder verificar dados inseridos e acessar documentos relacionadas ao cadastro. Esta página deve implementar os acessos a estas informações.

# Escopo

- [x]  Exibir dados pessoais na página de perfil da usuária
![Perfil](https://user-images.githubusercontent.com/64148308/90173207-7a8c8700-dd7a-11ea-8642-a94237df3613.png)

## Fora de escopo
- [x] Acesso a Política de Privacidade - será uma página com texto (#267 )

- [x] Acesso a Termos de Uso - será um pagina com texto ()

# Critérios de aceite

- [x] visualizar dados
**Dado que** sou uma usuária e estou logada
**Quando** acesso a página "Meu perfil"
**Então** visualizo os dados pessoais que forneci no cadastro

**Comment by ItaloRod** [comment]
Branch integrada com a #260

**Comment by nicoledbianchin** [comment]
No dispositovo Android aparecem os dados cadastrados e tem acesso para os termos de uso.
No emulador do IOS mesmo comportamento.
