### ISSUE TITLE
Label de senha e email fica coberto pela borda do campo na página de login

### ISSUE THREAD

**Issue by laurapmelo** [EscolaDeSaudePublica/isus-app#272]
##**Descrição**##
Na tela de login, as labels de usuário e senha ficam cortadas pela borda do componente uma vez que ele está com dados.
![image](https://user-images.githubusercontent.com/67436275/90676857-f717dd80-e232-11ea-8d52-1f99b2267723.png)

##**Passos para reproduzir o comportamento:**##
menu lateral -> meu perfil -> já possuo id saúde -> digitar senha e usuario

##**Comportamento esperado**##
a borda do componente deve ficar recortada, como nos outros campos do app
![image](https://user-images.githubusercontent.com/67436275/90677370-af458600-e233-11ea-8cf0-f0eca4f32c9e.png)

##**plataforma**##
testei no iphone, mas acredito que no android está igual

**Comment by ItaloRod** [comment]
integrado com a #260

**Comment by drmarcos** [comment]
Versão 3.10.0 aparece corretamente para mim
