### ISSUE TITLE
[BUGS- QA] Redirecionar links na seção "SUS no Ceará" para o navegador

### ISSUE THREAD

**Issue by laurapmelo** [EscolaDeSaudePublica/isus-app#276]
### **Objetivo**
Redirecionar todos links da seção "SUS no Ceará" para o navegador do celular, exceto as redes sociais.

### **Contexto**
Na tarefa #262 adicionamos links à seção "SUS no Ceará", direcionando para links relacionados ao texto abertos em uma webview. O objetivo desta tarefa é abrir estes links no navegador padrão do celular.

*Obs.:* a página atualizada está na branch `#283/atualizar-pagina-sus-ceara`

### **Escopo**
- [x] abrir links no navegador padrão do celular

- **Adicionar links no texto (estes links não são seguros - http - e por isso não era possível abrí-los na webview.**

 - [x] link: http://www.planalto.gov.br/ccivil_03/leis/l8080.htm#:~:text=LEI%20N%C2%BA%208.080%2C%20DE%2019%20DE%20SETEMBRO%20DE%201990.&text=Disp%C3%B5e%20sobre%20as%20condi%C3%A7%C3%B5es%20para,correspondentes%20e%20d%C3%A1%20outras%20provid%C3%AAncias.
       texto com hyperlink: Lei 8080
      local: fora do acordeon
![image](https://user-images.githubusercontent.com/67436275/91216467-6175c580-e6ec-11ea-8286-9631a8f2014d.png)

- [x] link: http://www.cesau.ce.gov.br/# 
       texto com hiperlink: participação das pessoas
      local: SUS no Ceará
![image](https://user-images.githubusercontent.com/67436275/91216552-8b2eec80-e6ec-11ea-9a52-7836588f8996.png)

- [x] link: http://www.uece.br/
        texto com hyperlink: Universidade Estadual do Ceará
       local: O iSUS é ESP
![image](https://user-images.githubusercontent.com/67436275/91216678-bb768b00-e6ec-11ea-8b0e-2d0c7f0493ef.png)

## **Fora do escopo**
- [x] abrir redes sociais no navegador 

### **Critérios de Aceitação**
- [x] navegador padrão
**Dado que** estou na página SUS no Ceará
**Quando** clico no hyperlink de "um dever do Estado e um direito de todos os brasileiros" ou "Governo estadual"
**Então** o link é aberto no navegador padrão **ou** eu posso escolher navegador eu quero usar

- [x] Universidade Estadual do Ceará 
**Dado que** estou na seção "o iSUS é ESP"
**Quando** clico em Universidade Estadual do Ceará 
**Então** o navegador padrão do celular abre com o link correto 
**ou** posso ver a opção e abrir no navegador da minha escolha

- [x] Lei 8080 
**Dado que** estou na página "SUS no Ceará"
**Quando** clico em Lei 8080
**Então** o navegador padrão do celular abre com o link correto
**ou** posso ver a opção e abrir no navegador da minha escolha

- [x] participação das pessoas 
**Dado que** estou na seção "SUS no Ceará" 
**Quando** clico em "participação das pessoas"
**Então** o navegador padrão do celular abre com o link correto
**ou** posso ver a opção e abrir no navegador da minha escolha

### **BUGS-QA**
- [x] "Lei 8080" aparecer como hiperlink **(IOS e Android)**
Dentro da página "SUS no ceará" temos informações fora dos acordeons 
**Comportamento atual:** o texto "lei 8080" não se comportar como um hiperlink 
**Comportamento esperado:** o texto "lei 8080" se comportar como um hiperlink e ao ser clicado ser aberto no navegador padrão ou ter a opção de selecionar o navegador.

- [x] hiperlink "um dever do Estado e um direito de todos os brasileiros" abrir no navegador **(IOS e Android)**
Dentro da página "SUS no ceará" temos informações fora dos acordeons  
**Comportamento atua no IOSl:** o hiperlink "um dever do Estado e um direito de todos os brasileiros" abre uma webview
**Comportamento atual  no Android:** o hiperlink "um dever do Estado e um direito de todos os brasileiros"  continua pedindo para baixar o conteúdo no celular
**Comportamento esperado:** o hiperlink "um dever do Estado e um direito de todos os brasileiros" ao ser clicado ser aberto no navegador padrão ou ter a opção de selecionar o navegador.

- [x] "participação das pessoas" aparecer como hiperlink **(IOS e Android)**
Dentro da página "SUS no ceará", na da sessão "SUS no Ceará" temos informações
**Comportamento atual:** o texto "participação das pessoas" não se comportar como um hiperlink 
**Comportamento esperado:** o texto "participação das pessoas" se comportar como um hiperlink e ao ser clicado ser aberto no navegador padrão ou ter a opção de selecionar o navegador.

- [x] "Universidade Estadual do Ceará" aparecer como hiperlink **(IOS e Android)**
Dentro da página "SUS no ceará", na sessão "o iSUS é ESP" temos informações
**Comportamento atual no IOS:** o texto "Universidade Estadual do Ceará" aparentemente é um link mas quando a usuária clica, ele não abre no seu navegador padrão, e o navegador não aparece como uma das opções de aplicativos para abrir.
**Comportamento atual no Android:** o texto "Universidade Estadual do Ceará" não se comportar como um hiperlink 
**Comportamento esperado:** o texto "Universidade Estadual do Ceará" se comportar como um hiperlink e ao ser clicado ser aberto no navegador padrão ou ter a opção de selecionar o navegador.

texto: https://docs.google.com/document/d/1svbOm46TsX8d2ZgOGO-ste79JAZv4WCt1KHPl4wtquY/edit
links: https://docs.google.com/spreadsheets/d/1CqqiVEWH-YchqFSTlx3NN5zG7RBpvPRUkGo_CCyLThw/edit#gid=250852473
épico #134

**Comment by kurjes** [comment]
Bug IOS: ao clicar no hiperlink "um dever do Estado e um direito de todos os brasileiros" o mesmo não abre no navegador padrão, ele abre uma webview dentro do aplicativo.

ps: teste no android precisa ser realizado.

**Comment by kurjes** [comment]
Bug IOS: ao clicar on hiperlink "Universidade Estadual do Ceará" que está dentro da sessão "o iSUS é ESP" nem abre no meu navegador padrão, e tbm o navegador não aparece como uma das opções de aplicativos para abrir o link. 

[link com o vídeo](https://drive.google.com/file/d/1UBpa-8MpDwSjloWcXmMnMPJbjwR2k-U0/view?usp=sharing)

ps: teste no  android precisa ser realizado

**Comment by kurjes** [comment]
Bug IOS: "Lei 8080" não aparece como hiperlink

![8080](https://user-images.githubusercontent.com/69155423/92011506-863bef80-ed21-11ea-8bd3-0c0258e84a5a.jpeg)

ps: teste no android precisa ser realizado

**Comment by kurjes** [comment]
Bug IOS: "participação das pessoas" dentro da sessão "SUS no Ceará" não aparece como hiperlink

![si](https://user-images.githubusercontent.com/69155423/92012107-6658fb80-ed22-11ea-9d78-7a3288548121.jpeg)

ps: teste no android precisa ser realizado

**Comment by mbernardes19** [comment]
Testei agora a partir da branch #283/atualizar-pagina-sobre-sus que tem essa página atualizada.

- O link "um dever do Estado e um direito..." continua baixando o conteúdo no celular Android, no iOS ele abre normalmente no navegador.

Versão do app: 3.8.2
Plataforma: dispositivo físico Android

**Comment by ilizakoski** [comment]
- Hiperlink "um dever do Estado e um direito de todos os brasileiros"...
**Comportamento atual no Android**: o hiperlink "um dever do Estado e um direito de todos os brasileiros" continua pedindo para baixar o conteúdo no celular -> Sim, Android é padrão, pois sempre baixar como navegador padrão.
