### ISSUE TITLE
Botão de sair não está funcionando no perfil

### ISSUE THREAD

**Issue by ItaloRod** [EscolaDeSaudePublica/isus-app#279]
## Contexto

Ao realizar o login e depois de um tempo clicar no botão de sair, ele impede de sair da conta do usuário. No app ele parece estar logado, mas no keycloak a sua sessão já expirou junto com o token.

## Comportamento esperado

* Quando a sessão do usuário expira
então a usuária deve ser redirecionado para a tela de login.

## Objetivo 

* Aumentar o tempo do token de acesso no keycloak para o tempo máximo permitido (60 dias);

* Permitir que o usuário consiga se deslogar mesmo com sessão expirada.

**Comment by ItaloRod** [comment]
integrado com a #260

**Comment by drmarcos** [comment]
Versão 3.10 Android está OK

**Comment by nicoledbianchin** [comment]
Criei uma conta e consegui logar, quando eu estava na minha página de perfil, cliquei no botão nativo do Android de voltar, fui redirecionada para a Home mas não consegui mais acessar o conteúdo do Drawer (ao clicar nas seções eu não era redirecionada).
