### ISSUE TITLE
Inputs de cadastro com comportamento inesperado

### ISSUE THREAD

**Issue by mbernardes19** [EscolaDeSaudePublica/isus-app#280]
## Contexto
Ao preencher os campos do cadastro, alguma parte dos dados preenchidos podem ser apagados se escritos com muita rapidez.

Campos em que isso acontece:
CPF, telefone, senha, repetir senha

## Comportamento esperado
Ao preencher os campos acima, de forma rápida ou não, o que for preenchido não terá alguma parte apagada.

**Comment by mbernardes19** [comment]
Suspeita-se que a causa de alguns dados serem apagados seja pelo campo `value` do componente `TextInput` estar recebendo o retorno da função `getValues()`.

Caso perceba-se lentidão ao preencher os campos testando num dispositivo físico, uma opção pra tentar deixar isso mais rápido seria tirar o `await` da função `trigger` responsável por ativar a validação do que está sendo escrito

**Comment by drmarcos** [comment]
Não tive problemas com digitação rápida, por observo que a lista dos municípios não aparece completa (ultima cidade aparece cortada) dando a impressão que existe mais opções que no entando não tem como "rolar" a lista para saber
