### ISSUE TITLE
[BUGS- QA] Atualizar página do sus no ceará

### ISSUE THREAD

**Issue by laurapmelo** [EscolaDeSaudePublica/isus-app#283]
## **Objetivo**
Reorganizar o texto da seção do sus no Ceará e adicionar o link para o plano de modernização da Saúde.

# **Escopo**
- [x] Colocar texto para fora do acordeon - os dois primeiros parágrafos da Seção SUS no Ceará devem ficar fora do acordeon conforme o protótipo
![image](https://user-images.githubusercontent.com/67436275/91210271-55393a80-e6e3-11ea-936f-ed8ca963b8d9.png)
 
- [x] Adicionar link do "plano de modernização da saúde" na seção sus no Ceará - o link deve abrir em webview
![image](https://user-images.githubusercontent.com/67436275/91210948-5c147d00-e6e4-11ea-8d7a-aefa7727a9d2.png)

link: https://www.saude.ce.gov.br/wp-content/uploads/sites/9/2019/09/plataforma_de_modernizacao_da_saude_13_08_2019.pdf

## **Critérios** de Aceitação**
- [x] Texto fora do acordeon
**Dado que** cliquei no botão de SUS no Ceará no menu lateral
**Quando** sou redirecionada para a página
**Então** vejo dois parágrafos de texto mesmo com o acordeon fechado

- [x] link do plano de modernização
**Dado que** estou na seção do sus no Ceará
**Quando** abro o acordeon do "Sus no ceará" e clico em "plano de modernização"
**Então** vejo o pdf do plano numa webview

### **BUGS-QA**
- [x] abrir o web-view com o plano de modernização **(IOS)**
Dentro da sessão "SUS no Ceará" temos o link para o plano de Modernização da Saúde
**Comportamento atual:** Quando a usuária clica no link não acontece nada
**Comportamento esperado:** quando a usuária clica no link deve ser aberta uma webview com o plano de modernização da saúde

figma: https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=1691%3A6044

**Comment by kurjes** [comment]
BUG IOS: Na página tem o link para o Plano de Modernização da Saúde mas ao clicar não acontece nada.

[link com o vídeo](https://drive.google.com/file/d/1T_NTLlIqxYffOFQZhGjOUVxlslV53Ju3/view?usp=sharing)

ps: preciso que alguém teste no android para verificar o comportamento

**Comment by drmarcos** [comment]
Na versão 3.10.0 não tem esse link

**Comment by nicoledbianchin** [comment]
@kurjes no dispositivo físico do Android ele abre uma webview e baixa o documento.

[Link do vídeo](https://drive.google.com/file/d/1NN25rAzipIHmQpXvIRHUtmSC3FZkZQdx/view?usp=sharing)

**Comment by ilizakoski** [comment]
Link para o **plano de Modernização da Saúde** somente abrir para navegador padrão como link [#278](https://github.com/EscolaDeSaudePublica/isus-app/issues/278)
