### ISSUE TITLE
Exibir as informações profissionais na página de perfil

### ISSUE THREAD

**Issue by laurapmelo** [EscolaDeSaudePublica/isus-app#285]
## **Objetivo**
**Como** usuária logada
**Quero** ter acesso aos informações profissionais
**Para** consultar os dados cadastrados

## **Contexto**
No menu lateral temos o botão **Meu Perfil** que quando a usuária está logada a leva até a página do seu perfil. Atualmente a página mostra os dados pessoais da usuária, queremos que ela tenha acesso aos informações profissionais também. 

## **Escopo**
- [x] Exibir dados profissionais que foram cadastrados
![Screen Shot 2020-09-11 at 13 54 32](https://user-images.githubusercontent.com/69155423/92952460-6188fb80-f436-11ea-88be-55c9f9f323e6.png)

- [x] Atualização do design 
![Screen Shot 2020-09-11 at 13 55 22](https://user-images.githubusercontent.com/69155423/92952588-9ac16b80-f436-11ea-9348-45c491d799fe.png)

## **Fora de Escopo**
- [ ] A tela de adicionar informações profissionais, será a tarefa #288 

## **Critérios de Aceitação**
- [x] visualizar informações profissionais
**Dado que** sou uma usuária e estou logada
**Quando** acesso a página "Meu perfil"
**Então** visualizo informações profissionais que forneci no cadastro

- [x] não possuo informações profissionais cadastradas
**Dado que** sou uma usuária e não possuo informações profissionais cadastradas
**Quando** acesso a página "Meu perfil"
**Então** visualizo somente os meus dados pessoais

[Prototipo no Figma ](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=3636%3A0)

**Comment by KelmaSouto** [comment]
![Ready for QA em Android 9 - dispositivo LG K40S por Kelma Souto - Versão 3 10 3](https://user-images.githubusercontent.com/65924048/93258479-bf8a4b80-f774-11ea-9909-602356202c51.jpg)

**Comment by KelmaSouto** [comment]
Ready for QA em Android 9, dispositivo LG K40S por Kelma Souto - Versão 3.10.3 
Atividade/Card: Exibir as informações profissionais na página de perfil #285

-> Escopo: visualizar informações profissionais - Critérios de Aceitação

Comportamento atual: 
Dado que sou uma usuária e "estou logada"
Quando acesso a página "Meu perfil"
Então visualizo informações profissionais que forneci no cadastro

Comportamento esperado:  
Dado que sou uma usuária e "estou logada"
Quando acesso a página "Meu perfil"
Então visualizo informações profissionais que forneci no cadastro

**Comment by KelmaSouto** [comment]
Ready for QA em Android 9, dispositivo LG K40S por Kelma Souto - Versão 3.10.3 
Atividade/Card: Exibir as informações profissionais na página de perfil #285

-> Escopo: não possuo informações profissionais cadastradas - Critérios de Aceitação

Comportamento atual: 
Dado que sou uma usuária e possuo informações profissionais já cadastradas
Quando tento alterar meu cadastro, não consigo 
Então se apresenta assim: 
Dado que sou uma usuária e "estou logada"
Quando acesso a página "Meu perfil"
Então visualizo informações profissionais que forneci no cadastro

Comportamento esperado:  
Dado que sou uma usuária e não possuo informações profissionais cadastradas
Quando acesso a página "Meu perfil"
Então visualizo somente os meus dados pessoais
