### ISSUE TITLE
Adicionar botão para o Cadastro no Primeiro Acesso

### ISSUE THREAD

**Issue by uira** [EscolaDeSaudePublica/isus-app#286]
## **Objetivo**
**Como** uma usuária acessando o iSUS pela primeira vez
**Quero** saber que posso realizar meu cadastro
**Para** ter acesso a conteúdo personalizado

## **Contexto**
Quando o app é aberto pela primeira vez, logo após baixar da loja, é exibido um carrossel de slides. Queremos que o último slide fale sobre o cadastro no iSUS e tenha um botão que direcione a usuária para o fluxo do cadastro.

## **Escopo**
- [x] tirar slide "minha saúde" do carrossel 
![image](https://user-images.githubusercontent.com/67436275/91220301-57ef5c00-e6f2-11ea-86ed-e7531f144e90.png)

- [x] adicionar slide do Cadastro Profissional, com botão que redireciona para o fluxo do cadastro
![Screen Shot 2020-08-31 at 17 31 05](https://user-images.githubusercontent.com/69155423/91765913-21ad5300-ebb0-11ea-9a86-e150dcd1a719.png)

- Botão **Realizar meu cadastro** na página Cadastro Profissional deve redirecionar para a página: 
![image](https://user-images.githubusercontent.com/67436275/91220528-ad2b6d80-e6f2-11ea-9169-1a027a8f3b56.png)

## **Critérios de Aceitação**
- [x] retirar slide minha saúde do fluxo
**Dado** que fiz o download do app e estou vendo o slide de "Bem vindo ao iSUS"
**Quando** movo para o próximo slide
**Então** vou para o slide de Educação

- [x] adicionar slide cadastro profissional 
**Dado** que fiz o download do app e estou vendo o slide de "Bem vindo ao iSUS"
**Quando** movo o até o fim do carrossel 
**Então** vou para o slide de cadastro profissional 

- [x] botão realizar meu cadastro
**Dado** que fiz o download do app e estou vendo o slide de "Bem vindo ao iSUS"
**Quando** estou no slide de cadastro profissional  
**Então** quando clicar no botão realizar cadastro devo ser redirecionado para o fluxo de cadastro.

## **BUG**
- [x] concertar os erros de português
Quando e estou no primeiro acesso e estou lendo as informações dos banners
**Comportamento atual:** No banner de "Bem  vindo aos iSUS" no fim do  texto a palavra **decisões** está com dois "s", em todos os banners está faltando o ponto no fim da frase.
**Comportamento esperado:** Que a palavra **decisões** esteja escrita corretamente e as frases em todos os banners tenham um ponto final.

**Comment by KelmaSouto** [comment]
Dado que fiz o download do app e e estou vendo o slide de "Bem vindo ao iSUS"
Quando movo o carrossel para o próximo slide 
Então vou para o slide "Educação" 

Quando movo o carrossel para o próximo slide 
Então vou para o slide "Pesquisa"  

Quando movo o carrossel para o próximo slide 
Então vou para o slide "Manejo Clínico"   

Quando movo o carrossel para o próximo slide 
Então vou para o slide Apoio "Diagnóstico"    

Quando movo o carrossel para o próximo slide 
Então vou para o slide "Cadastro de Profissional"     

Quando clico na opção Realizar Meu cadastro 
Então vou para o slide "Crie seu ID Saúde" 

Quando clico na opção Realizar Meu cadastro 
Então vou para slide "Cadastro"    

Quando faço cadastro e clico na opção Próximo
Então vou para slide "Cadastro (Informações profissionais)"   

Quando faço cadastro e clico na opção Próximo
Então vou para slide "Cadastro (Definição de senha)"   

Quando defino a senha e clico na opção Finalizar 
Então aparece uma mensagem Parabéns! Você finalizou seu cadastro do ID Saúde. Conheça seu perfil no iSUS. 

Comportamento atual: cadastro realizado sem impedimento e com sucesso.
Comportamento esperado: cadastro realizado sem impedimento e com sucesso.
