### ISSUE TITLE
Autocomplete não encontra a cidade caso a usuária comece a digitar com letra minúscula

### ISSUE THREAD

**Issue by laurapmelo** [EscolaDeSaudePublica/isus-app#287]
## **Descrição**
Na tela de cadastro de dados pessoais do iSUS, quando preenchemos o campo do município, caso a usuária comece a palavra com letra minúscula, o autocomplete não busca as cidades conforme esperado.

![image](https://user-images.githubusercontent.com/67436275/91204569-a8f35600-e6da-11ea-82e5-3d3453880e34.png)

## **Passos para reproduzir o comportamento:**
menu lateral -> meu perfil -> realizar meu cadastro -> campo: município - digitar uma letra minúscula

## **Comportamento esperado**
O componente deve encontrar os municípios independente das letras estarem maiúsculas ou minúsculas
![image](https://user-images.githubusercontent.com/67436275/91204734-e22bc600-e6da-11ea-9dfc-717fdd8d24bb.png)

**Comment by kurjes** [comment]
Devido aos problemas encontrados no campo de município resolvemos passar o card com um dropdown para que seja possível realizar o cadastro, mas foi criada a issue #304 no backlog para ser pensado uma nova experiência de usuário com esse campo.

**Comment by ItaloRod** [comment]
Não faz sentido mergear essa branch com a develop, pois o campo de cidade é um dropdown.
