### ISSUE TITLE
Adicionar informações profissionais não cadastradas 

### ISSUE THREAD

**Issue by laurapmelo** [EscolaDeSaudePublica/isus-app#288]
## **Objetivo**
**Como** usuária logada
**Quero** ter acesso ao meu Perfil
**Para** adicionar informações profissionais que não forneci durante o cadastro

## **Contexto**
No menu lateral temos o botão **Meu Perfil** que quando a usuária está logada a leva até a página do seu perfil, onde a usuária pode encontrar os dados que nos forneceu durante o cadastro. Queremos que se a usuária não preencheu suas informações profissionais durante o cadastro tenha uma mensagem à informando, e que ela seja capaz de fazer isso através da sua página de perfil.

## **Escopo**
- [x] apresentar mensagem convidando a usuária a adicionar seus dados profissionais caso ela não tenha feito isso durante o cadastro.
![Screen Shot 2020-09-11 at 15 19 37](https://user-images.githubusercontent.com/69155423/92959515-576cfa00-f442-11ea-8d67-368fe531735d.png)

- [x] criar botão "Adicionar Informações" para que a usuária seja capaz de adicionar informações profissionais caso não tenha feito durante o cadastro.
![Screen Shot 2020-09-11 at 15 20 51](https://user-images.githubusercontent.com/69155423/92959572-710e4180-f442-11ea-9be7-9f157bff4f08.png)

- [x] criar página de "Informações Profissionais"
![Screen Shot 2020-09-11 at 15 21 36](https://user-images.githubusercontent.com/69155423/92959626-88e5c580-f442-11ea-90d4-8aee70b25324.png)
 
- [x] Campo de **Categoria profissional:** dropdown com as opções abaixo, sendo possível selecionar apenas um dos itens

*Categoria profissional
- Medicina
- Fisioterapia
- Enfermagem
- Terapia Ocupacional
- Farmácia
- Coordenação Clínica
- Coordenação de Enfermagem
- Outra

- [x] Campo de **Setor de Atuação**: acordeon com select que permite múltiplas escolhas.  Os itens do campo podem ser encontrados na coluna "Descrição" desta  [planilha](https://docs.google.com/spreadsheets/d/1Ud5jLWDe30gjZDfnVqf4bgIa243mctUQ/edit#gid=1922492045)

- [x] criar página informando a usuária que suas informações foram salvas 
<img width="399" alt="Screen Shot 2020-09-03 at 19 24 49" src="https://user-images.githubusercontent.com/69155423/92179557-4822f680-ee1b-11ea-8d0b-321754f16132.png">

- [x] A criação do endpoint que permite a edição de dados. Tarefa relacionada na api: https://github.com/EscolaDeSaudePublica/isus-api/issues/78

## **Critérios de Aceitação**
- [x] botão **Adicionar informações** 
**Dado que** sou uma usuária e estou logada
**Quando** acesso a página "Meu perfil"
**Então** visualizo o botão **Adicionar informações**  caso não tenha fornecido informações profissionais no cadastro

- [x] redirecionamento para página "Informações Profissionais"
**Dado que** clico no botão **Adicionar informações** 
**Quando** acesso a página "Meu perfil"
**Então** sou levada a página "Informações Profissionais"

- [x] campo "Categoria Profissional"
**Dado que** estou na página "Informações Profissionais"
**Quando** clico no campo "categoria profissional"
**Então** vejo uma lista com o itens do campo

- [x] campo "Categoria Profissional"
**Dado que** o dropdown do campo "categoria profissional" está aberto
**Quando** quando clico em seu topo
**Então** a lista é fechada 

- [x] campo "Setor de atuação"
**Dado que** estou na página "Informações Profissionais"
**Quando** clico no campo "setor de atuação"
**Então** o acordeon é aberto com os itens do campo

- [x] campo "setor de atuação"
**Dado que** o acordeon do campo "setor de atuação" está aberto
**Quando** quando clico em seu topo
**Então** o acordeon é fechado

- [x] botão habilitado 
**Dado que** estou na página "Informações Profissionais"
**Quando** preencho todos os campos da página
**Então** o botão "Salvar" será habilitado

- [x] redirecionar para página de perfil
**Dado que** finalizo o preenchimento das minhas informações profissionais 
**Quando** clico no botão "salvar" 
**Então** visualizo a página de finalização de cadastro  por 2s **E** sou redirecionado para minha página de "Perfil"

- [x] visualização  dos dados
**Dado que** finalizei o preenchimento dos campos na página de "Informações Profissionais"
**Quando** sou redirecionado para página de "Perfil"
**Então** visualizo minha "categoria profissional" e o "setor em que atua" com as  informações que preenchi

Prototipo: https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=3636%3A0

**Comment by victorMagalhaesPacheco** [comment]
@kurjes Onde vejo o número do card da API?

**Comment by victorMagalhaesPacheco** [comment]
Card relacionado a API: https://github.com/EscolaDeSaudePublica/isus-api/issues/78

**Comment by kurjes** [comment]
> @kurjes Onde vejo o número do card da API?

Victor se vc olhar dentro do scopo desse card tem um item que relaciona a issue da api. Foi comentado durante o desk check com Italo e Nicole.

**Comment by victorMagalhaesPacheco** [comment]
> > @kurjes Onde vejo o número do card da API?
> 
> Victor se vc olhar dentro do escopo desse card tem um item que relaciona a issue da api. Foi comentado durante o desk check com Italo e Nicole.

Entendi :) Esse daqui?  A criação do endpoint que permite a edição de dados. Tarefa relacionada na api: #78

**Comment by kurjes** [comment]
> > > @kurjes Onde vejo o número do card da API?
> > 
> > 
> > Victor se vc olhar dentro do escopo desse card tem um item que relaciona a issue da api. Foi comentado durante o desk check com Italo e Nicole.
> 
> Entendi :) Esse aqui? A criação do endpoint que permite a edição de dados. Tarefa relacionada na api: #78 (Permitir a busca dos usuarios no app)

Isso mesmo :D

**Comment by nicoledbianchin** [comment]
Fiz o teste no simulador IOS e em um dispositivo Android e todos os comportamentos estão como o esperado. 
Versão: 3.10.5
