### ISSUE TITLE
Marcos - Observações testes V3.10.0

### ISSUE THREAD

**Issue by drmarcos** [EscolaDeSaudePublica/isus-app#301]
Dois testes realizados

https://docs.google.com/document/d/1S1h0j5OjtcmzJdFeXzRUHWdLZ8OKyT8q9Z2Y8Ms67B0/edit

https://docs.google.com/document/d/1DuCnht0Pksa4vghWELYKZAXX7qyUOlxPmmaTnnASBKc/edit#heading=h.exf8kswgdwkm

**Comment by kurjes** [comment]
É necessária uma validação do PO @uira para ver se faz sentido as sugestões de marcos, e ai podemos criar cards a partir das sugestões que forem acatadas.
