### ISSUE TITLE
Dispor os nossos serviços em carrossel

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-app#302]
## **Objetivo**
**Como** acesso a home do iSUS
**Quero** ter a sessão "Serviços"
**Para** que eu possa saber quais serviços são oferecidos pelo app

## **Contexto**
Atualmente nossos serviços estão dispostos de uma maneira estática na nossa home, tendo em vista que queremos oferecer mais serviços a disposição dos mesmos em carrossel nos possibilita isso. 

## **Escopo**
- [x] disposição dos nossos serviços em carrossel
![Screen Shot 2020-09-08 at 13 50 12](https://user-images.githubusercontent.com/69155423/92505470-81bc7e80-f1da-11ea-9644-b008957e584f.png)

- [x] mudança de design dos botões a sessão **Serviços**

## **Critérios de Aceitação**
- [x] apresentação dos serviços carrossel 
**Dado que** sou  usuária do iSUS
**Quando** estou na home 
**Então** vejo  os serviços oferecidos dispostos em forma de carrossel 

Protótipo: https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=2288%3A0

**Comment by ItaloRod** [comment]
os ícones do integrasus e o do SUS no Ceará deram certo, porém está faltando no figma a apresentação do fale cosnosco e o de ações do governo, visto que está parcialmente apresentado ou nem sequer está presente.

**Comment by kurjes** [comment]
> os ícones do integrasus e o do SUS no Ceará deram certo, porém está faltando no figma a apresentação do fale cosnosco e o de ações do governo, visto que está parcialmente apresentado ou nem sequer está presente.

Italo já falei com Rodrigo e ele tirou os ícones pra fora da página, agora da pra vcs pegarem.

**Comment by KelmaSouto** [comment]
![Ready for QA em Android 9, dispositivo LG K40S por Kelma Souto - Versão 3 10 3 - Imagem 1](https://user-images.githubusercontent.com/65924048/93260264-83a4b580-f777-11ea-9c53-d17376b34929.jpg)

**Comment by KelmaSouto** [comment]
![Ready for QA em Android 9, dispositivo LG K40S por Kelma Souto - Versão 3 10 3 - Imagem 2](https://user-images.githubusercontent.com/65924048/93260275-87d0d300-f777-11ea-9d4b-1ea52b11f5f7.jpg)

**Comment by KelmaSouto** [comment]
Ready for QA em Android 9, dispositivo LG K40S por Kelma Souto - Versão 3.10.3 
Atividade/Card: Dispor os nossos serviços em carrossel #302

-> Escopo: disposição dos nossos serviços em carrossel - Critérios de Aceitação

Comportamento atual: 
Dado que sou usuária do iSUS
Quando estou na home
Então vejo os serviços oferecidos dispostos em forma de carrossel: IntegraSUS, SUS no Ceará, Fale Conosco e Ações do governo

Comportamento esperado:  
Dado que sou usuária do iSUS
Quando estou na home
Então vejo os serviços oferecidos dispostos em forma de carrossel: IntegraSUS, SUS no Ceará, Fale Conosco e Ações do Governo

**Comment by KelmaSouto** [comment]
Ready for QA em Android 9, dispositivo LG K40S por Kelma Souto - Versão 3.10.3
Atividade/Card: Dispor os nossos serviços em carrossel #302
Bug Narrativas
-> Escopo: disposição dos nossos serviços em carrossel - Critérios de Aceitação

Comportamento atual:
Dado que sou usuária do iSUS
Quando estou na home
Então vejo os serviços oferecidos dispostos em forma de carrossel: IntegraSUS, SUS no Ceará, Fale Conosco e Ações do **governo** 

Comportamento esperado:
Dado que sou usuária do iSUS
Quando estou na home
Então vejo os serviços oferecidos dispostos em forma de carrossel: IntegraSUS, SUS no Ceará, Fale Conosco e Ações do **Governo**
