### ISSUE TITLE
Criar seção de conteudo Home Personalizada

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-app#306]
## **Objetivo**
**Como** usuária logada
**Quero** ter acesso a seção de conteúdos específicos de acordo com o meu perfil
**Para** que eu possa ter uma capacitação efetiva

## **Contexto**
Como usuária logada queremos que ela tenha acesso a uma seção de conteúdo personalizado, esse conteúdo será filtrado de acordo com as informações profissionais do perfil que está acessando. 

## **Escopo**
- [x] criação da seção "Meus conteúdos", a mesma deve si comportar como um carrossel de posts. 
<img width="250" alt="Screen Shot 2020-09-10 at 21 44 49" src="https://user-images.githubusercontent.com/69155423/92833252-065ff600-f3af-11ea-8907-375cba652b73.png">

- [x] Seção "Meus conteúdos" será disponibilizada com posts apenas se no seu perfil, o usuário tiver no campo "Setor em que  atua" pelo menos uma das opções abaixo: 

-UTI
-Gestão estratégica
-Regulação, contas hospitalares e gestão de riscos
-Gestão de pessoas
-Formação ou qualificação profissional
-Estágio profissional
-Residência médica ou multiprofissional 
-Saúde e segurança do trabalho
-Apoio administrativo
-Higiene e limpeza
-Transporte e segurança
-Materiais e suprimentos
-Manutenção e reparos
-Outro setor ou serviço de apoio administrativo

- [x] Exibição do botão "ver mais" caso a a sessão "meus conteúdos" contenha posts

- [x] Sessão "Meus conteúdos" será disponibilizada com uma mensagem caso o campo "Setor em que atua" da usuária não seja nenhum dos citados acima.
<img width="250" alt="Screen Shot 2020-09-10 at 21 41 04" src="https://user-images.githubusercontent.com/69155423/92833376-27c0e200-f3af-11ea-861e-b8d91ce17f56.png">

- [x] Criação da página "Meus conteúdos"
<img width="250" alt="Screen Shot 2020-09-10 at 21 43 10" src="https://user-images.githubusercontent.com/69155423/92832936-a79a7c80-f3ae-11ea-92e3-4ce56906d7cc.png">

## **Fora de Escopo**

- Sessão de "Serviços" que será tratada na issue #302

- Endpoint que vai disponibilizar os conteúdos será feito na issue: https://github.com/EscolaDeSaudePublica/isus-api/issues/82

## **Critérios de Aceitação**
- [x] visualização da sessão "Meus conteúdos"
**Dado que** estou logado e faço parte de um dos serviços que terá posts 
**Quando** estiver na home
**Então** visualizo conteúdos de acordo com o serviço em que atuo com posts em forma de carrossel 

- [x] redirecionamento para página "Meus conteúdos"
**Dado que** estou logado e faço parte de um dos serviços que terá posts 
**Quando** clicar no botão "ver mais"
**Então** sou redirecionado para página "Meus Conteúdos"

- [x] página "Meus Conteúdos"
**Dado que** estou na página "Meus Conteúdos"
**Quando** der scroll
**Então** devo ser capaz de ver os posts filtrados de acordo com os serviços em que atuo

- [x] mensagem para  usuária sem posts
**Dado que** estou logada e não faço parte dos serviços com posts
**Quando** visualizar a sessão "meus conteúdos" 
**Então** devo ter uma mensagem informando que ainda não temos conteúdos para a área da usuária junto com o link do "Fale Conosco"

- [x] redirecionamento do "Fale Conosco"
**Dado que** estou logada e não faço parte dos serviços com posts
**Quando** quando  clicar  no link "Fale Conosco"
**Então** devo ser redirecionada para a página "Fale Conosco"

- [x] usuária deslogada
**Dado que** sou usuária 
**Quando** estiver deslogada do app
**Então** não devo visualizar a sessão "Meus Conteúdos" na minha home 

- [x] disposição das informações dos posts 
**Dado que** sou usuária **E** tenho posts na sessão de "meus conteúdos"
**Quando** clicar em um post
**Então** devo visualizar suas informações em uma tela dentro do app

Protótipo: https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=3827%3A2160

**Comment by ItaloRod** [comment]
Queria saber quantos posts são exibidos na seção de meus conteúdos na home? Todos? O app exibe todos para que no "ver mais" ele exiba os conteúdos de outra forma?

**Comment by KelmaSouto** [comment]
![Criar seção de conteudo Home Personalizada #306_Imagem 1](https://user-images.githubusercontent.com/65924048/93818061-3ff6f380-fc30-11ea-9db7-c4934f361ecc.jpg)

**Comment by KelmaSouto** [comment]
![Criar seção de conteudo Home Personalizada #306_Imagem 2](https://user-images.githubusercontent.com/65924048/93818185-6b79de00-fc30-11ea-8748-d097ac916678.jpg)

**Comment by KelmaSouto** [comment]
![Criar seção de conteudo Home Personalizada #306_Imagem 3](https://user-images.githubusercontent.com/65924048/93818297-9106e780-fc30-11ea-9672-01cb391c3336.jpg)

**Comment by KelmaSouto** [comment]
![Criar seção de conteudo Home Personalizada #306_Imagem 4](https://user-images.githubusercontent.com/65924048/93818384-ad0a8900-fc30-11ea-9f7b-c50b4575c63c.jpg)

**Comment by KelmaSouto** [comment]
![Criar seção de conteudo Home Personalizada #306_Imagem 5](https://user-images.githubusercontent.com/65924048/93818500-d3302900-fc30-11ea-83be-3e5a3d8297b2.jpg)

**Comment by KelmaSouto** [comment]
![Criar seção de conteudo Home Personalizada #306_Imagem 6](https://user-images.githubusercontent.com/65924048/93818574-f064f780-fc30-11ea-8dae-49fdf907439b.jpg)

**Comment by KelmaSouto** [comment]
Ready for QA em Android 9, dispositivo LG K40S por Kelma Souto - Versão 3.10.5 
Atividade/Card: Criar seção de conteudo Home Personalizada #306


**Comportamento atual:**
Dado que sou usuária logada
Quando estou na home 
Então visualizo a sessão "Meus conteúdos"
Dado que estou logado e faço parte de um dos serviços que terá posts
Quando clico no botão "ver mais"
Então sou redirecionada para página "Meus Conteúdos"
Dado que estou na página "Meus Conteúdos"
Quando der scroll
Então vejo os posts filtrados de acordo com os serviços em que atuo
Dado que sou usuária e tenho posts na sessão de "meus conteúdos"
Quando clico em um post
Então visualizo minhas informações em uma tela dentro do app

**Comportamento esperado:** 
Dado que sou usuária logada
Quando estiver na home 
Então visualização da sessão "Meus conteúdos"
Dado que estou logado e faço parte de um dos serviços que terá posts
Quando clicar no botão "ver mais"
Então sou redirecionado para página "Meus Conteúdos"
Dado que estou na página "Meus Conteúdos"
Quando der scroll
Então devo ser capaz de ver os posts filtrados de acordo com os serviços em que atuo
Dado que sou usuária E tenho posts na sessão de "meus conteúdos"
Quando clicar em um post
Então devo visualizar suas informações em uma tela dentro do app

**Comment by KelmaSouto** [comment]
**Comportamento atual: mensagem para usuária sem posts**
Dado que estou logada e não faço parte dos serviços com posts
Quando visualizo a sessão "meus conteúdos"
Então devo ter uma mensagem informando que ainda não temos conteúdos para a área da usuária junto com o link do "Fale Conosco"
Dado que estou logada e não faço parte dos serviços com posts
Quando quando clicar no link "Fale Conosco"
Então devo ser redirecionada para a página "Fale Conosco"


**Comportamento esperado: mensagem para usuária sem posts ** 
Dado que estou logada e não faço parte dos serviços com posts
Quando visualizar a sessão "meus conteúdos"
Então devo ter uma mensagem informando que ainda não temos conteúdos para a área da usuária junto com o link do "Fale Conosco"
Dado que estou logada e não faço parte dos serviços com posts
Quando quando clicar no link "Fale Conosco"
Então devo ser redirecionada para a página "Fale Conosco"

**Comment by KelmaSouto** [comment]
**Comportamento atual: usuária deslogada**
Dado que sou usuária
Quando estou deslogada no app
Então não visualizo a sessão "Meus Conteúdos" na minha home

**Comportamento esperado: usuária deslogada** 
Dado que sou usuária
Quando estiver deslogada do app
Então não devo visualizar a sessão "Meus Conteúdos" na minha home
