### ISSUE TITLE
Adicionar o campo de especialidades ao cadastro

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-app#309]
## **Objetivo**
**Como** usuária do iSUS
**Quero** adicionar minha especialidade caso seja Enfermeira ou Médica
**Para** realizar meu cadastro 

## **Contexto**
Estamos evoluindo nosso cadastro adicionando o campo de especialidades caso a usuária seja Enfermeira ou Médica, pois foi visto que essa informação será essencial para que nossa home personalizada tenha conteúdos mais específicos. 

## **Escopo**
- [x] Adicionar o campo de **Especialidade** ao cadastro caso a usuária seja Enfermeira ou Médica: dropdown com múltiplas seleções
![especialidade](https://user-images.githubusercontent.com/69155423/92811674-0ce17400-f395-11ea-8af8-42afdf1bd075.png)

- [x] Itens do campo **Especialidade** caso a usuária marque a **Categoria Profissional** como Enfermagem: https://docs.google.com/spreadsheets/d/1SAPWZZvYcs28b2UmCtV4NHYHhgaQkRBRDv-bePur1wI/edit#gid=0

- [x] Itens do campo **Especialidade** caso a usuária marque a **Categoria Profissional** como Medicina: https://docs.google.com/spreadsheets/d/1HMj-1oAOtnX3Nxwj1TEANUt7oXOZKlK2wL3M1sMMNxM/edit#gid=0

- [x] Mudar a cor da statusbar
![parte de cima](https://user-images.githubusercontent.com/69155423/92811970-53cf6980-f395-11ea-97d2-8f26b853e8f3.png)

- [x] Mudar texto da página  onde o usuário insere as informações 
![Screen Shot 2020-09-10 at 18 45 08](https://user-images.githubusercontent.com/69155423/92812658-13242000-f396-11ea-8ed0-e16ec03142b4.png)

- [x] Fazer as mudanças na API que são necessárias para inserção desse campo no cadastro. Card que representa essa tarefa na api:  https://github.com/EscolaDeSaudePublica/isus-api/issues/89

## **Critérios de Aceitação**
- [x] Adicionar campo de **Especialidade** para profissional de Enfermagem
**Dado que** sou usuária do iSUS
**Quando** estou realizando meu cadastro e escolho enfermagem como **Categoria Profissional**  
**Então** visualizo o campo de **Especialidade** com os dados [desta planilha](https://docs.google.com/spreadsheets/d/1SAPWZZvYcs28b2UmCtV4NHYHhgaQkRBRDv-bePur1wI/edit#gid=0)

- [x] Adicionar campo de **Especialidade** para profissional de Medicina
**Dado que** sou usuária do iSUS
**Quando** estou realizando meu cadastro e escolho medicina como **Categoria Profissional**
**Então** visualizo o campo de **Especialidade** com os dados [desta planilha](https://docs.google.com/spreadsheets/d/1HMj-1oAOtnX3Nxwj1TEANUt7oXOZKlK2wL3M1sMMNxM/edit#gid=0)

- [x]  selecionar múltiplos itens
**Dado que** seleciono Medicina ou Enfermagem como **Categoria Profissional**
**Quando** visualizo o campo **Especialidade** 
**Então** sou capaz de selecionar quantos itens quiser

- [x] dados não selecionados 
**Dado que** seleciono Medicina ou Enfermagem como **Categoria Profissional**
**Quando** visualizo o campo **Especialidade** e não marco nenhuma opção 
**Então** o botão "Próximo" continua habilitado  

- [x] não mostrar campo **Especialidade**
**Dado que** estou realizando meu cadastro
**Quando** seleciono uma opção diferente de **Enfermagem** e **Medicina** no campo categoria profissional
**Então** não visualizo o campo de **Especialidade**

- [x] abrir dropdown
**Dado que** tenho acesso ao campo de especialidade 
**Quando** clico no topo do campo 
**Então** um dropdown é aberto com os itens da lista

- [x] fechar dropdown
**Dado que** tenho o campo de especialidade com a lista aberta
**Quando** clico no topo do campo 
**Então** um dropdown é fechado

Prototipo: https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=1550%3A7606

**Comment by nicoledbianchin** [comment]
OS: Android
Versão: 3.11.0

Dado que seleciono Medicina ou Enfermagem como Categoria Profissional
Quando visualizo o campo Especialidade
**Comportamento esperado:** Então sou capaz de selecionar apenas um dos itens
**Comportamento atual:** Sou capaz de selecionar mais de um item


Dado que sou médica ou enfermeira
Quando seleciono minha especialidade
**Comportamento esperado:** Então o dropdown é fechado e a especialidade escolhida deve ser mostrada no campo
**Comportamento atual:** O dropdown continua aberto e a(s) especialidade(s) escolhida(s) não aparecem no campo

**Esse critério entra em conflito com esse último:**
Dado que tenho o campo de especialidade com a lista aberta
Quando clico no topo do campo
**Então um dropdown é fechado**
