### ISSUE TITLE
Explorar: benchmark e entrevista

### ISSUE THREAD

**Issue by matheuscpl** [EscolaDeSaudePublica/isus-app#31]
Foi decidido pela construção de um formulário para guiar nossa entrevista, formulei umas perguntas para que possamos chegar numa hierarquização de requisitos mais tarde: 
https://drive.google.com/open?id=1-7Z85vwllhU1PROC6DwBRFZv7Y3E_3K7KMUgWYkWWV8
P.S: Não sei se algumas dessas perguntas já estão respondidas...

Aqui também servira de repositório para aplicações similares de referência.
https://play.google.com/store/apps/details?id=cl.gob.digital.coronapp&hl=es_CL
https://play.google.com/store/apps/details?id=br.gov.datasus.guardioes
https://play.google.com/store/apps/details?id=br.gov.datasus.cnsdigital
http://digisus.saude.gov.br/gestor/#/indicador/SSIT201704

**Comment by uira** [comment]
Entendo que essa demanda é específica do Design, podendo ser passada para outro ambiente, por isso estou fechando a issue.
