### ISSUE TITLE
Adicionar tela de finalização do cadastro

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-app#310]
## **Objetivo**
**Como** usuária do iSUS
**Quero** ser informada que meu cadastro foi finalizado
**Para** ter maior fluidez dentro do app

## **Contexto**
Atualmente a usuária é informada que cadastro foi finalizado através de uma snackbar, foi criado uma página de finalização de cadastro que informa a usuária que ela finalizou o cadastro e será redirecionada para a tela de login. 

## **Escopo**
- [x] criação da página de finalização de cadastro
![Screen Shot 2020-09-17 at 11 51 24](https://user-images.githubusercontent.com/69155423/93487913-22e2bd80-f8dc-11ea-9ce3-2e8fa08925bc.png)

## **Critérios de Aceitação**
- [x] visualizar página de finalização de cadastro
**Dado que** estou realizando meu cadastro 
**Quando** estou na página de **Senha** e clico finalizar se meu cadastro for aprovado
**Então** visualizo por 4s a página de finalização de cadastro

- [x] redirecionamento
**Dado que** finalizo meu cadastro
**Quando** visualizo a página de finalização de cadastro por 4s
**Então** sou redirecionado para página de login

**Comment by ItaloRod** [comment]
Há uma tela no app chamada "Tela de sucesso" E que pode ser utilizada para poder fazer essa tarefa. @ilizakoski  caso tenha dúvida depois você pode me chamar

**Comment by nicoledbianchin** [comment]
Fiz o teste no simulador IOS e no dispositivo Android e o comportamento está como esperado. 
Versão: 3.10.5
