### ISSUE TITLE
Exibição das informações profissionais na home personalizada

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-app#311]
## **Objetivo**
Exibição dos nome da usuária juntamente com seus dados profissionais na home personalizada

## **Contexto**
Quando a usuária estiver logada e ela for  para a página de home ela deve seus dados para que entenda que a home se tornou uma home personalizada para ela. 

## **Escopo**
- [x] Exibição do nome da usuária
![Screen Shot 2020-09-11 at 18 15 34](https://user-images.githubusercontent.com/69155423/92973576-dd953a80-f45a-11ea-8daa-f179bc103e3d.png)

- [x]  Exibição da setor de atuação e categoria profissional da usuária
![Screen Shot 2020-09-11 at 18 17 18](https://user-images.githubusercontent.com/69155423/92973700-1af9c800-f45b-11ea-8dd5-ed6493b59a72.png)

- [x] Edição de cor do statusbar 
![Screen Shot 2020-09-11 at 18 18 26](https://user-images.githubusercontent.com/69155423/92973824-48467600-f45b-11ea-8b17-bf3abc144ce3.png)

### **Critérios de Aceitação**

- [x] visualizar dados
**Dado que** sou usuária logada
**Quando** for Home do Isus
**Então** devo visualizar meu nome e meus dados profissionais

- [x] comportamento quando a usuária deslogar
**Dado que** sou usuária deslogada 
**Quando** for Home do Isus
**Então** devo visualizar a home genérica sem minhas informações e com a statusbar verde

Protótipo: https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=2288%3A0

**Comment by KelmaSouto** [comment]
![Ready for QA em Android 9, dispositivo LG K40S por Kelma Souto - Versão 3 10 5 _Imagem 1](https://user-images.githubusercontent.com/65924048/93520817-76b5cc80-f905-11ea-8566-d5ca0c9a3524.jpg)

**Comment by KelmaSouto** [comment]
![Ready for QA em Android 9, dispositivo LG K40S por Kelma Souto - Versão 3 10 5 _Imagem 2](https://user-images.githubusercontent.com/65924048/93520838-7ddcda80-f905-11ea-9bd0-301cdeaa59f7.jpg)

**Comment by KelmaSouto** [comment]
Ready for QA em Android 9, dispositivo LG K40S por Kelma Souto - Versão 3.10.5 
Atividade/Card: Exibição das informações profissionais na home personalizada #311

-> Escopo: Exibição do nome da usuária/Exibição da setor de atuação e categoria profissional da usuária/Edição de cor do statusbar. Critérios de Aceitação:

Comportamento atual: visualizar dados - Logoda
Dado que sou usuária logada
Quando for Home do Isus
Então devo visualizar meu nome e meus dados profissionais

Comportamento esperado: visualizar dados - Logada
Dado que sou usuária logada
Quando for Home do Isus
Então devo visualizar meu nome e meus dados profissionais, e a edição de cor do statusbar
Então devo visualizar **Home/Terapia Intensiva (em cor cinza), acima do statusbar**


comportamento atual: visualizar dados - quando a usuária deslogar
Dado que sou usuária deslogada
Quando for Home do Isus
Então devo visualizar a home genérica sem minhas informações e com a statusbar verde

comportamento esperado: visualizar dados - quando a usuária deslogar
Dado que sou usuária deslogada
Quando for Home do Isus
Então devo visualizar a home genérica sem minhas informações e com a statusbar verde
