### ISSUE TITLE
Adicionar o campo de especialidade a tela de perfil

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-app#313]
## **Objetivo**
**Como** usuária logada
**Quero** ter acesso aos informações profissionais
**Para** consultar os dados cadastrados

## **Contexto**
No menu lateral temos o botão **Meu Perfil** que quando a usuária está logada a leva até a página do seu perfil. O fluxo de cadastro foi modificando, o campo de especialidade foi inserido para os profissionais de medicina e enfermagem. Queremos que esses profissionais que possuem especialidade sejam capazes de visualizar o dado inserido durante o cadastro. 

## **Escopo**

- [x] Adicionar o campo **especialidade** a tela de perfil 
<img width="446" alt="Screen Shot 2020-09-16 at 19 13 01" src="https://user-images.githubusercontent.com/69155423/93397817-bec6e780-f850-11ea-9f08-73dddc454964.png">

## **Fora de escopo**

- Atualização do cadastro que será feito no card #309 

## **Critérios de Aceite**

- [x] enfermeiras e médicas que preencheram a especialidade 
**Dado que** preenchi o campo de especialidade
**Quando** realizei o cadastro
**Então** devo visualizar o campo com essa informação na tela de perfil  

- [x] enfermeiras e médicas  que não preencheram a especialidade
**Dado que** não preenchi minha especialidade durante o cadastro
**Quando** acesso meu perfil 
**Então** devo visualizar o campo vazio 

- [x] demais profissionais  de saúde sem especialidade 
**Dado que** não sou enfermeira ou médica **E** durante o  cadastro eu preenchi os dados profissionais 
**Quando** acesso meu perfil 
**Então** não devo visualizar o campo de especialidade

**Comment by nicoledbianchin** [comment]
OS: Android
Versão: 3.11.0
Comportamentos de acordo com o esperado.
