### ISSUE TITLE
Adicionar o campo especialidade ao fluxo de informações profissionais não cadastradas

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-app#314]
## **Objetivo**
Como usuária logada
Quero ter acesso ao meu Perfil
Para adicionar informações profissionais que não forneci durante o cadastro

## **Contexto**
Estamos evoluindo nosso cadastro,  o campo de especialidades caso a usuária seja Enfermeira ou Médica já foi adicionado ao fluxo. Foi visto que esse campo é essencial para que possamos entregar as usuárias  uma home personalizada com conteúdos mais assertivos. Agora é necessário que esse campo também esteja no fluxo de adicionar informações profissionais não cadastradas que temos dentro do perfil. 

## **Escopo**
- [x] Adicionar o campo de **Especialidade** ao fluxo caso a usuária seja Enfermeira ou Médica: dropdown com múltipla seleção
![Screen Shot 2020-09-18 at 19 24 13](https://user-images.githubusercontent.com/69155423/93650317-907a1100-f9e4-11ea-8859-97152c228edd.png)

- [x] Itens do campo **Especialidade** caso a usuária marque a **Categoria Profissional** como Enfermagem: https://docs.google.com/spreadsheets/d/1SAPWZZvYcs28b2UmCtV4NHYHhgaQkRBRDv-bePur1wI/edit#gid=0

- [x] Itens do campo **Especialidade** caso a usuária marque a **Categoria Profissional** como Medicina: https://docs.google.com/spreadsheets/d/1HMj-1oAOtnX3Nxwj1TEANUt7oXOZKlK2wL3M1sMMNxM/edit#gid=0

- [x] Fazer as mudanças na API que são necessárias para inserção desse campo no fluxo. Card que representa essa tarefa na api:  https://github.com/EscolaDeSaudePublica/isus-api/issues/92

## **Fora de Escopo**
- Criação da tela de sucesso

- Criação do fluxo de adicionar informações profissionais

## **Critérios de Aceitação**

- [x]  fluxo de adição de informações profissionais 
**Dado que** estou logada e acesso meu perfil através do menu lateral
**Quando** não tiver nenhuma informação profissional cadastrada
**Então** sou capaz de visualizar o botão "Adicionar Informações" 

- [x] Adicionar campo de **Especialidade** para profissional de Enfermagem
**Dado que** sou usuária logada sem informações profissionais
**Quando** clico em "Adicionar Informações" e escolho enfermagem como **Categoria Profissional**  
**Então** visualizo o campo de **Especialidade** com os dados [desta planilha](https://docs.google.com/spreadsheets/d/1SAPWZZvYcs28b2UmCtV4NHYHhgaQkRBRDv-bePur1wI/edit#gid=0)

- [x] Adicionar campo de **Especialidade** para profissional de Medicina
**Dado que** sou usuária logada sem informações profissionais
**Quando** clico em "Adicionar Informações" e escolho medicina como **Categoria Profissional**
**Então** visualizo o campo de **Especialidade** com os dados [desta planilha](https://docs.google.com/spreadsheets/d/1HMj-1oAOtnX3Nxwj1TEANUt7oXOZKlK2wL3M1sMMNxM/edit#gid=0)

- [x]  múltipla seleção
**Dado que** seleciono Medicina ou Enfermagem como **Categoria Profissional**
**Quando** visualizo o campo **Especialidade** 
**Então** sou capaz de selecionar múltiplos itens

- [x] não mostrar campo **Especialidade**
**Dado que** preenchendo os campos da tela de "Informações Profissionais"
**Quando** seleciono uma opção diferente de **Enfermagem** e **Medicina** no campo categoria profissional
**Então** não visualizo o campo de **Especialidade**

- [x] abrir dropdown
**Dado que** tenho acesso ao campo de especialidade 
**Quando** clico no topo do campo 
**Então** um dropdown é aberto com os itens da lista

- [x] fechar dropdown
**Dado que** tenho o campo de especialidade com a lista aberta
**Quando** clico no topo do campo 
**Então** um dropdown é fechado

- [x] habilitar botão salvar
**Dado que** estou preenchendo os campos da tela de "Informações Profissionais"
**Quando** termino de preencher todos os campos
**Então** botão "salvar" é habilitado 

- [x] loading e página de sucesso 
**Dado que** termino de preencher os campos da tela "Informações Profissionais"
**Quando** clico no  botão "salvar"
**Então** um loading é adicionado ao botão salvar **E** visualizo a tela de sucesso por 4s

- [x] redirecionar para página de perfil
**Dado que** visualizo a tela de sucesso
**Quando** se passa 4s
**Então** sou redirecionada para a página de perfil onde posso ver os dados adicionados 

Prototipo: https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=1550%3A7606

**Comment by nicoledbianchin** [comment]
OS: Android
Versão: 3.11.0
Comportamentos de acordo com o esperado
