### ISSUE TITLE
Disposição da Força-tarefa Anticorona em forma de carrossel

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-app#315]
## **Objetivo**
**Como** acesso a home do iSUS
**Quero** ter a sessão "Força-tarefa Anticorona"
**Para** que eu possa ter mais informações sobre a pandemia 

## **Contexto**
Atualmente as informações sobre a Força-tarefa Anticorona estão dispostas de uma maneira estática na nossa home, tendo em vista que otimização do espaço da home queremos que essas informações sejam dispostas em forma de carrossel. 

## **Escopo**
- [x] disposição da Força-tarefa Anticorona em forma de carrossel
![Screen Shot 2020-09-18 at 19 33 26](https://user-images.githubusercontent.com/69155423/93650815-e56a5700-f9e5-11ea-9fd1-a8ab22e22d56.png)

- [x] mudança de design dos botões a sessão **Força-tarefa Anticorona**
![Screen Shot 2020-09-18 at 19 35 29](https://user-images.githubusercontent.com/69155423/93650908-2498a800-f9e6-11ea-8fcb-c710dc1f5d7a.png)

## **Critérios de Aceitação**
- [x] apresentação da Força-tarefa Anticorona
**Dado que** sou  usuária do iSUS
**Quando** estou na home 
**Então** vejo a sessão Força-tarefa Anticorona dispostos em forma de carrossel 

Protótipo: https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=2288%3A0

**Comment by KelmaSouto** [comment]
Ready for QA em Android 9, dispositivo LG K40S por Kelma Souto - Versão 3.10.5 
Atividade/Card: Disposição da Força-tarefa Anticorona em forma de carrossel #315


           **Escopo: disposição da Força-tarefa Anticorona em forma de carrossel**


**Comportamento atual:**
apresentação da Força-tarefa Anticorona
Dado que sou usuária do iSUS
Quando estou na home
Então vejo a sessão Força-tarefa Anticorona dispostos em forma de carrossel


**Comportamento esperado:**
apresentação da Força-tarefa Anticorona
Dado que sou usuária do iSUS
Quando estou na home
Então vejo a sessão Força-tarefa Anticorona dispostos em forma de carrossel
