### ISSUE TITLE
Criar persistência de dados ao realizar o cadastro

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-app#316]
## **Objetivo**
**Como** usuária do iSUS realizando o cadastro
**Quero** poder voltar as telas e que meus dados já inseridos persistam
**Para** que eu não precise digitar novamente

## **Contexto**
Atualmente quando a usuária está inserindo os dados do cadastro e ela clica na seta de voltar, ela volta para a página que da início ao fluxo de cadastro e login. Queremos que quando ela clique em voltar ela volte para a tela do fluxo que ela estava anteriormente, que os dados já inseridos persistam e que ao clicar em próximo se ela já  tiver inserido algo que esse estado do componente também persista. 

## **Escopo**

- [x] criar persistência de dados dentro do fluxo de cadastro.

## **Critérios de Aceite**

- [x] persistência de dados 
**Dado que** estou preenchendo o cadastro
**Quando** clico na seta de voltar
**Então** os dados que já foram preenchidos devem persistir

**Comment by nicoledbianchin** [comment]
O card está bloqueado até a finalização da tarefa #324, para podermos migrar a parte de especialização para o novo cadastro.

**Comment by KelmaSouto** [comment]
**Comportamento atual:** 
Dado que estou preenchendo o cadastro
Quando clico na seta de voltar
Então os dados que já foram preenchidos devem persistir

**Comportamento esperado:**
Dado que estou preenchendo o cadastro
Quando clico na seta de voltar
Então os dados que já foram preenchidos devem persistir
