### ISSUE TITLE
Incluir banner na página "SUS no Ceará"

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-app#318]
## **Objetivo**
Como usuária do iSUS
Quero ter acesso acessa a página "SUS no Ceará"
Para ter acesso ao banner de comemoração de 30 anos do SUS no ceará

## **Contexto**
O SUS no Ceará está completando 30 anos e foi feito um banner de  comemoração, queremos colocar esse banner na página "SUS no Ceará"

## **Escopo**
- [x] Adicionar banner de comemoração de 30 anos do SUS na página "SUS no Ceará"
<img width="466" alt="Screen Shot 2020-09-23 at 16 31 03" src="https://user-images.githubusercontent.com/69155423/94060380-40bb9100-fdba-11ea-99df-662fe98480ef.png">

## **Critérios de Aceitação**
- [x] visualizar banner 
**Dado que** sou usuária do iSUS
**Quando** clico no menu lateral no botão "SUS no Ceará"
**Então** sou  redirecionada para a página "SUS  no Ceará" onde visualizo no topo da página um banner

Prototipo: https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=1691%3A6044

**Comment by KelmaSouto** [comment]
Ready for QA em Android 9, dispositivo LG K40S por Kelma Souto - Versão 3.10.5 
Atividade/Card: Disposição da Força-tarefa Anticorona em forma de carrossel #315

**Escopo: Incluir banner na página "SUS no Ceará" #318**

**Comportamento atual:**
visualizar banner
Dado que sou usuária do iSUS
Quando clico no menu lateral no botão "SUS no Ceará"
Então sou redirecionada para a página "SUS no Ceará" onde visualizo no topo da página um banner

**Comportamento esperado:**
visualizar banner
Dado que sou usuária do iSUS
Quando clico no menu lateral no botão "SUS no Ceará"
Então sou redirecionada para a página "SUS no Ceará" onde visualizo no topo da página um banner
