### ISSUE TITLE
Demanda por Educação Permanente, para que as Unidades manifestem suas necessidades de Educação Permanente.

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-app#320]
um fale conosco para o pessoal de  demanda de educação permanente.
criar uma tela no aplicativo, explique o que é
aproveitando a lógica de feedback
canal para receber demandas deles
pontos do refinamento: a distribuição desses feedbacks

**Comment by ilizakoski** [comment]
Oi @rodrigoplimafreire @daianefreira @kurjes terminei a tarefa, porém duas bordas vermelhos (olha a imagem), texto está muito grande. Se mudar o texto, por favor comentar aqui e vou ajustar o texto. Obrigado

<img width="458" alt="Screen Shot 2020-10-02 at 11 01 29" src="https://user-images.githubusercontent.com/38507756/94932075-f5327280-049e-11eb-93e9-0ba2b5d3e491.png">

**Comment by kurjes** [comment]
@ilizakoski acredito que @rodrigoplimafreire pode falar o que fica melhor

**Comment by rodrigoplimafreire** [comment]
O título da Tela pode ser Educação Permanente. E no campo do de texto pode ser: Demandar por Educação Permanente.

**Comment by ilizakoski** [comment]
@rodrigoplimafreire Acabei de ajustar o título da tela e campo de texto. Obrigado.

**Comment by KelmaSouto** [comment]
Comportamento atual:
Dado que estava logada
Acessei o menu Fale conosco na aba Demanda por Educação Permanente
Preenchi todos os campos e a demanda foi enviada 

Comportamento esperado:
Dado que estava logada
Acessei o menu Fale conosco na aba Demanda por Educação Permanente
Preenchi todos os campos e a demanda foi enviada

**Comment by KelmaSouto** [comment]
Comportamento atual:
Dado que eu não estava logada
Acessei o menu Fale conosco e não visualizei a aba Demanda por Educação Permanente

Comportamento esperado:
Dado que eu não estava logada
Acessei o menu Fale conosco e não visualizei a aba Demanda por Educação Permanente
