### ISSUE TITLE
Edição dos dados profissionais

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-app#323]
## **Objetivo**
Como usuária logada
Quero ter acesso ao meu Perfil
Para editar as informações profissionais que informei durante o cadastro

## **Contexto**
Estamos evoluindo a interação das usuárias com seus dados,  atualmente a usuária é apenas capaz de adicionar informações profissionais que não foram informadas durante o cadastro, queremos que ela seja capaz também  de editar os campos que já foram informados. 

## **Escopo**
- [x] Adicionar botão "editar informações" para a sessão de dados profissionais 
<img width="321" alt="Screen Shot 2020-10-13 at 11 06 03" src="https://user-images.githubusercontent.com/69155423/95871589-369b0b80-0d44-11eb-890c-dbe94d645b1d.png">

- [x]  Tela para edição dos dados 
<img width="321" alt="Screen Shot 2020-10-13 at 11 07 44" src="https://user-images.githubusercontent.com/69155423/95871772-6f3ae500-0d44-11eb-9680-0d838b52276b.png">

- [x] mensagem de sucesso 
<img width="321" alt="Screen Shot 2020-10-13 at 11 08 02" src="https://user-images.githubusercontent.com/69155423/95871910-95608500-0d44-11eb-8542-9e6c133d427b.png">

- [x] categoria profissional: dropdown com seleção única

- [x] especialidade: acordeon com multipla seleção 

- [x] setor  em  que atua: acordeon com múltipla seleção 

## **Fora de Escopo**
- Edição  do endpoint pois o mesmo já foi feito em outra tarefa. EscolaDeSaudePublica/isus-api#96
- Botão de "esqueci minha senha" que será tratado em outra tarefa

## **Critérios de Aceitação**

- [x]  fluxo de perfil 
**Dado que** sou usuária do iSUS e estou logada
**Quando** clico no botão de "meu perfil" no menu lateral
**Então** sou redirecionada para a página de perfil 

- [x]  botão de edição de informações 
**Dado que** sou usuária do iSUS e estou logada
**Quando** estou no meu perfil **E** adicionei pelo menos um campo  de informações profissionais preenchido
**Então** visualizo o botão "editar informações" na sessão de informações profissionais 

- [x]  redirecionamento do botão de edição 
**Dado que** estou meu perfil **E** visualizo o botão de "editar informações" na  sessão de informações profissionais
**Quando** clico no botão "editar  informações"
**Então** sou redirecionada para o fluxo de edição 

- [x] habilitação do botão "salvar"
**Dado que** clico no botão de "editar informações"
**Quando** sou redirecionada para o fluxo de edição 
**Então** o botão de "salvar" está sempre habilitado 

- [x] categoria profissional 
**Dado que** estou editando minhas informações profissionais 
**Quando** clico no campo de "categoria profissional"
**Então** abro o dropdown com a categoria que selecionei durante o cadastro já selecionada **E** sou capaz de edita-la  

- [x] visualizar campo especialidade no momento de edição 
**Dado que** estou editando minhas informações profissionais 
**Quando** seleciono "medicina" ou "enfermagem" como categoria profissional no momento de edição 
**Então** visualizo o campo de especialidade 

- [x] não visualizar campo especialidade 
**Dado que** estou editando minhas informações profissionais **E** havia escolhido "medicina"  ou "enfermagem" como categoria profissional durante o cadastro 
**Quando** mudo minha categoria profissional para uma diferente de "medicina" ou "enfermagem"
**Então** não visualizo mais o campo de especialidade 

- [x] apagar especialidade que foi preenchida no momento de cadastro
**Dado que** estou editando minhas informações profissionais **E** havia preenchido meu campo de especialidade durante o cadastro
**Quando** não visualizo mais esse campo na minha edição 
**Então** a especialidade selecionada durante o cadastro é apagada

- [x] especialidade preenchida no momento de cadastro 
**Dado que** estou editando minhas informações profissionais **já possuía** o campo especialidade preenchido
**Quando** clico no campo de "especialidade"
**Então** abro o acordeon com a especialidade que selecionei durante o cadastro já selecionada **E** sou capaz de edita-la  

- [x] setor em que atua
**Dado que** estou editando minhas informações profissionais 
**Quando** clico no campo de "setor em que atua"
**Então** abro o acordeon com a setor  que selecionei durante o cadastro já selecionada **E** sou capaz de edita-la 

- [x] campos com nenhum dado selecionado durante o cadastro
**Dado que** estou editando minhas informações profissionais 
**Quando** tenho o campo que não foi preenchido durante o cadastro
**Então** o campo aparece sem nenhuma seleção prévia

- [x] redirecionamento para perfil
**Dado que** termino de editar minhas informações
**Quando** clico no botão de "salvar"
**Então** visualizo a tela de sucesso por 3s e sou redirecionada para a página de perfil onde visualizo meus dados atualizados

Prototipo: https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=3858%3A0

**Comment by rodrigoplimafreire** [comment]
feito! https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=3858%3A0

**Comment by nicoledbianchin** [comment]
Conversando com o @victorMagalhaesPacheco, eu e @ItaloRod concluímos que não fazia sentido pedir a senha para editar informações profissionais, dado que a usuária já está logada. Então não desenvolvemos essa parte do card.

**Comment by nicoledbianchin** [comment]
Versão: 3.11.2
OS: dispositivo Android
Comportamentos de acordo com o esperado.
