### ISSUE TITLE
[BUG-QA] Editar os dados pessoais da usuária em seu perfil 

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-app#324]
## **Objetivo**
**Como** usuária logada
**Quero** ter acesso ao meu Perfil
**Para** editar as informações pessoais que informei durante o cadastro

## **Contexto**
Estamos evoluindo a interação das usuárias com seus dados, atualmente a usuária é apenas capaz de adicionar informações pessoais durante o cadastro, porém, queremos também que ela possa editar essas informações. 

Deve ser possível atualizar as informações pessoais de: 
- Nome
- Email
- Telefone
- Município

Não deve ser possível atualizar as informações pessoais de: 
- CPF 

## **UX**
- [x] Adicionar botão Editar Informações para o escopo das informações pessoais 
- [x] Tela para edição dos dados pessoais
- [x] Mensagem de sucesso na atualização dos dados
- [x] Experiência para cenário sem internet 

## **Escopo**
- [x] Adicionar botão Editar Informações para o escopo das informações pessoais conforme [Figma](
https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4914%3A240)
- [x] Tela para edição dos dados pessoais

![image](https://user-images.githubusercontent.com/74663400/100744882-3c64b300-33bd-11eb-94c6-acfa503a7bc8.png)

- [x] Mensagem de sucesso na atualização dos dados

![image](https://user-images.githubusercontent.com/74663400/100745103-8c437a00-33bd-11eb-94b3-9d6075d93412.png)

- [x] Implementar possibilidade de atualização de Nome, Email, Município e Telefone
- [ ] Implementar mensagem de informação para cenário de falha de conexão com internet conforme [Figma](
https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4914%3A240)

![image](https://user-images.githubusercontent.com/74663400/100745046-76ce5000-33bd-11eb-97bd-b6ea03f0f878.png)

## **Fora de Escopo**
- Não deve ser exigido a inserção da senha para confirmação da atualização dos dados pessoais 

## **Critérios de Aceitação**

- [x] 1. fluxo de perfil 
**Dado que** sou usuária do iSUS e estou logada
**Quando** clico no botão de "meu perfil" no menu lateral
**Então** sou redirecionada para a página de perfil 

- [x] 2. botão de edição de informações 
**Dado que** sou usuária do iSUS e estou logada
**E** acesso meu perfil
**Quando** clico no botão de Editar Informações 
**Então** sou direcionada para o fluxo de edição apresentando os campos de Nome, Email, Telefone e Município

- [x] 3. redirecionamento do botão de edição 
**Dado que** estou na tela de edição das informações pessoais
**Quando** realizo a edição de somente a informação de email e clico no botão Salvar 
**Então** sou direcionada para o meu perfil com a informação de email atualizada 

- [x] 4. redirecionamento do botão de edição 
**Dado que** estou na tela de edição das informações pessoais
**Quando** realizo a edição de somente a informação de telefone e clico no botão Salvar 
**Então** sou direcionada para o meu perfil com a informação de telefone atualizada 

- [x] 5. redirecionamento do botão de edição 
**Dado que** estou na tela de edição das informações pessoais
**Quando** realizo a edição de somente a informação de município e clico no botão Salvar 
**Então** sou direcionada o meu perfil com a informação de município atualizada 

- [x] 6. redirecionamento do botão de edição 
**Dado que** estou na tela de edição das informações pessoais
**Quando** realizo a edição de somente a informação de nome e clico no botão Salvar 
**Então** sou direcionada para o meu perfil com a informação de nome atualizada 

- [x] 7. redirecionamento do botão de edição 
**Dado que** estou na tela de edição das informações pessoais
**Quando** realizo a edição da informação de email e telefone e clico no botão Salvar 
**Então** sou direcionada para o meu perfil com a informação de email e telefone atualizadas

- [x] 8. redirecionamento do botão de edição 
**Dado que** estou na tela de edição das informações pessoais
**Quando** realizo a edição de somente a informação de email, telefone e município e clico no botão Salvar 
**Então** sou direcionada para o meu perfil com a informação de email, telefone e município atualizadas

- [x] 9. habilitação do botão "salvar"
**Dado que** clico no botão de "editar informações"
**Quando** sou redirecionada para o fluxo de edição 
**Então** o botão de "salvar" está sempre habilitado 

- [x] 10. redirecionamento para perfil
**Dado que** termino de editar minhas informações
**Quando** clico no botão "salvar"
**Então** visualizo a tela de sucesso por 3s e sou redirecionada para a página de perfil onde visualizo meus dados atualizados

**### Links Úteis**
Menu > Meu Perfil > Informações Pessoais > Editar informações
https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4914%3A240

**Comment by wforte88** [comment]
**Menu > Meu Perfil > Informações Pessoais > Editar informações**
https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4914%3A240

**Comment by ItaloRod** [comment]
Foi adicionada mensagem quando a usuária possui erros nos campos. Para isso, foi adicionada mensagem de que há erros no cadastro.

**Comment by Clarisse1983** [comment]
Teste realizado conforme esperado no Android One Signal.

**Comment by Wanderley97** [comment]
Ao realizar testes não foi encontrado o botão de Editar Informações nas Informações Pessoais no ios Iphone X.

**Comment by Wanderley97** [comment]
![photo5163804988202395925](https://user-images.githubusercontent.com/74379182/103655442-05e30080-4f46-11eb-9829-d5e15058af8e.jpg)

**Comment by Clarisse1983** [comment]
![bug edição informações pessoais](https://user-images.githubusercontent.com/63013269/103655778-830e7580-4f46-11eb-9795-84fc01e2f49b.jpg)
