### ISSUE TITLE
Gestão de linhas de cuidado e protocolos

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-app#326]
**Contexto**
Fornecer uma seção para usuárias do iSUS onde tenhamos conteúdos de fácil acesso sobre protocolos disponibilizados e oficiais sobre covid e conteúdos de cuidado, procedimentos e manejos que possam auxiliar e manter os profissionais atualizados sobre como lidar com seus pacientes em relação ao covid.

**Comment by jessica-salmazzo** [comment]
Atividade duplicada com a #339. Finalizando essa para não deixar atividades duplicadas no backlog.
