### ISSUE TITLE
travar o aplicativo no modo retrato e não deixar dividir tela no android

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-app#328]
## **Objetivo**
Como usuária 
Quero ser capaz de acessar o app apenas no modo retrato
Para ter maior aproveitamento de design pensado

## **Contexto**
Atualmente a usuária de Android é capaz de usar o app  no modo landscaping e dividir tela, queremos que ela seja capaz de utilizar apenas no modo retrato

## **Escopo**
- [x] travar o uso do modo landscaping no android

- [x] travar o uso de dividir tela no android

## **Critérios de Aceitação**

- [x]  travar landscaping
**Dado que** sou usuária do app
**Quando** uso o modo landscaping
**Então** o app é travado no modo retrato

- [x]  travar divisão de tela
**Dado que** sou usuária do app
**Quando** uso o modo dividir tela
**Então** o app é travado no modo retrato

**Comment by nicoledbianchin** [comment]
OS: Android
Versão: 3.11.0
Comportamentos de acordo com o esperado
