### ISSUE TITLE
voltar para home  depois de navegar pelo app

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-app#331]
## **Objetivo**
Como usuária do iSUS
Quero acessar ao home através do menu lateral
Para ter uma maior usabilidade do app

## **Contexto**
Quando estou dentro das  abas de "Pesquisa" ou "Educação", acesso o menu lateral e clico em home, não consigo voltar para home do app. É ideal que a usuária consiga voltar para home através do menu lateral não importando onde ela esteja no app. 

## **Escopo**
- [x] ter uma seta de voltar na aba pesquisa e na aba educação

## **Critérios de Aceitação**

- [x]  aba de Educação
**Dado que** sou usuária do iSUS e estiver na aba educação
**Quando** clico na seta de voltar
**Então** sou redirecionada para home

- [x]  aba de Pesquisa
**Dado que** sou usuária do iSUS e estiver na aba pesquisa
**Quando** clico na seta de voltar
**Então** sou redirecionada para home

**Comment by nicoledbianchin** [comment]
OS: Android
Versão: 3.11.0
Comportamentos de acordo com o esperado.
