### ISSUE TITLE
[Bugs-QA] Mensagem padrão para quando a usuária faz pesquisa e não encontra resultados

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-app#332]
### **Objetivo**
**Eu como** usuária do app iSUS 
**gostaria que** ao realizar uma pesquisa no app e essa pesquisa não obtivesse resultados retornados, que então o app me retornasse uma mensagem informando que não existem resultados
**para que** eu tenha ciência de que o conteúdo que eu pesquisei, ainda não existe no app. 

### **Contexto**
Atualmente, quando realizamos uma pesquisa no app pelo ícone de lupa, em qualquer sessão do app de algum conteúdo não existente ainda, o app não retorna nenhuma mensagem informativa para a usuária esclarecendo que aquele determinado conteúdo pesquisado não encontra-se no app. 

**Passos para simular o cenário:** 
1. Acesse o iSUS
2. Clique no ícone de lupa
3. Digite a palavra 'Batata' (Exemplo)
4. Observe que não será retornado nenhum resultado, mas também não será retornado nenhuma mensagem deixando explícito de que não houveram resultados encontrados para a pesquisa

### **Escopo**
- [x] Implementar a mensagem definida explicitando que não houveram resultados encontrados conforme [figma](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4901%3A7861)

![image](https://user-images.githubusercontent.com/74663400/100474114-a714a680-30be-11eb-829f-d3ba2a5b1ad8.png)

### **Critérios de Aceitação** 
1.  Realizar uma pesquisa sem resultados na Home - usuária não logada 
**Dado** que eu acesse o iSUS sem estar logada
**Quando** eu realizar uma pesquisa pela palavra 'batata' na Home pelo ícone de lupa
**Então** uma mensagem deve ser exibida informando que não foram encontrados resultados

2. Realizar uma pesquisa sem resultados na Minha Saúde - usuária não logada 
**Dado** que eu acesse o iSUS sem estar logada
**Quando** eu realizar uma pesquisa pela palavra 'batata' na Minha Saúde pelo ícone de lupa
**Então** uma mensagem deve ser exibida informando que não foram encontrados resultados

3.  Realizar uma pesquisa sem resultados na Educação - usuária não logada 
**Dado** que eu acesse o iSUS sem estar logada
**Quando** eu realizar uma pesquisa pela palavra 'batata' na Educação pelo ícone de lupa
**Então** uma mensagem deve ser exibida informando que não foram encontrados resultados

4.  Realizar uma pesquisa sem resultados na Pesquisa - usuária não logada 
**Dado** que eu acesse o iSUS sem estar logada
**Quando** eu realizar uma pesquisa pela palavra 'batata' na Pesquisa pelo ícone de lupa
**Então** uma mensagem deve ser exibida informando que não foram encontrados resultados

5.  Realizar uma pesquisa sem resultados na Home - usuária logada
**Dado** que eu acesse o iSUS estando logada
**Quando** eu realizar uma pesquisa pela palavra 'batata' na Home pelo ícone de lupa
**Então** uma mensagem deve ser exibida informando que não foram encontrados resultados

6.  Realizar uma pesquisa sem resultados na Minha Saúde - usuária logada
**Dado** que eu acesse o iSUS estando logada
**Quando** eu realizar uma pesquisa pela palavra 'batata' na Minha Saúde pelo ícone de lupa
**Então** uma mensagem deve ser exibida informando que não foram encontrados resultados

7.  Realizar uma pesquisa sem resultados na Educação - usuária logada
**Dado** que eu acesse o iSUS estando logada
**Quando** eu realizar uma pesquisa pela palavra 'batata' na Educação pelo ícone de lupa
**Então** uma mensagem deve ser exibida informando que não foram encontrados resultados

8.  Realizar uma pesquisa sem resultados na Pesquisa - usuária logada
**Dado** que eu acesse o iSUS estando logada
**Quando** eu realizar uma pesquisa pela palavra 'batata' na Pesquisa pelo ícone de lupa
**Então** uma mensagem deve ser exibida informando que não foram encontrados resultados

## BUGS QA

Esperado: **Quando** realizar uma pesquisa pela palavra 'batata'  pelo ícone de lupa
**Então** uma mensagem deve ser exibida informando que não foram encontrados resultados e logo após
**Quando** realizar uma pesquisa pela palavra 'Educação'  pelo ícone de lupa
**Então**  deve ser exibida informando os resultados encontrados

Obtido: **Quando** realizar uma pesquisa pela palavra 'batata'  pelo ícone de lupa
**Então** uma mensagem deve ser exibida informando que não foram encontrados resultados e logo após
**Quando** realizar uma pesquisa pela palavra 'Educação'  pelo ícone de lupa
**Então**  uma mensagem é exibida informando que não foram encontrados resultados e logo após exibe os resultados encontrados

**Comment by wforte88** [comment]
**Busca > Sem Resultados**
https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4901%3A7861

**Comment by ItaloRod** [comment]
Testes realizados no Moto G7 e um iPhone 11

**Comment by Clarisse1983** [comment]
Teste realizado conforme esperado no Android Moto One Signal.

**Comment by Wanderley97** [comment]
Teste realizado conforme esperado no ios Iphone X.
