### ISSUE TITLE
[BUG] Trocar os ícones do projeto de PNG para SVG

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-app#334]
### **Objetivo**
**Eu como** pessoa desenvolvedora
**gostaria de** realizar a troca dos ícones do projeto de PNG para SVG
**para que** os ícones tenham melhor resolução e o app apresente ganho de performance visto que ícones png tem baixa resolução e deixam mais pesado o app

### **Contexto**
Foi identificado que ícones no formato PNG tem baixa resolução e deixam o app mais pesado, dessa forma, alguns ícones já foram alterados para SVG, porém, ainda falta realizar a troca dos demais ícones existentes no projeto. 

### **Escopo**
- [x] Mapear todos os ícones que ainda estão no formato PNG no projeto
- [x] Realizar a troca dos ícones mapeados para o formato SVG

**_Obs.:_** Para realizar a troca dos ícones, basta acessar o [Figma](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4011%3A100), buscar o ícone que necessita de conversão de formato e seleciona-lo, acessar em Export e solicitar a exportação no formato SVG. 

![image](https://user-images.githubusercontent.com/74663400/100392995-1df66480-3017-11eb-9201-3de558343115.png)

**_Obs2.:_** Caso seja localizado algum ícone em bitmap na fonte, por favor, falar com o @wforte88 para que ele possa providenciar o ícone em curvas, para que fique 100% de resolução e seja possível escolher como exportar o ícone e nesse cenário, para os ícones encontrados em bitmap, trataremos a conversão deles em SVG em outra atividade. 

### **Critérios de Aceitação** 
- [x] Confirmação da troca do formato dos ícones - usuária Android não logada 
**Dado** que acesso o app Android nos caminhos levantados que estão os ícones e não estou logada 
**Quando** eu verificar o formato do ícone no projeto
**Então** o ícone deve estar no formato SVG

- [x] Confirmação da troca do formato dos ícones - usuária Android logada 
**Dado** que acesso o app Android nos caminhos levantados que estão os ícones e estou logada 
**Quando** eu verificar o formato do ícone no projeto
**Então** o ícone deve estar no formato SVG

- [x] Confirmação da troca do formato dos ícones - usuária iOS não logada 
**Dado** que acesso o app iOS nos caminhos levantados que estão os ícones e não estou logada 
**Quando** eu verificar o formato do ícone no projeto
**Então** o ícone deve estar no formato SVG

- [x] Confirmação da troca do formato dos ícones - usuária iOS logada 
**Dado** que acesso o app iOS nos caminhos levantados que estão os ícones e estou logada 
**Quando** eu verificar o formato do ícone no projeto
**Então** o ícone deve estar no formato SVG

**Comment by ItaloRod** [comment]
- Icons

    - share.png
        - forcaTarefa
            - [ ] farolDenuncia.png
    - estagiosManejo
        - [ ] estagio04.png
        - [ ] pulmao.png
    - apresentacao
        -  [ ] bemvindo.png
        - [ ] cadastro-profissional.png
        - [ ] diagnóstico.png
        - [ ] educacao.png
        - [ ] manejoClinico.png
        - [ ] pesquisa.png
- Imagens
    - [ ] user_account_delete.png
    - [ ] sus_30_anos.png
    - sobreOiSUS
        - [ ] euce2.png
    - banners
        - [ ] banner.png
        - [ ] cartilhaSaudeMental.png
        - [ ] covidHeroes.png
        - [ ] guiaAssistenciaFarmaceutica.jpg
        - [ ] IDSaude.png
        - [ ] protocoloSindromeAguda.png
- Backgrounds
    - [ ] Tutorialbackground.png

**Comment by wforte88** [comment]
**Ícones com problema de renderização**
SO: MIUI 12.0.4.0 / Android 10 QKQ1
iSUS: 3.14.2

**Passos para simulação**
1. Executar o app;
2. Colocar o app em segundo plano;
3. Reexibir o app.

https://user-images.githubusercontent.com/21333612/104020504-1a203b00-519c-11eb-9b5b-e0d41207fa78.mp4

**Comment by ItaloRod** [comment]
@wforte88 Tentei reproduzir os mesmo passos que você para tentar fazer aparecer o erro. Porém não funcionou. Fiz o processo logado e deslogado e só filmei a versão logada, conforme o vídeo.

https://drive.google.com/drive/folders/1EWWsPKyt2k1q3n5jrLbqisdCP9SAak_M?usp=sharing

**Comment by wforte88** [comment]
Em testes adicionais realizados em outros dispositivos Android 9 e 10, com e sem MIUI, os ícones foram exibidos normalmente. Verificou-se que o erro é específico do primeiro dispositivo testado.
