### ISSUE TITLE
Encontrar maneira de diminuir o tamanho do app

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-app#335]
**Contexto** 
Encontrar alternativas para conseguirmos diminuir o tamanho que o app iSUS querer de seus usuários para sua instalação e processamento e armazenamento dos conteúdos offline. Dessa forma, a usuária não fica 'incomodada' ao realizar o download do app por conta de seu tamanho; além do ponto que ganharemos com performance realizando ações nesse objetivo.

**Comment by oxechicao** [comment]
Remover todas as imagens ou fazer nativo.
