### ISSUE TITLE
Trocar dropdown do cadastro de usuário para o dropdown nativo.

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-app#336]

**Comment by ericsonmoreira** [comment]
@uira Nos dê um contexto dessa atividade. Não entendemos muito bem do que isso se trata.

**Comment by ericsonmoreira** [comment]
Passando para refinamento técnico para avaliar a possibilidade de implementação.

**Comment by ericsonmoreira** [comment]
Foi desenvolvido componentes de select usando a lib do react native paper com dois tipos de selects. Essa issue não faz mais sentido.
