### ISSUE TITLE
[BUG-QA] Incluir links da ESP e ESP virtual no carrossel de serviços da home

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-app#337]
## **Objetivo**
Como usuária 
Quero ter acesso ao links da ESP e da ESP Virtual
Para consultar informações

## **Contexto**
Foi solicitada a inclusão dos links da ESP e da ESP Virtual  no carrossel de "Serviços" do iSUS

## **Escopo**
- [x] Inclusão dos ícones
![Screen Shot 2020-09-28 at 10 24 15](https://user-images.githubusercontent.com/69155423/94438007-e719e480-0174-11eb-800a-69ac377fcab5.png)

- [x] Link da Esp: https://www.esp.ce.gov.br/

- [x] Link da Esp Virtual: http://espvirtual.esp.ce.gov.br/

## **Critérios de Aceitação**

- [x]  Visualizar ícones
**Dado que** sou usuária e estou  na home
**Quando** rolo o carrossel de serviços
**Então** visualizo o campo o link para Esp e Esp Virtual

- [x]  redirecionar
**Dado que** sou usuária e estou na sessão de Serviços
**Quando** clico no link da Esp ou Esp Virtual
**Então** é aberta uma webview

Prototipo: https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=2288%3A0

### **BUG-QA**

- [x] - Link da ESP Virtual quebrado
Dado que sou usuária e estou na home
Quando clico no link da Esp Virtual
**Comportamento atual:** Eu visualizo uma [página de erro](https://drive.google.com/file/d/1ZcX0Urj1nM3NtVoLJMVuoFk9aUpu0QS0/view?usp=sharing)
**Comportamento esperado:** Então visualizo o campo o link para Esp e Esp Virtual

**Comment by nicoledbianchin** [comment]
OS: Android
Versão: 3.11.0
O link da ESP está funcionando corretamente. 
O link da ESP Virtual está quebrado
Screenshot do erro: https://drive.google.com/file/d/1ZcX0Urj1nM3NtVoLJMVuoFk9aUpu0QS0/view?usp=sharing

**Comment by ItaloRod** [comment]
O Link da Esp Virtual está quebrando devido ao problema da página não estar com https, somente http.No simulador funciona normalmente, mas ao ir pra produção ele acaba não funcionando corretamente. Subimos uma versão via CodePush para remover esse link até encontrar uma forma de contornar essa situação.

**Comment by kurjes** [comment]
Colocar o link da ESP Virtual para abrir no navegador porque ai não vai quebrar

**Comment by nicoledbianchin** [comment]
OS: Android
Versão: 3.11.0
Os dois links agora estão funcionando, sendo que o link da ESP Virtual é aberto no navegador padrão.
