### ISSUE TITLE
usuária ser capaz de excluir cadastro

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-app#338]
## **Objetivo**
**Como** usuária logada
**Quero** poder excluir meus dados do app iSUS
**Para** não ter mais vínculo com o app

## **Contexto**
Atualmente, não é possível que a usuária exclua seu cadastro do APP, mas para estarmos alinhados com a nova lei de proteção de dados é necessário que essa funcionalidade seja implementada.

_**16/11:** Foi decidido em conjunto com o time que não será mais utilizado o recurso de senha pois o fluxo de esqueci senha não estava pronto e se a usuária não soubesse a senha, seria impedida de realizar a exclusão prevista por lei. Foi alterado o recurso para solicitar o termo "excluir"._ 

## **Escopo**
- [x] Adicionar botão de excluir cadastro

- [x] Modal para confirmação de exclusão de perfil

- [x] Tela de confirmação de exclusão 

- [x] Mensagem de erro 

- [x] Criar endpoint na api para excluir cadastro: https://github.com/EscolaDeSaudePublica/isus-api/issues/111

## **Fora de Escopo**

- Não será utilizada senha para realizar exclusão
- Botão de "esqueci minha senha" será tratado em outra tarefa

## **Critérios de Aceitação**

- [x] 1. botão de exclusão do perfil
**Dado que** sou usuária do iSUS **E** estou logada
**Quando** clico no botão "meu perfil" no menu lateral
**Então** visualizo o botão "Excluir Conta"

- [x] 2. clicar no botão "Excluir Conta"
**Dado que** estou logada **E** na minha tela de perfil
**Quando** quando clico no botão "Excluir Conta"
**Então** visualizo o modal para confirmar a exclusão ou voltar para tela de perfil

- [x] 3. botão "voltar" do modal de exclusão 
**Dado que** estou visualizando o modal de exclusão de conta
**Quando** clico em "voltar"
**Então** volto para minha tela de perfil 

- [x] 4. botão "voltar" do android no modal de exclusão 
**Dado que** estou visualizando o modal de exclusão de conta
**Quando** clico em "voltar" pelo android
**Então** volto para minha tela de perfil 

- [x] 5. clique fora de tela no modal de exclusão 
**Dado que** estou visualizando o modal de exclusão de conta
**Quando** clico em algum espaço da tela fora do modal
**Então** volto para minha tela de perfil 

- [x] 6. botão "excluir" do modal de exclusão 
**Dado que** estou visualizando o modal de exclusão de conta
**Quando** clico  em "excluir"
**Então** sou redirecionada para tela de confirmação da exclusão de conta

- [x] 7. confirmar exclusão
**Dado que** estou excluindo minha conta
**Quando** digito o termo "EXCLUIR" em maiúsculo e clico no comando "Excluir conta" 
**Então** sou redirecionada para tela de conta excluída do ID saúde, o app realiza o logout e a exclusão da conta com sucesso

- [x] 8. termo incorreto para confirmar exclusão 
**Dado que** estou excluindo minha conta
**Quando** digito o termo "excluir" em minúsculo e clico no comando "Excluir conta" 
**Então** a conta não é excluída e uma mensagem de erro é apresentada informando que a usuária deve digitar exatamente o texto EXCLUIR

- [x] 9. termo incorreto para confirmar exclusão 
**Dado que** estou excluindo minha conta
**Quando** digito um termo diferente de "EXCLUIR" (case sensitive) **E** clico no comando "Excluir conta" 
**Então** é apresentada a mensagem "Por favor, digite exatamente o termo EXCLUIR para confirmar a exclusão dos seus dados" e a conta não é excluída 

- [x] 10. termo incorreto para confirmar exclusão 
**Dado que** estou excluindo minha conta
**Quando** digito o termo "excluir " (em minúsculo com um espaço ao lado) e clico no comando "Excluir conta" 
**Então** a conta não é excluída

- [x] 11. termo incorreto para confirmar exclusão 
**Dado que** estou excluindo minha conta
**Quando** digito o termo "EXCLUIR " (em maiúsculo com um espaço ao lado) e clico no comando "Excluir conta" 
**Então** a conta não é excluída

- [x] 12. termo incorreto para confirmar exclusão 
**Dado que** estou excluindo minha conta
**Quando** digito o termo "excluir &" (em minúsculo com um caractere ao lado) e clico no comando "Excluir conta" 
**Então** a conta não é excluída

- [x] 13. termo incorreto para confirmar exclusão 
**Dado que** estou excluindo minha conta
**Quando** digito o termo "EXCLUIR &" (em maiúsculo com um caractere ao lado) e clico no comando "Excluir conta" 
**Então** a conta não é excluída

- [x] 14. exclusão da conta 
**Dado** o termo "EXCLUIR" no campo de confirmação de exclusão de conta
**Quando** clico no botão "Excluir Conta"
**Então** o app efetuará o logout do usuário em questão e, em seguida, realizará a remoção da conta em questão

- [x] 15. redirecionamento para tela de login
**Dado que** estou visualizando a tela de sucesso de exclusão do perfil
**Quando** clico no botão "ok"
**Então** sou redirecionada para tela Home sem nenhum usuário logado no app

- [x] 16. redirecionamento para tela de login
**Dado que** estou visualizando a tela de sucesso de exclusão do perfil
**Quando** clico no "voltar" do android
**Então** sou redirecionada para tela Home sem nenhum usuário logado no app

- [x] 17. limpar o termo EXCLUIR
**Dado que** estou na tela de confirmação da exclusão da minha conta com o termo EXCLUIR escrito devidamente
**Quando** volto para a página anterior do app
**E** clico novamente no botão Excluir Conta para acessar a tela de confirmação da exclusão da conta
**Então** sou redirecionada para a tela de confirmação da exclusão da conta e o campo de texto para inclusão do termo EXCLUIR está em branco novamente 

- [x] 18. falha de exclusão de conta por falta de conexão com internet
**Dado que** estou na tela de confirmação de exclusão de conta
**E** perco conexão com a internet
**Quando** clico no botão EXCLUIR CONTA com o termo escrito devidamente
**Então** a exclusão da conta não acontecerá e uma mensagem de falha deve ser exibida para o usuário informando que o dispositivo está sem conexão com internet (mensagem será definida pelo UX) 

- [x] 19. Exibição da mensagem de sucesso da remoção da conta conforme dimensão do dispositivo
**Dado** a confirmação da remoção da minha conta pelo meu dispositivo de dimensão 360x640
**Quando** eu visualizar a mensagem de sucesso da remoção da conta
**Então** a mensagem deve ser exibida com sucesso no campo de visão, ou seja, sem nenhum corte no texto realizado

Algumas sugestões de dimensões para o teste: 
1. 320x568
2. 360x640
3. 213x320
4. 480x854
5. 424x753
6. 320x533
7. 384x640
8. 375x667

_**Fonte:** http://whatismyscreenresolution.net/multi-screen-test_ 

**Protótipo:** https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=3858%3A0

**_16/11: Critérios de aceite retirados após alteração de escopo_**

botão "remover" do modal de exclusão 
**Dado que** estou visualizando o modal de exclusão de perfil
**Quando** clico  em "remover"
**Então** sou redirecionada para tela de confirmação de senha para exclusão 

visualização da senha digitada
**Dado que** estou digitando a minha senha no fluxo de exclusão de  perfil
**Quando** digito a senha e clico no ícone de visualizar que tem no campo de senha
**Então** posso ver qual a senha  que digitei **E** clicando novamente a senha volta a ser asteriscos 

habilitação do botão salvar
**Dado que** estou digitando a minha senha no fluxo de exclusão de perfil
**Quando** digito uma senha com no mínimo 8 dígitos 
**Então** o botão "salvar" é habilitado 

senha correta
**Dado que** estou digitando a minha senha no fluxo de adicionar informação de cadastro
**Quando** digito a senha correta e clico em "salvar"
**Então** os meus dados são salvos 

tela de sucesso
**Dado que** estou digitando a minha senha no fluxo de adicionar informação de cadastro
**Quando** digito a senha correta e meus dados são salvos
**Então** visualizo a tela de sucesso 

redirecionamento para tela de login
**Dado que** estou visualizando a tela de sucesso de exclusão do perfil
**Quando** clico no botão "ok"
**Então** sou redirecionada para tela de login 

senha incorreta
**Dado que** estou digitando a minha senha no fluxo de adicionar informação de cadastro
**Quando** digito a senha incorreta e clico em "salvar"
**Então** visualizo a mensagem de erro

**_Imagens antes da alteração de escopo:_**
https://user-images.githubusercontent.com/69155423/95883337-2fc6c580-0d51-11eb-95a8-93e908f2a7ca.png
https://user-images.githubusercontent.com/69155423/95883448-52f17500-0d51-11eb-843c-1f078675563d.png
https://user-images.githubusercontent.com/69155423/95883555-774d5180-0d51-11eb-9051-e2c985023190.png
https://user-images.githubusercontent.com/69155423/95883640-8e8c3f00-0d51-11eb-85a7-559f96a79b78.png
https://user-images.githubusercontent.com/69155423/95883770-ae236780-0d51-11eb-9a1d-e186491b5907.png

**Comment by rodrigoplimafreire** [comment]
feito! https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=3858%3A0

**Comment by victorMagalhaesPacheco** [comment]
Detalhes endpoint para consumo: https://github.com/EscolaDeSaudePublica/isus-api/issues/111#issuecomment-717328367

**Comment by wforte88** [comment]
Protótipo atualizado com nova cor, label e posição do botão de confirmação da senha para exclusão da conta:
https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=3858%3A0

**Comment by Junior-Shyko** [comment]
Protótipo atualizado com um checkbox de mostrar e ocutar senha.
https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4245%3A1024

**Comment by wforte88** [comment]
### Protótipo atualizado

**Meu Perfil > Preferências**
Opção "Excluir Perfil" renomeada para "Excluir Conta" - [Figma](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4203%3A93)
Novo texto no dialog de alerta - [Figma](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4203%3A237)

**Meu Perfil > Preferências > Exclusão de Conta**
Confirmação de exclusão da conta apenas com digitação da palavra "EXCLUIR" - [Figma](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4245%3A956)

**Comment by victorMagalhaesPacheco** [comment]
> ### Protótipo atualizado
> **Meu Perfil > Preferências**
> Opção "Excluir Perfil" renomeada para "Excluir Conta" - [Figma](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4203%3A93)
> Novo texto no dialog de alerta - [Figma](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4203%3A237)
> 
> **Meu Perfil > Preferências > Exclusão de Conta**
> Confirmação de exclusão da conta apenas com digitação da palavra "EXCLUIR" - [Figma](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4245%3A956)

@Junior-Shyko e @ruigmoreno vamos ter uma pequena alteração no fluxo.

**Comment by Junior-Shyko** [comment]
> > ### Protótipo atualizado
> > **Meu Perfil > Preferências**
> > Opção "Excluir Perfil" renomeada para "Excluir Conta" - [Figma](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4203%3A93)
> > Novo texto no dialog de alerta - [Figma](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4203%3A237)
> > **Meu Perfil > Preferências > Exclusão de Conta**
> > Confirmação de exclusão da conta apenas com digitação da palavra "EXCLUIR" - [Figma](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4245%3A956)
> 
> @Junior-Shyko e @ruigmoreno vamos ter uma pequena alteração no fluxo.

Ok, belezinha, ciente e já estou dando andamento.

**Comment by aninhasantos** [comment]
@wforte88 
Conforme acordamos: 
1) Reformular o texto da msg assim que clicar no comando "Excluir Perfil"
2) Criar novo recurso para confirmar a exclusão (retirar a senha)
3) Retirar o comando "Esqueci minha senha"

Para conhecimento @Junior-Shyko @ruigmoreno @victorMagalhaesPacheco @Clarisse1983

**Comment by wforte88** [comment]
### Protótipo atualizado

**Meu Perfil > Preferências > Exclusão de Conta > Confirmação**
Incluída mensagem de erro ao digitar texto diferente de EXCLUIR - [Figma](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4665%3A7753)

**Comment by jessica-salmazzo** [comment]
Realizado desk check e 4 ajustes ficaram pra gente atuar:

- [ ] Atualização da descrição e critérios de aceite da atividade;
- [ ] Tratamento de case sensitive no momento da confirmação da exclusão da conta para que somente permita excluir a conta se a usuária inserir o texto 'EXCLUIR' em maiúsculo;
- [ ] Tratamento de efetuar logout quando uma conta for excluída; a ideia que foi sugerida é que ao clicar em Excluir Conta, o app deve efetuar o logout (função já existente) e, em seguida, excluir a conta realmente para que não tenhamos o problema de experiência de ter algum resquício de sessão do usuário que acabou de solicitar a exclusão da conta;
- [ ] Implementar o mesmo comportamento tanto para o botão 'OK' quanto para o 'voltar' do android que será de encaminhar o usuário para a Home quando o processo de exclusão da conta ter sido realizado com sucesso.

@daianefreira @Junior-Shyko

**Comment by jessica-salmazzo** [comment]
Novo desk check realizado ontem e dois novos ajustes levantados: 

- [ ] Tratamento de limpar o campo de texto de confirmação de exclusão de conta ao sair da tela de confirmação de conta, ir pra tela anterior e, em seguida, acessar novamente a tela de confirmação de conta;
- [ ] Realizar tratamento exibindo mensagem de erro pro usuário quando ele realiza a confirmação da exclusão da conta mas o dispositivo encontra-se sem internet.

**Comment by jessica-salmazzo** [comment]
Ajuste conforme o desk check: 
- [ ] Criar margens nas laterais da tela da mensagem de sucesso da exclusão da conta para verificar se a mensagem não fica cortada dependendo da dimensão do dispositivo que estou

**Comment by jessica-salmazzo** [comment]
Testes realizados no Mi A3 (Android) e Iphone 11 (iOS).
