### ISSUE TITLE
Solicitar senha para a adição de informações profissionais

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-app#342]
## **Objetivo**
Como usuária logada
Quero ter uma solicitação de senha ao adicionar informações profissionais ao meu Perfil
Para ter mais segurança dos meus dados

## **Contexto**
Atualmente é possível que a usuária adicione informações profissionais que não forneceu no momento do cadastro, através da tela de perfil. Queremos que seja solicitada a senha da usuária  ao fim desse fluxo.

## **Escopo**
- [ ] Adicionar o campo de confirmação de senha 
<img width="321" alt="Screen Shot 2020-10-13 at 10 47 12" src="https://user-images.githubusercontent.com/69155423/95869179-7e6c6380-0d41-11eb-9879-05be2f66150d.png">

- [ ] mensagem de erro
<img width="321" alt="Screen Shot 2020-10-13 at 10 48 46" src="https://user-images.githubusercontent.com/69155423/95869414-b5db1000-0d41-11eb-9ea3-98ed03cc3060.png">

- [ ] tela de confirmação 
<img width="321" alt="Screen Shot 2020-10-13 at 10 49 20" src="https://user-images.githubusercontent.com/69155423/95869486-ca1f0d00-0d41-11eb-83b9-c2d11ea3622c.png">

- [ ] Implementação do backend que está referenciado no card: https://github.com/EscolaDeSaudePublica/isus-api/issues/96

## **Fora de escopo**
- [ ] botão de esqueci minha senha que será tratado em outra tarefa 

## **Critérios de Aceitação**

- [ ] fluxo
**Dado que** não adicionei dados profissionais durante o cadastro
**Quando** entro no perfil
**Então** sou capaz de entrar no fluxo através do botão "adicionar informações"

- [ ] redirecionamento tela de senha
**Dado que** estou no fluxo de adição de dados profissionais 
**Quando** preencho todos os campos e clico em salvar
**Então** sou redirecionada para a página de solicitação de senha 

- [ ] visualização da senha digitada
**Dado que** estou digitando a minha senha no fluxo de adicionar informação de cadastro
**Quando** digito a senha correta e clico no ícone de visualizar que tem no campo de senha
**Então** posso ver qual a senha  que digitei **E** clicando novamente a senha volta a ser asteriscos 

- [ ] habilitação do botão salvar
**Dado que** estou digitando a minha senha no fluxo de adicionar informação de cadastro
**Quando** digito uma senha com no mínimo 8 dígitos 
**Então** o botão "salvar" é habilitado 

- [ ] senha correta
**Dado que** estou digitando a minha senha no fluxo de adicionar informação de cadastro
**Quando** digito a senha correta e clico em "salvar"
**Então** os meus dados são salvos 

- [ ] redirecionamento para perfil
**Dado que** estou digitando a minha senha no fluxo de adicionar informação de cadastro
**Quando** digito a senha correta e meus dados são salvos
**Então** visualizo a tela de sucesso por 3s e sou redirecionada para a página de perfil onde tem os dados que acabei de adicionar

- [ ] senha incorreta
**Dado que** estou digitando a minha senha no fluxo de adicionar informação de cadastro
**Quando** digito a senha incorreta e clico em "salvar"
**Então** visualizo a mensagem de erro

Prototipo: https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=3858%3A0

**Comment by rodrigoplimafreire** [comment]
feito!

**Comment by daianefreira** [comment]
Issue cancelada, a confirmação ficou somente para a parte de exclusão de dados. Sendo que mesmo para exclusão a validação é realizada sem o uso da senha.
