### ISSUE TITLE
Realizar tagueamento Analytics fluxo de adição de dados profissionais ao perfil

### ISSUE THREAD

**Issue by daianefreira** [EscolaDeSaudePublica/isus-app#344]
### **Objetivo**
**Como** gestor
**Quero** visualizar e analisar o acompanhamento da evolução dos dados do iSUS de forma fácil e rápida
**Para** Tomar a melhor decisão baseada em dados

### **Contexto**
Com a evolução constante dos dados de cadastros dos profissionais, fica inviável realizar o acompanhamento por planilhas, baseado nesse contexto surgiu a necessidade de implementação de alguns indicadores para visualização completa dos dados.

### **Escopo**

- [ ] Realizar o tageamento do fluxo de adição de dados profissionais ao perfil no iSUS para visualizar os dados dentro do analytics

- [ ] Planilha com o fluxo de tageamentos:  

### **Links para ajudar**

- [ ] https://rnfirebase.io/analytics/screen-tracking

- [ ] https://developers.google.com/analytics/devguides/collection/analyticsjs/events?hl=pt-br

- [ ] https://support.google.com/analytics/answer/1033068?hl=pt-br

**Comment by jessica-salmazzo** [comment]
Atividade centralizada na issue #345.
