### ISSUE TITLE
Realizar tagueamento Analytics Home Serviços

### ISSUE THREAD

**Issue by daianefreira** [EscolaDeSaudePublica/isus-app#347]
### **Objetivo**
**Como** pessoa responsável pela evolução contínua do app iSUS
**Quero** poder visualizar e analisar os dados gerados no iSUS de forma fácil e rápida
**Para** tomar a melhor decisão e ter indícios baseados em dados do que precisa ser evoluído no app. 

### **Contexto**
Implementamos o recurso Analytics no app iSUS para alcançarmos o objetivo de colher cada vez mais dados de nossas usuárias para nos auxiliar na tomada de decisões referente à evolução do app. Com isso, surge a necessidade de implementação de novos mapeamentos do comportamento de nossas usuárias que ainda não estão mapeadas. 

Dessa forma, essa atividade tem objetivo de continuar na evolução dos tagueamentos das áreas ainda não monitoradas pelo Analytics no app iSUS. 

### **Escopo**

- [x] Realizar o tagueamento da Home para a seção Serviços no iSUS para visualizar os dados dentro do analytics

- [x] Planilha com o fluxo de tagueamentos:  
https://docs.google.com/spreadsheets/d/1w_ZUQdb5Ho-VYYKnMc8lfIUeuR8d8bZfpdP6dyy3auo/edit?usp=sharing

### **Critérios de aceite**

_Cenários abaixo para serem executados tanto em Android quanto iOS_

- [x] 1. Simulação dos dados mapeados
**Dado** que estou logada no app iSUS e na Home
**Quando** clico no ícone IntegraSUS
**Então** no Analytics deve ficar registrado essa ação conforme tageamento da planilha (Home | Click | IntegraSUS)

- [x] 2. Simulação dos dados mapeados
**Dado** que não estou logada no app iSUS e na Home
**Quando** clico no ícone IntegraSUS
**Então** no Analytics deve ficar registrado essa ação conforme tageamento da planilha (Home | Click | IntegraSUS)

- [x] 3. Simulação dos dados mapeados
**Dado** que estou logada no app iSUS e na Home
**Quando** clico no ícone SUS no Ceará
**Então** no Analytics deve ficar registrado essa ação conforme tageamento da planilha (Home | Click | SUS no Ceará)

- [x] 4. Simulação dos dados mapeados
**Dado** que não estou logada no app iSUS e na Home
**Quando** clico no ícone SUS no Ceará
**Então** no Analytics deve ficar registrado essa ação conforme tageamento da planilha (Home | Click | SUS no Ceará)

- [x] 5. Simulação dos dados mapeados
**Dado** que estou logada no app iSUS e na Home
**Quando** clico no ícone Fale Conosco
**Então** no Analytics deve ficar registrado essa ação conforme tageamento da planilha (Home | Click | Fale Conosco)

- [x] 6. Simulação dos dados mapeados
**Dado** que não estou logada no app iSUS e na Home
**Quando** clico no ícone Fale Conosco
**Então** no Analytics deve ficar registrado essa ação conforme tageamento da planilha (Home | Click | Fale Conosco)

- [x] 7. Simulação dos dados mapeados
**Dado** que estou logada no app iSUS e na Home
**Quando** clico no ícone Ações do governo
**Então** no Analytics deve ficar registrado essa ação conforme tageamento da planilha (Home | Click | Ações do Governo)

- [x] 8. Simulação dos dados mapeados
**Dado** que não estou logada no app iSUS e na Home
**Quando** clico no ícone Ações do governo
**Então** no Analytics deve ficar registrado essa ação conforme tageamento da planilha (Home | Click | Ações do Governo)

- [x] 9. Simulação dos dados mapeados
**Dado** que estou logada no app iSUS e na Home
**Quando** clico no ícone ESP
**Então** no Analytics deve ficar registrado essa ação conforme tageamento da planilha (Home | Click | ESP)

- [x] 10. Simulação dos dados mapeados
**Dado** que não estou logada no app iSUS e na Home
**Quando** clico no ícone ESP
**Então** no Analytics deve ficar registrado essa ação conforme tageamento da planilha (Home | Click | ESP)

- [x] 11. Simulação dos dados mapeados
**Dado** que estou logada no app iSUS e na Home
**Quando** clico no ícone ESP Virtual
**Então** no Analytics deve ficar registrado essa ação conforme tageamento da planilha (Home | Click | ESP Virtual)

- [x] 12. Simulação dos dados mapeados
**Dado** que não estou logada no app iSUS e na Home
**Quando** clico no ícone ESP Virtual
**Então** no Analytics deve ficar registrado essa ação conforme tageamento da planilha (Home | Click | ESP Virtual)

### **Links para ajudar**

- [ ] https://rnfirebase.io/analytics/screen-tracking

- [ ] https://developers.google.com/analytics/devguides/collection/analyticsjs/events?hl=pt-br

- [ ] https://support.google.com/analytics/answer/1033068?hl=pt-br

**Comment by ItaloRod** [comment]
Funcionou conforme esperado no Moto G7 e iPhone 11
