### ISSUE TITLE
Realizar tagueamento Analytics Home - lupa de Pesquisa

### ISSUE THREAD

**Issue by daianefreira** [EscolaDeSaudePublica/isus-app#350]
### **Objetivo**
**Como** pessoa responsável pela evolução contínua do app iSUS
**Quero** poder visualizar e analisar os dados gerados no iSUS de forma fácil e rápida
**Para** tomar a melhor decisão e ter indícios baseados em dados do que precisa ser evoluído no app. 

### **Contexto**
Implementamos o recurso Analytics no app iSUS para alcançarmos o objetivo de colher cada vez mais dados de nossas usuárias para nos auxiliar na tomada de decisões referente à evolução do app. Com isso, surge a necessidade de implementação de novos mapeamentos do comportamento de nossas usuárias que ainda não estão mapeadas. 

Dessa forma, essa atividade tem objetivo de continuar na evolução dos tagueamentos das áreas ainda não monitoradas pelo Analytics no app iSUS. 

### **Escopo**
- [ ] Estudar e definir a estratégia de qual vai ser o momento de disparo para conseguirmos mapear o texto digitado para pesquisa que a usuária inserir  

- [x] Realizar o tagueamento da Home quando a usuária clica no ícone de lupa para realizar uma pesquisa no iSUS para visualizar os dados dentro do analytics

- [x] Planilha com o fluxo de tagueamentos:  
https://docs.google.com/spreadsheets/d/19QBbzlQZaEz_Gp18zUliNiHoE3Fifo5k1NZJjPMUQhk/edit#gid=53222801

### **Critérios de aceite**

- [x] 1. Simulação dos dados mapeados
**Dado** que estou logada no app iSUS e na home
**Quando** clico na lupa de pesquisa
**Então** no Analytics deve ficar registrado essa ação conforme tageamento da planilha (Home | Click | lupa de pesquisa)

- [x] 2. Simulação dos dados mapeados
**Dado** que não estou logada no app iSUS e na home
**Quando** digito o texto de pesquisa e clico no ícone de lupa
**Então** no Analytics deve ficar registrado essa ação conforme tageamento da planilha (Home | Pesquisa | <Texto inserido para pesquisa>)

### **Links para ajudar**

- [x] https://rnfirebase.io/analytics/screen-tracking

- [x] https://developers.google.com/analytics/devguides/collection/analyticsjs/events?hl=pt-br

- [ ] https://support.google.com/analytics/answer/1033068?hl=pt-br

### **Observações**
- A implementação deve ser realizada nas plataformas de Android e iOS, e os testes devem ser executados em emuladores ou conforme for possível de acordo com a disponibilidade do recurso das plataformas.

**Comment by ItaloRod** [comment]
A estratégia definida para o disparo na pesquisa é quando ele realiza a solicitação ao servido para a busca dos resultados. Cada vez que ele terminar, este será disparado.
