### ISSUE TITLE
Realizar tagueamento Analytics seções Sobre o iSUS e Termos de Uso

### ISSUE THREAD

**Issue by daianefreira** [EscolaDeSaudePublica/isus-app#354]
### **Objetivo**
**Como** gestor
**Quero** visualizar e analisar o acompanhamento da evolução dos dados do iSUS de forma fácil e rápida
**Para** Tomar a melhor decisão baseada em dados

### **Contexto**
Com a evolução constante dos dados de cadastros dos profissionais, fica inviável realizar o acompanhamento por planilhas, baseado nesse contexto surgiu a necessidade de implementação de alguns indicadores para visualização completa dos dados.

### **Escopo**

- [ ] Realizar o tageamento das seções Sobre o iSUS e Termos de Uso no iSUS para visualizar os dados dentro do analytics

- [ ] Planilha com o fluxo de tageamentos:  

### **Links para ajudar**

- [ ] https://rnfirebase.io/analytics/screen-tracking

- [ ] https://developers.google.com/analytics/devguides/collection/analyticsjs/events?hl=pt-br

- [ ] https://support.google.com/analytics/answer/1033068?hl=pt-br

**Comment by jessica-salmazzo** [comment]
O escopo dessa atividade será tratada na de número #357
