### ISSUE TITLE
Realizar tagueamento Analytics fale conosco

### ISSUE THREAD

**Issue by daianefreira** [EscolaDeSaudePublica/isus-app#356]
### **Objetivo**
**Como** pessoa responsável pela evolução contínua do app iSUS
**Quero** poder visualizar e analisar os dados gerados no iSUS de forma fácil e rápida
**Para** tomar a melhor decisão e ter indícios baseados em dados do que precisa ser evoluído no app. 

### **Contexto**
Implementamos o recurso Analytics no app iSUS para alcançarmos o objetivo de colher cada vez mais dados de nossas usuárias para nos auxiliar na tomada de decisões referente à evolução do app. Com isso, surge a necessidade de implementação de novos mapeamentos do comportamento de nossas usuárias que ainda não estão mapeadas. 

Dessa forma, essa atividade tem objetivo de continuar na evolução dos tagueamentos das áreas ainda não monitoradas pelo Analytics no app iSUS. 

### **Escopo**

- [ ] Realizar o tagueamento do iSUS para visualizar os dados dentro do analytics

- [ ] Planilha com o fluxo de tagueamentos:  
https://docs.google.com/spreadsheets/d/1pHKzBeB_2GmqIKEUPuyVS7rQ2-rdQAkrBwh82gk8Cbo/edit?usp=sharing

### **Critérios de aceite**

- [ ] 1. Simulação dos dados mapeados
**Dado** que acesso o iSUS no Fale Conosco
**Quando** clico em Enviar com o tipo de ocorrência Relatar sugestão iSUS
**Então** no Analytics deve ficar registrado essa ação conforme tagueamento da planilha (Fale Conosco | Click | Enviar {{tipo de ocorrência}})

- [ ] 2. Simulação dos dados mapeados
**Dado** que acesso o iSUS no Fale Conosco
**Quando** clico em Enviar com o tipo de ocorrência Relatar problema iSUS
**Então** no Analytics deve ficar registrado essa ação conforme tagueamento da planilha (Fale Conosco | Click | Enviar {{tipo de ocorrência}})

- [ ] 3. Simulação dos dados mapeados
**Dado** que acesso o iSUS no Fale Conosco
**Quando** clico em Enviar com o tipo de ocorrência Alerta de falta de EPI
**Então** no Analytics deve ficar registrado essa ação conforme tagueamento da planilha (Fale Conosco | Click | Enviar {{tipo de ocorrência}})

- [ ] 4. Simulação dos dados mapeados
**Dado** que acesso o iSUS no Fale Conosco
**Quando** clico em Enviar com o tipo de ocorrência Demanda por educação permanente
**Então** no Analytics deve ficar registrado essa ação conforme tagueamento da planilha (Fale Conosco | Click | Enviar {{tipo de ocorrência}})

### **Links para ajudar**

- [ ] https://rnfirebase.io/analytics/screen-tracking

- [ ] https://developers.google.com/analytics/devguides/collection/analyticsjs/events?hl=pt-br

- [ ] https://support.google.com/analytics/answer/1033068?hl=pt-br,

### **Observações**
- A implementação deve ser realizada nas plataformas de Android e iOS, e os testes devem ser executados em emuladores ou conforme for possível de acordo com a disponibilidade do recurso das plataformas.

**Comment by jessica-salmazzo** [comment]
O escopo dessa atividade será tratada na de número #357
