### ISSUE TITLE
Realizar tagueamento Analytics do Menu lateral

### ISSUE THREAD

**Issue by daianefreira** [EscolaDeSaudePublica/isus-app#357]
### **Objetivo**
**Como** pessoa responsável pela evolução contínua do app iSUS
**Quero** poder visualizar e analisar os dados gerados no iSUS de forma fácil e rápida
**Para** tomar a melhor decisão e ter indícios baseados em dados do que precisa ser evoluído no app. 

### **Contexto**
Implementamos o recurso Analytics no app iSUS para alcançarmos o objetivo de colher cada vez mais dados de nossas usuárias para nos auxiliar na tomada de decisões referente à evolução do app. Com isso, surge a necessidade de implementação de novos mapeamentos do comportamento de nossas usuárias que ainda não estão mapeadas. 

Dessa forma, essa atividade tem objetivo de continuar na evolução dos tagueamentos das áreas ainda não monitoradas pelo Analytics no app iSUS. 

### **Escopo**

- [x] Realizar o tagueamento do Menu lateral no iSUS para visualizar os dados dentro do analytics

- [x] Planilha com o fluxo de tagueamentos:  
https://docs.google.com/spreadsheets/d/1T-UAUSyyrkjM5ep6s67-E2M1mTn3fUteRLx0MNhdjPk/edit?usp=sharing

### **Critérios de aceite**

- [x] 1. Simulação dos dados mapeados
**Dado** que estou logada no app iSUS e no menu lateral
**Quando** clico em Home
**Então** no Analytics deve ficar registrado essa ação conforme tageamento da planilha (Home | Click | Home)

- [x] 2. Simulação dos dados mapeados
**Dado** que não estou logada no app iSUS e no menu lateral
**Quando** clico em Home
**Então** no Analytics deve ficar registrado essa ação conforme tageamento da planilha (Home | Click | Home)

- [x] 3. Simulação dos dados mapeados
**Dado** que estou logada no app iSUS e no menu lateral
**Quando** clico em Meu perfil
**Então** no Analytics deve ficar registrado essa ação conforme tageamento da planilha (Home | Click | Meu perfil)

- [x] 4. Simulação dos dados mapeados
**Dado** que não estou logada no app iSUS e no menu lateral
**Quando** clico em Meu perfil
**Então** no Analytics deve ficar registrado essa ação conforme tageamento da planilha (Home | Click | Meu perfil)

- [x] 5. Simulação dos dados mapeados
**Dado** que estou logada no app iSUS e no menu lateral
**Quando** clico no ícone Fale Conosco
**Então** no Analytics deve ficar registrado essa ação conforme tageamento da planilha (Home | Click | Fale Conosco)

- [x] 6. Simulação dos dados mapeados
**Dado** que não estou logada no app iSUS e no menu lateral
**Quando** clico no ícone Fale Conosco
**Então** no Analytics deve ficar registrado essa ação conforme tageamento da planilha (Home | Click | Fale Conosco)

- [x] 7. Simulação dos dados mapeados
**Dado** que estou logada no app iSUS e no menu lateral
**Quando** clico em SUS no Ceará
**Então** no Analytics deve ficar registrado essa ação conforme tageamento da planilha (Home | Click | SUS no Ceará)

- [x] 8. Simulação dos dados mapeados
**Dado** que não estou logada no app iSUS e no menu lateral
**Quando** clico em SUS no Ceará
**Então** no Analytics deve ficar registrado essa ação conforme tageamento da planilha (Home | Click | SUS no Ceará)

- [x] 9. Simulação dos dados mapeados
**Dado** que estou logada no app iSUS e no menu lateral
**Quando** clico em Sobre o iSUS
**Então** no Analytics deve ficar registrado essa ação conforme tageamento da planilha (Home | Click | Sobre o iSUS)

- [x] 10. Simulação dos dados mapeados
**Dado** que não estou logada no app iSUS e no menu lateral
**Quando** clico em Sobre o iSUS
**Então** no Analytics deve ficar registrado essa ação conforme tageamento da planilha (Home | Click | Sobre o iSUS)

- [x] 11. Simulação dos dados mapeados
**Dado** que estou logada no app iSUS e no menu lateral
**Quando** clico em Termos de Uso
**Então** no Analytics deve ficar registrado essa ação conforme tageamento da planilha (Home | Click | Termos de Uso)

- [x] 12. Simulação dos dados mapeados
**Dado** que estou logada no app iSUS e no menu lateral
**Quando** clico em Termos de Uso
**Então** no Analytics deve ficar registrado essa ação conforme tageamento da planilha (Home | Click | Termos de Uso)

- [x] 14. Simulação dos dados mapeados
**Dado** que estou logada no app iSUS e no menu lateral
**Quando** clico em Compartilhe o iSUS
**Então** no Analytics deve ficar registrado essa ação conforme tageamento da planilha (Home | Click | Compartilhe o iSUS)

- [x] 15. Simulação dos dados mapeados
**Dado** que não estou logada no app iSUS e no menu lateral
**Quando** clico em Compartilhe o iSUS
**Então** no Analytics deve ficar registrado essa ação conforme tageamento da planilha (Home | Click | Compartilhe o iSUS)

### **Links para ajudar**

- [x] https://rnfirebase.io/analytics/screen-tracking

- [x] https://developers.google.com/analytics/devguides/collection/analyticsjs/events?hl=pt-br

- [x] https://support.google.com/analytics/answer/1033068?hl=pt-br,

### **Observações**
- A implementação deve ser realizada nas plataformas de Android e iOS, e os testes devem ser executados em emuladores ou conforme for possível de acordo com a disponibilidade do recurso das plataformas.

**Comment by ItaloRod** [comment]
alterei o nome das labels na planilha para entrarem para serem enviadas corretamente para o Analytics. O Google Analytics não suporta nomes de labels contendo espaços e acentuação. Aproveitei e deixei todos os nomes com letras minúsculas.
