### ISSUE TITLE
Inscrição para Curso em Cascavel

### ISSUE THREAD

**Issue by daianefreira** [EscolaDeSaudePublica/isus-app#362]

**Comment by daianefreira** [comment]
## **Duvidas**
Onde será apresentado o link para inscrição?
Quais as condições para exibir ou não essa oferta? Vamos usar localização para ver se a pessoa esta ou é de cascavel?
Mesmo quem não é cadastrado recebe esse de incentivo?
É necessário um email para confirmar inscrição? 
Vamos criar lembrete do evento na agenda da pessoa?

## **O que precisamos**
- [ ] De uma descrição sobre o curso
- [ ] Dia, horário, local
- [ ] Uma imagem


## **UX**
- [ ] Criar Pop up para confirmação de desejo de exclusão 
- [ ] Cenário de sucesso (Mensagem confirmando inscrição)
- [ ] Cenário de falha (Retorno de erro do backend)
- [ ] Cenário de falta de internet

**Comment by daianefreira** [comment]
*Cadastro e certificado...  
*Acrescentar as categorias profissionais...

**Comment by daianefreira** [comment]
*pre e pos teste

**Comment by aninhasantos** [comment]
1) Cadastro por categorias (para integrar com o SAGU)
2) Inscrição do aluno no curso Materno Infantil (que é parte do programa Nascer Ceara)
3) Disponibilizar o material (PDF) para o curso como linha de cuidado 
4) Exibir o certificado (do SAGU)

**Comment by Clarisse1983** [comment]
Esse curso foi adiado, está sem data definida, portanto a tarefa foi bloqueada até novas definições.

**Comment by luisfcosta2015** [comment]
Fechando a issue porque o curso já aconteceu. Se formos procurados novamente reabrimos e editamos a demanda.

**Comment by Clarisse1983** [comment]
O curso não aconteceu, na verdade, rs. Mas é isso, caso sejamos procurados,
reabrimos.

*Clarisse Castro Cavalcante*
Jornalista pela Universidade Federal do Piauí.
Especialista em Teorias da Comunicação e da Imagem pela Universidade
Federal do Ceará.
Mestre e Doutora em Informação e Comunicação em Saúde pela Fundação Oswaldo
Cruz (RJ).
85.981116986





Em qua., 17 de fev. de 2021 às 16:26, Luis Felipe Coimbra Costa <
notifications@github.com> escreveu:
