### ISSUE TITLE
Criar seção Linhas de Cuidados e Protocolos

### ISSUE THREAD

**Issue by daianefreira** [EscolaDeSaudePublica/isus-app#365]
## **Objetivo**
**Como** usuária do aplicativo iSUS
**Quero** visualizar uma seção separada para linha de cuidados contendo o Manejo Clinico
**Para** facilitar o acesso a informações referente as linhas de cuidados e Protocolos

## **Contexto**
Para viabilizar a iniciativa de disponibilizar protocolos e linhas de cuidados, é importante que seja criada uma seção separada na home do iSUS. O primeiro item que será criado na seção será a do Manejo Clinico que já existe disponível no aplicativo, mas hoje se encontra no banner. 

## **Escopo**
- [x] Criar uma nova seção na home do iSUS para linha de cuidados e Protocolos
- [x] Criar um ícone para identificar o Manejo Clínico 
- [x] Redirecionar o usuário para mesma tela que é apresentada quando clicamos no banner de manejo clínico já existente
- [x] Retirar o banner assim que subir a seção com o ícone. 

## **Fora de Escopo**
- A linha de cuidado Materno Infantil será contemplada em outra história

## **UX**
- [x] Definir cor a ser usada para os cards dessa seção
- [x] Criar modelo de card para Manejo Clínico 

## **Critérios de Aceitação**
- [x] Visualizar seção da linha de cuidados e Protocolos
**Dado** que acessei o iSUS
**Quando** estou na home 
**Então** visualizarei a seção "Linha de Cuidados e Protocolos" logo antes da seção "Força-tarefa Anticorona"

- [x] Acessar conteúdo sobre linha de cuidado
**Dado** que estou na seção de "Linha de Cuidados e Protocolos"
**Quando** clico no ícone de manejo clínico 
**Então** visualizarei a tela "Manejo clínico dos pacientes com Covid-19

## **Observações**
[Seção "Linhas de Cuidados e Protocolos" e ícone de "Manejo Clínico"
](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4296%3A10283)
Cor utilizada: #9c27b0

**Comment by rodrigoplimafreire** [comment]
Feito.
![image](https://user-images.githubusercontent.com/46686642/96275233-ddcbad00-0fa7-11eb-84ee-b0b59e358a48.png)

**Comment by daianefreira** [comment]
Olhar questão da imagem para trazer manejo clinico para essa seção.

**Comment by daianefreira** [comment]
![home](https://user-images.githubusercontent.com/969604/98287326-f403d200-1f83-11eb-8377-6ce01357588a.png)

**Comment by nicoledbianchin** [comment]
Versão: 3.11.2
OS: dispositivo Android

Comportamento de acordo com o esperado.
