### ISSUE TITLE
Adicionar linha de cuidados Nascer no Ceará

### ISSUE THREAD

**Issue by daianefreira** [EscolaDeSaudePublica/isus-app#366]
https://www.socego.com.br/nascer-no-ceara/

**Comment by rodrigoplimafreire** [comment]
Feito...
![image](https://user-images.githubusercontent.com/46686642/96275272-e8864200-0fa7-11eb-9628-39c92ae4fb40.png)

**Comment by jessica-salmazzo** [comment]
Essa atividade será arquivada porque está duplicada com essa outra atividade #393

**Comment by Laysacunha** [comment]
Atividade duplicada com #393 que já foi concluída.
