### ISSUE TITLE
Renomear a branch principal do repositório padrão do app para main

### ISSUE THREAD

**Issue by ItaloRod** [EscolaDeSaudePublica/isus-app#367]
### **Objetivo**
**Eu como** pessoa desenvolvedora 
**quero que** os nomes das branchs padrões do github sejam renomeadas para main em vez de master 
**para que** seja evitado referências à escravidão. 

### **Contexto**
A partir de agora todas as novas branches padrões  do github se chamarão main no lugar da master para evitar referências à escravidão. 
É importante para o iSUS e seus repositórios rejeitar quaisquer referências racistas.

### **Escopo**
- [x] Realizar o renomeio das branchs de master para main

### **Critérios de Aceitação**
- [x] Apresentar para o time como ficou os nomes das branchs no repositório
**Dado** o repositório padrão do app
**Quando** eu visualiza-lo em detalhes e consultar os nomes das branches
**Então** perceberei a alteração dos nomes das branches de master para main 

### **Links Úteis**
- https://github.com/github/renaming
- Link de como realizar a troca de branches: https://alismed.github.io/blog/2020/07/27/mudar-master-main.html

**Comment by uira** [comment]
@ItaloRod ❤️❤️❤️❤️❤️❤️

**Comment by ItaloRod** [comment]
Link de como realizar a troca de branches: https://alismed.github.io/blog/2020/07/27/mudar-master-main.html
