### ISSUE TITLE
Gerenciamento de notificações dentro do aplicativo

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-app#368]
## Objetivo

**Como**  usuária do aplicativo iSUS
**Quero** gerenciar minhas notificações 
**Para** ter melhor domínio das novidades publicadas no app

## Contexto

Para melhorar a experiência da usuária com uso o iSUS, precisamos qualificar a exposição das notificações e o auto gerenciamento do consumo destes conteúdos. 
Obs.: O contador de notificações irá controlar itens não vistos e o fundo da notificação irá representar o status de lida ou não lida. 

## **UX**
- [x] Desenhar modelo sem as divisões 
- [x] Apresentar número de notificações no menu lateral
- [x] Criar diferenciação entre notificações lidas e não lidas
- [x] Criar experiência da usuária quando ainda não há notificações
[Figma (Layout)](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4292%3A0)

## Escopo 
- [x] Adicionar no menu lateral, o submenu "Notificações" seguido do contador de alertas não vistos
- [x] Apresentar alerta (bolinha vermelha) no ícone do menu lateral quando houver notificações não vistas 
- [x] Abrir uma tela com a lista de notificações ordenadas por data mais recente assim que a usuária clicar no submenu (utilizar recurso scroll infinity)
- [ ] Zerar o contador de notificações assim que abrir a tela 
- [x] Apresentar notificações não lidas com fundo amarelo e as lidas com fundo branco
- [ ] Mudar o status da notificação de fundo amarelo para fundo branco somente quando a usuária clicar na notificação
- [x] Mudar o status de todas as notificações de fundo amarelo para fundo branco quando a usuária acionar o comando "Marcar todas como lidas" 
- [x] Apresentar a tela de notificações apenas com a msg: "Aqui você verá as notificações envidas sobre atividades, notícias e atualidades do SUS no Ceará" quando não houver nenhum item para a usuária.
- [x] Quando a notificação é do dia corrente, então a notificação deve ser registrada que aconteceu há X horas
- [x] Quando a notificação é da semana corrente, então a notificação deve ser registrada que aconteceu no dom às {{horário}} ou seg às {{horário}} ou ter às {{horário}} ou qua às {{horário}} ou qui às {{horário}} ou sex às {{horário}} ou sab às {{horário}} conforme o dia da semana que ocorreu a notificação 
- [x] Quando a notificação é de mais de 7 dias atrás, então a notificação deve ser registrada que aconteceu em {{data - formato DD de MM}} às {{horário}}. Exemplo: 01 DE SET ÀS 22:15. 

_Obs.: As escritas dos horários das notificações e o botão são em maiúsculo._ 

## Fora de Escopo 
- Nesta primeira versão, não será possível remover uma ou todas notificações

## Critérios de Aceite
- [ ] Visualizar o alerta (bolinha vermelha) no ícone do menu lateral
**Dado** que possuo notificações não vistas 
**Quando** abro o app iSUS
**Então** visualizo o alerta no ícone do menu lateral 

- [ ] Visualizar o menu notificações 
**Dado** que possuo notificações não vistas 
**Quando** aciono o menu lateral 
**Então** visualizo o contador quantificando as notificações não vistas

- [ ] Visualizar apenas menu sem contador
**Dado** que não possuo notificações não vistas 
**Quando** abro o app iSUS
**Então** visualizo o menu lateral "Notificações" sem alerta e sem contador

- [ ] Listar minhas notificações 
**Dado** que quero visualizar minhas notificações
**Quando** clico no submenu "Notificações"
**Então** visualizo todas elas existentes

- [ ] Diferenciar notificações lidas de não lidas
**Dado** que quero identificar o status de minhas notificações 
**Quando** visualizo a lista 
**Então** percebo a distinção de fundo amarelo para não lidas e fundo branco para lidas

- [ ] Marcar todas como lidas 
**Dado** que quero marcar todas como lidas 
**Quando** clico no botão "Marcar todas como lidas"
**Então** toda a lista fica com fundo branco

- [ ] Msg para usuária sem notificações
**Dado** que quero visualizar minhas notificações
**Quando** clico no menu "Notificações" e ainda não recebi nenhuma
**Então** vejo a tela de notificações sem nenhum item e com a mensagem "Aqui você verá as notificações enviadas sobre atividades, notícias e atualidades do SUS no Ceará"

- [ ] Distinção do registro de horários das notificações - semanas atrás 
**Dado** que possuo uma notificação não vista e não lida de 3 semanas atrás
**Quando** acesso o submenu de Notificações
**Então** visualizo que o registro de horário da notificação está com formato de data e hora 

- [ ] Distinção do registro de horários das notificações - na semana corrente
**Dado** que possuo uma notificação não vista e não lida da semana corrente 
**Quando** acesso o submenu de Notificações
**Então** visualizo que o registro de horário da notificação está registrando o dia da semana e hora que a notificação foi enviada

- [ ] Distinção do registro de horários das notificações - no dia
**Dado** que possuo uma notificação não vista e não lida do dia
**Quando** acesso o submenu de Notificações
**Então** visualizo que o registro de horário da notificação está registrando que a notificação foi enviada há X horas

## **Dúvidas** 
- Qual o período em que as notificações ficam sendo exibidas? semana, dia? 
Não existirá prazo. 
- Possui status? (lida, nao lida) 
Sim, lida e não lida. As não lidas ficarão com fundo amarelo, as lidas fundo branco. 
- As notificações tem tipo? quais serias os tipos? 
Não implementar tipos nesta primeira versão.
- Caso desative como faço para reativar? 
Não existirá função para desativar. 
- Botão fica no final da página? 
Sim.
- Ao clicar na notificação, é direcionado para webview ou navegador? 
Conforme notificação original.
- Ao clicar no submenu de Notificações, o contador zera mas o fundo das notificações não lidas permanece sem alteração até que a usuária clique na notificação em si? 
Sim.
- A bolinha vermelha representa notificações não lidas ou notificações não vistas? 
Notificações não vistas. 

## Observações 
- Programa para push de notificações One Signal
[Figma (Layout)](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4292%3A0)
- Essa atividade é dependente da atividade #408, ou seja, enquanto a atividade #408 não for realizada e finalizada, essa atividade em questão não pode ser iniciada.

**Comment by rodrigoplimafreire** [comment]
Feito.
![image](https://user-images.githubusercontent.com/46686642/96273777-18344a80-0fa6-11eb-9b05-9ee521fbd1dc.png)

**Comment by wforte88** [comment]
Sugestões para análise:

![image](https://user-images.githubusercontent.com/21333612/98382872-8959a180-202a-11eb-9beb-84dbedaf3e69.png)
![image](https://user-images.githubusercontent.com/21333612/98382928-9bd3db00-202a-11eb-86d1-9ddafc474810.png)
![image](https://user-images.githubusercontent.com/21333612/98382984-ac845100-202a-11eb-9ffe-e13c6aa6f72b.png)

OU

![image](https://user-images.githubusercontent.com/21333612/98383059-c32aa800-202a-11eb-8f6c-66664de4f023.png)

**Comment by ericsonmoreira** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/iSUS---Refinamento-61672dbc32f1ce0015aa7eca/issues/EscolaDeSaudePublica/isus-app/368?planning-poker) with ZenHub @janeteamaral @JefersonNSoares @Laysacunha

**Comment by Laysacunha** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/iSUS---Refinamento-61672dbc32f1ce0015aa7eca/issues/EscolaDeSaudePublica/isus-app/368?planning-poker) with ZenHub @fpontef

**Comment by ericsonmoreira** [comment]
Implementação das interfaces concluída. A integração com o serviço de notificação e/ou API será implementado em outra `issue`.
