### ISSUE TITLE
Integrar experiência de cadastro de usuários do ID Saúde

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-app#370]
**Contexto** 
Ser possível deixar claro para a usuária que os cadastros no Mapas e iSUS utilizam uma plataforma compartilhada (ID Saúde) e que existe um compartilhamento de informações entre as plataformas. 

Dessa forma, caso a usuária já tenha cadastro no Mapas e consentir o compartilhamento de dados, então é possível que o cadastro dela no iSUS já exista automaticamente ou que ela só tenha que adicionar algumas informações a mais, as demais seriam aproveitadas do cadastro já existente no Mapas e vice-versa. 

**Sugestão de jornada da usuária no cadastro iSUS** 
1. Solicitar que a usuária insira o CPF

2. Verificar o CPF informando e retornar feedback para a usuária 
2.1 CPF já cadastrado, então apareceria uma mensagem informando que já temos ciência do CPF por conta de alguma plataforma (ex. Mapas) explicando que ambas plataformas utilizam o ID Saúde

3. Perguntamos para a usuária se podemos aproveitar as informações que ela já possui no ID Saúde por conta do cadastro que ela já tem no Mapas
3.1 Se ela permitir, a gente segue com o cadastro só perguntando se as informações estão atualizadas e solicitamos somente informações adicionais que ainda não temos, o restante dos dados, pegamos do Mapa
3.2 Se ela não permitir, ai prosseguimos com o cadastro de forma manual, solicitando o preenchimento das informações 
(Verificar se ela poderá ter acesso a todas as informações e funcionalidades do iSUS; caso ela tenha uma experiência mais restrita, deixar explícito esse informativo para a usuária estar ciente)

4. CPF não cadastrado ainda, então segue pro cadastro normal, conforme processo que temos hoje

5. Explicitar que o iSUS utiliza o ID Saúde que é fornece seu serviço de cadastro para demais plataformas e que por conta disso, é possível que haja compartilhamento de dados solicitando o acordo ou não desse compartilhamento. 

6. Concorda, então segue pro cadastro 

7. Não concorda, então... (???)

Referência de telas para a ampliação do Cadastro: #263

**Comment by jessica-salmazzo** [comment]
Vamos agendar uma conversa com uma pessoa que possui conhecimento claro sobre LGPD para conseguirmos esclarecer dúvidas sobre como devemos lidar e o que devemos implementar nas atividades de compartilhamento de dados/cadastros entre ID Saúde, Mapa da Saúde, iSUS, entre outras plataformas. 

Tendo essas questões esclarecidas, conseguimos seguir com o refinamento e detalhamento das estórias.

@Clarisse1983 está em contato para marcar a reunião.

**Comment by Clarisse1983** [comment]
Essa tarefa está dependendo da definição da arquitetura de dados do próprio ID Saúde (autenticador geral), que deverá prever a integração de todos os cadastros dos nossos sistemas (iSUS, Mapa etc). As jornadas das usuárias dependem diretamente dessa arquitetura.
