### ISSUE TITLE
Consentimento da usuária do MAPAS para utilizar seus dados no iSUS

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-app#371]
**Contexto**
Atualmente, existem algumas plataformas que utilizam o ID Saúde para a realização do cadastro da usuária, exemplo de plataformas: o próprio iSUS e Mapa da Saúde. 
Dessa forma, quando uma usuária do Mapa da Saúde realiza seu cadastro na plataforma do mapa, caso ela venha a conhecer o iSUS e realizar a ação de cadastro, o iSUS retornará que o cadastro dela já está realizado, visto que o Mapa e o iSUS utilizam a mesma 'central de cadastros de usuárias' que é o ID Saúde. 

Tendo isso, temos algumas problemáticas que precisamos resolver: 
- Como deixar claro para a usuária que essas plataformas utilizam o ID Saúde?
- Como deixar claro para a usuária quais dados estão sendo compartilhados entre as plataformas? 
- Como conseguir a ciência e o consentimento da usuária de que os dados de cadastro são compartilhados?

**Comment by jessica-salmazzo** [comment]
Atividade duplicada com a #410. Dessa forma, será fechada para não termos atividades duplicadas no backlog.
