### ISSUE TITLE
Implementação refresh token (app)

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/isus-app#373]
### **Contexto**
Atualmente o token do usuário expira depois de um determinado tempo "x", ao expirar e ser realizado uma solicitação para API gerar um novo token atualizado baseado no refresh token.

### **Objetivo**
**Eu como**  profissional da saúde
**Quero** realizar o login no aplicativo e após alguns dias sem acessar o aplicativo, acessar o meu perfil e continuar com os meus dados preenchidos.
**Para** consultar o perfil sem perder a sessão

 Card que representa essa tarefa na api: https://github.com/EscolaDeSaudePublica/isus-api/issues/101

**Comment by victorMagalhaesPacheco** [comment]
Fluxo:
![Captura de tela de 2020-10-08 17-12-55](https://user-images.githubusercontent.com/3487411/95508528-8a46d700-0989-11eb-8c0a-1af057381d49.png)

**Comment by KelmaSouto** [comment]
**Comportamento atual: (EM TESTE)**  
Dado que eu como profissional da saúde, realizei meu login no app.
Dados que após alguns dias sem acessar o app, volto para acessar o meu perfil e continuo com os meus dados preenchidos.
Então consulto o perfil sem perder a sessão. 

**Comportamento esperado:** 
Dado que eu como profissional da saúde, realizei meu login no app.
Dados que após alguns dias sem acessar o app, volto para acessar o meu perfil e continuo com os meus dados preenchidos.
Então consulto o perfil sem perder a sessão.

**Comment by KelmaSouto** [comment]
![Implementação refresh token (app) #373 - Kelma Souto](https://user-images.githubusercontent.com/65924048/97480458-31d47b00-1932-11eb-90c4-db6eeca2a25d.jpg)
