### ISSUE TITLE
Cadastro Profissional-Melhorias na experiência do cadastro do profissional

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/isus-app#375]
### **Contexto**
- Ao fim do cadastro usuário ir pra tela de perfil já logado.
- Verificação do CPF na primeira tela, assim que que digita o CPF.
- Feedback visual nos campos de e-mail e CPF

Observação: Necessário refinar e distribuir em outros cards.

**Comment by Laysacunha** [comment]
Comportamentos descritos na issue já implementados e em pleno funcionamento. Issue será fechada.
