### ISSUE TITLE
No fim do cadastro do profissional ir pra tela de perfil já logado.

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/isus-app#376]
### **Objetivo**
**Como** profissional da saúde
**Quero** Realizar meu cadastro no idSaúde através do aplicativo iSUS e automaticamente ir para a tela de perfil sem a necessidade de realizar o processo de autenticação
**Para** Acessar as informações de perfil de forma rápida e sem burocracia

### **Contexto**
Atualmente no final do processo de cadastro do profissional, o usuário é redirecionando para preencher os dados de login (autenticação) sendo que nas etapas anteriores os dados já foram fornecidos, o que adiciona mais um processo no fluxo (autenticação), necessário realizar o processo transparente de autenticação do profissional e acessar o perfil.

## **Escopo**

- [x] Acessar perfil sem necessidade de autenticação após cadastro

## **Critérios de Aceite**

- [x] Acesso ao perfil após cadastro 
**Dado que** preencho todos os dados para cadastro
**Quando** clico no botão de cadastrar e recebo uma mensagem de sucesso (cadastro bem sucedido)
**Então** Sou redirecionado para a página de perfil com meus dados previamente cadastrado

**Comment by nicoledbianchin** [comment]
OS: Android
Versão: 3.11.0
Comportamento de acordo com o esperado.
