### ISSUE TITLE
Verificação do CPF e EMAIL já existente no primeiro formulário

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/isus-app#377]
### **Objetivo**
**Como** usuária
**Quero** preencher o EMAIL e CPF no formulário de cadastro no aplicativo do iSUS e ao preencher qualquer um desses campos obrigatórios e ÚNICO no sistema, se já existir cadastro na base, adicionar de forma visual uma mensagem informando que o usuária já existe na aplicação.
**Para** Otimizar o fluxo de cadastro sem a necessidade de ir até o ultimo formulário e receber a mensagem de verificação.

### **Contexto**
Atualmente o processo de validação dos dados preenchidos pelo usuário é informado apenas no fim do processo, ou seja necessário preencher todos os dados e em seguida ter uma resposta da validação tanto do CPF como também do EMAIL que são únicos.

## **Escopo**

- [x] Verificação de CPF já existente na base do iSUS
- [x] Verificação de EMAIL já existente na base do iSUS

## **Critérios de Aceite**

- [x] Validação CPF
**Dado que** Acesso o formulário de cadastro e preencho o CPF com um CPF que já existe na base
**Quando** Digito o ultimo número do CPF já existente na base
**Então** Recebo uma mensagem informando que o CPF já está cadastrado e o campo fica com as bordas vermelha pra especificar o alerta.

- [x] Validação EMAIL
**Dado que** Acesso o formulário de cadastro e preencho o EMAIL com um EMAIL que já existe na base
**Quando** finalizo o preenchimento do CPF
**Então** Recebo uma mensagem informando que o EMAIL já está cadastrado e o campo fica com as bordas vermelha pra especificar o alerta.

Atividades vínculadas: https://github.com/EscolaDeSaudePublica/isus-api/issues/103 e https://github.com/EscolaDeSaudePublica/isus-api/issues/104

**Comment by victorMagalhaesPacheco** [comment]
Atividade concluída na API, referência cards: https://github.com/EscolaDeSaudePublica/isus-api/issues/103 e https://github.com/EscolaDeSaudePublica/isus-api/issues/104

**Comment by ItaloRod** [comment]
Testamos a versão de homologação e encontramos os seguintes problemas no cadastro:
* Ao digitar uma senha, o mesmo informa que as senhas não são iguais, mesmo sendo.
![image](https://user-images.githubusercontent.com/20058085/96178500-e075c600-0f05-11eb-9c6d-46ffc0dfa812.png)

* Ao realizar o cadastro, ele acusa como se não estivesse no formato correto, mesmo estando.
* O Município de residência não funciona conforme esperado, não abrindo os municípios.

**Comment by ItaloRod** [comment]
Testamos usando a API de Homologação e Produção porém não conseguimos reproduzir os mesmos problemas encontrado na sexta-feira. Todos os cadastrados não apresentavam erros, mesmo com os mesmos dados imputados e seleção de municípios, tanto no simulador como instalando o .apk nos dispositivos.

**Comment by ruigmoreno** [comment]
> 
> 
> Testamos usando a API de Homologação e Produção porém não conseguimos reproduzir os mesmos problemas encontrado na sexta-feira. Todos os cadastrados não apresentavam erros, mesmo utilizando os mesmos dados imputados nos prints e seleção de municípios, tanto no simulador como instalando o .apk nos dispositivos.

Informações técnicas do dispositivo de teste:
**_Moto G6 Plus_**
**_Versão Android: 9_**
**_Build Number: PPW29.116-16-29_**

**Comment by nicoledbianchin** [comment]
Comportamento do campo de CPF e do campo de Email de acordo com o esperado.
OS: Dispositivo Android
Versão: 3.11.0
