### ISSUE TITLE
Feedback visual nos campos de e-mail e CPF

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/isus-app#378]
### **Objetivo**
**Como** usuária do iSUS
**Quero** preencher o EMAIL ou CPF no formulário de cadastro no aplicativo do iSUS e ao preencher qualquer um desses campos e algum estiver com irregularidades, mostrar de forma visual o feedback do erro (cor vermelha).
**Para** ter uma visão fácil de quais campos estão com alguma irregularidade.

### **Contexto**
Atualmente o processo de validação dos dados preenchidos pelo usuário é informado EMAIL ou CPF no formulário no aplicativo do iSUS e ao preencher qualquer um desses campos e algum estiver com irregularidades, mostrar de forma visual o feedback do erro (cor vermelha).

Atividades vínculadas: #377

**Comment by nicoledbianchin** [comment]
Comportamentos de acordo com o esperado. O feedback visual foi aplicado para todos os campos do cadastro de informações pessoais, como foi acordado em conversa com o Victor.
OS: Dispositivo Android
Versão: 3.11.0
