### ISSUE TITLE
Adicionar mensagem quando o storage do aplicativo está cheio ao baixar conteúdo offline

### ISSUE THREAD

**Issue by ItaloRod** [EscolaDeSaudePublica/isus-app#379]
### **Objetivo**
**Eu como** usuária do app iSUS 
**gostaria de** ser informada quando não é possível realizar o download de algum conteúdo offline 
**para que** eu possa ficar ciente de que o processo não foi bem sucedido. 

### **Contexto**
Atualmente, ao baixar conteúdo nas seções de educação e pesquisa e o storage do aplicativo estiver com o armazenamento cheio, a usuária se depara com um erro em inglês, não tratado e que não informa o que aconteceu. Dessa forma, surge a necessidade de tratar a mensagem que hoje é exibida para que a usuária saiba que o processo de download não foi bem sucedido. 

Hoje o app utiliza um recurso de async que faz com que os conteúdos offline sejam armazenados em um determinado espaço delimitado pelo próprio app, ou seja, não é utilizado hoje, a quantidade total livre disponível do dispositivo da usuária para armazenamento dos conteúdos offline, dessa forma, é possível que ao tentar baixar um conteúdo, esse espaço não esteja mais disponível. Ao mesmo tempo, não podemos exibir uma mensagem informando sobre o armazenamento do dispositivo, visto que o app não utiliza esse recurso de armazenamento no dispositivo ainda. 

### **Pendências**
- [x] Confirmar o contexto descrito aqui  
- [x] Definir solução
- [x] Continuar as descrições dos critérios de aceite conforme definições

### **UX**
- [x] Pensar em uma mensagem que informe a usuária que foi identificado que o armazenamento do dispositivo está cheio e não conseguimos espaço pra disponibilizar o conteúdo offline por conta disso

### **Escopo**
- [x] Implementar mensagem informando a usuária que não foi possível realizar a ação de download conforme [figma](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4880%3A0)

![image](https://user-images.githubusercontent.com/74663400/100462612-45960d00-30a9-11eb-9edc-dc4546e561b6.png)

### **Critérios de Aceitação**
- [ ] Tentativa de realizar download usuária logada
**Dado** que estou logada no iSUS 
**E** o async encontra-se cheio
**Quando** tento realizar o download de algum conteúdo de Educação Permanente 
**Então** uma mensagem é exibida informando que não é possível realizar o download

- [ ] Tentativa de realizar download usuária não logada
**Dado** que não estou logada no iSUS 
**E** o async encontra-se cheio
**Quando** tento realizar o download de algum conteúdo de Educação Permanente 
**Então** uma mensagem é exibida informando que não é possível realizar o download

- [ ] Tentativa de realizar download usuária logada
**Dado** que estou logada no iSUS 
**E** o async encontra-se cheio
**Quando** tento realizar o download de algum conteúdo de Pesquisa
**Então** uma mensagem é exibida informando que não é possível realizar o download

- [ ] Tentativa de realizar download usuária não logada
**Dado** que não estou logada no iSUS 
**E** o async encontra-se cheio
**Quando** tento realizar o download de algum conteúdo de Pesquisa
**Então** uma mensagem é exibida informando que não é possível realizar o download

- [ ] Tentativa de realizar download usuária logada
**Dado** que estou logada no iSUS 
**E** o async encontra-se cheio
**Quando** tento realizar o download de algum conteúdo de Minha Saúde
**Então** uma mensagem é exibida informando que não é possível realizar o download

- [ ] Tentativa de realizar download usuária não logada
**Dado** que não estou logada no iSUS 
**E** o async encontra-se cheio
**Quando** tento realizar o download de algum conteúdo de Minha Saúde
**Então** uma mensagem é exibida informando que não é possível realizar o download

### **Links Úteis**
Home > Seção > Artigo > Baixar conteúdo > Async cheio
https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4880%3A0

**Comment by rodrigoplimafreire** [comment]
Entedi, mas o que o usuário deve saber sobre "está cheio o async"???, qual operação ele deve realizar para, por exemplo, liberar espaço??? qual é o ganho mque o usuário terá ao saber que o asyncStorage está cheio... Nem eu, leigo nesta área, sei o que significa que Async está cheio, quem dirá o usuário...

**Comment by rodrigoplimafreire** [comment]
O que a gente pode considerar como _storage_ para o usuário leigo?

**Comment by uira** [comment]
@rodrigoplimafreire É Armazenamento ou Memória do dispositivo

**Comment by daianefreira** [comment]
@Clarisse1983 você poderia ajudar a gente com um texto?

**Comment by daianefreira** [comment]
https://undraw.co/search

**Comment by wforte88** [comment]
@ItaloRod A solução do problema é liberar espaço no gerenciador de armazenamento do dispositivo? Se for isso, é possível colocarmos um link diretamente para a tela de configurações de armazenamento?

**Comment by ItaloRod** [comment]
> @ItaloRod A solução do problema é liberar espaço no gerenciador de armazenamento do dispositivo? Se for isso, é possível colocarmos um link diretamente para a tela de configurações de armazenamento?

a solução sim seria liberar o armazenamento do dispositivo, mas foge do escopo dessa tarefa que é somente de notificar ao fazer download. 

Com relação a essa tela de configuração seria uma nova tela pra gerenciar o que foi armazenado offline do iSUS?

**Comment by wforte88** [comment]
**Home > Seção > Artigo > Baixar conteúdo > Async cheio**
https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4880%3A0

![Async_Full](https://user-images.githubusercontent.com/21333612/100354348-cb915580-2fce-11eb-8caa-fe5f37ecd725.png)

**Comment by jessica-salmazzo** [comment]
Testes realizados no Mi A3 (Android). Não conseguimos simular a mensagem no iOS.
