### ISSUE TITLE
Melhorar a experiência de seleção de categorias e setores profissionais

### ISSUE THREAD

**Issue by ItaloRod** [EscolaDeSaudePublica/isus-app#380]
## Objetivo
**Como** usuária realizando cadastro ou atualizando informações profissionais no aplicativo iSUS
**Quero** selecionar categorias e serviços de forma prática
**Para** efetuar meu cadastro ou atualização de perfil

## Contexto

Hoje a escolha de categorias profissionais e setores é realizada através de **acordions**, onde estão expostas todas as categorias e setores disponíveis. Esse cenário tem falhas de usabilidade porque a navegação por **acordions** com muitas informações prejudica a experiência da usuária. O _component_  [Chip](https://callstack.github.io/react-native-paper/chip.html) é uma sugestão a ser utilizada para os profissionais escolherem suas categorias profissionais. Isso proporcionará melhores experiências personalizadas no futuro.

![image.png](https://images.zenhubusercontent.com/6107e6f995403630490497bf/a9c827cd-fd8c-430f-a665-ebc4620f2b91)

Contexto 2022:
- Foi necessário realizar uma reformulação geral no fluxo de cadastro porque existem bugs causados pela falta de padronização e pela estratégia de implementação não concisa. Dessa forma, uma padronização nos componentes utilizados para construção do formulário está sendo realizada. 
- A equipe do iSUS forneceu propostas para os componentes de seleção com base no alinhamento com o Rani que propôs uma padronização de acordo com o número de itens a serem exibidos. 
- São dois componentes de seleção: accordion para exibir as opções com até 5 itens e componente de seleção que usa modal para exibir opções com mais de 5 itens. Utilizou-se a estilização da biblioteca de componentes já implementada (Material Design).

- Dessa forma, necessitamos do desenho desses componentes, já que os implementamos em caráter emergencial contando apenas com a orientação do tipo de componente (alinhado com o Rani) e não o desenho dos mesmos. Foi acordado que o desenho seria feito posteriormente.

- Esse componente se propõe a melhorar a experiência na escolha das categorias e dos setores profissionais. 

- Vídeo do que foi atualizado até o momento:

https://user-images.githubusercontent.com/20958122/164730475-b4bedd79-2add-4a54-8045-5efe5a8caa8d.mp4

## UX
- [ ] Facelifting do cadastro, na seção de seleção de categorias e serviços, para entender se a experiência do chip pode ser implantada
- [ ] Melhorar a experiência da usuária na seleção/atribuição dessas categorias

## Observações
Escopo UX não atualizado. Favor revisar contexto de 2022 e atualizar lista de tarefas do Design.
https://callstack.github.io/react-native-paper/chip.html

Existe uma atividade #304 que já se refere à melhorar a experiência da usuária com o cadastro no app

**Comment by wforte88** [comment]
Tarefa será tratada no facelifting do iSUS.

**Comment by RaniGub** [comment]
Card vinculado a tarefa 'Fluxo de Cadastro do Trabalhador da Saúde #78', no designlab.

**Comment by ericsonmoreira** [comment]
@RaniGub tu pode nos dar algum contexto de como está essa atividade?

**Comment by RaniGub** [comment]
@ericsonmoreira o que acontece é basicamente o mesmo cenário do Mapa no ambiente Mobile. A seleção de categorias profissionais no momento do cadastro possui muitas informações que, no click da pessoa usuária, o accordion com as categorias transpassa a quebra de visualização da página. Temos duas opções:
1- Pelo histórico, a tarefa tinha sido entendida por mim como concluída, pois esse problema será automaticamente resolvido com o Facelifting do iSUS.
OU
2- Analisar com o PO se faz sentido atender essa demanda com a versão atual do iSUS e priorizar o desenho da solução.

De qualquer forma vou colocar novamente a TAG do Fluxo de Cadastro pq elas se relacionam. Fico à disposição. Desculpe a demora na resposta, os últimos dias estão corridos.

**Comment by Laysacunha** [comment]
Tarefa está sendo atendida na Revisão do Fluxo de cadastro - #696. Foi alinhado brevemente com o @RaniGub sobre quais componentes utilizar e como seria a experiência. Agora vamos precisar que o DesignLab desenvolva o design da tela do componente de seleção (que é um modal). História será atualizada e tarefa direcionada para DesignLab.

**Comment by ericsonmoreira** [comment]
Tarefa já implementada na issue #696 como comentada acima pela @Laysacunha. Fechando essa issue.
