### ISSUE TITLE
[BUGS-QA] Adicionar novo card em força tarefa anticorona chamado "Denúncias"

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/isus-app#385]
## **Objetivo**
**Como** Usuária do aplicativo iSUS
**Quero** acessar informações sobre como denunciar irregularidades sobre COVID 19(aglomerações de pessoas)
**Para** Ajudar a combater irregularidades relativas ao distanciamento social

## **Contexto**
Atualmente o iSUS não oferece informações sobre como realizar denúncias referente a irregularidades sobre COVID19, nesse contexto necessário realizar a implementação de um novo CARD dentro da HOME do iSUS, para que o usuário possa conhecer de forma fácil e rápido os canais oficiais de recebimento de denúncias.

## **Escopo**

- [x] Adicionar um novo CARD na seção Anti Corona na home do iSUS chamado "Denúncias"
<img width="533" alt="Captura de Tela 2020-11-04 às 13 30 33" src="https://user-images.githubusercontent.com/969604/98138625-102f4280-1ea2-11eb-832b-50a784510d1c.png">
<img width="207" alt="Captura de Tela 2020-11-04 às 13 30 42" src="https://user-images.githubusercontent.com/969604/98138635-11f90600-1ea2-11eb-991b-5fc7eee3d9ae.png">

- [x] Criar Tela com dados sobre denúncias 

<img width="192" alt="Captura de Tela 2020-11-04 às 13 30 53" src="https://user-images.githubusercontent.com/969604/98138981-6d2af880-1ea2-11eb-9706-33a125cdf498.png">

- [x] Implementar clique no botão **Mandar email** para redirecionar para cliente de email
com destinatário como ouvidoriasesa@saude.ce.gov.br e assunto Quero fazer uma denúncia
- [x] Implementar clique no botão **Ligar para ouvidoria do SUS** abrindo o cliente de chamada do aparelho com o número 136
- [x] Implementar clique no texto **ouvidoriasesa@saude.ce.gov.br** redirecionando para cliente de email
com destinatário como ouvidoriasesa@saude.ce.gov.br e assunto Quero fazer uma denúncia
- [x] Implementar clique no texto **136** abrindo o cliente de chamada do aparelho com o número 136 discado
- [x] Implementar clique no texto **190** abrindo o cliente de chamada do aparelho com o número 190 discado
- [x] Implementar clique no texto **08002751520** abrindo o cliente de chamada do aparelho com o número 08002751520 discado
- [x] Implementar clique em **Termos de uso** redirecionando para termos de uso
- [x] Implementar botão voltar, voltando para Home

## **Links utéis**
[Figma (Layout)](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4325%3A0)

## **Critérios de Aceite**

- [x] Acesso ao CARD "Denúncias"
**Dado que** Acesso o aplicativo iSUS e  na seção "Força-tarefa Anticorona"
**Quando** Clico no ícone (card) "Denúncias" 
**Então** Sou redirecionado para a tela de denúncias

- [x] Ao clicar no botão **Mandar email** abre o cliente de email do aparelho
**Dado que** Acesso o card de denúncia
**Quando** Clico no botão **Mandar email**
**Então** Sou redirecionando para cliente de email com destinatário como ouvidoriasesa@saude.ce.gov.br e assunto Quero fazer uma denúncia

- [x] Ao clicar no texto ouvidoriasesa@saude.ce.gov.br abre o cliente de email do aparelho
**Dado que** Acesso o card de denúncia
**Quando** Clico no email ouvidoriasesa@saude.ce.gov.br
**Então** Sou redirecionando para cliente de email com destinatário como ouvidoriasesa@saude.ce.gov.br e assunto Quero fazer uma denúncia

- [x] Ao clicar no botão  **Ligar para Ouvidoria do SUS** telefone abre o cliente de chamada do aparelho
**Dado que** Acesso o card de denúncia
**Quando** Clico no botão **Ligar para Ouvidoria do SUS**
**Então** Sou redirecionado para cliente de chamada do aparelho com o número 136

- [x] Ao clicar no texto 136 abre o cliente de chamada do aparelho
**Dado que** Acesso o card de denúncia
**Quando** Clico no texto **136**
**Então** Sou redirecionado para cliente de chamada do aparelho com o número 136

- [x] Ao clicar no texto 190 abre o cliente de chamada do aparelho
**Dado que** Acesso o card de denúncia
**Quando** Clico no texto **190**
**Então** Sou redirecionado para cliente de chamada do aparelho com o número 190

- [x] Ao clicar no texto 08002751520 abre o cliente de chamada do aparelho
**Dado que** Acesso o card de denúncia
**Quando** Clico no texto **08002751520**
**Então** Sou redirecionado para cliente de chamada do aparelho com o número 08002751520

- [x] Ao clicar em termos de uso devo ser redirecionada para a tela de termos de uso
**Dado que** Acesso o card de denúncia
**Quando** Clico no termos de uso
**Então** Sou redirecionado para a tela de termos de uso

- [x] Ao clicar em voltar devo ser redirecionada para Home
**Dado que** Acesso o card de denúncia
**Quando** Clico no botão voltar
**Então** Sou redirecionado para a Home

## BUGS QA

- Comportamento esperado: Ao clicar no botão de "Ligar para ouvidoria do SUS", então devo entrar no cliente de Telefone com o número 136
- Comportamento obtido: Ao clicar no botão de "Ligar para ouvidoria do SUS", sou redirecionado para o cliente de email com o destinatário para ouvidoriasesa@saude.ce.gov.br

- Comportamento esperado: Ao entrar na tela de Denúncias no iOS, a barra de status deve ficar visível para mim.
- Comportamento obtido: Ao entrar na tela de Denúncias no iOS, a barra de Status some.

![image](https://user-images.githubusercontent.com/20058085/100909813-ea4e8b00-34ab-11eb-93a4-7d4ab604f18c.png)

- Comportamento esperado: Ao entrar na tela de Denúncias no iOS, o fundo da tela deve estar branco.
- Comportamento obtido: Ao entrar na tela de Denúncias no iOS, uma barra cinza aparece na parte debaixo da tela.

**Comment by victorMagalhaesPacheco** [comment]
@Clarisse1983 necessário especificação do texto (Telefone e e-mail).

**Comment by rodrigoplimafreire** [comment]
Sugestão de texto para a sessão
**Mande um e-mail**
Você irá enviar um e-mail para a Secretaria. É uma forma silenciosa e segura de denunciar.

**Fale por ligação**
Só prossiga se estiver em segurança para falar ao telefone.

**Comment by rodrigoplimafreire** [comment]
Fiz uma proposta, precisa validar os textos.
![image](https://user-images.githubusercontent.com/46686642/97214309-b3e16a00-17a1-11eb-8d9a-b6e0a2d43087.png)

**Comment by rodrigoplimafreire** [comment]
![image](https://user-images.githubusercontent.com/46686642/97214371-c8256700-17a1-11eb-918b-032a5a461d45.png)

**Comment by victorMagalhaesPacheco** [comment]
@rodrigoplimafreire o texto implementado pela @Clarisse1983.

Texto para o card 'Denúncias':

O coronavírus continua circulando em nosso estado, portanto as medidas de prevenção e proteção seguem obrigatórias para todas as pessoas. 

Uso de máscara, distanciamento social, não aglomeração permanecem como atitudes que devem ser seguidas. 

Denúncias de não cumprimento dessas regras podem ser encaminhadas para a Ouvidoria do SUS:
Telefone: 08002751520 ou 136
Email: ouvidoriasesa@saude.ce.gov.br  

Para conter eventos com aglomeração de pessoas deve-se acionar a Polícia através do número 190.

**Comment by rodrigoplimafreire** [comment]
Feito!
![image](https://user-images.githubusercontent.com/46686642/97342226-c2dd2080-1864-11eb-8e96-a762f0b5e257.png)

**Comment by uira** [comment]
@rodrigoplimafreire

**Comment by daianefreira** [comment]
https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4325%3A0

**Comment by aninhasantos** [comment]
teste acesso!

**Comment by jessica-salmazzo** [comment]
Conforme conversa, algumas modificações realizadas: 
- Assunto do email modificado DE Denúncia PARA Quero fazer uma denúncia

**Comment by ItaloRod** [comment]
removido a parte de sem conexão com internet dos critérios de aceite, visto que independe de conexão com a internet para poder realizar uma denúncia.

**Comment by ItaloRod** [comment]
Testes realizados em um Moto G7 e um iPhone 11

**Comment by jessica-salmazzo** [comment]
Testes realizados no Mi A3 (Android). 
Falta realizar os testes novamente para iOS.

**Comment by marciovcampos** [comment]
Testes realizados em um iphone 11 (iOS).
