### ISSUE TITLE
[Feedback] - problema ao baixar PDF de notificação no iOS

### ISSUE THREAD

**Issue by ItaloRod** [EscolaDeSaudePublica/isus-app#386]
## **Objetivo**
**Como** usuária do aplicativo iSUS no iPhone
**Quero** baixar um arquivo PDF 
**Para** realizar a leitura no meu aparelho

(*) **Bug específico para PLATAFORMA IOS**

### **Passo para simulação**
1. Enviar uma notificação para **um usuário** com iphone, utilizando a plataforma One Signal com o link do decreto: https://coronavirus.ceara.gov.br/project/decreto-prorroga-medidas-de-isolamento-social-no-ceara-ate-01-11/
2. Clicar no link da notificação para redirecionamento para uma webview. 
3. A página será aberta, o PDF será apresentado, porém ao clicar no comando "Baixe aqui o PDF", ocorrerá uma mensagem de erro impossibilitando o download do arquivo. 

### **Resultado esperado**
Conseguir realizar o download do pdf ao clicar no botão **"Baixe aqui o PDF"** existente dentro da página https://coronavirus.ceara.gov.br/project/decreto-prorroga-medidas-de-isolamento-social-no-ceara-ate-01-11/

### **Resultado Atual**
Acesso ao webview com conteúdo, porém ao clicar no botão **"Baixe aqui o PDF"** existente dentro da página https://coronavirus.ceara.gov.br/project/decreto-prorroga-medidas-de-isolamento-social-no-ceara-ate-01-11/ o download não é realizado.

### **Relato Fale conosco**
Mensagem de usuário no Fale Conosco: 'Pela notificação fui encaminhada ao arquivo do último decreto estadual publicado. Algum bug aconteceu e não baixou o pdf do decreto. E agora não encontro o local em que ele está no aplicativo!'

Link do acesso: https://coronavirus.ceara.gov.br/project/decreto-prorroga-medidas-de-isolamento-social-no-ceara-ate-01-11/

Plataforma: iOS

**Comment by ItaloRod** [comment]
verificados testes e quando clica no site,  não acontece nada. Nem sequer baixa. No android funciona normalmente

**Comment by victorMagalhaesPacheco** [comment]
> verificados testes e quando clica no site, não acontece nada. Nem sequer baixa. No android funciona normalmente

Isso, quando acessa a página não faz o download, mas a partir do momento que clica no botão "BAIXE AQUI O PDF" o mesmo vai baixar. @ItaloRod seria interessante fazermos um teste no IOS.

**Comment by ItaloRod** [comment]
> > verificados testes e quando clica no site, não acontece nada. Nem sequer baixa. No android funciona normalmente
> 
> Isso, quando acessa a página não faz o download, mas a partir do momento que clica no botão "BAIXE AQUI O PDF" o mesmo vai baixar. @ItaloRod seria interessante fazermos um teste no IOS.

fiz os testes no iOS e realmente não abriu nada. só abre se estiver no navegador. Na webview em que se abre a notificação,  o PDF não baixa

**Comment by ItaloRod** [comment]
Vamos criar uma abordagem de download direto a partir da Webview do próprio aplicativo:
* Buscar ajuda na comunidade (Github + Stackoverflow) para fazer o donwload de pdf a partir da WebView
* Buscar plugin do Wordpress que realize direto do pdf ao clicar em "baixar agora"

Observação: Para essa abordagem, as notificações precisa ser enviadas com um DeepLink. 
`isusapp://coronavirus.ceara.gov.br/project/decreto-prorroga-medidas-de-isolamento-social-no-ceara-ate-01-11/`

**Comment by ItaloRod** [comment]
Devido a questões relacionadas a fazer o download direto  através do próprio safari (Sem que abra diretamente o visualizador para realizar o download). A atividade será feita para abrir a notificação através do aplicativo.
