### ISSUE TITLE
Alterar banners da home do iSUS

### ISSUE THREAD

**Issue by ItaloRod** [EscolaDeSaudePublica/isus-app#388]
# Contexto
Precisamos retirar o banner do SUS no Ceará 30 anos (1º) e substitui-lo pelo banner Covid-19 Heroes Study visto que o SUS no Ceará 30 anos já está está ultrapassado. Também colocar o banner do iD Saúde.

# Objetivo

- [x] Retirar o banner do SUS no Ceará 30 anos
- [x] Colocar o Banner Covid-19 Heroes Study
- [x] colocar o banner do iD Saúde.

# Critérios de aceitação

- [x] **Retirar o banner do SUS no Ceará 30 anos**
Dado que entro no aplicativo, 
quando entro na home, 
então o Banner do SUS no Ceará 30 anos não deve aparecer.
- [x] **Adicionar o banner do Covid-19 Heroes Study**
Dado que entro no aplicativo, 
quando entro na home, 
então o Banner do Covid-19 Heroes Study deve aparecer.
- [x] **Adicionar o banner do ID Saúde**
Dado que entro no aplicativo, 
quando entro na home, 
então o Banner do ID Saúde deve aparecer.
- [x] **Clicar no banner deslogado**
Dado que estou no aplicativo deslogado, 
quando clico no banner do iD Saúde, 
então devo ser redirecionado para a tela de apresentação do iD Saúde.
- [x] **Clicar no banner logado**
Dado que estou no aplicativo logado, 
quando clico no banner do iD Saúde, 
então devo ser redirecionado para a tela de perfil.

**Comment by KelmaSouto** [comment]
![Alterar banners da home do iSUS #388 - Banner do Covid-19 Heroes Study visualizado com sucesso - Kelma Souto](https://user-images.githubusercontent.com/65924048/97601770-4b84c980-19e9-11eb-80f8-443b5ff9514a.jpg)

**Comment by KelmaSouto** [comment]
![Alterar banners da home do iSUS #388 - Banner do ID Saúde visualizado com sucesso - Kelma Souto](https://user-images.githubusercontent.com/65924048/97601782-4fb0e700-19e9-11eb-89a1-2209c99384c7.jpg)

**Comment by KelmaSouto** [comment]
![Alterar banners da home do iSUS #388 - Quando clico no Banner do ID Saúde (deslogado) sou redirecionado para a tela de apresentação do iD Saúde com sucesso - Kelma Souto](https://user-images.githubusercontent.com/65924048/97602681-5e4bce00-19ea-11eb-84c5-aac0e1339ecc.jpg)

**Comment by KelmaSouto** [comment]
![Alterar banners da home do iSUS #388 - Quando clico no Banner do ID Saúde (logada) sou redirecionada para a tela de perfil com sucesso - Kelma Souto](https://user-images.githubusercontent.com/65924048/97602935-ae2a9500-19ea-11eb-93cc-17a0782cfb61.jpg)

**Comment by KelmaSouto** [comment]
**Comportamento atual:**

Dado que entro no aplicativo.
Quando entro na home.
Então o **Banner do SUS no Ceará 30 anos não aparece**.

Dado que entro no aplicativo.
Quando entro na home.
Então o **Banner do Covid-19 Heroes Study aparece**.

Dado que entro no aplicativo.
Quando entro na home.
Então o **Banner do ID Saúde aparece**.

Dado que estou no aplicativo **deslogada**.
Quando clico no banner do iD Saúde.
Então sou **redirecionada para a tela de apresentação do iD Saúde**.

Dado que estou no aplicativo **logada**.
Quando clico no banner do iD Saúde.
Então sou **redirecionada para a tela de perfil**.


**Comportamento esperado:**

Dado que entro no aplicativo.
Quando entro na home.
Então o **Banner do SUS no Ceará 30 anos não aparece**.

Dado que entro no aplicativo.
Quando entro na home.
Então o **Banner do Covid-19 Heroes Study aparece**.

Dado que entro no aplicativo.
Quando entro na home.
Então o **Banner do ID Saúde aparece**.

Dado que estou no aplicativo **deslogada**.
Quando clico no banner do iD Saúde.
Então sou **redirecionada para a tela de apresentação do iD Saúde**.

Dado que estou no aplicativo **logada**.
Quando clico no banner do iD Saúde.
Então sou **redirecionada para a tela de perfil**.
