### ISSUE TITLE
Implementação da calculadora covid19

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/isus-app#39]
### Calculadora de triagem para o covid19

**Contexto**
Proporcionar uma funcionalidade para as usuárias profissionais de saúde que possam indicar no app as informações do atendimento e a funcionalidade de calculadora possa retornar dicas de nível de severidade com base nas informações inputadas pela usuária, facilitando e agilizando o processo de triagem de pacientes. 

Médicos não especialistas estão fazendo esse tipo de triagem, como ortopedistas. O contexto de uso pode não oferecer sinal de internet, como algumas cidades do interior do Estado. Os diretórios serão separados pois quem controla os dados não utiliza React, apenas nativo Android. Por isso, deve-se até então, criar dois diretórios e criar as telas baseados no padrão de pages, aproveitando apenas a regra de negócio (transpilar). Atualmente, é utilizado esse protocolo:

**Atendimento**
- Sinais ou sintomas (Alto, Intermediário ou Baixo)
- Fatores de risco (Alto, Intermediário, Baixo)
- Tempo de doença
- Idade

**Estratificação de Risco e Avaliação de Internação Hospitalar**
- Avaliação clínica
- Exame físico
- Conduta

![photo_2020-05-11_17-45-09](https://user-images.githubusercontent.com/3487411/81610047-40909b00-93af-11ea-8499-627bafd02f88.jpg)

### **Objetivo**
**COMO** Profissional da saúde pública
**EU QUERO** Saber o nível de gravidade da suspeita a partir de sintomas
**PARA** Ajudar no processo de triagem do paciente

**Comment by victorMagalhaesPacheco** [comment]
![photo_2020-05-11_17-45-09](https://user-images.githubusercontent.com/3487411/81610047-40909b00-93af-11ea-8499-627bafd02f88.jpg)

**Comment by oxechicao** [comment]
Os processos foram todos implementados no protocolo do Manejo Clínico COVID-19
