### ISSUE TITLE
Realizar teste de avaliação pós curso de Cascavel via quiz

### ISSUE THREAD

**Issue by aninhasantos** [EscolaDeSaudePublica/isus-app#390]
## Objetivo

**Como** usuária cadastrada no aplicativo iSUS e inscrita no curso de Cascavel  
**Quero** realizar teste (quiz) 
**Para** avaliação do meu conhecimento após o curso

## Contexto
**Problema**
Como incentivo do uso do aplicativo iSUS e melhoria no processo de implantação de testes de avaliação de conhecimento, ficará disponível um pós testes apenas para usuárias inscritas no curso de Materno Infantil em Cascavel. 

**Premissas**
- O curso ficará disponível na seção "Meus conteúdos"
- Apenas usuárias inscritas no curso poderão visualizar o ícone do quiz e realizar o teste
- A validação se a usuária já realizou o quiz ou não será na API (na chamada do qualiquiz)
- O curso será realizado no período de 26/nov a 02/dez. Com isso, o teste deverá ficar disponível a partir de 02/dez. 
- Qual a jornada se usuária aborta o teste? O teste não deverá ser armazenado e a usuária poderá iniciá-lo novamente quantas vezes forem necessárias até que ela finalize o teste. 

## Pendências
- [ ] Data do curso foi confirmada? 
- [ ] Questões que serão aplicadas no pós testes do curso de Cascavel
- [ ] Criar um teste no Qualiquiz com as questões enviadas 
- [ ] Gerar lista de CPF das usuárias que irão realizar o curso (via o SAGU)

## UX
- [x] Ícone/imagem do pós testes na seção "Meus Conteúdos""

## Escopo

- [ ] Habilitar ícone para o pós testes apenas para usuárias que estão inscritas no curso de Cascavel. Conforme alinhamento com o time, inicialmente, esta validação será realizada pelo CPF da usuária. 
- [ ] Criar webview para chamada do endpoint do qualiquizz
- [ ] Enviar o token do usuário (passar por parametro JWT)
- [ ] Redirecionar para teste número **XX** do Qualiquiz
- [ ] Disponibilizar o ícone apenas no dia 02/dez

## Critérios de Aceitação

- [ ] Não visualizar o quiz se sou usuária cadastrada e não estou inscrita no curso de Cascavel 
**Dado que** não estou inscrita no curso de Cascavel
**Quando** estou na seção "Meus conteúdos"
**Então** não visualizo o ícone para acessar o quiz

- [ ] Visualizar o quiz se sou usuária cadastrada e estou inscrita no curso de Cascavel 
**Dado que** estou inscrita no curso de Cascavel
**Quando** estou na seção "Meus conteúdos"
**Então** visualizo o ícone para acessar o quiz

- [ ] Acessar o quiz se estou inscrita no curso de Cascavel, mas ainda não realizei o teste 
**Dado que** estou inscrita no curso de Cascavel e ainda não realizei o teste
**Quando** clico no ícone do quiz na seção "Meus conteúdos"
**Então** sou redirecionada para realizar o pós teste do curso (quiz número "XX")

- [ ] Acessar o quiz se estou inscrita no curso de Cascavel e já realizei o teste 
**Dado que** estou inscrita no curso de Cascavel e já realizei o teste
**Quando** clico no ícone do quiz na seção "Meus conteúdos"
**Então** sou redirecionada para o qualiquiz que irá informar o resultado do meu teste (o quiz não poderá ser refeito pós concluído) 

## Observações
- Link do Qualiquiz: https://escoladesaudepublica.github.io/qualiquiz/
- [Icone do quiz na seção "Meus conteúdos"](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4468%3A7796)

**Comment by wforte88** [comment]
Opções para avaliação:

![Testes_Quiz](https://user-images.githubusercontent.com/21333612/98669111-aabed400-232f-11eb-9e03-5a1ccf349248.png)

**Comment by uira** [comment]
@wforte88 Resolve. 

As pras próximas podia ficar na parte de educação. Estruturar lá uma home com destaques

**Comment by wforte88** [comment]
Solução definida:

![image](https://user-images.githubusercontent.com/21333612/98802821-9ee81600-23f2-11eb-999f-915d5202e258.png)

https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4468%3A7796

**Comment by daianefreira** [comment]
Card bloqueado uma vez que o curso foi adiado e estamos aguardando as definições necessários para seguirmos com o detalhamento.

**Comment by luisfcosta2015** [comment]
Fechando a issue porque o curso já aconteceu. Se formos procurados novamente reabrimos e editamos a demanda.
