### ISSUE TITLE
[BUGS-QA] Adicionar novas categorias e novos serviços de profissionais de saúde no cadastro de usuários

### ISSUE THREAD

**Issue by aninhasantos** [EscolaDeSaudePublica/isus-app#392]
## **Objetivo**

**Como** usuária do aplicativo do iSUS  
**Quero** realizar meu cadastro na categoria e no serviço em que atuo
**Para** que eu consiga me inscrever como profissional que sou

## **Contexto**

Trabalhadores de saúde que atuam na atenção materno infantil, no Hospital Municipal de Cascavel, realizarão sua inscrição a partir do iSUS. Para que sua experiencia fique mais personalizada precisamos adicionar as novas categorias relativas a esse universo que ainda não se encontram no cadastro do iSUS. 

## **Pendências**

- [x] Verificar com o Victor se existe um motivo para as categorias não estarem ordenadas, ver se podemos ordenar
- [x] Verificar se existe algum recurso melhor para entender que é uma lista de categorias

## **Escopo**

- [x] Relacionar as categorias que serão listadas no iSUS
- [x] Implementar as categorias na seção de cadastro no campo **CATEGORIA PROFISSIONAL**
- [x] Implementar os serviços no campo **SERVIÇOS EM QUE ATUA** 
[Lista de categorias e serviços](https://docs.google.com/spreadsheets/d/1l6BzLCVRo7nChkxTMg2kv4eGjdRvK216C2sJNKXJ1zA/edit#gid=0)
- [x] Ordenar as categorias em ordem alfabética
- [x] Ordenar os serviços em ordem alfabética
- [x] Implementar tela com modal com mensagem de falha de conexão com internet na transição da tela de informações pessoais para informações profissionais conforme imagem abaixo e [figma](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=3858%3A0)

![image](https://user-images.githubusercontent.com/74663400/100137390-26aa3780-2e6b-11eb-95fd-976164281d7c.png)

_Obs.: A imagem acima refere-se ao protótipo da atividade de exclusão de conta (imagem de fundo), porém, para essa atividade das categorias, deve ser utilizado somente o modal da imagem._ 

## **Critérios de Aceitação**

- [x] 1. Selecionar minha categoria profissional
**Dado que** quero me cadastrar no iSUS
**Quando** informar minha categoria profissional 
**Então** serão exibidos as novas categorias ordenadas pelos nomes das mesmas 

- [x] 2. Selecionar meu serviço
**Dado que** informei minha categoria profissional
**Quando** informar o serviço no qual atuo 
**Então** serão exibidos os novos serviços ordenados pelos seus nomes 

- [x] 3. Consultar informações profissionais
**Dado que** finalizei o cadastro no iSUS
**Quando** visualizo meu perfil 
**Então** serão exibidos minha categoria e meu setor atualizados

- [x] 4. Selecionar uma nova categoria profissional
**Dado que** quero me cadastrar no iSUS 
**E** minha categoria profissional é Técnico em Radiologia
**Quando** informar minha categoria profissional 
**Então** será exibida essa nova categoria sendo possível meu cadastro

- [x] 5. Selecionar uma nova categoria profissional
**Dado** o cenário de teste 4, no qual informei minha categoria
**Quando** informar meu serviço que é o Obstetrícia/Neonatologia/Banco de Leite Humano
**Então** será exibido esse novo serviço sendo possível finalizar meu cadastro

- [x] 6. Simular cenário sem conexão com internet
**Dado que** quero me cadastrar no iSUS, mas estou sem conexão com internet
**Quando** eu tentar acessar a tela de informações profissionais 
**Então** um modal com mensagem de falha de conexão deve ser exibida

- [x] 7. Simular cenário sem conexão com internet ao clicar no botão OK 
**Dado que** estou sem internet com a tela com a mensagem exibida em modal informando que não há conexão
**Quando** eu clicar no botão OK da mensagem 
**Então** a mensagem deve ser removida da visão

- [x] 8. Simular cenário sem conexão com internet ao clicar fora do modal da mensagem 
**Dado que** estou sem internet com a tela com a mensagem exibida em modal informando que não há conexão
**Quando** eu clicar fora do espaço da mensagem 
**Então** a mensagem deve ser removida da visão

# BUGS QA

- Bugs no Critério de Aceitação 6:
- **Comportamento esperado**: Ao clicar no Botão de próximo da tela de cadastro profissional sem conexão com a internet, deveria aparecer um modal informando que não a conexão.
- **Comportamentos Obtidos**: Ao clicar no Botão de próximo da Tela de cadastro profissional sem conexão com a internet (Desligando o 4G), o app retorna a tela anterior e exibe o modal, mas somente ao tentar fazer o cadastro novamente.
![image](https://user-images.githubusercontent.com/20058085/100785264-28d24000-33ef-11eb-8c5d-086a1764d6b1.png)
- Ao Chegar na tela de Cadastro profissionais, desligando o 4G, e retornando a tela de informações pessoais, (Botão de voltar), ao tentar avançar novamente foi que o modal apareceu.
- Ao clicar no Botão de próximo da Tela de cadastro profissional sem conexão com a internet (Desligando o 4G), ele avançou para a tela de senha normalmente sem mostrar o modal.
![image](https://user-images.githubusercontent.com/20058085/100785305-3687c580-33ef-11eb-9afb-a30e9e4fed52.png)
- Ao entrar na tela de cadastro profissionais sem conexão com a internet (Desligando o 4G), o App não mostra o modal de sem conexão com a internet, mostrando avisos de que o email fora do padrão.
![image](https://user-images.githubusercontent.com/20058085/100785325-3daed380-33ef-11eb-8489-0364c8eedd45.png)

**Comment by ItaloRod** [comment]
Todos os critérios de aceitação 1,2,3,4,5,7 e 8 funcionaram conforme o esperado no Moto G7 e no iPhone 11

**Comment by ItaloRod** [comment]
Testes funcionando conforme o esperado no Moto G7 e no iPhone 11
