### ISSUE TITLE
[Bugs-QA] Criar opção para linha de cuidado Materno Infantil

### ISSUE THREAD

**Issue by aninhasantos** [EscolaDeSaudePublica/isus-app#393]
## **Objetivo**

**Como** usuária do aplicativo iSUS
**Quero** ter acesso a conteúdos sobre linha de cuidado Materno Infantil
**Para** adquirir conhecimentos 

## **Contexto**

Disponibilizar conteúdos sobre a linha de cuidado Materno Infantil iniciando pela Guia do Nascer no Ceará. 

Além dessa seção de Nascer no Ceará que trataremos nessa atividade, a linha contará com mais duas seções que serão tratadas no futuro: 
- Gestação e Covid19
- Saúde na Infância

## **Pendências**

- [x] Definir se o termo utilizado será "Nascer no Ceara" ou "Materno Infantil" >> Será "Materno Infantil" mesmo. 
- [x] Arquivos PDFs com conteúdos sobre a linha de cuidado Materno Infantil
- [x] Texto introdutório sobre a linha de cuidado Materno Infantil
- [x] Solicitar os capítulos separados do PDF (como cartilha) >> Ascom vai entregar até terça, 17/11
- [x] Redução dos textos da subseção Nascer no Ceará

## **UX**
- [x] Mudar a label do icone para "Materno Infantil"

- [x] Imagem do Materno Infantil

- [x] Criar layout da tela que será exibida logo que clicar no ícone do "Materno Infantil" (sugestão: layout semelhante a tela SUS no Ceara):
       1.  logo do Materno Infantil
       2. o texto explicativo da linha de cuidado materno infantil
       3. uma seção denominada Nascer no Ceara seguida dos arquivos PDFs

- [x] Na seção do Nascer no Ceara incluir 5 arquivos PDFs conforme lista abaixo. Estes 5 tópicos serão retirados do arquivo "Condutas assistenciais"
        (link para o fluxograma/dados essenciais)
       [Estratificação de risco](https://coronavirus.ceara.gov.br/wp-content/uploads/2020/11/Nascer_Ceara_1.pdf)
       [Pré-natal de risco habitual ](https://coronavirus.ceara.gov.br/wp-content/uploads/2020/11/Nascer_Ceara_2.pdf)
       [Pré-natal de alto risco ](https://coronavirus.ceara.gov.br/wp-content/uploads/2020/11/Nascer_Ceara_3.pdf)
       [Síndromes hipertensivas em gestação ](https://coronavirus.ceara.gov.br/wp-content/uploads/2020/11/Nascer_Ceara_4.pdf)
       [Hemorragia em gestação](https://coronavirus.ceara.gov.br/wp-content/uploads/2020/11/Nascer_Ceara_5.pdf) 

- [x] Elaborar uma experiência do usuário melhor considerando a quantidade e tamanho dos arquivos PDFs

## **Escopo**

- [x] Criar um ícone para uma nova opção da linha de cuidado do Materno Infantil 
- [x] Assim que clicar no ícone, será exibida uma tela com o texto introdutório sobre esta linha de cuidado. 
- [x] Ao final da tela, serão disponibilizados os links com os nomes dos arquivos para baixar os PDFs. 
- [x] Implementar o accordion dentro de Linha Materno-Infantil para a seção Nascer no Ceará que ficará localizado logo após o fim do texto introdutório da linha Materno Infantil
- [x] Implementar o ícone de Materno Infantil na linha de cuidados e protocolos 
- [x] Implementar banner do Nascer no Ceará que ficará na tela do conteúdo com o texto introdutório conforme [Figma](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4570%3A0)
- [x] Implementar o texto que será exibido ao clicar no ícone de Materno Infantil
- [x] Implementar o texto que será exibido ao clicar na seção Nascer no Ceará
- [x] Disponibilizar a seção com os PDFs
- [x] Implementar mensagem de falha de conexão 

![image](https://user-images.githubusercontent.com/74663400/99999716-525feb80-2d9f-11eb-924c-fa649bf6e68c.png) 

## **Critérios de Aceitação**

- [x] Visualizar ícone da linha de cuidado "Materno Infantil"
**Dado que** acessei o iSUS e não estou logada
**Quando** vou para a seção de "Linha de Cuidados e Protocolos"
**Então** visualizarei o ícone de linha de cuidados do Materno Infantil 

- [x] Acessar conteúdo sobre linha de cuidado 
**Dado que** estou na seção de "Linha de Cuidados e Protocolos" 
**E** estou logada no app iSUS
**Quando** clico no ícone de Materno Infantil 
**Então** visualizarei o conteúdo da linha de cuidado materno infantil 

- [x] Visualizar ícone da linha de cuidado "Materno Infantil"
**Dado que** acessei o iSUS e estou logada
**Quando** vou para a seção de "Linha de Cuidados e Protocolos"
**Então** visualizarei o ícone de linha de cuidados do Materno Infantil 

- [x] Acessar conteúdo sobre linha de cuidado 
**Dado que** estou na seção de "Linha de Cuidados e Protocolos" 
**E** não estou logada no app iSUS
**Quando** clico no ícone de Materno Infantil 
**Então** visualizarei o conteúdo da linha de cuidado materno infantil 

- [x] Cenário de falha de conexão com internet 
**Dado que** estou na seção de "Linha de Cuidados e Protocolos" 
**E** não estou logada no app iSUS e não estou com internet 
**Quando** clico no ícone de Materno Infantil 
**Então** visualizarei a mensagem de informação sobre falha de conexão

- [x] Cenário de falha de conexão com internet 
**Dado que** estou visualizando a mensagem de falha de internet
**Quando** clico no botão Voltar
**Então** sou direcionada para a Home

- [x] Acessar conteúdo das guias assistenciais
**Dado que** estou acessando o conteúdo de materno infantil 
**E** não estou logada no app iSUS
**Quando** clico na seção de Nascer no Ceará
**Então** visualizarei o conteúdo e as seções separadas das guias assistenciais

- [x] Acessar conteúdo das guias assistenciais
**Dado que** estou acessando o conteúdo de Nascer no Ceará
**E** não estou logada no app iSUS
**Quando** clico nas guias assistenciais
**Então** sou direcionada para acessar os PDFs de cada guia clicada 

- [x] Acessar conteúdo das guias assistenciais
**Dado que** estou acessando o conteúdo de materno infantil 
**E** estou logada no app iSUS
**Quando** clico na seção de Nascer no Ceará
**Então** visualizarei o conteúdo e as seções separadas das guias assistenciais

- [x] Acessar conteúdo das guias assistenciais
**Dado que** estou acessando o conteúdo de Nascer no Ceará
**E** estou logada no app iSUS
**Quando** clico nas guias assistenciais
**Então** sou direcionada para acessar os PDFs de cada guia clicada 

## **Observações**
[Seção "Linhas de Cuidados" e ícone de "Nascer no Ceara"
](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4296%3A10283)

[Tela "Materno-Infantil" e accordion "Nascer no Ceará"](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4570%3A13)

[Texto introdutório e links](https://docs.google.com/document/d/1-ZHm8MEwXAxSAg9SlbIIdV4fHG8cH3KTkutlCC6GrL8/edit)

[Banner do Nascer no Ceara para a tela com texto introdutório](https://drive.google.com/drive/folders/1hn1p-ffOPHgRQHhsWBTxkf3sPAVyPbPf)

Cor utilizada: #9c27b0

**Links das Guias Assistenciais:**

Home > Linhas de Cuidado e Protocolos > Materno-Infantil > Nascer no Ceará > Guias Assistenciais

Estratificação de risco
https://coronavirus.ceara.gov.br/wp-content/uploads/2020/11/Nascer_Ceara_1.pdf

Pré-natal de risco habitual
https://coronavirus.ceara.gov.br/wp-content/uploads/2020/11/Nascer_Ceara_2.pdf

Pré-natal de alto risco
https://coronavirus.ceara.gov.br/wp-content/uploads/2020/11/Nascer_Ceara_3.pdf

Síndromes hipertensivas em gestação
https://coronavirus.ceara.gov.br/wp-content/uploads/2020/11/Nascer_Ceara_4.pdf

Hemorragia em gestação
https://coronavirus.ceara.gov.br/wp-content/uploads/2020/11/Nascer_Ceara_5.pdf

## Bugs QA

- Comportamento esperado: Ao abrir a seção de Linha Materno-infantil no Android, o banner da linha deve estar centralizado adequadamente.
- comportamento obtido: Ao abrir a seção de Linha Materno-infantil no Android, o banner aparece alinhado a direita
![image](https://user-images.githubusercontent.com/20058085/100912374-21726b80-34af-11eb-9bdd-3df594079d89.png)

**Comment by Clarisse1983** [comment]
Vamos fazer uma primeira versão dessa seção indo até Nascer no Ceará porque Liduina quer revisar os materiais que serão alocados na subseção Gestação e Covid-19.

**Comment by wforte88** [comment]
**Home > Linhas de Cuidado e Protocolos > Materno-Infantil**
[Protótipo v1](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4570%3A13)

**Home > Linhas de Cuidado e Protocolos > Materno-Infantil > Nascer no Ceará > Guias Assistenciais**

Estratificação de risco
https://coronavirus.ceara.gov.br/wp-content/uploads/2020/11/Nascer_Ceara_1.pdf

Pré-natal de risco habitual
https://coronavirus.ceara.gov.br/wp-content/uploads/2020/11/Nascer_Ceara_2.pdf

Pré-natal de alto risco
https://coronavirus.ceara.gov.br/wp-content/uploads/2020/11/Nascer_Ceara_3.pdf

Síndromes hipertensivas em gestação
https://coronavirus.ceara.gov.br/wp-content/uploads/2020/11/Nascer_Ceara_4.pdf

Hemorragia em gestação
https://coronavirus.ceara.gov.br/wp-content/uploads/2020/11/Nascer_Ceara_5.pdf

**Comment by ItaloRod** [comment]
Testes foram realizados no Moto G7 e iPhone 11

**Comment by ItaloRod** [comment]
Testes realizados conforme esperado
