### ISSUE TITLE
Adicionar banner do Protocolo de Insuficiência Aguda do Miocárdio na home

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/isus-app#394]
## **Objetivo**

**Como** usuária do app iSUS 
**Quero** clicar no banner do Protocolo de Insuficiência Aguda do Miocárdio 
**Para** acessar o pdf do referido Protocolo

## **Contexto**

O Protocolo de Insuficiência Aguda do Miocárdio está publicado no hotsite coronavirus e precisa ser publicizado no iSUS para ganhar maior visibilidade e ser consumido por seus usuários interessados no tema. Dr. Marcelo pediu destaque para esse material no app, e como ainda estamos em processo de implantação das Linhas de Cuidado, onde esse material deverá compor uma das linhas, fizemos a ação de já publicá-lo e destacá-lo via banner.

## **Escopo**

- [x] Adicionar na home, na primeira posição, o banner disponível na [planilha da arquitetura de informação](https://docs.google.com/spreadsheets/d/1CqqiVEWH-YchqFSTlx3NN5zG7RBpvPRUkGo_CCyLThw/edit#gid=2004870043)
- [x] Direcionar o usuário que clica no banner para [a página do protocolo](https://coronavirus.ceara.gov.br/project/protocolo-da-sesa-orienta-atendimentos-a-pacientes-com-sindrome-coronariana-aguda/) postado no hotsite

## **Critérios de Aceitação**

- [x] Visualizar o banner quando entrar no iSUS  
**Dado que** entro no iSUS 
**Quando** estou na home
**Então** visualizo o banner do Protocolo na primeira posição do Carrossel

- [x] Acessar Protocolo de IAM a partir de clique no banner  
**Dado que** clico no banner do Protocolo de IAM 
**Quando** estou visualizando o carrossel da home no iSUS
**Então** sou direcionada para a página onde o Protocolo está publicado

## **Observações**

Conforme conversado com Paulo Ítalo, sugerimos que a publicação do banner seja realizada por uma atualização de versão, uma vez que observamos que o code push pode estar atualizando para alguns usuários e outros não. Na versão da Clarisse Castro, os banners não estão sendo atualizados, embora ela utilize a versão mais atual do app.

**Comment by nicoledbianchin** [comment]
Versão: 3.11.2
OS: dispositivo Android

Comportamento de acordo com o esperado.
