### ISSUE TITLE
Criar card de protocolos dentro da seção de Linha de Cuidado e Protocolos

### ISSUE THREAD

**Issue by jessica-salmazzo** [EscolaDeSaudePublica/isus-app#398]
## **Objetivo**
**Como** usuária do aplicativo iSUS
**Quero** visualizar um card específico para Protocolos publicados no site coronavirus
**Para** facilitar o acesso às informações que se caracterizam como Protocolos

## **Contexto**
Protocolos são conteúdos com instruções sobre como agir em situações muito específicas de adoecimento e e necessidade de atenção. Por essa razão, são muito procurados por profissionais de saúde como informações confiáveis para a tomada de decisão no processo de atendimento às pessoas no SUS. Assim, é importante dar visibilidade à exposição de Protocolos no iSUS, e por isso estamos criando um card/subseção específica para isso, alocada numa seção maior chamada Linhas de Cuidado e Protocolos.

## **Escopo**
- [x] Criar um novo card na home do iSUS para Protocolos, dentro da seção Linhas de Cuidado e Protocolos conforme [Figma](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4296%3A10283). Obs: A imagem abaixo já possui o ícone do materno-infantil, que será tratado em outra atividade, portanto o card de protocolos pode aparecer logo depois de manejo clínico.

![image](https://user-images.githubusercontent.com/74663400/99996609-bd5af380-2d9a-11eb-9c03-b6eb551d4937.png)

- [x] Redirecionar o usuário para uma webview onde são apresentados os protocolos no site coronavirus - https://coronavirus.ceara.gov.br/isus/protocolos/
- [x] Implementar tratamento de exibir mensagem de falha com internet conforme [Figma](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=2288%3A0) 

![image](https://user-images.githubusercontent.com/74663400/99996326-53dae500-2d9a-11eb-8f5d-1fd865556dfd.png)

Obs.: Se possível, desenvolver o item acima como um componente/webview que possa ser utilizado em outros cenários e atividades. 

- [x] Retirar o banner de Protocolo de IAM assim que concluída a tarefa

## **Fora de Escopo**
- A criação da seção Linhas de Cuidado e Protocolos já foi contemplada em outra história

## **UX**
- [x] Definir a jornada do usuário ao clicar nesse card na home 
- [x] Criar um ícone para identificar os Protocolos
- [x] Definir um cenário para falta de internet (é a mesma já prevista para os banners?)
- [x] Quando o usuário clicar no ícone de Protocolos, ele deve ser direcionado para webview da página https://coronavirus.ceara.gov.br/isus/protocolos/

## **Critérios de Aceitação**
- [x] Visualizar card de Protocolos ao acessar a home
**Dado** que acessei o iSUS
**Quando** estou na home 
**Então** visualizarei o card "Protocolos" dentro da seção "Linhas de Cuidado e Protocolos"

- [x] Acessar conteúdos que são Protocolos
**Dado** que estou na seção de "Linhas de Cuidado e Protocolos"
**Quando** clico no ícone de Protocolos
**Então** visualizarei a webview com a lista de todos os protocolos publicados no site coronavirus

- [x] Falha de conexão com internet
**Dado** que estou na home
**E** sem conexão com internet
**Quando** clico no ícone de Protocolos
**Então** visualizarei a mensagem informando que estou sem internet

- [x] Falha de conexão com internet
**Dado** que estou visualizando a mensagem de falha de internet 
**Quando** clico no botão Voltar da mensagem de falha de internet
**Então** sou redirecionada para a Home

## **Observações**
[Seção "Linhas de Cuidado e Protocolos" e ícone de "Protocolos"
](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4296%3A10283)

[Página para webview](https://coronavirus.ceara.gov.br/isus/protocolos/) (visível apenas em dispositivos móveis)

Cor utilizada: #9c27b0

**Comment by wforte88** [comment]
**Home > Linhas de Cuidado e Protocolos > Protocolos**
Webview da página https://coronavirus.ceara.gov.br/isus/protocolos/

**Comment by ItaloRod** [comment]
Resultados conforme esperado. Testes realizados no iPhone 11 e 
Moto G7
