### ISSUE TITLE
Ter mensagem de confirmação para usuária na ação de clicar no botão Sair

### ISSUE THREAD

**Issue by jessica-salmazzo** [EscolaDeSaudePublica/isus-app#399]
## **Objetivo**

**Como** usuária logada no iSUS
**Quero** visualizar uma confirmação de saída do app
**Para** ter certeza da ação de sair do app

## **Contexto**

Como usuária do app, posso eventualmente clicar no botão de sair do meu perfil sem intenção de fazê-lo, apenas por descuido. Assim, se faz interessante visualizar uma mensagem de confirmação dessa ação, para não sair do app se esse não for meu desejo.

## **UX**

- [x] Criar modal de mensagem de confirmação de saída da usuária. Sugestão: colocar opção de confirmar e cancelar, ou sim e não.
 
## **Escopo**
- [x] Adicionar o modal de mensagem de confirmação de saída da usuária conforme [figma](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4884%3A108)
- [x] Implementar ação de confirmação da saída
- [x] Implementar ação de cancelamento da saída 

![image](https://user-images.githubusercontent.com/74663400/100462351-ea641a80-30a8-11eb-9365-bb77e7bb6948.png)

## **Critérios de Aceitação**
- [x] 1. Mensagem de confirmação exibida para a usuária 
**Dado** que estou logada no app e em Meu Perfil
**Quando** clico no botão Sair 
**Então** uma mensagem de confirmação da ação de logout é exibida

- [x] 2. Ação de confirmação da saída
**Dado** que estou visualizando a mensagem de confirmação de logout
**Quando** clico no botão Sim
**Então** sou direcionada para a Home

- [x] 3. Ação de cancelamento da saída
**Dado** que estou visualizando a mensagem de confirmação de logout
**Quando** clico no botão Não
**Então** sou direcionada para o meu perfil 

## **Links Úteis**
Menu > Meu Perfil > Preferências > Sair
https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4884%3A108

**Comment by wforte88** [comment]
**Menu > Meu Perfil > Preferências > Sair**
https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4884%3A108

![Logout](https://user-images.githubusercontent.com/21333612/100359861-e5cf3180-2fd6-11eb-95d3-39731bec0740.png)

**Comment by jessica-salmazzo** [comment]
Testes realizados em um Mi A3 (Android).
Ainda falta testar em um iOS.

**Comment by marciovcampos** [comment]
Testes realizados em uma iphone 11 (iOS).
