### ISSUE TITLE
Tela de educação permanente não está funcionando corretamente

### ISSUE THREAD

**Issue by ItaloRod** [EscolaDeSaudePublica/isus-app#4]
Ao tentar acessar a tela de educação permanente, não há o carregamento da tabs e do conteúdo.
![image](https://user-images.githubusercontent.com/20058085/80968353-34746e80-8dee-11ea-9208-faa19d7fcb00.png)

**Comment by Junior-Shyko** [comment]
Atualmente está correto. parece que pode fechar a issue. 

![Captura de tela de 2020-05-08 14-38-02](https://user-images.githubusercontent.com/7341117/81432570-8b08e200-9139-11ea-85de-81dbe9ed62e6.png)
