### ISSUE TITLE
[BUGS-QA] Adicionar banner do Guia de Assistência Farmacêutica na home e remover banner de saúde mental e pandemia

### ISSUE THREAD

**Issue by jessica-salmazzo** [EscolaDeSaudePublica/isus-app#401]
## **Objetivo**

**Como** usuária do app iSUS 
**Quero** clicar no banner de Guia de Assistência Farmacêutica 
**Para** acessar o link da publicação do guia

## **Contexto**

O Guia de Assistência Farmacêutica está publicado no hotsite coronavirus e precisa ser publicado no iSUS para ganhar maior visibilidade e ser consumido por seus usuários interessados no tema. 

## **Escopo**

- [x] Adicionar na home, na primeira posição, o banner disponível na [planilha da arquitetura de informação](https://docs.google.com/spreadsheets/d/1CqqiVEWH-YchqFSTlx3NN5zG7RBpvPRUkGo_CCyLThw/edit#gid=2004870043);
- [x] Direcionar o usuário que clica no banner para o [link](https://coronavirus.ceara.gov.br/project/secretaria-de-saude-disponibiliza-guia-da-assistencia-farmaceutica-no-estado-do-ceara/) postado no hotsite.
- [x] Remover o banner já existente chamado "SAÚDE MENTAL E PANDEMIA" disponível na [planilha da arquitetura de informação](https://docs.google.com/spreadsheets/d/1CqqiVEWH-YchqFSTlx3NN5zG7RBpvPRUkGo_CCyLThw/edit#gid=2004870043)
- [x] Implementar tratamento de mensagem de falha de conexão ao tentar acessar o link do banner sem internet disponível

![image](https://user-images.githubusercontent.com/74663400/99809694-6c8c9600-2b21-11eb-87a8-bb859e17ce88.png)

## **Links Úteis**
[Figma](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=2288%3A0)

## **Critérios de Aceitação**

- [x] 1. Visualizar o banner quando logar no iSUS  
**Dado que** efetuo o login no iSUS 
**Quando** estou na home
**Então** visualizo o banner do Guia de Assistência Farmacêutica na primeira posição do Carrossel

- [x] 2. Visualizar o banner quando entrar no iSUS sem efetuar login
**Dado que** acesso o iSUS sem efetuar login
**Quando** estou na home
**Então** visualizo o banner do Guia de Assistência Farmacêutica na primeira posição do Carrossel

- [x] 3. Acessar o guia a partir de clique no banner  
**Dado que** clico no banner do Guia de Assistência Farmacêutica
**Quando** estou visualizando o carrossel da home no iSUS
**Então** sou direcionada para a página onde o guia está publicado

- [x] 4. Acessar a home ao clicar no botão "voltar"
**Dado que** clico no banner para acessar o Guia de Assistência Farmacêutica e acesso o link do guia
**Quando** clico no voltar do app ou no voltar do celular (Android e iOS)
**Então** sou direcionada para a página Home

- [x] 5. Simular cenário de falha de conexão  
**Dado que** estou sem internet no celular
**Quando** eu clicar no banner referente ao Guia
**Então** deve aparecer uma mensagem tratada para o usuário informando sobre a falha de conexão com o botão Voltar disponível para ser clicado pelo usuário

- [x] 6. Clicar no botão Voltar em cenário de falha de conexão
**Dado que** estou visualizando a mensagem de falha de conexão dado o cenário 5
**Quando** eu clicar no botão Voltar disponível na mensagem
**Então** devo ser redirecionada para a página Home do app

- [x] 7. Remoção do banner de saúde mental e pandemia
**Dado que** estou logada no app iSUS e acesso o app
**Quando** eu visualizar a página home do app
**Então** não devo visualizar mais o banner de saúde mental e pandemia

- [x] 8. Remoção do banner de saúde mental e pandemia
**Dado que** não estou logada no app iSUS mas acesso o app 
**Quando** eu visualizar a página home do app
**Então** não devo visualizar mais o banner de saúde mental e pandemia

## **Observações**

Conforme conversado com Paulo Ítalo, sugerimos que a publicação do banner seja realizada por uma atualização de versão, uma vez que observamos que o code push pode estar atualizando para alguns usuários e outros não. Na versão da Clarisse Castro, os banners não estão sendo atualizados, embora ela utilize a versão mais atual do app.

## BUGS QA

- Comportamento esperado: Ao clicar no banner de Guia de Assistência Farmacêutica, devo ser redirecionado para onde a Guia de Assistência Farmacêutica está publicada.
- Comportamento Obtido: Ao Clicar no banner aparece uma mensagem "Sem conexão com a internet", mesmo estando conectado no 4G
![image](https://user-images.githubusercontent.com/20058085/100908319-22ed6500-34aa-11eb-9dfe-123fa4658bde.png)
- Ao clicar no banner sem conexão com a internet, logo aparece outra mensagem "erro de carregamento de página, domínio indefinido. "
![image](https://user-images.githubusercontent.com/20058085/100908255-0f41fe80-34aa-11eb-935c-79aee9efa83e.png)

- Comportamento esperado: Ao clicar no banner de covid 19 heroes study, devo ser redirecionado para o webview de acesso do Covid19 heroes study.
- Comportamento Obtido: Ao Clicar no banner aparece uma mensagem "Sem conexão com a internet", mesmo estando conectado no 4G
- Ao clicar no banner sem conexão com a internet, logo aparece outra mensagem "erro de carregamento de página, domínio indefinido. "

**Comment by ItaloRod** [comment]
Testes realizados no iPhone 11 e no Moto G7.

**Comment by ruigmoreno** [comment]
Foi feito o teste do bug em Moto G6+. Não apresentou o bug, portanto, considera-se resolvida essa issue.
