### ISSUE TITLE
[BUGS-QA] Realizar teste de avaliação sobre o SUS

### ISSUE THREAD

**Issue by jessica-salmazzo** [EscolaDeSaudePublica/isus-app#403]
## Objetivo
**Como** usuária cadastrada no aplicativo iSUS
**Quero** realizar teste (quiz) 
**Para** avaliação do meu conhecimento sobre o SUS

## Contexto
**Problema**
Como incentivo ao uso do aplicativo iSUS, melhoria no processo de implantação de testes de avaliação de conhecimento, e melhoria no processo de educação permanente do profissional de saúde, essa atividade refere-se à realização de um teste sobre o SUS, com questões gerais sobre a organização e funcionamento do Sistema. 

**Premissas**
- O card ficará disponível na seção "Serviços"
- Todas as usuárias do iSUS poderão visualizar o ícone do quiz independentes de terem cadastro ou não
- Apenas usuárias cadastradas no iSUS poderão realizar o teste
- Nesse primeiro momento, não teremos uma validação se a usuária já realizou o quiz ou não, ou seja, a usuária poderá realizar o teste quantas vezes quiser
- Nos casos em que a usuária não finalize o teste, o mesmo não deverá ser armazenado, e a usuária poderá iniciá-lo novamente quantas vezes forem necessárias até que ela finalize o teste
- Nesse primeiro momento também não teremos feedbacks para a usuária. Isso será tratado posteriormente

## Pendências
- [x] Questões que serão aplicadas [link](https://docs.google.com/document/d/1aawVNB7TCy6-i4G4ffdvS2Bk-iins0JUS4AaejRtrbs/edit)
- [x] Criar um teste no Qualiquiz com as questões disponíveis
- [x] Gerar o link e o número do teste (https://{qualiquiz_url}/isus/login/{cod_id_quiz}/{authToken_jwt})

## UX
- [x] Criar ícone/imagem do quiz na seção "Serviços", segundo link do figma [link](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/?node-id=4884%3A253)
- [x] Definir a localização do card do quiz dentro de Serviços (posição)
- [x] Mensagem para informar à usuária não cadastrada, que clica no quiz, que é necessário realizar o cadastro para fazer o teste

## Escopo
- [x] Criar o card do quiz na seção de Serviços

![image](https://user-images.githubusercontent.com/74663400/100747016-40460480-33c0-11eb-8c75-e21b2e5d9a99.png)

- [x] Implementar validação para que somente usuárias cadastradas consigam realizar o teste
- [x] Criar webview para chamada do endpoint do qualiquizz
- [x] Enviar o token do usuário (passar por parametro JWT)
- [x] Redirecionar para teste número **1** do Qualiquiz
- [x] Gerar URL do Qualiquiz

- [x] Implementar imagem de loading no meio tempo entre clicar no ícone do qualiquiz e ser direcionado para o quiz de fato

![image](https://user-images.githubusercontent.com/74663400/100747610-0cb7aa00-33c1-11eb-973e-1477a5bd2023.png)

- [x] Implementar cenário de realizar login caso a usuária não esteja autenticada ainda no momento de clicar no ícone do quiz
- [x] Implementar cenário de realizar cadastro caso a usuária não tenha cadastro ainda no momento de clicar no ícone do quiz
- [x] Implementar cenário de esqueci minha senha caso a usuária não lembre da senha 

![image](https://user-images.githubusercontent.com/74663400/100747756-383a9480-33c1-11eb-8f51-bd18048158e6.png)

![image](https://user-images.githubusercontent.com/74663400/100749074-edba1780-33c2-11eb-8d93-b31375157db4.png)

- [x] Implementar cenário de falta de internet, conforme figma [link](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=2288%3A0)

![image](https://user-images.githubusercontent.com/74663400/100274139-b10e9c00-2f3c-11eb-87cb-237cb649e719.png)

- [x] Implementar validação já existente sobre padrão de email no momento do preenchimento do dado do email pela usuária

## Critérios de Aceitação

- [x] Visualizar o quiz se sou usuária cadastrada no iSUS 
**Dado que** estou cadastrada no iSUS
**Quando** estou na seção "Serviços"
**Então** visualizo o ícone para acessar o quiz

- [x] Visualizar o quiz se não sou usuária cadastrada no iSUS 
**Dado que** não estou cadastrada no iSUS
**Quando** estou na seção "Serviços"
**Então** visualizo o ícone para acessar o quiz

- [x] Acessar o quiz se estou cadastrada no iSUS mas ainda não realizei o teste 
**Dado que** estou cadastrada no iSUS e ainda não realizei o teste do SUS
**Quando** clico no ícone do quiz na seção "Serviços"
**Então** sou redirecionada para realizar o teste sobre o SUS

- [x] Não acessar o quiz se não estou cadastrada no iSUS  
**Dado que** não estou cadastrada no iSUS 
**Quando** clico no ícone do quiz na seção "Serviços"
**Então** visualizo uma mensagem orientando para a realização do cadastro

- [x] Falha de conexão com internet
**Dado** que estou na home
**E** sem conexão com internet
**Quando** clico no ícone de Quiz em "Serviços"
**Então** visualizarei a mensagem informando que estou sem internet

- [x] Voltar home ao visualizar mensagem de falha de internet
**Dado** que estou visualizando a mensagem de falha de internet 
**Quando** clico no botão Voltar da mensagem de falha de internet
**Então** sou redirecionada para a Home

- [x] Usuária não está logada no app 
**Dado** que estou acessando o iSUS mas não estou logada
**Quando** clico no botão do quiz 
**Então** sou direcionada para realizar o login no app 

- [x] Usuária realiza login a partir do acesso ao ícone do quiz 
**Dado** que estou na tela de efetuar login a partir do quiz 
**Quando** preencho as informações e clico no botão fazer login
**Então** meus dados são validados e é realizado o login e sou direcionada para a webview com o quiz 

- [x] Usuária não possui cadastro de conta no app iSUS
**Dado** que estou na tela de efetuar login a partir do quiz 
**Quando** clico no botão cadastre-se agora
**Então** sou direcionada para realizar o cadastro da conta 

- [x] Usuária tenta realizar login com dados incorretos 
**Dado** que estou na tela de efetuar login a partir do quiz 
**Quando** preencho a informação de senha incorretamente
**Então** uma mensagem de erro é exibida informando que os dados estão incorretos 

- [x] Usuária esqueceu a senha 
**Dado** que estou na tela de efetuar login a partir do quiz 
**Quando** clico no botão de esqueci minha senha 
**Então** sou direcionada para a tela já existente com as orientações sobre como recuperar minha senha 

- [x] Usuária tenta realizar login, porém, não possui cadastro
**Dado** que estou na tela de efetuar login a partir do quiz 
**Quando** preencho a informação de email e senha
**E** a informação de email não existe no cadastro do app
**Então** uma mensagem de erro é exibida informando que o email informado não existe 

- [x] Usuária tenta realizar login preenchendo email com um formato que foge do padrão
**Dado** que estou na tela de efetuar login a partir do quiz 
**Quando** preencho a informação de email com a ausência do caractere @ 
**Então** uma mensagem de erro é exibida informando que o email deve ser no formato exemplo@exemplo.com
_Essa mensagem e validação já existe atualmente na tela de Cadastro_

## Observações
- [Icone do quiz na seção "Meus conteúdos"](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4468%3A7796), caso ajude na criação do novo modelo
- Essa atividade deve ser disponibilizada somente para usuários cadastrados na versão Beta, visto que a priori, será um teste para alguns usuários selecionados; dessa forma, não deve ficar disponível em produção para todos os usuários cadastrados no app no momento (Uma estratégia que deve ser analisada se faz sentido é disponibilizar a funcionalidade somente em ambiente beta por ora). 
- Não foi implementado o Gif animado do loading: https://user-images.githubusercontent.com/21333612/98235905-41128480-1f41-11eb-8652-fd9b53309261.gif por conta do prazo estipulado da atividade. Não seria possível implementar em formado de gif e cumprir o prazo. Dessa forma, foi implementado uma imagem de loading e em tarefa futura, alteraremos para o formato do gif. 

- Critério de aceite abaixo foi removido do escopo de validações visto que não faz sentido a validação. Se o email está incorreto, é considerado um email novo pelo sistema, sendo assim, a usuária é encaminhada para o fluxo de cadastro. 

_Usuária tenta realizar login com dados incorretos_ 
**Dado** que estou na tela de efetuar login a partir do quiz 
**Quando** preencho a informação de email incorretamente
**Então** uma mensagem de erro é exibida informando que os dados estão incorretos 

# BUGS QA
## 1 
- **Comportamento esperado**: (Tanto Android quanto iOS) Ao efetuar login, clicar no qualiquiz e, em seguida, efetuar logout do app iSUS e clicar no ícone do Qualiquiz novamente, as informações de email e senha não devem estar preenchidas automaticamente, pois pode gerar uma falha de segurança sendo possível com que outra pessoa acesse o app ou o quiz com os dados da pessoa que acabou de fazer logout. 

Passos para simular: 
1. Acessar o app iSUS não estando logado 
2. Clicar no ícone do qualiquiz
3. Ser direcionada para realizar o login 
4. Efetuar login
5. Efetuar logout do app iSUS
6 . Clicar novamente no ícone do qualiquiz para ser direcionado ao login novamente

- **Comportamento obtido**: (Tanto Android quanto iOS) Ao efetuar login, clicar no qualiquiz e, em seguida, efetuar logout do app iSUS e clicar no ícone do Qualiquiz novamente, as informações de email e senha estão vindo preenchidas automaticamente. 

Passos para simular: 
1. Acessar o app iSUS não estando logado 
2. Clicar no ícone do qualiquiz
3. Ser direcionada para realizar o login 
4. Efetuar login
5. Efetuar logout do app iSUS
6 . Clicar novamente no ícone do qualiquiz para ser direcionado ao login novamente

![image](https://user-images.githubusercontent.com/74663400/101401337-f7ef8080-38b0-11eb-8caa-8e750a059c21.png)

## 2
- **Comportamento esperado**: (Android) Ao acessar o iSUS, clicar no ícone do qualiquiz e, em seguida, clicar uma vez no botão voltar do teclado do android, o app deveria voltar para a Home; assim como é realizado caso eu clique no botão de voltar do app. 

**Passos para simular:** 
Exemplo 1
1. Acessar o app iSUS não estando logado 
2. Clicar no ícone do qualiquiz
3. Ser direcionada para realizar o login 
4. Clicar uma vez no botão voltar do Android

Exemplo 2
1. Acessar o app iSUS estando logado 
2. Clicar no ícone do qualiquiz
3. Ser direcionada para o qualiquiz
4. Clicar uma vez no botão voltar do Android

- **Comportamento obtido**: (Android) Ao acessar o iSUS, clicar no ícone do qualiquiz e, em seguida, clicar uma vez no botão voltar do teclado do android, aguardar cerca de 3 segundos, o app fica em loop e não consegue voltar para a Home.

**Comment by uira** [comment]
@jessica-salmazzo Pessoal, essa demanda aqui acho que rolou um confusão...

Uma coisa é a avaliação sobre o SUS, e OUTRA COISA, é a avaliação do curso de cascavel.

**Comment by uira** [comment]
@uira Ambos utilizam o QualiQuiz, e vejo que muitos itens da história são comuns as duas demandas, mas são coisas diferentes.

**Comment by chicaothiago** [comment]
> Adequação da identidade visual do quiz para dar à impressão de que a usuária está no mesmo ambiente (iSUS)

Este ponto não vai ser feito nesta atividade pois isso alteraria todo o projeto do qualiquiz para se encaixar no modelo do isus. Será uma demanda posteriormente feita.

**Comment by chicaothiago** [comment]
>Usuária tenta realizar login com dados incorretos
Dado que estou na tela de efetuar login a partir do quiz
Quando preencho a informação de email incorretamente
Então uma mensagem de erro é exibida informando que os dados estão incorretos

Esse ponto de validação não faz muito sentido, porque se o  e-mail está errado é um email novo e vai ser solicitado o cadastro.

**Comment by ItaloRod** [comment]
Bug 1 Testado e funcionando conforme o esperado no iPhone X e um iPhone 11

**Comment by ItaloRod** [comment]
Bug 2 Testado e funcionando conforme esperado no Zenfone 5
