### ISSUE TITLE
Elencar telas que precisam de tratamento de falha de conexão com internet

### ISSUE THREAD

**Issue by jessica-salmazzo** [EscolaDeSaudePublica/isus-app#409]
### **Objetivo**
**Como** usuária do iSUS 
**Quero** ser informada que houve uma falha de conexão de internet quando eu estiver acessando algum conteúdo
**Para** que eu tenha uma experiência melhor com o aplicativo e saiba o que está acontecendo

### **Contexto**
Atualmente, algumas etapas do app iSUS dependem de conexão com internet, desse modo, ao acontecer uma falha com a conexão com a internet, devemos informar a usuária de que houve uma falha com a conexão e que o conteúdo não será exibido, para que a usuária saiba o status atual da situação em que se encontra.

### **Pendências**
- Validar se as telas e cenários mapeados estão corretos
- Verificar se a atividade deve ser quebrada
- Continuar a escrita dos critérios de aceitação 

### **UX**
- [x] Apresentar uma tela para a usuária ao ser identificado que houve falha de conexão com a internet e ações possíveis
- [x] Analisar cenários mapeados, categorizá-los e definir indicação adequada

### **Escopo**
- Implementar tela informando a usuária que houve falha de conexão com a internet
- Implementar ação de tentar novamente com limite (3x)
- Implementar ação de voltar à página anterior ou sair da mensagem dada 

### **Telas e Cenários Mapeados**
- [x] Força-tarefa Anticorona > Boletins
- [x] Força-tarefa Anticorona > Notificação de casos
- [x] Força-tarefa Anticorona > Farmaco-vigilância
- [x] Força-tarefa Anticorona > Notas Técnicas
- [x] Força-tarefa Anticorona > Central de Ventiladores
- [x] Força-tarefa Anticorona > Denúncias
- [x] Aba Minha Saúde > Medidas de Proteção 
- [x] Alterar alguma aba em Minha Saúde para Minha Saúde > Saúde Mental
- [x] Alterar alguma aba em Minha Saúde para Minha Saúde > Bem-Estar Físico
- [x] Aba Educação > Cursos On-Line 
- [x] Alterar alguma aba em Educação para Educação > Tutoriais
- [x] Alterar alguma aba em Educação para Educação > Trilhas de Formação
- [x] Alterar alguma aba em Educação para Educação > Cartilhas
- [x] Alterar alguma aba em Educação para Educação > Documentos 
- [x] Aba Pesquisa > Epidemiologia 
- [x] Alterar alguma aba em Pesquisa para Pesquisa > Saúde do Profissional
- [x] Alterar alguma aba em Pesquisa para Pesquisa > Saúde Pública
- [x] Alterar alguma aba em Pesquisa para Pesquisa > Quadro Clínico
- [x] Alterar alguma aba em Pesquisa para Pesquisa > Manejo Clínico
- [x] Alterar alguma aba em Pesquisa para Pesquisa > Bases e Periódicos 
- [x] Cenários de realizar uma pesquisa pelo ícone de lupa
- [x] Cenário de enviar solicitação pelo Fale Conosco 
- [x] Cenário de realizar cadastro de perfil 
- [x] Cenário de Esqueci minha senha 
- [x] Cenário de Editar informações pessoais 
- [x] Cenário de Editar informações profissionais 
- [x] Cenário de Meus Conteúdos ao acessar seus cards

### **Critérios de Aceitação**
- [x] 1. Acessar as telas mapeadas sem internet e garantir mensagens tratadas sejam retornadas
**Dado que** estou na Home do iSUS 
**Quando** clico para acessar às telas mapeadas
**Então** uma mensagem de falha de conexão de internet deve ser exibida  

**Observações** 
- Já foram realizadas implementações de tratamento de falta de internet para o banner, a linha de cuidado e protocolos, serviços e a funcionalidade de exclusão de conta.

**Comment by MayaraMonte** [comment]
Levando em conta que a mensagem de falha de conexão não é o mesmo para todos os cenários apresentados listei o que acontece em cada tela.

O Erro: _Error loading page – Domain: undefined – Error Code: -2 – Description net:: ERR_NAME_NOT_RESOLVED_ aparecem nas seguintes telas: 

- Boletins 
- Notificações de casos
- Fármaco vigilância 
- Notas técnicas 
- Central de ventiladores
- Esqueci minha senha

Outros erros: 
- Nas seções: **Minha Saúde, Educação e Pesquisa**, quando o usuário entre sem conexão à internet aparece a tela de início do iSUS e permanece assim até que o usuário saia do app;
- Ao **pesquisar usando o ícone de busca** aparece um ícone de carregamento e permanece até que o usuário saia do app;
- A mensagem “Erro de conexão com o servidor” só aparece nas seções **Fale Conosco e Cadastro**;
- As informações do **perfil do usuário** desaparecem se ele está sem conexão com a internet;
- As opções de Editar **informações do usuário** e Editar informações profissionais não aparecem sem conexão. 

A seção de **Denúncias** está funcionando mesmo sem conexão à internet; 

A seção **Meus Conteúdos** não está disponível.

**Comment by wforte88** [comment]
Demanda tratada na tarefa #384
