### ISSUE TITLE
Implementar seção minha saúde

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/isus-app#41]
### **Objetivo**
**Como** usuária do APP
**Quero** abrir o APP e acessar a seção MINHA SAÚDE 
**Para** Acompanhar informações e projetos atualizados sobre "Medidas de Proteção", "Bem-estar Físico" e Saúde Mental.

### **Contexto**
Atualmente no APP BOTTOM TAB existem as seções Educação e Pesquisa Científica, no início do projeto foi definido outra seção chamada MINHA SAÚDE definido em categorias arquitetura.

## **Escopo**

- [x] Adicionar no APP BOTTOM TAB a seção MINHA SAÚDE
- [x] Adicionar tela minha saúde

## **Critérios de Aceite**

- [x] Acessar a seção MINHA SAÚDE
**Dado que** Acesso o APP
**Quando** clico em minha saúde
**Então** visualizo todas as subcategorias e projetos vinculados à "Medidas de Proteção", "Bem-estar Físico" e Saúde Mental.

Endpoints: https://apiisus.inova.esp.br/api/categoriasArquitetura

**Comment by victorMagalhaesPacheco** [comment]
Exemplo da tela no início do projeto:
![Captura de tela de 2020-10-14 09-04-22](https://user-images.githubusercontent.com/3487411/95986449-64438b80-0dfc-11eb-9949-7719a896aec1.png)

![Captura de tela de 2020-10-14 09-04-32](https://user-images.githubusercontent.com/3487411/95986459-67d71280-0dfc-11eb-86a7-7f0432d92d5d.png)

**Comment by victorMagalhaesPacheco** [comment]
No momento a categoria "medidas de proteção" está vazia, ou seja não existe projeto vinculado.

**Comment by nicoledbianchin** [comment]
Comportamentos de acordo com o esperado.
OS: Dispositivo Android
Versão: 3.11.0
