### ISSUE TITLE
Criar termo de consentimento de compartilhamento de dados entre sistemas que utilizam ID Saúde

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/isus-app#410]
**Contexto**
O termo de consentimento é um instrumento necessário para esclarecer e para dar autonomia à usuária sobre a utilização de seus dados por todos os sistemas integrados ao ID Saúde. Hoje não há clareza sobre isso, e o usuário que se cadastra via Mapas, por exemplo, poderá ter seus dados consumidos pelo iSUS, e por outros sistemas futuros, mas isso é ilegal conforme a LGPD. É uma tarefa sobre assegurar transparência e legalidade de uso de dados pessoais.

Prosseguir identificando envolvidos e reunindo com os mesmos.

- Clareza para o usuário do que é o iD Saúde
- Clareza de que o cadastro único integra com outras plataformas, para o usuario autorizar o consumo desses dados. Ex: se ele faz um cadastro no Mapas, ele já pode usar o iSUS com esses dados de login, pq o login na real é no iD Saúde

**Pendências**
- [ ] É necessário verificar se a atividade #267 se refere a esse consentimento ou se são coisas diferentes.

**Comment by jessica-salmazzo** [comment]
Vamos agendar uma conversa com uma pessoa que possui conhecimento claro sobre LGPD para conseguirmos esclarecer dúvidas sobre como devemos lidar e o que devemos implementar nas atividades de compartilhamento de dados/cadastros entre ID Saúde, Mapa da Saúde, iSUS, entre outras plataformas. 

Tendo essas questões esclarecidas, conseguimos seguir com o refinamento e detalhamento das estórias.

@Clarisse1983 está em contato para marcar a reunião.

**Comment by Clarisse1983** [comment]
A conversa com Danilo Doneda, em 18 de dezembro, esclareceu que Termo de consentimento é mais utilizado quando se trata da usuária conceder permissão de colher/utilizar seus dados em pesquisas. A informação essencial, contudo, é a seguinte: não importa como a gente chame o termo, se 'De Uso' ou 'De Consentimento', o que importa é deixar claro do que se trata o sistema que está coletando os dados e para quê. Como a interface do ID Saúde, na qual a usuária realiza seu cadastro (neste caso através do iSUS) já tem um Termo de Uso, que foi inclusive revisado, a continuação dessa tarefa é substituir a versão atual pela versão revisada pelo próprio Doneda. Além disso, a Política de Privacidade do iSUS, que está elaborada e será revisada, é ainda mais clara no referente à utilização de dados pessoais. E a ideia é estarem disponíveis no iSUS tanto o Termo de uso quanto a Política de Privacidade. 
Assim, vou fechar essa issue, abrir uma sobre atualizar o termo de uso já revisado no app, e atualizar a issue #267 para Criar Página de Política de Privacidade do iSUS.
