### ISSUE TITLE
Criar seção do Elmo no iSUS

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/isus-app#411]
## **Objetivo**

**Como** usuária do iSUS
**Quero** visualizar o ícone do Elmo
**Para** obter informações sobre o mesmo

## **Contexto**

O Elmo é um capacete de ventilação não invasiva, criado pela ESP e pela Fiec durante a pandemia, e que demonstrou eficácia quando utilizado em pacientes internados com Covid-19, a depender do grau de necessidade de intervenção de ventilação mecânica. É uma inovação que demandará a formação para seu uso, e que trará algumas oportunidades de negócios para o iSUS, tais como o apoio à decisão do profissional de saúde com o desenvolvimento de uma calculadora, o apoio à avaliação com quiz específico etc.

Para um MVP inicial, vamos entregar algumas informações sobre o Elmo, uma lista de espera para interessados no curso, e um estímulo a dúvidas através do Fale Conosco.

## **Pendências**

- Verificar API do sus.ce.gov.br/elmo para conteúdos da seção "Novidades".

## **UX**

- [x] Criar um ícone que ilustre esse card
- [x] Definir posicionamento do ícone (será em serviços ou em força tarefa anticorona?)
- [x] Definir jornada da usuária após o clique no ícone
- [x] Criar tela de apresentação das informações e inputs para a usuária
- [x] Definir experiência de preenchimento do formulário de interesse no curso. _Será adotado um Google Forms na versão inicial desta tela._
- [x] Definir qual será o fluxo da usuária quando ela clicar para enviar uma dúvida: vai direto para a tela do Fale Conosco já hospedada no menu lateral? _Sim, o mesmo fluxo do Fale Conosco, mas com uma opção adicional para o Elmo._
- [x] Criar a opção de 'Dúvidas sobre o Elmo' no Fale Conosco

## **Escopo**

- [x] Criar um card com o ícone do Elmo
- [x] Direcionar usuária para a webview [link] https://coronavirus.ceara.gov.br/elmo/ (etapa para visualização emergencial de conteúdo)
- [x] Criar uma tela com as informações introdutórias sobre o Elmo
- [x] Implementar tela com últimas postagens sobre o Elmo com o mesmo tratamento já realizado via API para postagens do Hotsite Coronavírus
- [x] Implementar botão que direciona para o formulário de interesse - https://forms.gle/41wzW4KkczuDH35H8
- [x] Implementar botão que direciona para o Fale Conosco
- [x] Criar a opção de 'Dúvidas sobre o Elmo' no [Fale Conosco](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=5447%3A8177)

## **Critérios de Aceitação**

- 1. Visualizar o ícone do Elmo   
**Dado que** estou acessando o iSUS 
**Quando** eu acessar a home 
**Então** devo visualizar o ícone do Elmo na seção Serviços

- 2. Visualizar o ícone do Elmo quando estou logada  
**Dado que** estou acessando o iSUS e estou logada
**Quando** eu acessar a home 
**Então** devo visualizar o ícone do Elmo na seção Serviços

- 3. Visualizar a página de informações sobre o Elmo  
**Dado que** estou na home do iSUS
**Quando** eu clicar no ícone do Elmo 
**Então** devo ser direcionada para a tela "Elmo"

- 4. Visualizar tela "Sobre o Elmo"
**Dado que** estou na tela "Elmo"
**Quando** eu clicar no link "Saiba Mais"
**Então** devo ser direcionada para a tela "Sobre o Elmo"

- 5. Baixar Manual Técnico
**Dado que** estou na tela "Elmo"
**Quando** eu clicar no botão "Manual Técnico"
**Então** devo baixar o pdf do Manual para o meu dispositivo

- 6. Ver informações sobre capacitação
**Dado que** estou na tela "Elmo"
**Quando** eu clicar no botão "Capacitação"
**Então** devo ser direcionada para a tela "Capacitação"

- 7. Sinalizar interesse em participar do curso 
**Dado que** estou na tela "Capacitação"
**Quando** eu clicar no botão "Realizar pré-inscrição"
**Então** devo ser direcionada para a página https://forms.gle/41wzW4KkczuDH35H8

 - 8. Esclarecer dúvidas sobre o Elmo 
**Dado que** estou na tela "Elmo"
**Quando** eu clicar no botão Fale Conosco
**Então** devo ser direcionada para o Fale Conosco do iSUS com a opção "[Dúvidas sobre o Elmo](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=5447%3A8177)"

 - 9. Enviar 'Dúvidas sobre o Elmo' no Fale Conosco 
**Dado que** escolhi a opção 'Dúvidas sobre o Elmo' no assunto do Fale conosco
**Quando** eu preencher os campos de mensagem e e-mail
**E** clicar no botão enviar
**Então** minha mensagem deverá ser enviada para o suporte do iSUS

 - 10. Visualizar últimos conteúdos sobre o Elmo
**Dado que** estou na tela "Elmo"
**Quando** eu visualizar a seção "Novidades"
**Então** devo ver as últimas cinco postagens da categoria "Notícias" do subsite do Elmo

 - 11. Visualizar todos os conteúdos sobre o Elmo
**Dado que** estou na tela "Elmo"
**Quando** eu clicar no link "Veja Mais" na seção "Novidades"
**Então** devo ser direcionada para a tela com todas as postagens da categoria "Notícias" do subsite do Elmo

## **Links úteis**

[Manual Técnico do Elmo](https://sus.ce.gov.br/elmo/wp-content/uploads/sites/2/2021/01/Manual_Elmo_1.1_JAN2021.pdf)
[Formulário de interesse em capacitação](https://forms.gle/41wzW4KkczuDH35H8)
[Arquitetura iSUS/Hotsite Coronovírus](https://docs.google.com/spreadsheets/d/1CqqiVEWH-YchqFSTlx3NN5zG7RBpvPRUkGo_CCyLThw/edit#gid=0)
[LP Elmo no Hotsite Coronavírus](https://coronavirus.ceara.gov.br/elmo/)

**Comment by wforte88** [comment]
### História atualizada
Edições realizadas no escopo e nos critérios de aceitação. Decisões de UX respondidas.

### Protótipo no Figma
https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=5298%3A48

**Comment by wforte88** [comment]
### História atualizada
**Manual de Uso**
Link alterado com PDF otimizado

**Formulário**
Link do Google Forms inserido no Escopo

**Pendências**
API do sus.ce.gov.br/elmo

**Comment by ItaloRod** [comment]
@Clarisse1983  Importante adicionarmos juntos o tagueamento do Analytics nos pontos chaves do Elmo na atividade para ser feito

**Comment by wforte88** [comment]
### História atualizada

**Manual de Uso**
Link alterado

**Protótipo**
Formulário de contato adicionado

**Comment by Clarisse1983** [comment]
O teste apresentou bug no critério a seguir:
Enviar 'Dúvidas sobre o Elmo' no Fale Conosco
Dado que escolhi a opção 'Dúvidas sobre o Elmo' no assunto do Fale conosco
Quando eu preencher os campos de mensagem e e-mail
E clicar no botão enviar
Então minha mensagem deverá ser enviada para o suporte do iSUS

Coloquei meus dois emails válidos e o botão enviar não ficou clicável. Eu estava logada. Tentei deslogada e o comportamento se repetiu.

**Comment by Wanderley97** [comment]
O teste apresentou bug no critério a seguir no aparelho Moto G9 Power:
Enviar 'Dúvidas sobre o Elmo' no Fale Conosco
Dado que escolhi a opção 'Dúvidas sobre o Elmo' no assunto do Fale conosco
Quando eu preencher os campos de mensagem e e-mail
E clicar no botão enviar
Então minha mensagem deverá ser enviada para o suporte do iSUS

Coloquei meu e-mail e o botão enviar não ficou clicável. Porém ao preencher o campo de e-mail primeiro depois preencher o campo de Descrição, o botão fica clicável.

**Comment by Wanderley97** [comment]
Teste realizado conforme esperado Moto G9 Power.

**Comment by Wanderley97** [comment]
Luis Felipe: Teste realizado conforme esperado Redmi 4x.
