### ISSUE TITLE
Avaliar possibilidades de separação dos ambientes de Firebase Analytics e Crashlytics

### ISSUE THREAD

**Issue by jessica-salmazzo** [EscolaDeSaudePublica/isus-app#412]
### **Objetivo**
**Como** pessoa desenvolvedora 
**Quero** estudar estratégias para separar os ambientes de Firebase Analytics e Crashlytics
**Para** que eles não colham dados de testes internos da equipe iSUS

### **Contexto**
Implementamos o recurso de Analytics e Crashlytics no projeto do iSUS para conseguirmos colher dados de comportamentos das nossas usuárias para auxiliar na tomada de decisão de demandas e ajudar na evolução do produto. 

Porém, atualmente, temos um problema onde temos um único ambiente Firebase Analytics e Crashlytics colhendo dados de usuárias em produção, usuárias que participam do grupo de beta do app e nossos testes internos quando estamos desenvolvendo alguma funcionalidade. Ou seja, um único ambiente Firebase Analytics e Crashlytics com dados de produção, grupo de beta e desenvolvimento. 

Dito isso, a consequência é que os dados ficam poluídos, visto que não estão separados ou filtrados de alguma forma por somente usuárias de produção. Os dados de testes estão se misturando com os dados de produção e isso pode influenciar nas análises desses dados. 

### **Escopo**

- [x] Estudar melhor forma de separação desses ambientes e avaliar a possibilidade conforme realidade do projeto

### **Links para ajudar**

- https://rnfirebase.io/analytics/screen-tracking

- https://developers.google.com/analytics/devguides/collection/analyticsjs/events?hl=pt-br

- https://support.google.com/analytics/answer/1033068?hl=pt-br

### **Critérios de aceite**

- [x] Ambiente produção 
**Dado** que estou acessando o app pelo ambiente de produção
**Quando** eu clicar no botão Pesquisa
**Então** somente o Analytics produção deve receber tais mapeamentos

- [ ] Ambiente beta 
**Dado** que estou acessando o app pelo ambiente de beta
**Quando** eu clicar no botão Pesquisa
**Então** somente o Analytics de homologação deve receber tais mapeamentos e o Analytics de produção não deve receber tais dados

- [x] Ambiente desenvolvimento 
**Dado** que estou acessando o app pelo meu ambiente interno de desenvolvimento para teste interno de uma funcionalidade que estou implementando
**Quando** eu clicar no botão Pesquisa
**Então** somente o Analytics de homologação deve receber tais mapeamentos e o Analytics de produção não deve receber tais dados

### **Observações**
- É interessante mostrar o Analytics para o time, assim que possível, para que todos possam ter conhecimento da estrutura e implementação que foi criada, caso seja criada realmente nessa atividade.
- Caso a estratégia que for definida demande um esforço considerável, é possível que implementemos ela em outro card e que esse card fique com foco em estudos.

**Comment by marciovcampos** [comment]
Foi possível realizar a separação dos ambientes de desenvolvimento e produção.
Agora quando um desenvolvedor estiver utilizando o aplicativo enquanto programa, ele não enviará dados para o ambiente do Firebase de produção.
Entretanto, quando o aplicativo estiver sendo testado quando estiver no TestFlight ou Android Beta Interno os dados continuam sendo enviados para o ambiente de produção.
Tal divisão é possível ao se utilizar o Fibase Remote Config. Porém, essa mudança exige mais tempo de pesquisa e desenvolvimento e deve ser tratada em um momento posterior.
