### ISSUE TITLE
Ao realizar login, se digitarmos credenciais inválidas é exibido uma mensagem de erro 400

### ISSUE THREAD

**Issue by jessica-salmazzo** [EscolaDeSaudePublica/isus-app#413]
## **Objetivo**
**Como** usuária do aplicativo iSUS no Android
**Quero** realizar meu login no app
**Para** ter acesso de forma mais prática a conteúdos personalizados para mim 

(*) **Bug simulado somente na plataforma Android por falta de possuir plataforma ios para simular**

### **Passo para simulação**
1. Acessar o app iSUS e realizar o login de acesso 
2. Digitar a informação de email 
3. No momento de digitar a informação de senha, inserir os dados '123456'
4. Clicar no botão de Fazer Login
5. Verificar o erro descrito

Outro cenário:

1. Acessar o app iSUS e realizar o login de acesso 
2. Digitar a informação de email incorreta 
3. No momento de digitar a informação de senha, digitar corretamente
4. Clicar no botão de Fazer Login
5. Verificar o erro descrito

Outro cenário:

1. Acessar o app iSUS e realizar o login de acesso 
2. Digitar a informação de email incorreta 
3. No momento de digitar a informação de senha, digitar incorretamente também 
4. Clicar no botão de Fazer Login
5. Verificar o erro descrito

### **Resultado esperado**
Aparecer uma mensagem tratada informando que os dados inseridos estão incorretos em vez de aparecer uma mensagem em inglês para trazer mais clareza para a usuária. 

Sugestão de Mensagem: Credenciais inválidas. Verifique seus dados e tente novamente. 

### **Resultado Atual**
Atualmente, aparece uma mensagem não tratada para a usuária nesse cenário. 

![image](https://user-images.githubusercontent.com/74663400/101072292-8f389900-357c-11eb-8f16-6b06435b71b9.png)

**Comment by Clarisse1983** [comment]
Teste de acordo com o esperado, aparecendo a mensagem 'Usuário ou senha inválidos'. Testado em Android One Fusion.

**Comment by uira** [comment]
@Clarisse1983 😍
