### ISSUE TITLE
App trava ao acessar minha saúde com o dispositivo no modo de avião pela primeira vez

### ISSUE THREAD

**Issue by jessica-salmazzo** [EscolaDeSaudePublica/isus-app#416]
## **Objetivo**
**Como** usuária do aplicativo iSUS no Android
**Quero** acessar os conteúdos offline que realizei download
**Para** acessa-los enquanto não estou com internet no celular 

(*) **Bug simulado somente na plataforma Android por falta de simulador IOS**

### **Passo para simulação**
1. Acessar o app iSUS pela primeira vez
3. Habilitar o modo avião do dispositivo 
4. Acessar o menu Minha Saúde
5. Observe que o app ficará travado em sua página inicial, exibindo somente a imagem inicial do iSUS

### **Resultado esperado**
Aparecer uma mensagem informando ao usuário que ele está sem internet e não permitindo o app ficar travado. 

Sugestão de imagem: 
![image](https://user-images.githubusercontent.com/74663400/101082676-95357680-358a-11eb-8772-71f8c767fd16.png)

### **Resultado Atual**
![image](https://user-images.githubusercontent.com/74663400/101082749-b8f8bc80-358a-11eb-837d-7d68514bf438.png)

**Comment by Wanderley97** [comment]
Teste realizado conforme esperado Moto G9 Power.

**Comment by Wanderley97** [comment]
Luis Felipe: Teste realizado conforme esperado Redmi 4x.
