### ISSUE TITLE
Retornar pontuação de usuária que realizou o quiz

### ISSUE THREAD

**Issue by jessica-salmazzo** [EscolaDeSaudePublica/isus-app#417]
## **Objetivo**

**Como** usuária que realizou o Qualiquiz
**Quero** que seja retornado minha pontuação de um determinado quiz que realizei
**Para** que eu consiga saber como foi minha performance geral no quiz 

## **Contexto**

Dentro do iSUS, temos um ícone do Qualiquiz para proporcionar que as usuárias logadas possam realizar quizes que estarão disponíveis com o objetivo de testar seus conhecimentos sobre os temas disponíveis. (Atualmente, temos somente o quiz do SUS - _código do quiz é 1_). 

Com isso, surge a necessidade de implementarmos um feedback para a usuária que realizou o quiz, indicando para a mesma qual foi sua pontuação obtida do quiz realizado. 

As formas de feedback que foram pensadas até o momento são: 
1. Apresentar a pontuação para a usuária (será tratado nessa atividade) 
2. Apresentar detalhes sobre as respostas certas e a explicação delas, assim como as incorretas (atividade futura, #129 Implementar devolução de respostas certas e erradas durante teste do Qualiquiz)
3. Consultar um local com o histórico de quizes já realizados e meu desempenho e feedbacks nos mesmos (possível atividade futura, dependendo se vamos seguir com a estrutura do qualiquiz ou do moodle) 

## **Pendências**

- A devolução de pontuação vai acontecer na estrutura que existe hoje do Qualiquiz? Ou no Moodle, e aí já saberemos se é a hora de integrar. 
PS: Moodle já tem uma estrutura de devolução de feedback. Sim, para fechar esse MVP vamos fazer com a estrutura que já temos.
Seguiremos com o qualiquiz nessa atividade. 

## **Premissa**
- Após a usuária já ter realizado um quiz, ela não poderá realiza-lo novamente e nem edita-lo; ou seja, poderá somente consultar sua pontuação obtida. 

## **UX**
- [x] Definir visualização de retorno dessa pontuação para a usuária na finalização do quiz
- [x] Definir visualização da usuária acessar o quiz novamente após já ter realizado o quiz; a usuária não poderá realizar o quiz novamente, ela deverá visualizar somente a pontuação de seu quiz já realizado
- [x] Definir visualização de feedback das questões, em uma única página, com explicação das respostas de cada questão na mesma tela que apresenta a pontuação.

## **Escopo**

- Validar se a usuária já realizou o quiz
- Buscar as questões do quiz, caso ainda não tenha realizado para que a usuária possa realizar o quiz de fato
- Buscar sua pontuação final, caso a usuária já tenha realizado o quiz
- Buscar o feedback das questões e apresentá-los ao final do quiz

## **Critérios de Aceitação**

- Consultar pontuação do quiz para usuária que realizou o quiz  
**Dado que** estou logada e tenho cadastro no iSUS
**Quando** eu finalizar de responder o quiz pelo qualiquiz no iSUS
**Então** deve ser exibido minha pontuação final do quiz e o feedback das questões

- Visualizar a pontuação do quiz em caso de usuária que já realizou o quiz
**Dado que** eu estou logada e respondi o quiz no iSUS
**Quando** eu clicar no ícone do qualiquiz no app iSUS
**Então** devo visualizar minha pontuação obtida e o feedback das questões

**Comment by MayaraMonte** [comment]
Protótipo atualizado
QualiQuiz > Questões > Confirmação de Envio e Resultado
https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=5111%3A8252

**Comment by uira** [comment]
Faltou essa parte, que é essencial:
Apresentar detalhes sobre as respostas certas e a explicação delas, assim como as incorretas

**Comment by wforte88** [comment]
Isso está no contexto, mas não no escopo desta tarefa, será tratado [aqui](https://github.com/EscolaDeSaudePublica/isus-api/issues/129).

**Comment by uira** [comment]
@wforte88 Mas isso aí é mais pra frente, agora é um resultado detalhado no final mesmo

**Comment by uira** [comment]
@uira Precisa adicionar todas as respostas listadas abaixo do resultado total, da forma como já está no figma. Só falta adicionar tempo total do quiz.

Para exibir as respostas sugiro fazer tipo um acordeon, onde as respostas ficam escondidas sob uma linha com titulo, se acerto ou erro, e o tempo de resposta. 

E as repostas que a pessoa errou, já vem abertas.

O padrão de conteúdo da resposta é um texto explicativo e um link pra + conteúdo

**Comment by wforte88** [comment]
Ajuste realizado no escopo da tarefa para fechar o MVP:
Feedback das questões será apresentado em texto corrido, com link âncora para cada questão, na mesma tela de retorno da pontuação.

Alinhado com @uira, @chicaothiago e @MayaraMonte

**Comment by wforte88** [comment]
### Protótipo atualizado
**QualiQuiz > Confirmação de Envio > Resultado**
https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=5235%3A68
