### ISSUE TITLE
Elmo

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/isus-app#418]
## **Contexto**

O Elmo é um capacete de ventilação não invasiva, criado pela ESP e pela Fiec durante a pandemia, e que demonstrou eficácia quando utilizado em pacientes internados com Covid-19, a depender do grau de necessidade de intervenção de ventilação mecânica. É uma inovação que demandará a formação para seu uso, e que trará algumas oportunidades de negócios para o iSUS, tais como o apoio à decisão do profissional de saúde com o desenvolvimento de uma calculadora, o apoio à avaliação com quiz específico, Fórum, Telemedicina e Certificação.

Para um MVP inicial, vamos entregar algumas informações sobre o Elmo, uma lista de espera para interessados no curso, e um estímulo a dúvidas através do Fale Conosco.

## **Dúvidas**
- Onde será criado esse card? (Seção)
Colocar como um banner até data estipulada, e depois que sair do banner, coloca onde?
- Quais os materiais já disponíveis  para o mvp?
- Qual a jornada da usuária para acessar esses materiais?
- Curso: inscrições serão pelo iSUS?
A capacitação presencial vai acontecer, mas não tem data. 
- Qual a entrega do iSUS nesse mvp?
Apresentação do que é o Elmo
Lista de interesse - formulário para quem tem interesse no curso se cadastrar
Nome/email/telefone
Esses dados serão enviados pra ESP Virtual
Quando tiver o curso, o iSUS direciona para a matrícula
Os interessados receberão um email com data do curso etc.

## **Links úteis**

https://coronavirus.ceara.gov.br/elmo/

**Comment by jessica-salmazzo** [comment]
Atividade duplicada com a #433 devido integração com zen hub. Vou remover essa para centralizar em somente um card.
