### ISSUE TITLE
Refatorar Manejo Clínico de Covid-19

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/isus-app#420]
Cards relacionados:

#184 Gerar notificações no banner para novas atualizações do manejo
#180 Sinalizar o usuário onde houveram atualizações no manejo
#177 Visualizar versionamento do manejo clinico
#204 Template para Atualização do manejo no One Signal
#187 Gerar Notificações para novas atualizações do manejo

Dúvidas:

Quais conteúdos são mais importantes na atualização?
Como os profissionais descobrem o que mudou de uma versão para outra hoje em dia?
Como podemos apresentá-los?
Devemos apresentar o antes/depois? Ou só o depois? (Pensar em exemplos)
Notas Técnicas (como a ESP organiza o manejo):

Paramentação
Pacientes em Orientações iniciais
Pacientes em UAPS/UPA/Emergência
Pacientes em Internação Hospitalar
Pacientes em UTI
Exames Laboratoriais
Diretriz de Diagnóstico

**Comment by chicaothiago** [comment]
Existe atualmente um site para o manejo clinico.
