### ISSUE TITLE
Melhorar a experiência da usuária finalizar o preenchimento de informações e o enter do teclado do dispositivo estar integrado aos botões do app

### ISSUE THREAD

**Issue by jessica-salmazzo** [EscolaDeSaudePublica/isus-app#427]
**Contexto** 
Foi possível observar que pessoas usuárias realizam a ação de clicar no botão de ‘enter’ do teclado do dispositivo com o intuito de prosseguir com a ação

**Exemplo:**
**Dado** que estou realizando meu cadastro e termino de preencher as informações pessoas
**Quando** clico no botão de ‘enter’ do teclado do meu celular
**Então** sigo para a próxima seção de preenchimento de dados profissionais

**Comment by janeteamaral** [comment]
Solicitamos uma avaliação do time de UX para indicar a pertinência da solução indicada.

**Comment by RaniGub** [comment]
@Laysacunha pelo escopo da tarefa não é necessário protótipo.

**Comment by ericsonmoreira** [comment]
Já corrigido na issue #718.
