### ISSUE TITLE
Incluir Notas Técnicas como destaque na tela inicial

### ISSUE THREAD

**Issue by uira** [EscolaDeSaudePublica/isus-app#43]
**COMO**
Profissional da saúde pública

**EU QUERO**
Acessar as Notas Técnicas de forma rápida e fácil

**PARA**
Buscar referências e saber sobre mudanças ou novas informações

**Observações**
- Avaliar a possibilidade de incluir um ícone de notificação

![Captura de Tela 2020-05-12 às 15 10 46](https://user-images.githubusercontent.com/89998/81730552-16e57b80-9464-11ea-9b54-f8eb2bcc5dab.png)

**Comment by matheuscpl** [comment]
Pessoal, já tá atualizado na home do protótipo no Figma o ícone e botão desta issue, como também o link na planilha.
https://docs.google.com/spreadsheets/d/1CqqiVEWH-YchqFSTlx3NN5zG7RBpvPRUkGo_CCyLThw/edit#gid=0
[icon_notastecnicas.zip](https://github.com/EscolaDeSaudePublica/isus-app/files/4645862/icon_notastecnicas.zip)

**Comment by matheuscpl** [comment]
![Screenshot_45](https://user-images.githubusercontent.com/64148308/82331743-e8632580-99ba-11ea-91fe-05476a1dfaa3.png)

**Comment by matheuscpl** [comment]
Meu povo, temos uma nova alteração. "Notas técnicas" sobe para a linha de Serviços substituindo "Mapa da saúde", este é retirado da home.
![Início](https://user-images.githubusercontent.com/64148308/82368111-3db72b00-99eb-11ea-887e-7bdf965ca474.png)
