### ISSUE TITLE
Personalizar respostas automáticas em tela após envio de feeedback - OK

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/isus-app#439]

**Comment by Laysacunha** [comment]
@Clarisse1983 você pode nos dar mais contexto ou atualizar a história de usuário?

**Comment by Clarisse1983** [comment]
Mulher, morta de vergonha dessa issue sem nada, misericórdia hahaha. Como tem mil anos, eu imagino que seja aquela resposta automática que aparece na tela quando alguém envia mensagem no Fale Conosco, e que já está implementada. Por mim pode fechar.

**Comment by Laysacunha** [comment]
Obrigada @Clarisse1983. Issue sendo fechada.
