### ISSUE TITLE
Criar card de Plano de Contingência dentro da seção de Força Tarefa Anticorona

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/isus-app#440]
## **Objetivo**
**Como** usuária do aplicativo iSUS
**Quero** visualizar um card específico para Plano de Contingência publicado no site coronavirus
**Para** facilitar o acesso ao documento atualizado

## **Contexto**
Plano de Contingência é um documento construído pelo grupo técnico de enfrentamento à Covid-19, e que não se caracteriza nem como Protocolo, nem como Nota Técnica, nem como boletim, portanto em nenhum formato para o qual já dispomos destaque no iSUS. A ideia é justamente criar um card específico desse documento, dada a relevância do seu acesso pelos profissionais de saúde, no carrossel do Força-tarefa Anticorona. 

## **Escopo**
- [x] Criar um novo card na home do iSUS para Plano de Contingência, dentro da seção Força-tarefa Anticorona conforme [Figma]
- [x] Implementar o card na segunda posição no carrossel
- [x] Redirecionar a usuária que clica no card para a webview da página https://coronavirus.ceara.gov.br/project/governo-do-ceara-publica-plano-estadual-de-contigencia-para-respostas-as-emergencias-em-saude-publica-no-contexto-da-covid-19/
- [x] Implementar tratamento de exibir mensagem de falha com internet conforme [Figma](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=2288%3A0) 
![image](https://user-images.githubusercontent.com/74663400/99996326-53dae500-2d9a-11eb-8f5d-1fd865556dfd.png)
- [x] Realizar tagueamento Analytics do cartão com a seguinte estrutura (Home | Click | cartao_plano_contingencia).
## **UX**
- [x] Definir a jornada do usuário ao clicar nesse card na home 
- [x] Criar um ícone para identificar o Plano de Contigência
- [x] Definir um cenário para falta de internet 
- [x] Quando o usuário clicar no ícone de Plano de Contingência, ele deve ser direcionado para a webview da página https://coronavirus.ceara.gov.br/project/governo-do-ceara-publica-plano-estadual-de-contigencia-para-respostas-as-emergencias-em-saude-publica-no-contexto-da-covid-19/

## **Critérios de Aceitação**

- [x] Visualizar card de Plano de Contingência ao acessar a home
**Dado** que acessei o iSUS
**Quando** estou na home 
**Então** visualizarei o card "Plano de Contingência" dentro da seção "Força-tarefa Anticorona"

- [x] Acessar conteúdo que é Plano de Contingência
**Dado** que estou na seção de "Força-tarefa Anticorona"
**Quando** clico no ícone de Plano de Contingência
**Então** visualizarei a webview da página https://coronavirus.ceara.gov.br/project/governo-do-ceara-publica-plano-estadual-de-contigencia-para-respostas-as-emergencias-em-saude-publica-no-contexto-da-covid-19/

- [x] Falha de conexão com internet
**Dado** que estou na home
**E** sem conexão com internet
**Quando** clico no ícone de Plano de contingência
**Então** visualizarei a mensagem informando que estou sem internet

- [x] Falha de conexão com internet
**Dado** que estou visualizando a mensagem de falha de internet 
**Quando** clico no botão Voltar da mensagem de falha de internet
**Então** sou redirecionada para a Home

**Comment by MayaraMonte** [comment]
Protótipo atualizado: https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=5575%3A0

**Comment by ItaloRod** [comment]
@luisfcosta2015  e eu  notamos que o escopo estava sobrepondo o que estava sendo solicitado na tarefa anterior. Por isso colocamos o plano de contingência como segunda posição.

**Comment by Wanderley97** [comment]
Realizado testes conforme esperado aparelho Moto G9 Power.

**Comment by MayaraMonte** [comment]
Realizado testes conforme esperado aparelho Xiaomi Redmi Note 8
