### ISSUE TITLE
Criar seção "Vacina-COVID19" 

### ISSUE THREAD

**Issue by luisfcosta2015** [EscolaDeSaudePublica/isus-app#445]
## **Objetivo**

**Como** Pessoa usuária  
**Quero** Acessar conteúdos sobre a vacina COVID-19 
**Para** Me manter informado sobre todo o processo de vacinação no Estado do Ceará.

## **Contexto** 

Essa ideia surgiu de uma conversa com Washington sobre onde dispor e como um conteúdo indicado pelo Dr. Marcelo, de orientações para profissionais de saúde de administração da vacina do Butantan. Para não colocar só a bula solta, Wash deu a ideia de criar uma página no hotsite, tipo a de Farmacovigilância, para colocar esses conteúdos, que vão crescer ao longo do processo, incluindo, por exemplo, cronograma de vacinação no Estado. Em princípio nós vamos começar com a disponibilização pelo app do Isus do conteúdo da bula da vacina do Butantan e implementarmos as demais informações quando estas estiverem disponíveis.

## **UX**

- [x] Gerar o link de endereçamento para onde a pessoa usuária será enviada.
- [x] Definir o ícone do Carrossel
- [ ] Definir em acordo com a Ascom o banner

## **Escopo** 

- [x] Criar um banner sobre a Vacina. Inserir o banner na primeira posição.
- [x] Criar um card no carrossel  força-tarefa anticorona, com ícone Vacina COVID-19, segundo o figma.
- [x] Encaminhar a pessoa usuária para o link http://coronavirus.ceara.gov.br/vacina 
- [x] Implementar tratamento de exibir mensagem de falha com internet conforme [Figma](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=5617%3A8712)
- [x] Realizar tagueamento Analytics conforme [tabela](https://docs.google.com/spreadsheets/d/1yb95l1Hqcs8A81KE9HCYKztAdBlQL6j8JyKrlws95uU/edit#gid=53222801)

## **Critérios de Aceitação**

- [x] 1. Banner sobre a Vacina estando logada ou não
**Dado que** estou na Home do app, independente de estar logada ou não   
**Quando** navego pelos banners  
**Então** devo visualizar um banner sobre a Vacina na primeira posição

- [x] 2. Banner sobre a Vacina
**Dado que** visualizei o banner sobre a Vacina   
**Quando** clico nele
**Então** devo visualizar a webview indicada no escopo

- [x] 3. Card Vacina no Carrossel
**Dado que** estou na Home do app, independente de estar logada ou não  
**Quando** navego pelo Carrossel Força-tarefa Anticorona na Home
**Então** deve aparecer um card Vacina COVID-19

- [x] 4. Card sobre a Vacina
**Dado que** visualizei o card sobre a Vacina no Carrossel Força-tarefa Anticorona   
**Quando** clico nele
**Então** devo visualizar a webview indicada no escopo

- [x] 5. Falha de conexão com internet
**Dado** que estou na home
E sem conexão com internet
**Quando** clico no ícone de Protocolos
**Então** visualizarei a mensagem informando que estou sem internet

- [x] 6. Falha de conexão com internet
**Dado** que estou visualizando a mensagem de falha de internet
**Quando** clico no botão Voltar da mensagem de falha de internet
**Então** sou redirecionada para a Home

- [x] 7. Simulação de login clique em Card Vacina no Carrossel Força-tarefa Anticorona
**Dado** que estou na home e navegando pelo carrossel Força-tarefa Anticorona
**Quando** clico no card da Vacina
**Então** no Analytics deve ficar registrado essa ação conforme tagueamento da [planilha](https://docs.google.com/spreadsheets/d/1yb95l1Hqcs8A81KE9HCYKztAdBlQL6j8JyKrlws95uU/edit#gid=53222801)

- [x] 7. Simulação de login clique em Banner Vacina 
**Dado** que estou na home e navegando pelos banners
**Quando** clico no banner da Vacina
**Então** no Analytics deve ficar registrado essa ação conforme tagueamento da [planilha](https://docs.google.com/spreadsheets/d/1yb95l1Hqcs8A81KE9HCYKztAdBlQL6j8JyKrlws95uU/edit#gid=53222801)

# Observações
Nossa meta ao longo prazo é criar um MVP no hotsite que seja uma página de referência sobre a Vacina, com conteúdos administrados pela Ascom-ESP, para onde as usuárias serão direcionadas a partir desse mesmo endereço.

**Comment by wforte88** [comment]
### Protótipo atualizado
https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=5617%3A8712

**Comment by Wanderley97** [comment]
Teste conforme esperado no aparelho Moto G9 Power.

**Comment by Wanderley97** [comment]
Luis Felipe: Teste conforme esperado no aparelho Redmi 4x.
