### ISSUE TITLE
Analisar-Organizar fluxo de notificações iSUS

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/isus-app#447]
## **Contexto**
Precisamos definir a publicização das entregas do iSUS enquanto estratégia digital de divulgação. A princípio pensei em usar o One Signal e suas já implementadas notificações gerais, para começar a notificar coisas mais específicas para as pessoas usuárias do iSUS, diferentemente da Ascom, que vem usando o canal para notificar ações gerais da ESP. Mas conversando com Washington, conheci alguns desafios desse processo:
- notificações gerais sobre funcionalidades vão chegar em usuárias com diferentes versões do app, portanto haveria o risco e divulgarmos uma entrega que levaria a um vazio, no caso da usuária ter uma versão anterior à que apresenta a nova funcionalidade;
- isso levaria a necessidade de fazer notificações por versão... mas tanto isso não está implementado no one signal ainda, quanto não temos uma maneira muito clara de acompanhar as versões e suas funcionalidades (se o filtro de sprint fosse de versão, por exemplo, teríamos mais autonomia nesse processo).
Avançando na discussão, vimos que além do one signal com notificações, temos outras ações de comunicação que precisam/podem ser trabalhadas:
Canais:
Onboard com modal: quando a pessoa baixa uma nova versão e pode saber o que ela tem de novo
Notificação on signal
Banner
Release: o que há de novo na versão, para a loja
Play console: acompanhar os comentários e responder, sobre 

A decisão sobre o que/onde vamos comunicar pode ficar a cargo do PubliciLab. Já o 'como', é muito importante ser definido junto à equipe de Negócio e UX do projeto, uma vez que se o melhor caminho for um onboard, por exemplo, ele já precisa ser acordado na sprint que vai implementar a funcionalidade.
Resumindo:
Queremos comunicar isso, vamos fazer como?
- É uma notificação? Se for, precisa ter cuidado com a versão, o on signal preisa estar habilitado para enviar a notificação apenas para quem tem aquela versão
- É um onboard? Se é, é um texto, um texto com foto etc.
- É por versão?

## **Escopo**
- [x] Criar instrumento de mapeamento de notificações de novas entregas do iSUS
https://docs.google.com/spreadsheets/d/1d-ffbU_njfD0HKSX_TvDR6xy23kd-h2vp2N9TPBu-N0/edit#gid=0
- [ ] Reunir com Ascom para propor uma estratégia de notificações
- [ ] refinar épico de notificações
- [ ] separar o que é desenvolvimento e o que é estratégia de divulgação
- [ ] planejar a partir das notificações já possíveis (gerais, para o site)

**Comment by Laysacunha** [comment]
@ericabpinho @Clarisse1983 estamos usando essa issue como base para o trabalho atual? Já temos outra?
