### ISSUE TITLE
Retirar o Banner do Covid-19 Heroes, visto que a pesquisa se encerrou 

### ISSUE THREAD

**Issue by ItaloRod** [EscolaDeSaudePublica/isus-app#454]
## **Objetivo**

**Como** gestor do app iSUS
**Quero** retirar o banner do Covid-19 Heroes
**Para**  evitar com que profissionais de saúde realizem uma pesquisa que já encerrou.

## **Contexto**

- Conforme solicitado da Ascom (Júlio Lopes), a pesquisa do covid-19 heroes já acabou e deve ser removida do aplicativo.

## **Escopo**

- [x] Retirar do carrossel de banners, o banner do covid-19 heroes.

## **Fora de Escopo**

- Verificar se não há quebra nos testes ao retirar o banner

## **Critérios de Aceitação**

- [x] Visualização do banner Covid-19 heroes
**Dado que** abro o  app iSUS
**Quando** visualizo a home do app
**então** não devo visualizar o banner do covid-19 heroes.

**Comment by Wanderley97** [comment]
Teste realizado conforme esperado Moto G9 Power.

**Comment by MayaraMonte** [comment]
Teste realizado conforme esperado Xiaomi Redmi Note 8
