### ISSUE TITLE
Criar página de gestão do time iSUS Discovery - OK

### ISSUE THREAD

**Issue by luisfcosta2015** [EscolaDeSaudePublica/isus-app#459]
## **Objetivo**

**Como** time do iSUS Discovery  
**Quero** criar uma página de gestão de informações do time iSUS Discovery 
**Para** atender aos coordenadores e gestores do Felicilab, stackeholders e PO

## **Contexto**
Existe uma demanda de apresentar o roadmap do projeto iSUS semanalmente, indicando as métricas da Sprint atual, riscos ao projeto e todas as informações úteis sobre o projeto. [Aqui](https://docs.google.com/presentation/d/1KDY44Ifg8M7B2Rfey6Awo3ni7keHcGX5gkSD99MW_6Y/edit?usp=sharing) tem exemplo disponibilizado pela coordenação do Felicilab com apresentação. Além disso precisamos deixar visível e de fácil acesso o novo [template](https://github.com/EscolaDeSaudePublica/isus-app/issues/new/choose) criado para centralizar novas demandas do iSUS. Sobre o roadmap, pode ser útil analisar a geração de gráficos pelo Metabase.

-
UX

- [ ] Criar layout da página

## **Escopo**

- [ ] Criar site/página web com url na internet
- [ ] Deixar visível roadmap do projeto, através de gráficos
- [ ] Deixar visível template de novas demandas
- [ ] Inserir Logo do time iSUS Discovery
- [ ] Inserir informações dos membros do time e suas habilidades 

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [ ] Acesso à página 
**Dado que** Sou gestor do Felicilab, stackeholders ou PO quero acessar a página do time iSUS  
**Quando** preciso analisar a saúde do projeto
**então** as informações de gestão do projeto(Roadmap e Template demandas) devem aparecer com a logo do time

# Observações

Consultar o @victorMagalhaesPacheco sobre a possibilidade de usar o Metabse para gerar gráficos do Roadmap e perguntar se ele tem disponibilidade para nos ensinar a mexer no Metabase, principalmente porque temos a intenção de permitir que o @Wanderley97 possa aprender a usar o Metabase. 

Exemplo de como usar o GitHub Pages: https://docs.github.com/pt/github/working-with-github-pages/adding-a-theme-to-your-github-pages-site-with-the-theme-chooser

**Comment by luisfcosta2015** [comment]
Achei um projeto que pode servir muito bem para esta tarefa: https://docusaurus.io/

**Comment by Laysacunha** [comment]
Demanda não é mais aderente pois o ZenHub já atende a visualização de relatórios de produtividade.
