### ISSUE TITLE
Farmacovigilância: Termo de Consentimento com tramitação digital

### ISSUE THREAD

**Issue by wforte88** [EscolaDeSaudePublica/isus-app#46]
**COMO**
Profissional da Saúde

**EU QUERO**
enviar o Termo de Consentimento de Uso de Medicação aos pacientes

**PARA**
que eles assinem o documento digitalmente, sem necessidade de impressão ou deslocamento para entrega do Termo.

**CRITÉRIOS**
Termo deve ser convertido em um formulário;
O aceite deve ter segurança jurídica.

**Comment by kurjes** [comment]
Validar com @uira a construção ou não do épico telemedicina/teleconsultoria. Segundo informações de @rodrigoplimafreire  esse projeto foi descontinuado pela ESP e  está com a SESA.

**Comment by Laysacunha** [comment]
@gabrieladamarques Encaminhar para backlog de projeto.

**Comment by uira** [comment]
@ericsonmoreira Tem que repassar ela pra @gabrieladamarques incluir no backlog de Projetos ;)
