### ISSUE TITLE
Ajustar Carrossel do app organizando QualiQuiz no local correto

### ISSUE THREAD

**Issue by luisfcosta2015** [EscolaDeSaudePublica/isus-app#461]
## **Objetivo**

**Como** Gestor (dr marcelo)
**Quero** reordernar a forma como os serviços são apresentados
**Para** que serviços prioritários sejam vistos primeiros

## **Contexto**

-Quando ocorreu a demanda para subir o QualiQuiz, como categoria no Carrossel, o combinado era ele ir pra o final do carrossel, justamente pra não chamar a atenção. Por algum motivo, ele foi pra produção como segundo item, antes do integraSUS.

É necessário realizar o ajuste desta correção o quanto antes, principalmente por conta do pedido da alta direção da ESP.

## **Escopo**

- [x] Por o Qualiquiz como ultimo na lista de serviços
- [x] Exibir o IntegraSUS como o primeiro item na lsita de serviços
- [x] Exibir o Elmo como segundo item na lista de serviços

## **Fora de Escopo**

- Ordenar qualquer outro item da lista

## **Critérios de Aceitação**

- [x] Ajuste da categoria Qualiquiz no Carrossel de serviços
**Dado que** sou uma pessoa usuária do iSUS 
**Quando** acesso a página home
**Então** visualizo o QualiQuiz com oo ultimo na lista de serviços

- [x] Ajuste da categoria IntegraSUS no Carrossel de serviços
**Dado que** sou uma pessoa usuária do iSUS 
**Quando** acesso a página home
**Então** visualizo o IntegraSUS com o primeiro item na lista de serviços

- [x] Ajuste da categoria Elmo no Carrossel de serviços
**Dado que** sou uma pessoa usuária do iSUS 
**Quando** acesso a página home
**Então** visualizo o Elmo com o segundo item na lista de serviços

# Observações

Pela atividade atrasada, esta imagem foi enviada lembrando da alteração.
![image](https://user-images.githubusercontent.com/6399202/112665750-267e7080-8e3a-11eb-9fbb-b729dd57fe81.png)

**Comment by Wanderley97** [comment]
Conforme testes realizados em Moto G9 Power, os Critérios de Aceitação foram atendidos.
