### ISSUE TITLE
Quebra de layout ao selecionar muitas itens em setor de atuação na página HOME

### ISSUE THREAD

**Issue by chicaothiago** [EscolaDeSaudePublica/isus-app#463]
## **Descrição**

Ao selecionar muitas opções no campo de `Setor de atuação` dentro de Informações Profissionais o local onde exibe esta informação na página HOME sobrepõe-se a toda tela, dificultando navegação.

É necessária uma avaliação da interface para melhorar a disposição do conteúdo na tela.

## **Observações**

Texto íntegro:
```
Ticket 261: Para refina de hoje.
ISUS APP - FEEDBACK 04/10/2020 18:07:39
Categoria: Relatar sugestão (iSUS)
Texto: Assim fica qdo usuários selecionam várias opções ao se cadastrar. A página inicial fica sem utilidade.
E-mail usuário: wilson@bol.com.br
Versão do app: 3.11.0
Plataforma: android
```
![image](https://user-images.githubusercontent.com/6399202/111509146-322bb200-872b-11eb-8a32-5633715da1f3.png)

**Comment by MayaraMonte** [comment]
Conforme conversado na reunião de refinamento, vamos deixar visivel apenas o primeiro nome e a profissão.

**Comment by Wanderley97** [comment]
Teste realizado conforme esperado em Moto G9 Power.
