### ISSUE TITLE
ISUS APP-FEEDBACK [250] 26/09/2020 11:04:53

### ISSUE THREAD

**Issue by Wanderley97** [EscolaDeSaudePublica/isus-app#473]
# Características

- Categoria: Relatar sugestão (iSUS)
- E-mail: wilson@bol.com.br
- Versão do App: 3.10.5
- Plataforma: android

# Descrição

De que governo? Se é apenas do CE então deixe claro que é um App ISUS CEARÁ. Afinal de contas o SUS é nacional.

# Encaminhamentos

Será tratado juntamente com o grupo DesignLab para a informação precisa.
![Screenshot_20200926-110126](https://user-images.githubusercontent.com/74379182/111678543-2dd0c900-87ff-11eb-971a-eebd58ac5365.jpg)

**Comment by chicaothiago** [comment]
#477

**Comment by Wanderley97** [comment]
Aguardando por parte dos stakeholders uma definição válida de qual será a abrangência do app, se continuará como sendo apenas um app para o Ceará ou será de uso abrangente.

**Comment by Wanderley97** [comment]
Caso em tratamento no card a seguir:
https://github.com/escoladesaudepublica/isus-app/issues/549

**Comment by Wanderley97** [comment]
Após processos de atualização é possível identificar que as ações do governo são identificadas como sendo parte dos Serviços SUS Ceará conforme imagem, fazendo-se mais identificável de qual governo se trata, já que a seção está identificando o estado.

![photo_2022-01-26_16-14-45](https://user-images.githubusercontent.com/74379182/151230872-accbedf6-97d6-4c63-8b77-e1e6f61ca5fc.jpg)
