### ISSUE TITLE
Corrigir Botão de enviar imagem não funciona na tela de Fale Conosco 

### ISSUE THREAD

**Issue by oxechicao** [EscolaDeSaudePublica/isus-app#478]
## **Descrição**
Ao acessar a página para relatar sugestão/fale conosco, o botão de anexar imagem não está funcionando, mesmo depois de garantir a permissão de acesso.

O comportamento correto é abrir a galeria para escolher uma imagem para ser enviada.

## **Observações**

![image](https://user-images.githubusercontent.com/6399202/112872408-bae50f00-9096-11eb-8f4d-1db26d5d80ea.png)

![image](https://user-images.githubusercontent.com/6399202/112872507-d7814700-9096-11eb-82b4-d5f506220ab0.png)

**Comment by Wanderley97** [comment]
Durante testes em Moto G9 Power, ocorreu o seguinte erro.

![photo4958571367532440004](https://user-images.githubusercontent.com/74379182/117865017-d170af80-b26b-11eb-8292-3775e1420697.jpg)

**Comment by Laysacunha** [comment]
observação: Na última solução desse bug foi ativado uma opção legacy do picker, então as atualizações de pacotes realizadas nas ultimas semanas podem ter gerado algum tipo de incompatibilidade com o pacote de imagem.

**Comment by Wanderley97** [comment]
Durante testes em Moto G9 Power, ocorreu o seguinte erro novamente.
![117865017-d170af80-b26b-11eb-8292-3775e1420697](https://user-images.githubusercontent.com/74379182/120830844-50889900-c535-11eb-922d-e3c909bd90cb.jpg)

**Comment by chicaothiago** [comment]
![image](https://user-images.githubusercontent.com/6399202/121707237-be404200-caac-11eb-8292-8b7254cccdb1.png)
