### ISSUE TITLE
Os elementos da parte superior da tela de "Sobre o iSUS" estão sobrepostos e fora da Safe Area no iPhone XR.

### ISSUE THREAD

**Issue by camilaccolares** [EscolaDeSaudePublica/isus-app#48]
Ícone de busca (lupa) - lado direito - está sobrepondo o ícone da bateria.
Ícone do menu sanduíche - lado esquerdo - está sobrepondo o relógio.
Titulo "Sobre o iSUS" está fora da Safe Area e não aparece direito na tela.

Imagem do problema em anexo. 

![image](https://user-images.githubusercontent.com/58710064/81805754-d03e6280-94f1-11ea-9f98-d5e715404f2e.png)

**Comment by mbernardes19** [comment]
Por enquanto, eu e Amaury rodamos o app no emulador do Xcode usando um iPhone XR, porém não conseguimos reproduzir esse mesmo bug nele. Estamos procurando uma outra forma de reproduzí-lo.

<img width="438" alt="print iPhone XR" src="https://user-images.githubusercontent.com/26047592/81986840-f6a5f000-960e-11ea-9be1-8ccdf3999e43.png">
