### ISSUE TITLE
Gerenciar banners de destaque da HOME a partir de configurações oriundas da API

### ISSUE THREAD

**Issue by oxechicao** [EscolaDeSaudePublica/isus-app#483]
## **Objetivo**

**Como** pessoa gestora do iSUS  
**Quero** ser capaz de ativar, desativar, adicionar banners de destaques na tela da HOME  
**Para** que eu não tenha necessidade de aguardar uma nova versão do iSUS para gerenciar os banners

## **Contexto**

Estão surgindo necessidades de adicionar banners de destaque com período de duração. Atualmente para estes banners entrarem em produção é preciso gerar uma nova versão do iSUS, o mesmo processo para remover.
Com a visão de que está funcionalidade irá surgir diversas vezes, uma estrutura lógica foi pensada para que a partir de uma consulta da API, saber quais serão os banners e suas configurações.

## **Escopo**

- [x] Consultar na API os banners ativos e salvar/atualizar no localstorage: `GET /api/banner-config`
- [x] Exibir os banners consultados e executar de acordo com as suas configurações

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [x] Exibir lista de banners
**Dado que** tenho a lista de banners da API  
**Quando** estou na home  
**então** exibi a lista de banners com suas  imagens ordenadamente de acordo com a API.

- [x] Exibir WebView de Banner webview
**Dado que** clico em um banner na home  
**Quando** o banner está configurado para abrir uma webview  
**então** abrir o componente WebView com a URL definida

- [x] Redirecionar para rota o Banner do tipo rota
**Dado que** clico em um banner na home  
**Quando** o banner está configurado para abrir uma rota  
**então** redirecionar para a rota configurada no banner.

# Observações

> Atividade API
https://github.com/EscolaDeSaudePublica/isus-api/issues/162

> Modelo do Banner:

```json
{
  "titulo": "tituloDoBanner",
  "imagem": "imagem_do_banner(url|base64|seila)",
  "valor": "url|rota",
  "tipo":  "webview|rota",
  "ordem": "numeroOrdenado",
  "options": {
    "chave": "valor"
  }
}
```

> Tipos de Opções mapeadas:

| Opção | ex. Valor | Descrição |
| ------------------ |  ---------------- | ----------- |
|  "cor"                  | "branco"            | nome da cor_base usada no header da webview |
| "localImagem"  | "app" ou "web" | origem da fonte da imagem, pode estar dentro do app ou ser uma url externa |
| "login"                | true ou false      | identifica se o banner deve ser exibido somente quando autenticado |
| "labelAnalytics"   | "string"              | valor do texto enviado ao analytics |

> TestId

Seguir o padrão: 
```javascript
const testId = `home-banner-${ordem}`
```

> Exemplo de componentização: listaBanners

```javascript
if (tipo === 'webview')
  <Banner
    labelDoAnalytics={opcoes?.labelAnalytics || 'home-banner'}
    testID={`home-banner-${ordem}`}
    titulo={titulo}
    imagem={buscarImagem(imagem, opcoes?.localImagem)}
    enderecoUrl={valor}
  />
if (tipo === 'rota')
  <Banner
    labelDoAnalytics={opcoes?.labelAnalytics || 'home-banner'}
    testID={`home-banner-${ordem}`}
    titulo={titulo}
    imagem={buscarImagem(imagem, opcoes?.localImagem)}
    pagina={valor}
  />
```

Demanda original

> Enquete no iSUS
Foi feito no google forms: https://forms.gle/fDpC2FhTV88MwrpX9
Abrir com webview
Usuário anônimo, não precisa de login
Tem que ficar em destaque
Verificar a possibilidade de por um banner dinâmico baseado em uma consulta de API

**Comment by chicaothiago** [comment]
# Modificações para tentar testar

> pages/Banners/index.js

- Linha 12
    - Alterar a linha para ao invés de chamar listaBanners, chamar somente a consulta da API
        - import { pegarBanners } from '../../../apis/apiHome';
- Adicionar uma variável `navigation` e pasar como atributo/props para o componente `<BannerCarrosel navigation={navigation}>`
- Passar para o componente BannerCarrossel a variável estadoLogado com atributo

> pages/Banners/BannerCarrossel.js

- Adicionar as props a variável `nagigation` e `estaLogado`
- Adicionar um estado para armazenar a lista de banners: `const [listaBanners, definirListaBanners] = useState([]);`
- Adicionar um `useEffect(() => { definirListaBanners(gerarBanners(banners, estaLogado, navigation)); }, [banners]);`

> src\pages\Home\Banners\listaDeBanners.js

- Na função gerarListaBanner adicionar o argumento/parametro `navigation`
    - Passar o `navigation` para a função definirBanner
- Na função definirBanner adicionar o parâmetro navigate
    - Adicionar o `navigation` como atributo do componente Banner

> src\components\Banner\index.js

- Adicionar nas props o valor de `navigation`
- Na linha 24, alterar para `const navigationValue = navigation || useNavigation();`
- Alterar linhas que usam navigation para navigationValue: 32, 35, 37

> __tests__\pages\Home\Banners\banner.test.js

- Atualizar os testes passando navigation como atributo de BannerCarrossel na função de render();
