### ISSUE TITLE
Analisar PR: ⬆️ Bump axios from 0.19.2 to 0.21.1

### ISSUE THREAD

**Issue by oxechicao** [EscolaDeSaudePublica/isus-app#486]
## **Objetivo**

**Como** pessoa desenvolvedora do isus  
**Quero** manter atualizado os pacotes  
**Para** ter mais segurança

## **Contexto**

Dependabot é um bot do github que verifica pacotes instalados em repositórios.

## **Escopo**

- [ ] Modificar a branch do pull request para a branch que estará desenvolvendo (clicando em editar no titulo)
- [ ] Efetuar merge do pull request #438 
- [ ] Verificar integridade pós merge

## **Critérios de Aceitação**

- [ ] Efetuar merge 
**Dado que** acesso a página do pull request  
**Quando** efetuo o merge  
**então** instalo os pacotes novos corretamente
 
- [ ] Verificar integridade do app
**Dado que** instalo os pacotes novos  
**Quando** abro o aplicativo  
**então** as funcionalidades do aplicativos estão nos conformes

**Comment by ericsonmoreira** [comment]
Já feito na #478.
