### ISSUE TITLE
Testes no Formulário de Edição Informações Pessoais

### ISSUE THREAD

**Issue by oxechicao** [EscolaDeSaudePublica/isus-app#489]
## **Objetivo**

**Como** pessoa gestora da qualidade  
**Quero** garantir que o formulário de edição de informações pessoais tenham testes automatizados
**Para** manter uma melhor integridade do componente

## **Contexto**

A atividade foi feita em caráter emergência e não foram feitos os testes automatizados nos componentes.
Sendo assim quebrando no padrão de criar testes automatizados para os comportamentos das telas.

## **Escopo**

- [x] Testar se renderização do componente
- [x] Testar se texto exibido na tela
- [x] Testar se os campos do input estão recebendo os dados da pessoa autenticada
- [x] Testar se a validação dos campos ao alterar algum valor, ex: cpf.

## **Critérios de Aceitação**

- [x] Exibir text de introdução do formulário
**Dado que** estou na tela de edição de informações pessoais
**Quando** a tela é renderizada corretamente
**Então** devo visualizar o texto no topo: `Edite as informações pessoais que você deseja atualizar`

- [x] Exibir o campo Nome Completo
**Dado que** inicializo a tela do formulário de edição
**Quando** apresento o formulário  
**então** um campo do tipo input/text deve ser exibido com a label `Nome Completo`

- [x] Preencher o campo Nome Completo
**Dado que** inicializo a tela do formulário de edição
**Quando** apresento o formulário  
**então** o campo `Nome Completo` deve estar preenchido com o nome da pessoa autenticada

- [x] Exibir o campo E-mail
**Dado que** inicializo a tela do formulário de edição
**Quando** apresento o formulário  
**então** um campo do tipo input/text deve ser exibido com a label `E-mail`

- [x] Preencher o campo E-mail
**Dado que** inicializo a tela do formulário de edição
**Quando** apresento o formulário  
**então** o campo `E-mail` deve estar preenchido com o nome da pessoa autenticada

- [x] Exibir o campo Telefone
**Dado que** inicializo a tela do formulário de edição
**Quando** apresento o formulário  
**então** um campo do tipo input/text deve ser exibido com a label `Telefone`

- [x] Preencher o campo Telefone
**Dado que** inicializo a tela do formulário de edição
**Quando** apresento o formulário  
**então** o campo `Telefone` deve estar preenchido com o nome da pessoa autenticada

- [x] Exibir o campo CPF
**Dado que** inicializo a tela do formulário de edição
**Quando** apresento o formulário  
**então** um campo do tipo input/text deve ser exibido com a label `CPF`

- [x] Preencher o campo CPF
**Dado que** inicializo a tela do formulário de edição
**Quando** apresento o formulário  
**então** o campo `CPF` deve estar preenchido com o nome da pessoa autenticada

- [x] Exibir o campo Município
**Dado que** inicializo a tela do formulário de edição
**Quando** apresento o formulário  
**então** um campo do tipo input/text deve ser exibido com a label `Município`

- [x] Preencher o campo Município
**Dado que** inicializo a tela do formulário de edição
**Quando** apresento o formulário  
**então** o campo `Município` deve estar preenchido com o nome da pessoa autenticada

- [x] Habilitar botão se todos os campos estiverem preenchidos e validados
**Dado que** inicializo o componente inserindo os campos no FormContext  preenchidos
**Quando** apresento o formulário  com os campos preenchidos e validados
**então** o botão de ação está habilitado

- [x] Texto Salvar no botão
**Dado que** o componente é renderizado
**Quando** apresento o formulário e o botão
**Então** o botão deve exibir o texto `Salvar`

# Observações

O componente se utiliza de 2 contextos: 
- FormContext
- AutenticacaoContext

**Comment by ruigmoreno** [comment]
Esta atividade foi bloqueada devido a complexidade de tratar o envio das informações ao pressionar botão "Salvar" através do testing-library. O botão não é nativo do react-native, ele envolve outras depedências.

**Comment by oxechicao** [comment]
A função handleSubmit é uma promessa e nós estamos testando uma função interna desse handleSubmit.
Dessa forma não conseguimos testar a ação interna.
A decisão tomada foi de extrair os dois critérios de aceite para outra atividade, afim de finalizar esta.

Explicação da promessa
```javascript
function callback(){}

handleSubmit(callback)

const promessa = async (callback) => {
  if (sucesso()) {
    return callback(); // função que desejamos testar
  }

  throw new Exception();
}
```

Uma possível solução para este problema pode ser refatorar a função por completo do botão.
