### ISSUE TITLE
Impressão do Manejo COVID-19

### ISSUE THREAD

**Issue by matheuscpl** [EscolaDeSaudePublica/isus-app#49]
**TÍTULO**
Impressão do Manejo COVID-19

**AUTOR:**
Matheus

**COMO**
Profissional da saúde pública

**EU QUERO**
Imprimir o conteúdo de Manejo clínico

**PARA**
Expor de maneira física em minha unidade de saúde

**OBSERVAÇÕES**
- Posso escolher entre uma seção específica ou o manejo completo.
- Conter uma versão resumida dos protocolos.
- Posso escolher o formato de impressão (A4, A3,...).
- Deve ser dinâmico e seguir as atualizações de conteúdo do Manejo COVID-19.

**Comment by Clarisse1983** [comment]
A estrutura do manejo não se divide mais em quatro estágios, como foi inicialmente pensado, então hoje é possível imprimir o pdf inteiro do manejo, e diante desse contexto de refatoração, essa tarefa não se aplica mais e será arquivada.

**Comment by uira** [comment]
@Clarisse1983 Não vai ter a impressão no formato atual, ou não vai ter mais a função de imprimir?
