### ISSUE TITLE
Implementar experiência SEM INTERNET na ação de Login

### ISSUE THREAD

**Issue by oxechicao** [EscolaDeSaudePublica/isus-app#492]
## **Objetivo**

**Como** pessoa usuária do iSUS  
**Quero** ter uma experiência quando sem internet no login   
**Para** que eu tenha clareza no fluxo

## **Contexto**

Atualmente, a usuária pode ter sua experiência comprometida quando não tem acesso à internet e esse cenário não é tão claro para ela no momento, visto que não temos uma mensagem visual explicando o que aconteceu e o que ela pode tomar de ação.

## **Escopo**

- [x] Implementar Dialog com mensagem que não contém conexão
- [x] Implementar ação de cancelar/voltar no Dialog
- [x] Implementar ação de tentar novamente o login no Dialog
- [x] Implementar redirecionamento para uma tela de sem conexão, para quando tentar novamente três vezes

## **Fora de Escopo**

- Implementar atividade em algum outro formulário

## **Critérios de Aceitação**

- [x] Fazer Login sem internet  
**Dado que** estou na tela de Login
**E** preencho os campos corretamente  
**E** estou sem internet
**Quando** clico no botão de login  
**Então** exibir `Dialog` da falta de conexão (OBS 1)

- [x] Tentar Novamente COM Internet  
**Dado que** estou na tela de Login
**E** tentei login sem internet
**E** `Dialog` sem conexão foi exibido
**Quando** clico em `Tentar Novamente` com a internet ativada
**Então** efetuo o login normalmente

- [x] Tentar Novamente SEM Internet  
**Dado que** estou na tela de Login
**E** tentei login sem internet
**E** `Dialog` sem conexão foi exibido
**Quando** clico em `Tentar Novamente` com a internet desabilitada
**Então** o `Dialog` deve ser exibido novamente

- [x] LIMITE 3 Tentativas
**Dado que** estou com o Dialog de sem conexão
**Quando** clicar em `Tentar Novamente` pela terceira vez
**E** ainda continua sem internet
**Então** redirecionar para a tela de `Sem Conexão` (OBS 2)

- [x] Tela Sem conexão voltar para HOME
**Dado que** cliquei 3 vezes em `Tentar Novamente`
**E** estou na tela de `Sem Conexão`
**Quando** clicar em voltar
**Então** ir para HOME

# Observações

1. Dialog `Sem Conexão` 

![Dialog](https://user-images.githubusercontent.com/6399202/116099806-b8b8a500-a682-11eb-8465-3c83e5bfaadd.png)

2. Tela de sem conexão 

![Sem Conexão](https://user-images.githubusercontent.com/6399202/116100009-e9004380-a682-11eb-9e09-0dbd36daf69d.png)

**Comment by Wanderley97** [comment]
Todos os critérios de aceitação foram atendidos conforme teste em Moto G9 Power.
