### ISSUE TITLE
Implementar experiência SEM INTERNET ao acessar os MENUS INFERIORES

### ISSUE THREAD

**Issue by oxechicao** [EscolaDeSaudePublica/isus-app#494]
## **Objetivo**

**Como** pessoa usuária do iSUS  
**Quero** ter uma experiência quando tentar acessar uma menu inferior   
**Para** que eu tenha clareza no fluxo

## **Contexto**

Atualmente, a usuária pode ter sua experiência comprometida quando não tem acesso à internet e esse cenário não é tão claro para ela no momento, visto que não temos uma mensagem visual explicando o que aconteceu e o que ela pode tomar de ação.

## **Escopo**

- [ ] Implementar lógica de tentar acessar um menu inferior verificar se tem internet e redirecionar para Sem Conexão (OBS 1), caso não tenha.
    - [ ] Minha Saúde
    - [ ] Educação Permanente
    - [ ] Pesquisa Científica
- [ ] Implementar tela de sem conexão com tentar novamente (OBS 1)
- [ ] Implementar ação no botão VOLTAR para voltar p/ HOME
- [ ] Implementar ação de tentar novamente o acesso a rota do MENU Clicada
- [ ] Implementar redirecionamento para uma tela de sem conexão, para quando tentar novamente três vezes (OBS 2)

## **Critérios de Aceitação**

- [x] MINHA SAUDE: Redirecionar para Sem Conexão 1  
**Dado que** estou na HOME
**E** estou sem conexão com internet
**Quando** clico no Menu Inferior `Minha Saúde`
**Então** exibo a página de `Sem Conexão`

- [x] Educação Permanente: Redirecionar para Sem Conexão 1  
**Dado que** estou na HOME
**E** estou sem conexão com internet
**Quando** clico no Menu Inferior `Educação Permanente`
**Então** exibo a página de `Sem Conexão`

- [x] Pesquisa Científica: Redirecionar para Sem Conexão 1  
**Dado que** estou na HOME
**E** estou sem conexão com internet
**Quando** clico no Menu Inferior `Pesquisa Científica`
**Então** exibo a página de `Sem Conexão`

- [x] Acesso de artigo: Sem Conexão
**Dado que** estou na Minha saúde OU Educação Permanente OU Pesquisa Cientifica
**E** estou sem conexão com internet
**Quando** clico em um artigo
**Então** exibo a página de `Sem Conexão`

- [x] Mudando ABAS/MENUS superiores: Sem Conexão
**Dado que** estou na Minha saúde OU Educação Permanente OU Pesquisa Cientifica
**E** estou sem conexão com internet
**Quando** clico em um ABA/MENU SUPERIOR
**Então** exibo a página de `Sem Conexão`

- [x] Tentar Novamente COM Internet  
**Dado que** estou na página de Sem Conexão
**E** tenho conexão com internet ativada
**Quando** clico em `Tentar Novamente`
**Então** continuo o fluxo para o `conteúdo` desejado

- [x] LIMITE 3 Tentativas
**Dado que** estou na página de Sem Conexão
**Quando** clicar em `Tentar Novamente` pela terceira vez
**E** ainda continua sem internet
**Então** redirecionar para a tela de `Sem Conexão` (OBS 2)

- [x] Tela Sem conexão voltar para HOME
**Dado que** cliquei 3 vezes em `Tentar Novamente`
**E** estou na tela de `Sem Conexão` (OBS 2)
**Quando** clicar em voltar
**Então** ir para HOME

# Observações

https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=5290%3A8053

1. Tela de Sem Conexão com Tentar Novamente 

![Tela-Sem-Conexao](https://user-images.githubusercontent.com/6399202/116100190-14832e00-a683-11eb-8962-49cfee11e65a.png)

2. Tela Sem Conexão final
<img src="https://user-images.githubusercontent.com/6399202/116100009-e9004380-a682-11eb-9e09-0dbd36daf69d.png"  width="300">

**Comment by ruigmoreno** [comment]
**Análise do possível problema** 
A _promisse_ da função "salvarDados" cuja se encontra em **armazenamento.js** está lançando uma exceção para o arquivo **apiHooks.js** disparando a mensagem: ___'Erro ao salvar categorias no storage'___.

**Fluxo:** appBottomTab>appTopTab>apiHooks>armazenamento

**Comment by Wanderley97** [comment]
Todos os critérios de aceitação foram cumpridos corretamente conforme testado em Moto G9 Power.
