### ISSUE TITLE
Corrigir bug de textos no menu lateral.

### ISSUE THREAD

**Issue by oxechicao** [EscolaDeSaudePublica/isus-app#504]
## **Descrição**

O menu lateral não está exibindo textos dos 3 botões inferiores (visualizar na imagem).

- Exibir novamente os textos novamente

## **Observações**

Imagem da falha:
![image](https://user-images.githubusercontent.com/6399202/118499679-8cca9580-b6fd-11eb-9178-f92286875a92.png)

**Comment by chicaothiago** [comment]
Para o texto que está quebrando, deixar somente Compartilhar

**Comment by Wanderley97** [comment]
Textos estão sendo exibidos e funcionando normalmente conforme testes realizados em Moto G9 Power.
