### ISSUE TITLE
ISUS APP-FEEDBACK - [791] 04/06/2021

### ISSUE THREAD

**Issue by Wanderley97** [EscolaDeSaudePublica/isus-app#509]
# Características

- Categoria: Relatar sugestão (iSUS)
- E-mail: carlosbean2013@gmail.com
- Versão do App: 3.15.10
- Plataforma: Android

# Descrição

Sou Pedagogo e cursando pós em Neuropsicopedagogia. Trabalho na Saúde Mental há 7 anos e sinto muita falta da inserção da minha profissional na Saúde. Ainda não há estudos ou pesquisas sobre a contribuição da Pedagogia e suas abordagens. Sentimos a necessidade de uma interação multiprofissional através de cursos, capacitações e estudos. Obrigado.

# Encaminhamentos

Tratar com pessoas interessadas sobre a possibilidade de incluir nova categoria profissional e sobre como será lidado com a possibilidade de conteúdos sobre assunto.

**Comment by Clarisse1983** [comment]
Gente, muito legal esse contato. Pro negócio, acho bem significativo um pedagogo pedindo para ter sua categoria profissional inserida no iSUS ("minha profissional na Saúde"), porque o SUS é multiprofissional e todos que nele trabalham são trabalhadores do SUS. Inserir a categoria é um passo no processo de reconhecimento da pessoa como pertencente a essa rede. Então acho super viável que a gente inclua essa categoria no cadastro. Se e quando vamos ter conteúdos específicos é uma outra questão, que diz respeito não só a essa categoria como a todas as outras que inexistem e se registram como Outros, por exemplo, como é o meu caso - defendo inclusive que tenha Comunicação como mais uma categoria.

Nesse sentido, acho que vale criar a tarefa, que tem a ver com o épico de cadastro, e vale responder o usuário agradecendo o contato. Sugestão: "Boa tarde, Carlos. Como vai? Gostamos muito de sua mensagem, e achamos a questão da inclusão da Pedagogia como uma categoria profissional disponível no cadastro muito pertinente. Afinal, o SUS é o espaço da multi e da interdisciplinaridade, e suas soluções tecnológicas precisam refletir isso. Estamos levando a questão para a discussão junto ao nosso time de desenvolvimento. Agradecemos imensamente o contato. Atenciosamente (e a assinatura)"
