### ISSUE TITLE
Priorizar Manejo na Tela Inicial

### ISSUE THREAD

**Issue by uira** [EscolaDeSaudePublica/isus-app#51]
COMO
Usuário do Aplicativo

EU QUERO
Ver o protocolo de manejo como destaque na tela inicial

PARA
Conhecer, acessar e receber as atualizações e procedimentos relacionados ao manejo clínico.

**Comment by matheuscpl** [comment]
Home atualizada
- Subir banner de Manejo
- Tirar destaque dos ícones das seções

**Comment by ItaloRod** [comment]
Tirar destaque dos ícones das seções inclui retirar o minha saúde, educação e pesquisa?
