### ISSUE TITLE
Sem Conexão com internet ao acessar um menu inferior, ex: Minha Saúde.

### ISSUE THREAD

**Issue by oxechicao** [EscolaDeSaudePublica/isus-app#512]
## **Descrição**

Ao clicar no menu inferior na tela da home, por exemplo Minha Sáude, Educação Permanente,
E clicar em algum conteúdo de dentro da página
A tela exibida é de sem conexão
Mas ao clicar em tentar novamente ou em voltar, ele acessa a tela.

## **Observações**

3.18.7

**Comment by ruigmoreno** [comment]
Questão levantanda na biblioteca [netInfo](https://github.com/react-native-netinfo/react-native-netinfo/issues/405) similar ao problema tratado nesta issue.

Solução: atualizar a biblioteca para a nova versão 6.0.0. E, implementar verificação de estado inicial.
