### ISSUE TITLE
Rever o fluxo automático dos campos na tela de login

### ISSUE THREAD

**Issue by oxechicao** [EscolaDeSaudePublica/isus-app#519]
## **Objetivo**

**Como** persona usuária do iSUS  
**Quero** ter um fluxo mais amigável na tela de login  
**Para** não ver mensagens sem eu ter feito nada

## **Contexto**

Ao acessar a página de login o campo de texto automaticamente é exibido para inserir o login, quando fecha automaticamente abre-se o da senha. Se eu fechar ambos sem clicar escrever nada, pois eu quero, por exemplo, ler os termos, eu vejo uma mensagem de que os campos estão incorretos. Mas, não tive intenções de escrever.

## **Escopo**

- [x] Analisar e desenhar um fluxo de usabilidade na tela de Login, se a automação é algo bom ou ruim.

## **Fora de Escopo**

- Alterar o design da tela, a ideia é só o fluxo que hoje existem automações.

**Comment by Laysacunha** [comment]
Essa experiência já foi melhorada. Ao entrar na tela de login o campo não é mais automaticamente ressaltado. Vide vídeo abaixo:

https://user-images.githubusercontent.com/20958122/164369590-58a3c992-af7e-4bde-85d2-79f2eb97054d.mp4
