### ISSUE TITLE
Criar teste automatizado para validar se a ação do botão de submit é executada na tela de edição de informações pessoais.

### ISSUE THREAD

**Issue by oxechicao** [EscolaDeSaudePublica/isus-app#523]
## **Objetivo**

**Como** pessoa gestora da qualidade  
**Quero** ter garantias que o comportamento do botão existe automaticamente  
**Para** garantir uma melhor qualidade do comportamento da tela

## **Contexto**

O teste para o botão salvar não foi possível de ser feito no momento de outra atividade. Decidiu-se separar em outra issue para garantir a finalização da outra atividade e ter todos os teste da tela de edição de informações pessoais da persona feitas, menos o botão.

Esta atividade tem o objetivo de buscar desenvolver um teste automatizado para a função passada para dentro do handleSubmit()

## **Escopo**

- [ ] Chamar a função quando formulário está validado
- [ ] Não chamar a função quando formulário estiver invalidado

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [ ] Chamar função de atualizarUsuario quando form estiver sem erros
**Dado que** estou na tela de formulário de edição
**E** formulário está preenchido corretamente
**Quando** clico no botão salvar
**Então** a função de edição deve ser chamada `atualizarUsuario()`

- [ ] Não chamar função de atualizarUsuario quando formulário conter erros
**Dado que** estou na tela de formulário de edição
**E** contém algum erro no formulário
**Quando** clico no botão salvar
**Então** não se deve chamar a função de edição `atualizarUsuario()`

# Observações

ex: Prototipo

**Comment by janeteamaral** [comment]
débito técnico que não influencia no funcionamento do app
