### ISSUE TITLE
Encontrei um problema ao precisar recuperar a senha

### ISSUE THREAD

**Issue by drmarcos** [EscolaDeSaudePublica/isus-app#529]
# Encontrei um problema ao precisar recuperar a senha

> Ontem o ícone do app mostrou uma notificação
Quando fui acessar o aplicativo, não exibiu nada, assim experimentei "logar" para ver se havia alguma forma de encontrar a notificação
Percebi que havia esquecido a senha naquele momento, então solicitei a recuperação.
Recebi o email mas me deparei com um problema, não consigo recuperar/mudar a senha.

# Acessar tela de login/ clicar em esqueci senha/aguardar email

> Uma vez recebido email, ao acessar o site através do link, sou informado de estar logado. Se eu clicar no link voltar para o aplicativo, aparece a tela para login. Ou seja, não posso recuperar e nem trocar a senha.

Imagems:
> https://drive.google.com/file/d/1IBwBmO1jP6rCUqImCDIVfBIQM1gGSVXI/view?usp=sharing
> https://drive.google.com/file/d/1SV_z3gemb3PUAT8ih5wJtIzdS360pQtl/view?usp=sharing
> https://drive.google.com/file/d/1FS6PNioogtn2dntSKXpTdHr4EaLmPlZb/view?usp=sharing

# Sugestões

> Precisamos deixar a validade do email de recuperação em 365 dias?

**Comment by janeteamaral** [comment]
Avaliado o issue eo erro não persiste
