### ISSUE TITLE
Atualizar texto da splash screen

### ISSUE THREAD

**Issue by matheuscpl** [EscolaDeSaudePublica/isus-app#53]
O formato do texto na parte inferior da splash screen foi modificado

**Comment by ItaloRod** [comment]
A tarefa não está bem especificada. Qual parte do texto deve ser alterada?

**Comment by matheuscpl** [comment]
A única, o texto todo. Tá atualizado no Figma, agora se divide em duas linhas e uma parte é verde...

**Comment by wforte88** [comment]
@ItaloRod é uma pequena alteração no rodapé:
![bottom-splash](https://user-images.githubusercontent.com/21333612/82001870-99bc3100-9632-11ea-9604-09f6371d08bc.png)

**Comment by ItaloRod** [comment]
entendi. Muito obrigado

**Comment by ItaloRod** [comment]
Tarefa concluida tanto iOS quanto android
