### ISSUE TITLE
Erro nas máscaras de Telefone e CPF - Tela de cadastro

### ISSUE THREAD

**Issue by ericsonmoreira** [EscolaDeSaudePublica/isus-app#535]
# Descrição

> Ao concluir o cadastro pelo `ID-Saúde`, na tela de cadastro do `iSus`, não é possível alterar o `telefone` nem o `cpf`.

![photo_2021-09-01_10-09-59](https://user-images.githubusercontent.com/1212015/131677015-f8efbf04-4ee7-46ed-8f91-5c0cde1654ba.jpg)

# Passo-a-passo para replicar

1. Tentar fazer o Login pelo ID-Saúde
2. Verificar se é possível fazer a edição dos campos `telefone` e `cpf`.

# Sugestões

> Tentar verificar erros nas `máscaras` dos campos.

**Comment by Wanderley97** [comment]
Testes realizados com sucesso em Moto G9 Power. Foi possível editar e salvar informações de telefone e CPF.
