### ISSUE TITLE
Registro dos históricos dos trabalhos realizados - OK

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-app#540]
Escrever documentação do iSUS com base no conjunto de documentos e links disponíveis `[aqui.](https://docs.google.com/document/d/1k_ak7DLQ5BKSKbKmrHaUG8xnxUOPN4NF/edit#heading=h.gjdgxs)`

Documento deve ser criado com enfoque nos métodos de trabalho.

**Comment by Laysacunha** [comment]
Documento disponível para apreciação @JefersonNSoares @janeteamaral @ericsonmoreira

**Comment by ericsonmoreira** [comment]
Essa atividade será um prática constante.
