### ISSUE TITLE
Revisar cadastro de usuário para Id Saúde

### ISSUE THREAD

**Issue by ericsonmoreira** [EscolaDeSaudePublica/isus-app#548]

**Comment by uira** [comment]
@ericsonmoreira Pra que essa segunda etapa?

**Comment by ericsonmoreira** [comment]
@uira geralmente quando se tem cadastro de qualquer plataforma, tem-se sempre alguma etapa de confirmação de e-mail ou coisa parecida. Meu questionamento é se não deveria existir essa "verificação".

**Comment by uira** [comment]
@ericsonmoreira Foi pensado dessa forma para simplificar a jornada do usuario. 

Esse tipo de verificação será feito diretamente no iDsaude, quando for o caso e, principalmente, de acordo com a necessidade. 

Como não temos nenhuma operação sensível até agora, entendo que não há necessidade desse tipo de confirmação agora. 

o que acham?

**Comment by ericsonmoreira** [comment]
Tudo bem @uira. Só comentei pq surgiu essa dúvida na minha cabeça. 👍🏻

**Comment by Laysacunha** [comment]
Visto que não há necessidade no momento, encerrando issue.
