### ISSUE TITLE
Definir a Logomarca do Qualiquiz 

### ISSUE THREAD

**Issue by JefersonNSoares** [EscolaDeSaudePublica/isus-app#551]
# Definir a Logomarca do (Produto) Qualiquiz 

Definir a Logomarca do (Produto) Qualiquiz para uso na tela Splash de entrada do Qualiquiz. Esta tela se faz necessária para reduzir a sensação de delay na entrada do Qualiquiz. Atualmente, ao ser chamado o Qualiquiz, a tela Splash está apresentando a logo do ISUS. A tela de Splash.

![splat isus](https://user-images.githubusercontent.com/34108133/139057344-b842e363-139c-48a4-95a7-a16e942ab78b.png)

**Comment by RaniGub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DesignLab-606d8c0a23f88d0010676dd5/issues/EscolaDeSaudePublica/isus-app/551?planning-poker) with ZenHub @MayaraMonte @pauloamoreira

**Comment by RaniGub** [comment]
Foi solicitado ao @wforte88 o repasse do arquivo vetorial, assim que recebermos um comentário com o arquivo será postado.

**Comment by Laysacunha** [comment]
Esse arquivo atende @RaniGub?

![QualiQuiz](https://user-images.githubusercontent.com/20958122/160725349-c5c390b4-6e71-44c3-a047-7ef09252894d.svg)

**Comment by RaniGub** [comment]
Oi @Laysacunha, esse tem no Figma e foi usado para o protótipo. @wforte88 você consegue resgatar o logo original do QualiQuiz?

**Comment by RaniGub** [comment]
![Logo_qualiquiz_SVG](https://user-images.githubusercontent.com/79097920/175044268-9443bbf9-2045-4da2-84d9-61e0501e061e.svg)
Segue logo em SVG.

**Comment by ericsonmoreira** [comment]
@RaniGub Tem algum Figma do comportamento dessa tela para que eu possa finalizar essa discursão de criar uma issue mais limpa? Caso não tenha ou não seja necessário, vc pode descrever como é o comportamento esperado?

**Comment by RaniGub** [comment]
https://www.figma.com/file/ivBbsk8mkgSyW5nqXS5MZS/Tela-Splash?node-id=0%3A1

@ericsonmoreira
