### ISSUE TITLE
Indicativo para a volta do qualiquiz e melhoria na estética de apresentação da borda superior.

### ISSUE THREAD

**Issue by JefersonNSoares** [EscolaDeSaudePublica/isus-app#552]
# Indicativo para a volta do qualiquiz e melhoria na estética de apresentação da borda superior.

Em função da tecnologia empregada no desenvolvimento do `qualiquiz` (Webview) onde este é chamado dentro do aplicativo do `iSUS` é apresentada uma borda superior do aplicativo na cor verde e outra borda do qualiquiz na cor roxa ao acessar o serviço, tem-se então duas bordas superiores em cores diferentes e com título repetido como apresentado na figura a seguir. Ressalta-se também o consumo de grande parte da tela devido a essa duplicação.

![estetica qualiquiz](https://user-images.githubusercontent.com/34108133/139077278-b0985746-e588-48d1-9256-3181058ec4c4.png)

Outro ponto seria a experiência do usuário no botão voltar superior, onde o texto atual da barra é `Qualiquiz` e dá a entender ao usuário que a ação do botão vai ser direcionada a alguma tela referente ao qualiquiz e não ao iSUS.

#### Observações:
A cor da barra superior do aplicativo pode ser modificada de acordo com a cor solicitada. 

### Protótipo
Novo header: https://www.figma.com/file/JR5T67TVb8gDascGwM0kwp/MVP-1.0-beta3?node-id=882%3A575

![Analytics.png](https://images.zenhubusercontent.com/610accbe69320580a6a9c239/0477a8e8-0bb3-4d8c-b556-0a0e49b4f742)

**Comment by matheuscpl** [comment]
Adicionado protótipo com novo header
