### ISSUE TITLE
  Incluir a ação `sair` no menu principal

### ISSUE THREAD

**Issue by JefersonNSoares** [EscolaDeSaudePublica/isus-app#553]
#   Incluir a ação `sair` no menu principal

Atualmente no iSUS caso o usuário deseje sair do aplicativo deve-se seguir o passo a passo:

`Clicar no botão superior esquerdo na home > Meu perfil > sair`

<div>
<img src="https://user-images.githubusercontent.com/34108133/139080870-a08a5f7f-cad4-4fd6-a8e5-e1d1fe27317e.jpeg" width="200"  img>
<img src="https://user-images.githubusercontent.com/34108133/139081329-78a499fe-2d7a-440f-9f03-85eb99c1446d.jpeg" width="200"  img>
</div>

A ação `Sair` somente pode ser encontrada com a opção interna da tela `meu perfil`. Necessário avaliar  a experiência do usuário para a opção `sair` e se necessário desenhar o modelo da tela no Figma para inclusão do botão no menu principal. 

# Protótipo
Menu principal: https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=6925%3A8484

**Comment by matheuscpl** [comment]
Adicionado protótipo com adição do botão
