### ISSUE TITLE
Melhorar lentidão na hora do cadastro.

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-app#555]
# Contexto
Os campos de cadastro realizam validação de dados em tempo real e isso deixa o cadastro muito lento. Exemplo: ao começar a digitar um e-mail o campo já esta verificando e informando que não está de acordo com o esperado.
Simulação em vídeo 

Simulação em vídeo: https://www.youtube.com/embed/6mDknP3PC5E

# Escopo

- [ ] 1. Fazer o mapeamento de todos os formulários que existem na aplicação.
- [ ] 2. Verificar quais estão com lentidão.
- [ ] 3. Verificar quais estão usando o **react-hook-form**.
- [ ] 4. Testar uma abordagem onde possamos separa as lógicas do componente do formulário, validação dos campos e mensagens de erro (dar uma olha na lib [yup](https://github.com/jquense/yup) + react-hook-form).

> Opcional - testar a atualização da lib react-hook-form.

**Comment by ericsonmoreira** [comment]
## Análise Técnica

O time decidiu usar a seguinte abordagem:

1. Fazer o mapeamento de todos os formulários que existem na aplicação.
2. Verificar quais estão com lentidão.
3. Verificar quais estão usando o **react-hook-form**.
4. Testar uma abordagem onde possamos separa as lógicas do componente do formulário, validação dos campos e mensagens de erro (dar uma olha na lib [yup](https://github.com/jquense/yup) + react-hook-form).

> Opcional - testar a atualização da lib react-hook-form.

**Comment by ericsonmoreira** [comment]
Já corrigido na issue #718.
