### ISSUE TITLE
Rever alteração de CPF no cadastro do iSUS

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-app#557]
Eu como desenvolvedor do iSUS
Quero alterar campo de CPF para ser não editável
Para garantir confiabilidade na informação do CPF que é um número único.

# Contexto #
Ao editar informações é possível alterar o campo CPF no cadastro do iSUS. Tendo em vista que o CPF representa uma numeração única, sugere-se checar a regra de negócio.

Simulação em vídeo: https://youtu.be/PS_4hPmoeJE

**Comment by ericsonmoreira** [comment]
Funcionalidade já implementada,
