### ISSUE TITLE
Verificar experiência ao entrar com senha incorreta

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-app#560]
# Descrição

- Ao tentar realizar login com uma senha incorreta, o primeiro retorno para o usuário é a tela do idSaude. É necessário verificar esse fluxo de experiência.

Simulação em vídeo: https://www.youtube.com/watch?v=NZXOh_kdVo0

# Protótipo

ID Saúde: https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=5699%3A2

**Comment by matheuscpl** [comment]
Atualizei o protótipo adicionando os cenários solicitados

**Comment by ericsonmoreira** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/iSUS---Refinamento-61672dbc32f1ce0015aa7eca/issues/EscolaDeSaudePublica/isus-app/560?planning-poker) with ZenHub @janeteamaral @JefersonNSoares @Laysacunha

**Comment by ericsonmoreira** [comment]
Já corrigido na issue #718.

**Comment by Laysacunha** [comment]
Experiência não foi implementada na issue #718. Voltando pra product backlog
