### ISSUE TITLE
Permitir usuário baixar conteúdos de educação e pesquisa

### ISSUE THREAD

**Issue by wforte88** [EscolaDeSaudePublica/isus-app#57]
# Objetivo

**Eu como** profissional da saúde  
**Quero** Fazer download de conteúdos de Educação e Pesquisa  
**Para que** possa acessar quando quiser, mesmo sem conexão  

# Contexto
## O que originou
Há a demanda por acesso aos conteúdos do app em situações onde o profissional da saúde não possui conexão com rede de internet.

## Qual solução proposta
A criação de um botão que, quando selecionado, faz download do conteúdo referente e permite o usuário acessar a lista de conteúdos salvos e visualizar os mesmos sem nenhum tipo de conexão com a rede de internet. Este botão ficará localizado no **appbar** no inferior da página.

# Escopo
## Appbar

- [x] Uma barra de ferramentas deve ser inserida no inferior das páginas de leitura dos conteúdos, onde serão inseridos os botões com as funcionalidades de 'download' e 'compartilhar'

![Screenshot_84](https://user-images.githubusercontent.com/64148308/85319920-a8e79780-b498-11ea-9302-9fd4810c553f.png)

- [ ] A barra deve **desaparecer** ao fazer **scroll para baixo** na página e **aparecer** novamente ao fazer **scroll para cima**

![ezgif com-crop](https://user-images.githubusercontent.com/64148308/85321572-3e842680-b49b-11ea-89a6-a65f0d2c6240.gif)

Elemento React no Framework: https://callstack.github.io/react-native-paper/appbar.html

## Botão de download

- [x] Inserir botão de download para que o conteúdo esteja disponível quando offline
![Screenshot_85](https://user-images.githubusercontent.com/64148308/85321095-85bde780-b49a-11ea-9697-e871e4bf75ef.png)

- [x] Inserir botão de downloaded para excluir o conteúdo offline do app do usuário e o mesmo volte a ser disponível somente de forma online
![Screenshot_86](https://user-images.githubusercontent.com/64148308/85321105-89516e80-b49a-11ea-9ffe-84efa14fe50d.png)

## Feedbacks (snackbar)

- [x] Ao selecionar o conteúdo para download deve surgir a mensagem:
![Screenshot_87](https://user-images.githubusercontent.com/64148308/85321814-b05c7000-b49b-11ea-986c-451bef42335b.png)

- [x] Ao excluir o conteúdo da visualização offline deve surgir a mensagem:
![Screenshot_88](https://user-images.githubusercontent.com/64148308/85321823-b3eff700-b49b-11ea-9f19-2b3faf9d3b25.png)

OBS: Nunca deve sobrepor ao appbar

# Fora de contexto

- **Data de postagem**

- [x] A data de postagem do conteúdo deve ser retirada da parte inferior ao título e adicionada no appbar

- **Compartilhar**

- [x] Inserir botão de compartilhar o conteúdo também no appbar, retirando a feature da parte inferior ao título

# Critérios de aceitação

## Appbar

- [x] **Dado que** queira ler o conteúdo sem acessar a internet  
**Quando** clicar no botão de download  
**Então** deve estar disponível para leitura offline  

- [x] **Dado que** não queira mais ter o conteúdo salvo em meu telefone 
**Quando** clicar novamente no botão de download/downloaded  
**Então** não deve estar disponível para leitura offline  

- [ ] **Dado que** leio um conteúdo  
**Quando** realize scroll para baixo  
**Então** a appbar desaparece da tela  

- [ ] **Dado que** leio um conteúdo  
**Quando** realize scroll para cima  
**Então** a appbar reaparece na tela  

## Feedback

- [x] **Dado que** clico no botão de download  
**Quando** o download for realizado com sucesso
**Então** deve exibir a mensagem de conclusão  

- [x] **Dado que** clico no botão de downloaded  
**Quando** a exclusão for realizada com sucesso
**Então** deve exibir a mensagem de conclusão  

# Observações
Figma: https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=1550%3A11520

Referências: https://material.io/components/app-bars-bottom#behavior
https://developer.apple.com/design/human-interface-guidelines/ios/bars/toolbars/

**Comment by ItaloRod** [comment]
Plugin de apoio para o download desses conteúdos
https://github.com/react-native-community/async-storage

**Comment by ItaloRod** [comment]
é importante a atualização das postagens quando o usuário recuperar a internet, ou seja, manter uma atualização constante do conteúdo que o usuário tem salvo no celular.

**Comment by mbernardes19** [comment]
Foi decidido não implementar neste momento a funcionalidade de animação da barra inferior e deixá-la como melhoria a ser feita no futuro.
