### ISSUE TITLE
Problemas na validação do CPF

### ISSUE THREAD

**Issue by JefersonNSoares** [EscolaDeSaudePublica/isus-app#582]
# Descrição

- Quando faço o login no ID Saúde aparece uma tela pedindo para atualizar o cadastro, mas quando ponho o CPF não consigo avançar.

# Passo-a-passo para replicar

- 1° - Dado que venho de um cadastro do ID Saúde
- 2° - Tento fazer login no iSUS
- 3° - Sou redirecionado para tela de cadastro/integração
- 4° - Então não consigo finalizar o cadastro (o sistema informa que o cpf já está cadastrado)

# Ideia de solução

- Verificar cadastro previo no iSUS

**Comment by Laysacunha** [comment]
Este caso foi relatado por 2 usuário do iSUS. Foi verificado que esses usuários possuíam um cadastro no iSUS de um época e que não havia integração com o idSaude. Ambos usuários trocaram de e-mail e não conseguiam recuperar a senha do cadastro antigo.
Esses usuários possuem um cadastro no idSaude, e ao retornar ao iSUS (já integrado com idSaude) usuaram suas credenciais do idSaude. O iSUS busca as informações do idSaude e pede uma complementação de cadastro. Ao inserir o cpf, houve um conflito com o cadastro antigo na base do iSUS de uma época em que não havia integração com idSaude.
A solução para esses dois casos foi uma alteração na base de dados do iSUS para permitir que os usuários pudessem prosseguir com a atualização do cadastro.
