### ISSUE TITLE
Rever configurações de integração do OneSignal - Android

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-app#583]
# Objetivo

**Como** desenvolvedor do iSUS
**Quero** rever as configurações de integração do OneSignal
**Para** garantir funcionamento das notificações

# Contexto
OneSignal é um serviço para envio de notificações que já está sendo utilizado pelo app do iSUS. A documentação de configuração do OneSignal com React Native, disponível [aqui](https://documentation.onesignal.com/docs/react-native-sdk-setup#step-5-initialize-the-onesignal-sdk), solicita uma configuração para Android usando Gradle e isso não está feito.

# Escopo

- [ ] Seguir tutorial do OneSignal para React Native e rever todas as configurações

# Observações
- Recomenda-se seguir todo o tutorial para integração com Android para verificar integração de todos os passos.

**Comment by ericsonmoreira** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/iSUS---Refinamento-61672dbc32f1ce0015aa7eca/issues/EscolaDeSaudePublica/isus-app/583?planning-poker) with ZenHub @Laysacunha @janeteamaral @JefersonNSoares

**Comment by ericsonmoreira** [comment]
Para podermos descobrir qual o id do emulador basta colocar o seguinte código dentro do `useEffect` o App:

```javascript
OneSignal.getDeviceState().then(result => {
  console.log(result);
});
```

Isso irá imprmir no console um Json:

```json
{"hasNotificationPermission": true, "isEmailSubscribed": false, "isPushDisabled": false, "isSMSSubscribed": false, "isSubscribed": true, "pushToken": "cNkThNnpTIe8SP5tkO08FZ:APA91bH4YziLFX9CaOVeCIPP-m0op4xYxLjhE5FWkNjUzxFDqk6Oubs38-faR7G_FGNuGJVNZfRkZTeG8w6xQPGzIj8VmCq7KyKOtSYU-khe4Vco7ApLq5jK9xgd-K5VVOzTWWqIVXD-", "userId": "2803d1e5-5673-43ad-8ceb-aa36f72243e7"}
```

Agora basta procurar o usuário pelo campo `userId` no Onesignal e adicionar ele como usuário de teste.
