### ISSUE TITLE
Rever configurações de integração do iOS no OneSignal

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-app#584]
# Objetivo

**Como** desenvolvedor do iSUS
**Quero** rever as configurações de integração do OneSignal 
**Para** garantir funcionamento das notificações

# Contexto
OneSignal é um serviço para envio de notificações que já está sendo utilizado pelo app do iSUS. A documentação de configuração do OneSignal com React Native, está disponível [aqui](https://documentation.onesignal.com/docs/react-native-sdk-setup#step-5-initialize-the-onesignal-sdk). É necessário seguir todos os passos do tutorial e verificar se a configuração está adequada.

# Escopo

- [x] Seguir tutorial do OneSignal para React Native e rever todas as configurações

# Observações
- Recomenda-se seguir todo o tutorial para integração com iOS para verificar integração de todos os passos.

**Comment by ericsonmoreira** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/iSUS---Refinamento-61672dbc32f1ce0015aa7eca/issues/EscolaDeSaudePublica/isus-app/584?planning-poker) with ZenHub @janeteamaral @JefersonNSoares @Laysacunha
