### ISSUE TITLE
Levantamento técnico das notificações do OneSignal

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-app#587]
# Objetivo

**Como** pessoa desenvolvedora
**Quero** fazer um levantamento das notificações do oneSignal
**Para** prosseguir com o desenvolvimento da nova funcionalidade proposta na issue #368

# Contexto

Fazer refinamento técnico na issue #368 e propor divisão em tarefas menores e modelagem de solução.

# Escopo

- [x] Estudar sobre oneSignal
- [x] Refinar a tarefa tecnicamente e propor divisão em tarefas menores

**Comment by Laysacunha** [comment]
Levantamento culminou neste [documento.](https://docs.google.com/document/d/17Mu9dUexk7tTnpKQ9asufQ4vsF6-jMnfeAvo9kai9Po/edit?usp=sharing)

**Comment by ericsonmoreira** [comment]
# Estratégia escolhida

Depois de muito debater, a equipe decidiu usar uma abordagem simplificada usando os próprios eventos observados pela lib do `OneSignal`. Quando uma notificação é recebida pelo device do usuário, então elas serão salvas em um banco de dados que ficará no _device_ do usuário. O DB que iremos usar será o  RealmDB. Escolhemos ele pela sua facilidade de uso e implementação. 

## Funcionamento

Levando em consideração que o RealmDB esteja devidamente configurado, temos o seguinte _workflow_:

1. O site [do corona vírus ce](https://coronavirus.ceara.gov.br/) faz o _push_ de uma notificação para o `OneSignal`
2. O `OneSignal` recebe essa requisição, cria a mensagem e envia para os `devices` (aqui podem ser vários tipos, dês de browsers a dispositivos móveis)
3. As notificações são recebidas pelos dispositivos que tem o iSUS devidamente instalado
4. O app faz o tratamento dessas notificações salvandoas no DB.

Depois de salvas, as informações das notificações ficam disponíveis para que o app possa buscá-las e usá-las.

> **Obs.:** levamos em consideração apenas as notificações que vão para os aparelhos dos usuários do iSUS. Àquelas que são recebidas pelos browsers não está no nosso escopo.
