### ISSUE TITLE
Atualizar chave do iOS no OneSignal

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-app#592]
# Objetivo

**Como** desenvolvedor do iSUS
**Quero** atualizar a chave do iOS no OneSignal
**Para** garantir funcionamento das notificações

# Contexto
OneSignal é um serviço para envio de notificações que já está sendo utilizado pelo app do iSUS. 
É necessário acessar a conta do OneSignal e atualizar a chave do iOS que está expirada.
Imagens do erro de chave expirada:
![image](https://user-images.githubusercontent.com/20958122/143516290-dc848d70-ee91-4f00-a83b-c200e0ee611a.png)

# Escopo

- [x] Acessar conta do OneSignal e atualizar chave do iOS que está expirada.
- [ ] Documentação descrevendo o processo de atualização da chave iOS para o OneSignal.

# Observações

ex: Prototipo

**Comment by Laysacunha** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/iSUS---Dev-616733cf0d2aa30018f58088/issues/EscolaDeSaudePublica/isus-app/592?planning-poker) with ZenHub @janeteamaral @ericsonmoreira @JefersonNSoares

**Comment by ericsonmoreira** [comment]
[Aqui](https://app.zenhub.com/files/258529270/c2d362eb-310b-4acc-b9a3-e188a300cb45/download) temos um documento com o tutorial de como fazer essa atualização.
