### ISSUE TITLE
Implementar content loader nos links dos protocolos dentro do Manejo

### ISSUE THREAD

**Issue by wforte88** [EscolaDeSaudePublica/isus-app#60]
**COMO**
Usuário do iSUS

**EU QUERO**
saber se o app está carregando algum conteúdo

**PARA**
aguardar a disponibilidade do conteúdo e não confundir a carga com um erro

**OBSERVAÇÕES**
Incluir placeholder animado de carga de conteúdo
Exibir mensagem de erro quando houver indisponibilidade de rede

**Comment by wforte88** [comment]
**Referência**
https://medium.com/front-end-weekly/react-user-experience-tactics-placeholder-loading-content-fb734da0f9ae

**Comment by caetanooliveira** [comment]
conversei com matheus e para delimitar o escopo vamos começar por colocando loader nos links que temos dentro das informações do manejo

**Comment by caetanooliveira** [comment]
Objetivo:
Melhorar experiência do usuário enquanto espera carregamento de arquivos dentro do manejo.

Contexto:
O Manejo Clínico tem diversos links ao longo do fluxo de trabalho (paramentacao, triagem, orientacao inicial, internacao, etc). Hoje quando um usuário tenta acessar algum link mencionado nesses menus, o tempo de carregamento é longo (>3s). Queremos diminuir a fuga de usuários do app pela demora na carga desses cards.

Escopo: 
 - implementar loader nos links dentro do manejo

AC:
Dado que entrei em Manejo Clínico
Quando entro em UTI
e quero ver o "conforme protocolo"
enquanto carrega o acesso
Aparece um loader

**Comment by Junior-Shyko** [comment]
> conversei com matheus e para delimitar o escopo vamos começar por colocando loader nos links que temos dentro das informações do manejo

Vejo a necessidade também ao ler os artigos, pois fazemos uma requisição a api e as vezes pode chegar até 04s
