### ISSUE TITLE
Trocar imagem do banner (TOPO)  - NT Orientações para uso do Oselvamitir no APP ISUS

### ISSUE THREAD

**Issue by janeteamaral** [EscolaDeSaudePublica/isus-app#603]
Substituir o arquivo de imagem do destaque NT Orientações para uso do Oselvamitir, pois o atual se encontra pixelado. O link de destino continua o mesmo.
O Banner está hospedado: https://coronavirus.ceara.gov.br/wp-content/uploads/2022/01/banner-oseltamivir.png

**Comment by JefersonNSoares** [comment]
Realizado alteração do banner na produção.
