### ISSUE TITLE
Migração do app iSUS para Expo

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-app#604]
Expo é uma plataforma open-source para criar aplicativos universais com suporte a Andrdoid, iOS e web. Ele usa JS e React como base.
As vantagens da migração são para desenvolvimento e build.
Com ele é possível rodar a aplicação para o testes durante o desenvolvimento de forma mais rápida e prática.
É possível também que um membro do time esteja realizando uma alteração e envie um QRCode para que outro membro avalie as alterações em seu dispositivo de forma remota, por meio de uma estrutura oferecida pela plataforma Expo.
Essa é uma vantagem muito relevante para o iSUS visto o tempo gasto em realizar build, enviar para loja para conseguir efetivamente realizar testes.

Documentação: https://docs.expo.dev/

**Comment by ericsonmoreira** [comment]
Foi feito um estudo de testes dessa ferramenta no nosso projeto e concluímos que o **Expo** não é compatível.
