### ISSUE TITLE
Plano de Contingência Covid-19 [2022]

### ISSUE THREAD

**Issue by janeteamaral** [EscolaDeSaudePublica/isus-app#605]
Atividades conduzidas pelo Projeto "Plano de Contingência Covid-19 [2022]" em com Data Início e Fim predefinidas

**Comment by Laysacunha** [comment]
Não se refere a um épico. Tarefa fechada e label adicionada nas tarefas que estavam relacionadas com este épico para sinalizar que elas fazem parte do Plano de Contingência.
