### ISSUE TITLE
Verificação dos Testes - JEST

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-app#606]
Após atualização necessária do React Native para versão 0.66, os testes do app (JEST) pararam de passar.
Para atender as demandas prioritárias a versão está sendo enviada para GitHub sem verificação de testes.
É necessário realizar uma análise do motivo dessa quebra de testes e propor/realizar uma solução para tal.

**Comment by ericsonmoreira** [comment]
Atualmente, resolvemos grande parte dos erros no Jest que ocorriam durante os teste. Porém, foi identificado que os testes referentes ao `Firebase Analytics` estão ainda resultando em erros por que o mesmo não está enviando as informações. Então decidimos criar um novo card e associa-lo a essa atividade.

**Comment by ericsonmoreira** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/iSUS---Dev-616733cf0d2aa30018f58088/issues/EscolaDeSaudePublica/isus-app/606?planning-poker) with ZenHub @JefersonNSoares @Laysacunha
