### ISSUE TITLE
Alterar apresentação da Home do App ISUS.

### ISSUE THREAD

**Issue by janeteamaral** [EscolaDeSaudePublica/isus-app#608]
Alterar a Home do App iSUS com as seguintes mudanças:
- Subir o atual bloco “Força-Tarefa....” para acima do bloco “Linhas de Cuidados”
- Multar o título deste bloco para “Enfrentamento às Pandemias e Epidemias”
- Revisar a ordem de apresentação dos Cards: Vacinação / Notas Técnicas / Boletins / Plano de Contingência / Notificação de Casos / Fármaco-vigilância / Denúncias
- Publicar App nas duas plataformas

**Comment by JefersonNSoares** [comment]
Realizado alterações solicitadas.
