### ISSUE TITLE
Incluir Banner NT Oseltamivir  no APP iSUS

### ISSUE THREAD

**Issue by janeteamaral** [EscolaDeSaudePublica/isus-app#609]
Banner deve encaminhar para webview https://coronavirus.ceara.gov.br/project/nt-esp-sesa-01-2021-orientacoes-sore-uso-de-oseltamivir-para-tratamento-de-influenza/

**Comment by JefersonNSoares** [comment]
Adicionado Banner NT Oseltamivir no banco de dados. Banner já em produção.
