### ISSUE TITLE
Fazer o Deploy do aplicativo para as lojas

### ISSUE THREAD

**Issue by ItaloRod** [EscolaDeSaudePublica/isus-app#61]
TITULO
Fazer o menu lateral no aplicativo

EU QUERO
realizar o deploy da aplicação para suas respectivas lojas (Google play e / AppStore)

PARA
que o profissional de saúde possa utilizar o app e que possam dar seus feedbacks sobre o sistema.

**Comment by caetanooliveira** [comment]
Oi Italo,

fiquei pensando, será que não vale a gente dividir em duas tarefas pra ganhar velocidade?

**Comment by caetanooliveira** [comment]
uma pra google play e uma pra appstore
