### ISSUE TITLE
Analisar as configurações de transparência no rastreamento em APPS

### ISSUE THREAD

**Issue by janeteamaral** [EscolaDeSaudePublica/isus-app#611]
A Apple tem recusado o pedido de <App Tracking Transparency> contido em nosso App Isus. Tem sido justificada com a Mensagem a seguir:
==============================
**1 de jan de 2022 às 14:28
De Apple
5. 1.1 Legal: Privacy - Data Collection and Storage**
Guideline 5.1.1 - Legal - Privacy - Data Collection and Storage
....
We noticed your app includes App Tracking Transparency permissions requests, but it encourages or directs users to accept tracking. Specifically, your app directs the user to accept tracking in the following way(s):

- A message asks users to reconsider their decision after they deny permission.

Permission requests give users control of their personal information. It is important to respect their decision about how their data is used.
**Next Steps**
To resolve this issue, please revise the permission request process in your app so that the user is not inappropriately encouraged or directed to accept tracking.
If necessary, you may provide more information about why you are requesting permission to track before the request appears. If the user is trying to use a feature in your app that won't function without tracking, you may include a notification to inform the user and provide a link to the Settings app.
Resources
- Learn more about designing appropriate permission requests.
- See Frequently Asked Questions about the new requirements for apps that track users.
===============================================================
Segundo a APPLE, a partir do iOS 14.5 os apps terão que pedir permissão ao usuário para rastrear seus dados em apps.  Em Ajustes (IOS) o usuário poderá alterar suas preferências para qualquer app ou impedir que eles solicitem sua permissão.

![APPLE-RASTREAMENTO.jpg](https://images.zenhubusercontent.com/613b5ddea639049db13b61d9/6c88a6c4-f196-4a63-ae79-0026c41ed55b)

**Comment by JefersonNSoares** [comment]
Visto o retorno, no qual afirma que a mensagem apresentada ao solicitar acesso aos dados do usuário por meio da autorização do App Tracking Transparency não está de acordo com as exigências da Apple. Assim, baseado em exemplos de texto apresentados nas figuras a seguir, recomenda-se alteração do modal de apresentação/autorização do App Tracking Transparency no aplicativo isus.

<img src="https://user-images.githubusercontent.com/34108133/149155344-06fe7a7e-9288-4502-bef6-042e996c9497.jpg" width="200"/> <img src="https://user-images.githubusercontent.com/34108133/149155506-2c80a71d-145a-4d14-809d-665cdccd63c2.png" width="200"/>

# Sugestão:
## Alterar:

### App Tracking Transparency
Para efetuar o Cadastro, você deve habilitar nas configurações do seu dispositivo a permissão do App Track.

## Para:

### “App Tracking Transparency para ISUS” gostaria de permissão para rastreá-lo em aplicativos e sites de outras empresas. 

Para efetuar o Cadastro, você deve habilitá-lo nas configurações do seu dispositivo com a permissão do App Track. Seus dados serão usados para fornecer serviços personalizados. Se você não habilitar o “tracking” talvez não possamos fornecer determinadas experiências personalizadas, mas ainda podemos usar seus dados de acordo com nossa Política de Privacidade. Saiba mais sobre "tracking" na documentação de controle de privacidade da Apple.
