### ISSUE TITLE
Integração-Isus-IDSaude

### ISSUE THREAD

**Issue by janeteamaral** [EscolaDeSaudePublica/isus-app#617]

**Comment by janeteamaral** [comment]
Integrar bases com cadastro único entre os produtos ID-SAUDE / ISUS / MAPA / ESPVIRTUAL
- Análise dos cadastros inclusos unicamente no IDSaúde. Ocasião em que não existia a base iSUS.
- Observar esta visualização:
iSUS + ID Saúde - Cadastro Estadual de Profissionais de Saúde · Metabase (esp.ce.gov.br)
https://metabase.esp.ce.gov.br/public/dashboard/8f0d3137-c015-458c-adcb-f8373d40e2ed
Em 15/12/2021 – Sql direto na base IDSaúde havia 4366 registros na base (Count)
Em 18/01 – 3139 profissionais Cadastrados  e 4977 por Macro-unidade?

**Comment by Laysacunha** [comment]
Épico Duplicado
