### ISSUE TITLE
Integração iSUS-MAPA

### ISSUE THREAD

**Issue by janeteamaral** [EscolaDeSaudePublica/isus-app#622]

**Comment by janeteamaral** [comment]
Integração do Mapa da Saúde com a base de Usuários do Isus. A integração existente se dá apenas pelo login e senha do IDSaúde (Observar situação CPF)

Realizar estudo da Informação na ESP-CE, de forma a permitir que as entidades - Categoria Profissional, bem como, Especialidades -  tenham conceitos únicos dentro dos diferentes sistemas.

Integrar Usuários que realizaram QUIZ com a opção de emissão de certificados pelo Mapa da Saúde (SELOS)  (Não identificada a opção SELOS entre as _features_ disponibilizadas na versão Beta.

**Comment by Laysacunha** [comment]
Épico duplicado.
#372
