### ISSUE TITLE
Cadastro/incrição nos cursos da ESP Virtual por meio do iSUS

### ISSUE THREAD

**Issue by janeteamaral** [EscolaDeSaudePublica/isus-app#628]
# Objetivo

**Como** estudante da ESP Virtual 
**Quero** realizar meu cadastro/inscrição nos cursos da ESP Virtual por meio do iSUS
**Para** simplificar o processo de cadastro/inscrição

# Contexto

- Permitir que o Usuário realize seu cadastramento (Inscrição) direto no Moodle por meio do APP.

# Escopo

- [ ] escopo1

# Fora de Escopo

- fora_de_escopo

# Critérios de Aceitação

- [ ] titulo  
**Dado que** algo  
**Quando** faço  
**então** resulta

# Observações

ex: Prototipo

**Comment by Laysacunha** [comment]
Duplicada.
