### ISSUE TITLE
Criar seção de Residência Médica

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-app#632]
# Objetivo

**Como** pessoa usuária do iSUS
**Quero** ter uma seção de residência 
**Para** ter acesso a conteúdos específicos desta área,

# Contexto

Devemos criar no iSUS uma seção de residência com apresentação e links específicos, em alinhamento com Felicilab, Ascom e setor demandante.

# Escopo

- [x] alinhamento das necessidades
- [x] solicitar imagens para ASCOM
- [x] criar texto inicial
- [x] criar texto "Saiba Mais"
- [x] criar botão de entrada na home
- [x] criar botões internos para os links: SigResidência, SAGU e ESP Virtual
- [ ] criar página para o webview
- [ ] inserir alterações na sprint

# Critérios de Aceitação

**Dado que** entro no iSUS
**Quando** clico no botão residência
**então** acesso dados específicos da área

# Observações

ex: Prototipo

**Comment by danielgula** [comment]
@Laysacunha seguem as imagens:
![Residências em Saúde](https://user-images.githubusercontent.com/39468037/152019683-f80eb88b-8347-48df-8243-3578977efd80.svg)
![SAGU](https://user-images.githubusercontent.com/39468037/152019688-06008293-8777-48a3-b3bd-df647f6674bc.svg)
![Saiba Mais](https://user-images.githubusercontent.com/39468037/152019689-f8007527-3966-4e57-baa8-413dacdf2e0b.svg)
![SIG Residência](https://user-images.githubusercontent.com/39468037/152019692-f2517a18-4d0a-42e6-b9eb-5a6630aed977.svg)
![banner RES iSUS](https://user-images.githubusercontent.com/39468037/152019693-5a882b5f-f1d2-4037-b1d3-f63720c1a481.png)
![Banner RES iSUS](https://user-images.githubusercontent.com/39468037/152019696-669569c4-49e4-4c8b-8183-fc5eb6c4d831.svg)
![ESP Virtual](https://user-images.githubusercontent.com/39468037/152019698-45de0cfa-6749-48af-8ca4-e07148ee7565.svg)

**Comment by ericsonmoreira** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/iSUS---Dev-616733cf0d2aa30018f58088/issues/EscolaDeSaudePublica/isus-app/632?planning-poker) with ZenHub @JefersonNSoares @Laysacunha

**Comment by danielgula** [comment]
Segue texto inicial para a seção da residência:

RESIDÊNCIAS EM SAÚDE 

As Residências em Saúde constituem modalidade de ensino de pós-graduação destinada à profissionais da área da saúde, em formato de cursos de especialização, caracterizadas por treinamento em serviço, funcionando sob a responsabilidade de Instituições de Saúde. 
Trata-se de uma formação de especialista orientada pelos princípios e diretrizes do Sistema Único de Saúde (SUS), promovendo o fortalecimento da rede de atenção por meio da qualificação da força de trabalho alinhado com as necessidades regionais, reconhecendo a importância das conexões entre as práticas educacionais, a realidade social e necessidades assistenciais da população.

**Comment by Laysacunha** [comment]
Texto do Saiba Mais: 
[TEXTO PARA O I_SUS - RESMULTI e RESMED.docx](https://github.com/EscolaDeSaudePublica/isus-app/files/8026695/TEXTO.PARA.O.I_SUS.-.RESMULTI.e.RESMED.docx)

**Comment by ericsonmoreira** [comment]
@danielgula quais são os nome dos cards e os direcionamentos de cada um deles?

**Comment by danielgula** [comment]
@ericsonmoreira seguem as informações solicitadas:

Card Laranja - ficara no primeiro carrossel da home do iSUS com o nome Residências
Cards azuis na seguinte ordem:
SAGU - http://academico.esp.ce.gov.br/
ESP Virtual - http://espvirtual.esp.ce.gov.br/
SIG Residências - https://sigresidencias.saude.gov.br

**Comment by Laysacunha** [comment]
@danielgula alguns pontos relevantes:
1. Propomos melhoria na responsividade da página do SAGU (vide imagem abaixo).
2. Propomos melhoria na responsividade da página do SIG Residências (vide imagem abaixo).
3. A página Home do app na seção `Serviços SUS Ceará`  contém um card para ESP Virtual. Na seção de Residências também. Devemos manter ambos?
![image](https://user-images.githubusercontent.com/20958122/153432032-fe39dbb9-3da3-41aa-bcd0-a092e73f1e85.png)
![image](https://user-images.githubusercontent.com/20958122/153432062-d5ab2b5d-705f-47e8-9f60-2f5dac8ed681.png)

**Comment by danielgula** [comment]
> @danielgula alguns pontos relevantes:
> 
> 1. Propomos melhoria na responsividade da página do SAGU (vide imagem abaixo).
> 2. Propomos melhoria na responsividade da página do SIG Residências (vide imagem abaixo).
> 3. A página Home do app na seção `Serviços SUS Ceará`  contém um card para ESP Virtual. Na seção de Residências também. Devemos manter ambos?
>    ![image](https://user-images.githubusercontent.com/20958122/153432032-fe39dbb9-3da3-41aa-bcd0-a092e73f1e85.png)
>    ![image](https://user-images.githubusercontent.com/20958122/153432062-d5ab2b5d-705f-47e8-9f60-2f5dac8ed681.png)

Respondendo:
Tanto o SAGU como o SIG Residências não aplicativos de terceiros e não temos como realizar mudanças. Então eles devem ser acessados dessa forma ou abrirem o navegador do smartphone separadamente. Pergunto como isso está sendo feito nos outros links que levam para outros serviços e no caso repetir o mesmo procedimento.
Sobre o link ESP Virtual: sim, repete. Podemos ver mais adiante se o Moodle consegue abrir uma seção específica para a Residência e atualizamos os links.

**Comment by ericsonmoreira** [comment]
@danielgula a reprodução desses links está sendo feita da mesma maneira que fazemos nos outros links que o app usa. A questão ai é que essas páginas não tê responsividade. Acho melhor contactarmos eles mesmo sobre isso.

**Comment by danielgula** [comment]
@ericsonmoreira de acordo. Lembrando que SAGU é produto Felicilab, mas o Sig Residências é do governo federal e o contato deve, ao meu ver, ser institucional.
