### ISSUE TITLE
Banners estão com dimensionamento sem padronização

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-app#636]
# Descrição

Os banners estão sem padronização ou cortando parte da imagem. O comportamento pode variar de acordo com o aparelho.

# Passo-a-passo para replicar

Acessar o home do app. 

# Critérios de Aceitação
![photo_2022-01-26_10-29-40](https://user-images.githubusercontent.com/20958122/151172062-5e2b9404-1d91-4e94-aa13-905c61213cf6.jpg)
![photo_2022-01-26_10-29-47](https://user-images.githubusercontent.com/20958122/151172122-603e10f9-5e07-47bc-bc73-4b5242c646a0.jpg)
![photo_2022-01-26_10-29-57](https://user-images.githubusercontent.com/20958122/151172146-e865eb7c-ce2d-4c76-88ed-79a42a2daa88.jpg)

- [ ] Exibição adequada de banners
**Dado que** abro o app.
**Quando** estou na home.
**então** visualizo todos os banners sem cortes na imagem e com as bordas arredondadas.

- [x] Feedback de loading
**Dado que** abro o app.
**Quando** estou na home e os banners ainda não foram carregados.
**então** visualizo um spinner para dar o feedback que tem algo sendo carregado.

**Comment by ericsonmoreira** [comment]
## :rocket: Análise do problema

Verificamos que os problemas de dimensionamento que aparecem nas imagens dos banner acontece exatamente nas imagens que estão no formato SVG. O que acontece é que esses tipos de imagens não são nativamente suportadas. 

### :bug: Outros problemas relacionados

1. Algumas imagens em **SVG** são usadas em cards de postagens, como por exemplo no que aparecem na sessão do Elmo. Acarretando na não renderização dessas imagens no **app**.
2. Em **SVGs** é possível colocar estilização **CSS**. Nesse caso, pode acontecer um erro na versão **iOS** do **app** que até então não tínhamos achado solução. Esse erro causava problemas durante o desenvolvimento. O que é relatava na mensagem de erro é que uma fonte de texto específica não estava sendo encontrada - fonte _Soleto_. De fato essa fonte não é usada no projeto, mas ela vem junto com uma das imagens dos **Banners** dentro de uma tag **font-face**.

Conteúdo de uma das SVGs

```html
...
<font-face
    font-family="Soleto">
	<font-face-src>
		<font-face-name name="Soleto Bold"/>
	</font-face-src>
</font-face>
...
```

**Comment by Laysacunha** [comment]
Links dos banners em png:

https://coronavirus.ceara.gov.br/wp-content/uploads/2022/01/unnamed.png
https://coronavirus.ceara.gov.br/wp-content/uploads/2022/01/unnamed-1.png
https://coronavirus.ceara.gov.br/wp-content/uploads/2022/01/unnamed-2.png
https://coronavirus.ceara.gov.br/wp-content/uploads/2022/01/unnamed-3.png
https://coronavirus.ceara.gov.br/wp-content/uploads/2022/01/unnamed-4.png
https://coronavirus.ceara.gov.br/wp-content/uploads/2022/01/BANNER-ISUS.png
