### ISSUE TITLE
Melhorar retorno da busca (mais atuais primeiro)

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-app#638]
# Objetivo

**Como** pessoa usuária do iSUS
**Quero** realizar uma busca e visualizar os artigos mais atuais primeiro
**Para** me manter atualizado

# Contexto

A busca por conteúdos atualmente retorna os resultados em ordem crescente. Como se tratam de notícias e artigos é relevante que esse retorno seja em ordem decrescente de data, ou seja, que os artigos mais atuais apareçam antes.

# Escopo

- [x] implementar retorno do resultado da busca em ordem decrescente de data

# Critérios de Aceitação

- [x] retorno da busca 
**Dado que** estou na tela de busca
**Quando** digito um texto
**então** o primeiros artigos de resultado são os mais recentes

**Comment by ericsonmoreira** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/iSUS---Dev-616733cf0d2aa30018f58088/issues/EscolaDeSaudePublica/isus-app/638?planning-poker) with ZenHub @Laysacunha
