### ISSUE TITLE
Carregamento de nome do usuário não funciona ao finalizar cadastro

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-app#639]
# Descrição

- Quando terminamos o cadastro e somos direcionados para a página inicial, o nome não carrega. Só carrega após acessar a tela de Meu Perfil ou após fechar o app e abrir novamente.

# Passo-a-passo para replicar

- Realizar cadastro e observar o texto de recepção na tela inicial: Olá, [nome_da_pessoa]. O nome da pessoa é uma informação pessoal que não é carregada nesse cenário.

# Critérios de Aceitação

- [ ] Nome na tela Home
**Dado que** realizo um cadastro no iSUS
**Quando** sou direcionado para tela inicial ao enviar informações
**então** o texto de recepção `Olá, [nome_da_pessoa]` contém o nome inserido no cadastro.

**Comment by ericsonmoreira** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/iSUS---Dev-616733cf0d2aa30018f58088/issues/EscolaDeSaudePublica/isus-app/639?planning-poker) with ZenHub @JefersonNSoares @Laysacunha
