### ISSUE TITLE
Verificar chaves do iOS

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-app#644]
As chaves de acesso do iOS tem validade e se faz necessário verificação das datas de expiração das mesmas para cuidar dos processos administrativos de atualização.

Faz-se necessário também, verificar como funciona o processo de migração de chaves para novo dispositivo, considerando tempo de migração, possibilidade de perda de acesso até migração, valor de investimento entre outros itens.

Verificar também tempo de build do iOS usando o MacMini.

**Comment by Laysacunha** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/iSUS---Dev-616733cf0d2aa30018f58088/issues/EscolaDeSaudePublica/isus-app/644?planning-poker) with ZenHub @ericsonmoreira @JefersonNSoares

**Comment by ericsonmoreira** [comment]
# Conclusões

## Data de expiração

De acordo com o https://developer.apple.com/account/#!/membership/XT8X924G47 temos que a data de expuração da conta é **May 20, 2022**. Não colocaremos o `print` da página aqui pois nela tem informações sensíveis. 

## Processo de migração de chaves para novo dispositivo

Não conseguimos encontrar uma documentação sobre esse assunto.

## Build do iOS usando o MacMini

Por volta de 4 a 8 horas (variando de acordo com problemas de incompatibilidades que possam a aparecer).
