### ISSUE TITLE
Alterar experiência com check box no cadastro e adição de informações profissionais

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-app#646]
# Objetivo

**Como** pessoa usuária do iSUS 
**Quero** ver quantos itens selecionei no cadastro ou adição de informações profissionais
**Para** ter uma melhor experiência de usuário

# Contexto

- Na tela de cadastro, adição e edição de informações profissionais existe dois campos (um para setor de atuação e outro para especialidade) que permitem selecionar mais de uma opção - checkbox. A lista de opções é bem extensa, o que pode prejudicar a experiência.
- Na tela de edição de informações profissionais foi adicionado uma melhoria que informa para o usuário a quantidade de itens selecionados nesses campos. Dessa forma, é relevante replicar essa melhoria também nas telas de cadastro e de adição de informações profissionais.

# Escopo

- [ ] Alterar checkBox dos campos de especialidade e setor de atuação para informar quantidade de itens selecionados nas telas de cadastro e adição de informações profissionais

# Fora de Escopo

- Criar novo fluxo de cadastro.

# Critérios de Aceitação

- [ ] Tela de cadastro de informações profissionais 
**Dado que** estou realizando meu cadastro de informações profissionais
**Quando** seleciono itens no campo de especialidades ou setor de atuação
**Então** a quantidade de itens selecionados fica visível

- [ ] Tela de adição de informações profissionais 
**Dado que** estou adicionando informações profissionais
**Quando** seleciono itens no campo de especialidades ou setor de atuação
**Então** a quantidade de itens selecionados fica visível

**Comment by ericsonmoreira** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/iSUS---Dev-616733cf0d2aa30018f58088/issues/EscolaDeSaudePublica/isus-app/646?planning-poker) with ZenHub @fpontef

**Comment by ericsonmoreira** [comment]
Já corrigido na issue #718.
