### ISSUE TITLE
Centralizar documentação sensível 

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-app#647]
# Objetivo

**Como** pessoal desenvolvedora do iSUS
**Quero** centralizar documentação de acessos do iSUS de forma segura
**Para** acessar e gerenciar informações de forma fácil 

# Contexto

- É importante ter documentação de acessos e de rotinas internas ao time do iSUS centralizada e com fácil acesso aos membros do time. Isso facilita procedimentos do dia a dia, assim como também treinamento para novos membros. Dessa forma faz-se necessário a criação de um canal de centralização desses documentos.

# Escopo

- [ ] criar uma conta do notion com o email do isus `isus@esp.ce.gov.br`
- [ ] criar páginas com documentos e acessos e compartilhar com o time.

**Comment by ericsonmoreira** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/iSUS---Dev-616733cf0d2aa30018f58088/issues/EscolaDeSaudePublica/isus-app/647?planning-poker) with ZenHub @JefersonNSoares @Laysacunha

**Comment by ericsonmoreira** [comment]
@JefersonNSoares @Laysacunha como não temos como usar o email marcado acima, criei com uma conta com meu email institucional. Compartilhei com seus respectivos emails institucionais.

**Comment by ericsonmoreira** [comment]
# Resultado

Link para o documento https://www.notion.so/Chave-One-Signal-para-RN-iOS-a9d236346f134e049e34cef20b9dc477

## Conteúdo

1. [Atualização Qualiquiz & API](https://www.notion.so/Atualiza-o-Qualiquiz-API-b4cd710a7e044d1184fede05873acda4)
2. [Proteção de dados - iSUS](https://www.notion.so/Prote-o-de-dados-iSUS-a737d0f394bb4301bf3327de6757aefa)
3. [Sincronização de Dados](https://www.notion.so/Sincroniza-o-de-Dados-91d31438d216497a9f4ada8267353fbd)
4. [Chave One Signal para RN iOS](https://www.notion.so/Chave-One-Signal-para-RN-iOS-b0edfdcff8fb4d9c97afd7a3f96ad057)
