### ISSUE TITLE
Publicação das novas versões nas lojas da Apple e Google

### ISSUE THREAD

**Issue by ericsonmoreira** [EscolaDeSaudePublica/isus-app#648]
## Publicação das novas versões nas lojas da Apple e Google

> Versão: 3.20.13

- [x] Apple
- [x] Android

**Comment by Laysacunha** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/iSUS---Dev-616733cf0d2aa30018f58088/issues/EscolaDeSaudePublica/isus-app/648?planning-poker) with ZenHub @ericsonmoreira @JefersonNSoares

**Comment by ericsonmoreira** [comment]
Nova versão 3.20.14 disponível nas lojas. Ainda em testes. Assim que testarmos, colocamos a disposição dos usuários.
