### ISSUE TITLE
Textos não aparecem em algumas telas no Android 11

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-app#657]
# Descrição

- Textos não estão aparecendo na tela de Saiba Mais do Elmo e na tela de Exclusão de conta no Android 11.

# Passo-a-passo para replicar

- Acessar tela de Saiba mais do Elmo no Android 11 > Título acima da imagem não aparece. 
- Acessar tela do Elmo no Android 11 > Titulo Novidades ao lado esquerdo do botão Ver Mais não aparece. 
- Acessar tela de exclusão de conta -> Texto de orientação para exclusão de conta não aparece (acima do campo de texto).
- Acessar tela de denúncias -> texto abaixo da imagem.
- 

![image.png](https://images.zenhubusercontent.com/61673aa8c72e6da19ffd8c36/ceea06bc-d118-4db1-bb88-c7c8f21488b0)
![image.png](https://images.zenhubusercontent.com/61673aa8c72e6da19ffd8c36/b0360f1b-630b-4d81-b659-e5564febdfd6)
![image.png](https://images.zenhubusercontent.com/61673aa8c72e6da19ffd8c36/5010be30-4378-4221-a525-9814e745c82b)
![image](https://user-images.githubusercontent.com/20958122/152585008-9fcce540-bc74-4b35-bb5b-271f7bced92f.png)

# Ideia de solução

- Definir cor no estilo.

**Comment by ericsonmoreira** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/iSUS---Dev-616733cf0d2aa30018f58088/issues/EscolaDeSaudePublica/isus-app/657?planning-poker) with ZenHub @Laysacunha @JefersonNSoares
