### ISSUE TITLE
Erro ao baixar conteúdo

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-app#659]
# Descrição

Uma mensagem de erro aparece quando se tenta baixar um conteúdo. 
![image.png](https://images.zenhubusercontent.com/61673aa8c72e6da19ffd8c36/3aedc538-04dd-4cdc-bfd8-de06c2cf8cfc)

# Passo-a-passo para replicar

Acessar algum conteúdo das seções `Minha Saúde`, `Educação` ou `Pesquisa Científica` e clicar em `baixar`

# Critérios de Aceitação

- [ ] Baixar conteúdo
**Dado que** estou lendo uma postagem/conteúdo  
**Quando** clico em baixar conteúdo
**então** recebo uma mensagem de sucesso e o conteúdo fica salvo.

**Comment by ericsonmoreira** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/iSUS---Dev-616733cf0d2aa30018f58088/issues/EscolaDeSaudePublica/isus-app/659?planning-poker) with ZenHub @fpontef
