### ISSUE TITLE
Comportamento não esperado no cadastro/adição/edição de informações profissionais

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-app#660]
# Descrição

Na tela de cadastro/adição/edição de informações profissionais, quando escolho Área de atuação **Enfermagem** ou **Medicina**, é possível escolher especialidades para tais. Caso o usuário escolha uma área de atuação e selecione suas especialidades e logo em seguida mude a área de atuação e também selecione especialidades para a nova área, ao salvar, ficará armazenado as especialidades das duas áreas selecionadas. O vídeo a seguir exemplifica.

https://images.zenhubusercontent.com/258529270/1402b05f-08cb-4be0-b386-097a83cd9853/video_2022_02_04_11_19_38.mp4

# Passo-a-passo para replicar

- Acessar tela de cadastro, adição ou edição de informações profissionais 
- Escolher área de atuação `Enfermagem`
- Selecionar especialidades
- Mudar área de atuação para `Medicina`
- Selecionar especialidades
- Salvar cadastro e observar que foram armazenadas as especialidades selecionadas para Enfermagem e para Medicina.

# Ideia de solução

- Limpar seleção de especialidades ao trocar área de atuação.

# Critérios de Aceitação

- [ ] Limpeza de especialidades ao trocar área de atuação 
**Dado que** estou realizando o cadastro, adição ou edição de informações profissionais 
**Quando** altero área de atuação (e a área de atuação anterior seja Enfermagem ou Medicina)
**então** o campo de especialidades deve ter seu conteúdo zerado.

**Comment by ericsonmoreira** [comment]
Já corrigido na issue #718.
