### ISSUE TITLE
Criar espaço para registro de frequência dos participantes da RESMULTI no app

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-app#669]
# Objetivo

**Como** integrante da residência
**Quero** acessar uma área específica no app iSUS
**Para** realizar minha frequência nas aulas

# Contexto

- A Residência Multiprofissional (RESMULTI) controla a frequência dos participantes por meio de formulários preenchidos no Google Forms.  A cada turno de aula de uma disciplina o [formulário](https://docs.google.com/forms/d/1Vj2lXtKpkPtgp-21RhbgO4qWrk_4GO954awb-N3kavo/edit) deve ser respondido pelo estudante preenchendo nome, e-mail e função no programa.
- Ao final da disciplina, um trabalho manual de compilação é realizado para verificar o percentual de presença do participante que culmina em uma lista com os nomes dos que não obtiveram presença mínima de 85% da carga horária. Ao final do processo ainda há a demanda de inserir essas informações manualmente no SAGU.
- A proposta é que exista um espaço dentro da seção de Residências no app para que esses participantes realizem o registro de sua frequência em cada turno através de um clique.
- Ao final da disciplina, como MPV1 será entregue para coordenação da RESMULTI uma lista dos nomes e suas frequências.
- A proposta é que no futuro haja uma integração com o SAGU e que todo o processo se torne automatizado.
- Figma: https://www.figma.com/proto/FLKurtBDSBYAiYcS5xAPYC/iSUS?page-id=7271%3A8538&node-id=7271%3A8551&viewport=241%2C48%2C0.64&scaling=min-zoom&starting-point-node-id=7271%3A8551 

# Escopo UX

- [x] Disponibilizar as telas com base nas regras de frequência da Residência
- [x] Disponibilizar experiência

# Escopo

- [x] Adicionar card `Frequências` na tela da Residências
- [x] Criar tela com lista de disciplinas da Residência Multiprofissional
- [x] Criar tela de confirmação de presença**
- [x] Criar tela de histórico de presença

** Para essa tela devem ser consideradas as seguintes observações:
- A primeira caixa de seleção deve conter as opções: Comunitário e Hospitalar
- Caso o residente escolha a opção Comunitário uma caixa de seleção deverá ser habilitada contendo as opções de Programa de Residência para escolha do usuário. Deve-se também habilitar uma caixa de seleção com as opções de municípios.
- Caso o residente escolha a opção Hospitalar o comportamento deve ser similar ao descrito acima para a opção Comunitário.
- As listas de opções de residências e municípios encontram-se disponíveis [aqui](https://docs.google.com/forms/d/1Vj2lXtKpkPtgp-21RhbgO4qWrk_4GO954awb-N3kavo/edit?usp=sharing)
- As labels `Data` e `Turno` devem ser preenchidas automaticamente de acordo com a data atual e com o turno atual.
- o Botão `Marcar Presença` deve ser habilitado apenas em dois períodos diariamente durante os dias vigentes da disciplina: pela manhã, de 9h as 10h e pela tarde de 15h as 16h. 
- 

# Fora de Escopo

- integração com o SAGU

# Critérios de Aceitação

- [ ] Marcar presença
**Dado que** estou na tela para marcar presença
**Quando** a data ou horário não estiver no intervalo permitido
**então** o botão Marcar Presença fica desabilitado

# Observações
Protótipo:
https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=7271%3A8538

**Comment by RaniGub** [comment]
Protótipo disponibilizado.

**Comment by Laysacunha** [comment]
Tarefa realizada com base nas issues #678 #680 #681 #682 #683
