### ISSUE TITLE
Corrigir erro de digitação no Manejo Clínico

### ISSUE THREAD

**Issue by wforte88** [EscolaDeSaudePublica/isus-app#67]
**Manejo Clínico > Internação Hospitalar**
Alterar o termo SpO² para SpO₂ 

![spo2](https://user-images.githubusercontent.com/21333612/82107484-76f74e80-96fe-11ea-93c8-7ae3c79d7542.jpg)

**Comment by ItaloRod** [comment]
@wforte88 no estágio 2, também tem um "SpO²" .Troca ele também?
