### ISSUE TITLE
Corrigir a atualização das informações pessoais e profissionais do usuário

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-app#697]
## 🐛 Descrição

- Informações pessoais e profissionais não estão sendo atualizadas no app.

## Passo-a-passo para replicar

- Alterar informações pessoais ou profissionais no app e observar que a informação não foi atualizada. Ao deslogar e logar novamente a informação aparece atualizada. 

## Ideia de solução

- verificar atualização de informações no async storage

## Critérios de Aceitação

- [x] Atualização de informações pessoais ou profissionais
      **Dado que** estou na tela de meu perfil
      **Quando** altero minhas informações pessoais ou profissionais
      **então** as informações que alterei aparecem na tela do perfil

**Comment by ericsonmoreira** [comment]
Já corrigido na issue #718.
