### ISSUE TITLE
Escolher estratégia para refatoração dos formulários

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-app#698]
## 🚀 Objetivo

**Como** pessoa desenvolvedora do iSUS
**Quero** fazer um levantamento dos formulários existentes
**Para** criar uma estratégia adequada para a refatoração dos formulários

## Contexto

- Foi identificado que os formulários de cadastro e edição de informações pessoais e profissionais possuem diversas telas com estratégias distintas entre si. Esse comportamento ocasiona lentidão no cadastro (**[Melhorar lentidão na hora do cadastro. #555](https://github.com/EscolaDeSaudePublica/isus-app/issues/555)**), experiência ruim no preenchimento de informações (**[Melhorar a experiência da usuária finalizar o preenchimento de informações e o enter do teclado do dispositivo estar integrado aos botões do app #427](https://github.com/EscolaDeSaudePublica/isus-app/issues/427)**), erro na manipulação de informações profissionais(**[Comportamento não esperado no cadastro/adição/edição de informações profissionais #660](https://github.com/EscolaDeSaudePublica/isus-app/issues/660)**), problemas na tela de login, dentre outros pontos a serem melhorados (**[Trocar dropdown do cadastro de usuário para o dropdown nativo. #336](https://github.com/EscolaDeSaudePublica/isus-app/issues/336)**, **[Verificar experiência ao entrar com senha incorreta #560](https://github.com/EscolaDeSaudePublica/isus-app/issues/560)**, **[Alterar experiência com check box no cadastro e adição de informações profissionais #646](https://github.com/EscolaDeSaudePublica/isus-app/issues/646)**). Visto isso, faz-se necessário um levantamento de bibliotecas e estratégias utilizadas, estudo e implementação de uma abordagem consistente.

## Escopo

- [x]  Fazer levantamento da lista de formulários
- [x]  explicitar estratégias já implementadas e porque elas são falhas
- [x]  propor nova estratégia de comunicação e desenvolvimento
- [x]  criar lista de componentes a serem desenvolvidos

## Fora de Escopo

- realizar alterações no código não fazem parte dessa tarefa, apenas levantamento de informações e criação de propostas

**Comment by Laysacunha** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/iSUS---Refinamento-61672dbc32f1ce0015aa7eca/issues/EscolaDeSaudePublica/isus-app/698?planning-poker) with ZenHub @ericsonmoreira @fpontef

**Comment by ericsonmoreira** [comment]
Documentação gerada por essa atividade: https://www.notion.so/iSUS-8a6604c93c344fc1bc733f742e4da3dc

> Obs: tentamos gerar um arquivo PDF mas ficou muito grande para ser colocado aqui. Sem falar que podemos ter a necessidade de editar esse documento futuramente.
