### ISSUE TITLE
Implementar menu lateral

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/isus-app#7]
TITULO
Fazer o menu lateral no aplicativo

EU QUERO
Visualizar um menu lateral de acordo com o que está no protótipo

PARA
alinhar a estilização e obter uma melhor experiência do usuário.

basear-se no que está no protótipo do figma
![image](https://user-images.githubusercontent.com/20058085/82057784-3ebe2480-969a-11ea-9584-6cae3c718cf9.png)

**Comment by ItaloRod** [comment]
O detalhamento que percebi até o presente momento foi:
- [ ] Estilizar o Menu Lateral
