### ISSUE TITLE
Reduzir o tamanho do APP para android

### ISSUE THREAD

**Issue by ItaloRod** [EscolaDeSaudePublica/isus-app#70]
PRECISO
Reduzir o tamanho do aplicativo para Android

PARA
que não fique muito pesado no celular do cliente.

dica: Usar o App Bundle ao invés de gerar um  APK para a Loja

**Comment by uira** [comment]
https://developer.android.com/topic/performance/reduce-apk-size

**Comment by uira** [comment]
@mauricioholanda1 fez a magia e a parada tá com um terço do tamanho! Herói!!!
