### ISSUE TITLE
Criação de componente Select tipo Sanfonado (Accordion)

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-app#701]
## 🚀 Objetivo

**Como** pessoa desenvolvedora do iSUS
**Quero** criar componente genérico de seleção de texto do tipo Sanfonado
**Para** reutilizá-lo na biblioteca de formulários

## Contexto

- Os campos de seleção do app apresentam muitos dados a serem listados para escolha. Isso dificulta a usabilidade e resulta em uma experiência ruim para o usuário. Portanto, faz-se necessário a utilização do Select Sanfonado para campos com até 5 opções. É importante também, deixar claro para o usuário quais os itens selecionados em cada campo.

## Escopo

- [x]  criar componente base para seleção única
- [x]  criar componente base para seleção múltipla
- [x]  criar componente controlado por react-hook-form usando o componente base de seleção única
- [x]  criar componente controlado por react-hook-form usando o componente base de seleção múltipla
- [x]  usar componente chip da react-native-paper no componente de seleção múltipla

## Critérios de Aceitação

- [x]  Item selecionado - único
**Dado que** estou usando o componente de seleção único
**Quando** escolho uma opção
**então** a caixa de seleção retrai e visualizo o item selecionado no campo.
- [x]  Itens selecionados - múltiplo
**Dado que** estou usando o componente de seleção múltiplo
**Quando** escolho uma ou mais opções 
**então** visualizo de forma clara o(s) item(ns) selecionado(s)
- [x]  Remoção de item escolhido
**Dado que** estou usando o componente de seleção múltiplo
**Quando** clico no x do chip para remover o item selecionado
**então** ele desaparece da lista de itens selecionados
- [x]  Escolha de itens
**Dado que** estou na lista de itens do componente de seleção múltiplo
**Quando** clico num item que já estava selecionado
**então** a seleção desse item será removida

## Observações

- Para campos com até 5 opções utiliza-se campo de seleção do tipo sanfonado (Accordion) e com mais de 5 opções utiliza-se o tipo Modal.
- Componente chip: [https://callstack.github.io/react-native-paper/chip.html](https://callstack.github.io/react-native-paper/chip.html)

**Comment by Laysacunha** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/iSUS---Refinamento-61672dbc32f1ce0015aa7eca/issues/EscolaDeSaudePublica/isus-app/701?planning-poker) with ZenHub @ericsonmoreira @fpontef

**Comment by fpontef** [comment]
A organização dos Chips obedecem a ordem da lista (escolhido .sort() do javascript) e os chips vão para a próxima linha caso não caibam na linha de outro chip, onde podemos discutir outro comportamento caso necessário.
O estilo foi necessário e usei SyleSheet, sujeito a futuras atualizações.
Inserida uma propriedade "hasChips" com boolean default como true caso decida não usar o chip em determinada tela.
![Screenshot_SelectsAndChips.png](https://images.zenhubusercontent.com/62261afaf4c01ae8bebe9270/0b31c06f-707e-439b-9140-4cbfc4a54cdc)
