### ISSUE TITLE
Atualizar dependência AsyncStorage [@react-native-community/async-storage !!!Deprecated!!!]

### ISSUE THREAD

**Issue by ericsonmoreira** [EscolaDeSaudePublica/isus-app#704]
## 🚀 Objetivo

**Como** persona desenvolvedora
**Quero** atualizar uma dependência de desenvolvimento
**Para** manter um desenvolvimento sem erros e escalável

## Contexto

`AsyncStorage` é um sistema de armazenamento simples baseado em chave e valor (key-value), não criptografado, assíncrono e persistente, que é global para o aplicativo. Usamos o `AsyncStorage`  para persistir algumas informações no device da pessoa usuária. Porém, a atual dependência que estamos usando para essa funcionalidade está **depreciada**. Isso pode acarretar em problemas de segurança e desenvolvimento pois estaremos usando uma dependência que não está sendo mais mantida/atualizada.

- Lib depreciada que estamos usando: [@react-native-community/async-storage](https://www.npmjs.com/package/@react-native-community/async-storage)
- Lib atual: [@react-native-async-storage/async-storage](https://react-native-async-storage.github.io/async-storage/)

## Escopo

- [x] Remover lib depreciada
- [x] Instalar lib atualmente mantida pela equipe de desenvolvedores da lib antiga
- [x] Configurar a nova dependência de acordo com a [documentação](https://react-native-async-storage.github.io/async-storage/docs/install)
- [x] Promover ajustes onde se usa o `AsyncStorage`
- [x] Promover ajustes onde se usa o `AsyncStorage` nos testes (Jest) do app (vide [documentação](https://react-native-async-storage.github.io/async-storage/docs/advanced/jest) sobre isso)
- [ ] Alterar hook do AsyncStorage para o nativo da biblioteca

## Fora de Escopo

- Novas funcionalidades

## Critérios de Aceitação

- [ ] Remover dependência antiga
      **Dado que** estou desenvolvendo 
      **Quando** verifico quais bibliotecas estão sendo usadas nas dependências do projeto
      **então** a lib **@react-native-community/async-storage** não pode estar mais como uma dependência do projeto
 
- [ ] Instalar nova liv
      **Dado que** estou desenvolvendo 
      **Quando** verifico quais bibliotecas estão sendo usadas nas dependências do projeto
      **então** a lib **@react-native-async-storage/async-storage** deve estar como uma dependência do projeto

- [ ] Configuração da nova liv
      **Dado que** estou desenvolvendo 
      **Quando** verifico quais bibliotecas estão sendo usadas nas dependências do projeto
      **então** a lib **@react-native-async-storage/async-storage** deve estar devidamente configurada

- [ ] Promover ajustes onde se usa o `AsyncStorage`
      **Dado que** estou desenvolvendo 
      **Quando** implemento alguma funcionalidade que usa o `AsyncStorage` 
      **então** a lib **@react-native-async-storage/async-storage** deve estar sendo usada para isso

## Observações

> Para nossa alegria, os nomes das funções são iguais entre as lib. Sendo assim, esses ajustes não causarão muitos problemas para serem ajustados. Se trata apena de uma atualização bem vinda para manter o iSUS um app mais robusto e escalável.

> :rocket: Essa lib atual provê um `hook` que podemos usar para deixar o código mais performático e elegante. Vale a pena dar uma lida nessa documentação do `hook` [useAsyncStorage](https://react-native-async-storage.github.io/async-storage/docs/api#useasyncstorage).

**Comment by Laysacunha** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/iSUS---Refinamento-61672dbc32f1ce0015aa7eca/issues/EscolaDeSaudePublica/isus-app/704?planning-poker) with ZenHub @ericsonmoreira @fpontef
