### ISSUE TITLE
Reformulação do fluxo de login/tela de login

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-app#708]
## 🚀 Objetivo

**Como** pessoa desenvolvedora do iSUS
**Quero** ajustar estratégia de implementação do formulário de login
**Para** melhorar fluxo de desenvolvimento e promover padronização entre forms

## Contexto

- Refatorar código dessa tela/fluxo mantendo a mesma regra de negocio implantando as estratégias de formulários e de componentes criados para tal.

## Escopo

- [x]  alterar componente de texto já implementado
- [x]  manter as [regras de negócio](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=5699%3A2) da tela
- [x]  implementar biblioteca para garantir que o teclado não oculte os campos de texto para efetuar login

## Fora de Escopo

- criação de nova tela

## Critérios de Aceitação

- [x]  valida campo de e-mail
**Dado que** estou editando o campo de email
**Quando** mudo para o campo de senha
**então** automaticamente o campo valida o e-mail inserido e exibe a mensagem “Insira um e-mail válido” até que o texto do campo seja corrigido

- [x]  retira espaços do campo de email
**Dado que** estou editando o campo de email
**Quando** mudo para o campo de senha
**então** automaticamente os espaços extras no começo ou final são removidos

- [x]  teclado não sobrescreve campos de inserção
**Dado que** estou na tela de login
**Quando** edito o campo de email ou de senha
**então** o teclado não oculta (fica por cima) dos campos de login nem do botão `Fazer Login`.

- [x]  botão `FAZER LOGIN`desativado
**Dado que** estou na tela de login
**Quando** insiro um e-mail invalido
**então** o botão `FAZER LOGIN` fica desabilitado

- [x]  Teclado desaparece ao clicar em `FAZER LOGIN`
**Dado que** estou na tela de login
**Quando** preencho os campos email e senha e pressiono `FAZER LOGIN`
**então** o teclado desaparece e a tela fica completamente visível

- [x]  email e/ou Senha incorreto(s)
**Dado que** estou na tela de login
**Quando** pressiono `FAZER LOGIN` e meu login e/ou minha senha estão incorreto(s)
**então** uma mensagem com o conteúdo "Credencias incorretas! Tente novamente ou recupere sua senha" aparece na tela e os campos de email e senha ficam com bordas vermelhas até que alguma alteração seja realizada em algum dos campos o que faz a mensagem desaparecer e a coloração dos campos voltar ao original

- [x]  completar cadastro
**Dado que** estou na tela de login
**Quando** pressiono `FAZER LOGIN` e ainda não tenho cadastro completo no iSUS (já possuía cadastro realizado pelo idSaude ou pelo Mapa)
**então** sou direcionado para completar meu cadastro

- [x]  esquecer a senha
**Dado que** estou na tela de login
**Quando** pressiono `ESQUECI MINHA SENHA`
**então** sou direcionado para a tela de recuperar senha do idSaude

## Observações
----

**Comment by Laysacunha** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/iSUS---Refinamento-61672dbc32f1ce0015aa7eca/issues/EscolaDeSaudePublica/isus-app/708?planning-poker) with ZenHub @ericsonmoreira @fpontef

**Comment by ericsonmoreira** [comment]
Percebi agora que estou marcado nessa issue... pq mesmo? kkk

**Comment by Laysacunha** [comment]
Não sei...achei que era pq tava tu e o Fernando trabalhando rsrs

Em qua., 20 de abr. de 2022 17:38, Éricson Rogério Moreira <
***@***.***> escreveu:

**Comment by fpontef** [comment]
Eu marquei, é que o formulário foi iniciado na issue do zenhub 699. Passei as informações no PR:
As alterações iniciais foram realizadas na Feature/i699 add component campo texto #706
Link: https://github.com/EscolaDeSaudePublica/isus-app/pull/706
