### ISSUE TITLE
Iniciar a documentação do processo de Deploy do aplicativo para as lojas.

### ISSUE THREAD

**Issue by ItaloRod** [EscolaDeSaudePublica/isus-app#71]
### **Objetivo** 
**Eu como** pessoa desenvolvedora
**gostaria** de documentar os processos de deploy do aplicativo para as loja, tanto android, como iOS
**para que** seja possível que novos desenvolvedores que pegarem o aplicativo possam fazer o deploy da aplicação com maior facilidade.

### **Contexto** 
Implementamos uma atividade, #396, onde foi possível instaurar o processo de deploy automático em nosso projeto do app iSUS com o objetivo de o processo de deploy não ficar centralizado em apenas uma pessoa e não depender também de processos manuais, que sabemos que são sujeito a falhas. 

Com isso, com o sucesso da atividade citada, precisamos avançar para o próximo passo que seria a documentação de como está esse processo para que esse detalhamento fique claro para todas as pessoas desenvolvedoras envolvidas no projeto trazendo facilidade para absorver o conhecimento desse novo processo e aplica-lo com facilidade. 

### **Escopo**
- [x] Realizar a documentação do processo de deploy automático Android do projeto iSUS e deixar a documentação salva github wiki 
- [x] Realizar a documentação do processo de deploy automático iOS do projeto iSUS e deixar a documentação salva github wiki 

### **Critérios de Aceitação**
- [x] Visualizar a documentação do processo de deploy Android
**Dado que** eu acesso o github wiki do projeto iSUS 
**Quando** clico no tópico de Deploy da Aplicação
**Então** consigo visualizar a descrição detalhada do processo de deploy para Android que temos no projeto atualmente 

- [x] Visualizar a documentação do processo de deploy iOS 
**Dado que** eu acesso o github wiki do projeto iSUS 
**Quando** clico no tópico de Deploy da Aplicação
**Então** consigo visualizar a descrição detalhada do processo de deploy para iOS que temos no projeto atualmente 

### **Links Úteis**
[Github Wiki](https://github.com/EscolaDeSaudePublica/isus-app/wiki/Documenta%C3%A7%C3%A3o#deploy-da-aplica%C3%A7%C3%A3o)

**Comment by kurjes** [comment]
Tarefa bloqueada pois o processo de deploy esta sendo reformulado
