### ISSUE TITLE
Criação de thumb padrão para postagens do iSUS

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-app#710]
## 🚀 Objetivo

**Como** pessoa usuária
**Quero** visualizar um thumbnail padrão para quando não houver imagem destacada
**Para** ter uma melhor experiência visual no app

## Contexto

- Algumas postagens são criadas no wordpress sem imagem destacada, e por este motivo, quando são carregadas no iSUS aparecem apenas com a descrição do título e sem o thumbnail como é o padrão de exibição. Por este motivo faz-se necessário a criação de um thumbnail padrão para ser adicionado em postagens que não possuam imagem destacada. Atualmente, fica o espaço branco vazio. Vide imagem abaixo:
![image.png](https://images.zenhubusercontent.com/61673aa8c72e6da19ffd8c36/57fb93d2-2ffa-4b1d-b1a4-71691654b8c7)

## Escopo

- [ ] criar imagem de thumbnail padrão para quando não vier imagem destacada do wordpress

## Critérios de Aceitação

- [ ] imagem em todas as postagens
      **Dado que** estou na Home
      **Quando** clico em uma das seções do menu inferior (Minha Saúde, Educação ou Pesquisa)
      **então** todas as postagens contém uma imagem (seja padrão ou relacionada a postagem)

**Comment by caldy94** [comment]
Bom dia. Sugestão de imagem abaixo, vejam se está boa e verifiquem qual proporção eu envio a thumb. 
![sem-imagem-ícone](https://user-images.githubusercontent.com/101121073/162964881-3f7c57b3-0f7d-4ec3-8c11-36ece278d11c.png)

**Comment by pauloamoreira** [comment]
@caldy94 acredito que essa imagem não ocupe de forma adequada esse campo. sugiro fazer uma pesquisa mais ampla e sempre considerar os elementos visuais que já fazem parte da identidade do iSUS.

**Comment by caldy94** [comment]
imagem atualizada. 
![ícone-sem-imagem-destacada](https://user-images.githubusercontent.com/101121073/163190366-dbc389d1-d7bf-4065-9500-b4e55eaf29c2.jpg)

**Comment by caldy94** [comment]
segue também o modelo aplicado na tela 
![image](https://user-images.githubusercontent.com/101121073/163190762-50a9532f-8b51-4182-9c13-a5147489656f.png)

**Comment by caldy94** [comment]
Imagem e protótipos atualizados e aprovados por @pauloamoreira. Aguardando pareamento com @Laysacunha 

![verde-com-logo](https://user-images.githubusercontent.com/101121073/163238640-51685bce-7a02-4dbd-8933-854af7888988.png)

**Comment by caldy94** [comment]
![image](https://user-images.githubusercontent.com/101121073/163238710-924fdff5-4869-4272-8d36-8009eb7b21e2.png)

**Comment by caldy94** [comment]
![image](https://user-images.githubusercontent.com/101121073/163238807-7bd345cd-5e79-4f1e-a6cf-cb8cb26aa813.png)

**Comment by Laysacunha** [comment]
Último protótipo aprovado.

**Comment by ericsonmoreira** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/iSUS---Refinamento-61672dbc32f1ce0015aa7eca/issues/EscolaDeSaudePublica/isus-app/710?planning-poker) with ZenHub @fpontef @Laysacunha
