### ISSUE TITLE
Retirar susi do menu Lateral

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/isus-app#72]
Uirá reportou que no menu lateral há um botão com o nome de Susi e que leva para lugar nenhum. melhor solução é retirar

**Comment by caetanooliveira** [comment]
Objetivo:
Não permitir usuário visualizar Susi

Contexto:
Susi é um chatbot do SUS que queremos integrar com o iSUS, ele permite relação entre usuários e o sistema. Hoje em dia ainda não temos a integração feita e por isso, caso um usuário clique no Susi nesse momento, nenhuma ação acontece. Para finalizar o primeiro release que tem maior foco no Manejo Clínico e telas de Educação preferimos retirar o acesso à Susi, no futuro retomamos a integração e o acesso.

Notas:
Susi é o Assistente Digital do Sistema Único de Saúde, que também foi desenvolvida pelo NIT/ESP. Susi é um bot, criada para se relacionar com os usuários, gestores e trabalhadores do SUS, tanto em formato chatbot como um canal de comunicação com interface humana de interação. 

Critério de Aceite:
Android:
Dado que entrei no app
Quando entro no menu lateral
Não aparece opção de menu Susi
Porém ainda aparece o Sobre iSUS

iOS:
Dado que entrei no app
Quando entro no menu lateral
Não aparece opção de menu Susi
Porém ainda aparece o Sobre iSUS

**Comment by stratow** [comment]
No momento, esse link da SUSi é o voltar para home. Precisamos de um link desse no lugar caso contrário o usuário não tem como sair da tela de sobre. Seria ok trocar o nome da SUSi pra Home ou algo assim?

**Comment by caetanooliveira** [comment]
A pessoa pode voltar pra home clicando na parte em cinza da tela ou no botão voltar, certo?

De qualquer maneira acho bem essa solução, podemos colocar o ícone de "home" como o do menu inferior. Temos o ok de alguma pessoa UX?

**Comment by stratow** [comment]
O botão voltar depende do stack da aplicação, é possível estar num estado que você tenha que fechar e reabrir o app (eu descobri isso sem querer). Gostei da ideia de reuso do ícone
