### ISSUE TITLE
Textos não aparecem em algumas telas

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-app#722]
## 🐛 Descrição

- Alguns textos não estão aparecendo na tela de adição de informações profissionais e na tela de complementação de cadastro vindo do idSaude na etapa de adição de informações profissionais

## Passo-a-passo para replicar

- tela 1 (Adição de informações profissionais): Acessar a tela de Meu Perfil com um cadastro que não tenha adicionado informações profissionais -> Acessar o botão `Adicionar Informações` na seção de Informações Profissionais ->  chegar na tela de cadastro de informações profissionais e observar que faltam os textos de títulos dos campos.

- tela 2 (Tela de cadastro de informações profissionais no fluxo de complementação do cadastro vindo do idSaude): Realizar login, pela primeira vez no iSUS, com um usuário vindo do idSaude -> Clicar em `CONTINUAR` e seguir para tela de cadastro de informações pessoais -> preencher as informações corretamente e clicar em `CONTINUAR` -> chegar na tela de cadastro de informações profissionais e observar que faltam os textos de títulos dos campos.

## Ideia de solução

- Colocar o estilo direto nos textos

## Critérios de Aceitação

- [ ] tela de Adição de informações profissionais
      **Dado que**  estou na tela de Meu Perfil com um cadastro que não tenha adicionado informações profissionais
      **Quando** clico em `Adicionar Informações` na seção de Informações Profissionais
      **então** acesso a tela de cadastro de informações profissionais e todos os títulos dos campos aparecem corretamente

- [ ] Tela de cadastro de informações profissionais no fluxo de complementação do cadastro vindo do idSaude
      **Dado que**  estou na tela de cadastro de informações pessoais ao acessar pela primeira vez no iSUS, com um usuário vindo do idSaude
      **Quando** preencho as informações corretamente e clico em `CONTINUAR`
      **então** acesso a tela de cadastro de informações profissionais e todos os títulos dos campos aparecem corretamente

## Observações
Refatoração de cadastro em andamento, o que provavelmente resolverá esse problema.

**Comment by ericsonmoreira** [comment]
Já corrigido na issue #718.
