### ISSUE TITLE
retirar o acesso ao minha saúde

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/isus-app#73]
Uirá reportou que no menu lateral há um botão com o nome de minha saúde que por agora leva para lugar nenhum. melhor solução é retirar

**Comment by caetanooliveira** [comment]
Objetivo:
Não permitir usuário visualizar Minha Saúde

Contexto:
Minha Saúde é um menu de acesso pro profissional de saúde sobre autocuidado, com serviços psicológicos e acompanhamento. Atualmente ainda não há conteúdo para esse menu, então a fim de acelerar a primeira release, vamos retirar o acesso desse menu e deixar apenas os outros três funcionando. Os menus Home, Educação e Pesquisa seguem como opções.

Nota:
Ao retirar o menu Minha Saúde, devemos centralizar os três para que fiquei visualmente equilibrado.

Critério de Aceite:

Apagar o Minha Saúde:
Dado que entrei no app
Quando olho o menu inferior
Não aparece opção de Minha Saúde
Porém ainda aparecem os menus Home, Educação e Pesquisa 

Menus antigos continuam funcionando:
Dado que entrei no app 
Quando clico em qualquer menu inferior (Home, Educação e Pesquisa)
Consigo acessar seu conteúdo
