### ISSUE TITLE
Corrigir alertas no play console

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-app#737]
## 🐛 Descrição

- Ao subir a versão 3.22.0 no play console alguns alertas foram disparados e precisam ser analisados e corrigidos. 

## Passo-a-passo para replicar

- Acessar o play console e verificar os alertas que devem ser corrigidos

## Ideia de solução

- Verificar o email enviado para espce.apps para mais detalhes (em anexo em observações)

## Critérios de Aceitação

- [x] envio da versão sem alertas
      **Dado que** estou na tela de envio de versão do play console
      **Quando** promovo a versão
      **então** ela fica disponível para analise pela play console e em seguida disponível para loja.

## Observações

E-mail enviado: [https://app.zenhub.com/files/258529270/45fd2a53-0ac4-4501-9d3e-1e099e2d80e8/download](https://app.zenhub.com/files/258529270/45fd2a53-0ac4-4501-9d3e-1e099e2d80e8/download)

**Comment by ericsonmoreira** [comment]
Para resolver essa exigência da google, adicionamos uma conta e senha na seção "Credenciais" na play store. 

Como enviamos o app para revisão antes desse ajuste, o alerta ainda aparece, mas deve sumir no envio de uma próxima versão do.

Conta criada: `google@teste.com`.
