### ISSUE TITLE
Levantamento de custos do OneSignal

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-app#742]
## 🚀 Objetivo

**Como** gestor do iSUS
**Quero** fazer um levantamento de custos do OneSignal
**Para** me ajudar na tomada de decisões

## Contexto

- OneSignal é uma plataforma de notificações integrada ao site do coronavirus. Atualmente possuímos mais de 60 mil assinaturas com assinatura premium Growth. Nossa assinatura esta supensa temporariamente e faz-se necessário um levantamento de engajamento, número de usuários por dispositivo, entre outras informações relevantes para auxiliar na tomada de decisão.
 

## Escopo

- [ ] construir relatório do oneSignal com números e gráficos e proposta de melhoria com prós em contras em cada proposta.

**Comment by ericsonmoreira** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/iSUS---Refinamento-61672dbc32f1ce0015aa7eca/issues/EscolaDeSaudePublica/isus-app/742?planning-poker) with ZenHub @Laysacunha @fpontef

**Comment by ericsonmoreira** [comment]
[https://app.zenhub.com/files/258529270/0ad667e8-21a7-43f6-9b2d-2467e03d9d50/download](https://app.zenhub.com/files/258529270/0ad667e8-21a7-43f6-9b2d-2467e03d9d50/download)

Relatório preliminar.

**Comment by ericsonmoreira** [comment]
[https://app.zenhub.com/files/258529270/5da7caa5-d763-4b14-be44-9e450a90065a/download](https://app.zenhub.com/files/258529270/5da7caa5-d763-4b14-be44-9e450a90065a/download)

Relatório final.
