### ISSUE TITLE
Trocar tela de login do qualiquiz por tela do idSaude

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-app#747]
## 🚀 Objetivo

**Como** pessoa desenvolvedora do iSUS
**Quero** substituir a tela de login do qualiquiz pela tela do idSaude
**Para** manter uma padronização da experiência do usuário

## Contexto

A tela de login do `Qualiquiz` não está funcionando corretamente. Durante um refinamento técnico do time, identificamos que na realidade essa tela de login é antiga e não está de acordo com a nova padronização de login, que é pelo idSaude.

## Escopo

- [ ] substituir tela de login do qualiquiz pela tela do idSaude

## Critérios de Aceitação

- [ ] Login do qualiquiz
      **Dado que** estou na tela Home
      **Quando** clico em qualiquiz e não estou logado
      **então** sou redirecionado para tela do idSaude para fazer login

**Comment by ericsonmoreira** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/iSUS---Dev-616733cf0d2aa30018f58088/issues/EscolaDeSaudePublica/isus-app/747?planning-poker) with ZenHub @fpontef @Laysacunha

**Comment by victorMagalhaesPacheco** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Integraes-de-Produtos-622f81f2eaf7c70010bd1495/issues/EscolaDeSaudePublica/isus-app/747?planning-poker) with ZenHub @Junior-Shyko
