### ISSUE TITLE
Verificar Warnings do Fale Conosco

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-app#748]
## 🚀 Objetivo

**Como** pessoa desenvolvedora
**Quero** verificar warnings 
**Para** manter código limpo e consistente

## Contexto

- Durante o desenvolvimento alguns waornings ficam aparecendo. Um deles é o do Fale Conosco.
`Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.
Please update the following components: Dropdown`

## Escopo

- [ ] verificar porque ocorrerm warnings no Fale Conosco
- [ ] remover warnings do Fale Conosco

## Critérios de Aceitação

- [ ] Ambiente de desenvolvimento
      **Dado que** estou na ambiente de desenvolvimento
      **Quando** acesso o app
      **então** não aparece warning de Fale Conosco

**Comment by ericsonmoreira** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/iSUS---Dev-616733cf0d2aa30018f58088/issues/EscolaDeSaudePublica/isus-app/748?planning-poker) with ZenHub @fpontef @Laysacunha
