### ISSUE TITLE
Busca não funciona nas seções de Minha Saúde, Pesquisa e Educação

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-app#749]
## 🐛 Descrição

- o botão de busca que fica nas seções Minha Saúde, Educação e Pesquisa não está funcionando. Não direciona para a tela/campo de busca.

## Passo-a-passo para replicar

- Acessar Minha Saúde, Educação e Pesquisa e clicar na lupa de pesquisa

## Ideia de solução

-

## Critérios de Aceitação

- [ ] buscar 
      **Dado que** estou nas seções Minha Saúde, Educação ou Pesquisa
      **Quando** clico na lupa
      **então** posso digitar minha busca e obter o resultado.

## Observações

ex: Prototipo

**Comment by ericsonmoreira** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/iSUS---Dev-616733cf0d2aa30018f58088/issues/EscolaDeSaudePublica/isus-app/749?planning-poker) with ZenHub @fpontef @Laysacunha
