### ISSUE TITLE
Permitir a busca desde o Sobre iSUS

### ISSUE THREAD

**Issue by matheuscpl** [EscolaDeSaudePublica/isus-app#76]
Implementar as atualizações de layout da tela "Sobre o Isus" conforme protótipo no Figma no frame "Sobre"

**Comment by matheuscpl** [comment]
![Screenshot_44](https://user-images.githubusercontent.com/64148308/82223560-30ba0f00-98f9-11ea-9f63-b98ed1b2b4bf.png)

**Comment by caetanooliveira** [comment]
Objetivo: 
Permitir a busca desde o Sobre iSUS.

Contexto:
A tela de sobre não está permitindo a busca quando o usuário clica na lupa; tampouco permite digitar uma busca. O que deve ser feito nesse card é o mesmo comportamento da tela de manejo clínico, de quando o usuário clica na lupa, nós redirecionamos ele à página de busca habilitando o comportamento normal da busca.

Nota:
Dentro dessa issue já cabe a atualização do layout da tela de Sobre iSUS (invertendo as ordens)

AC:
Dado que entro no sobre ISUS
quando clico na lupa
posso buscar conteúdos.

Dado que abro o sobre iSUS
quando vejo o sobre
os ícones estão embaixo do texto
