### ISSUE TITLE
Disponibilizar área para frequência dos participantes da Oficina de Design de Serviços da ESP

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/isus-app#761]
## 🚀 Objetivo

**Como** pessoa participante da Oficina de Design
**Quero** acessar uma área do iSUS
**Para** marcar minha presença nos dias da Oficina

## Contexto

Com a proximidade da Oficina de Design de Serviços da ESP, é preciso criar um ambiente no iSUS que dê suporte a frequência das pessoas que irão participar do evento.

## Escopo UX

- [x] Disponibilizar experiência, telas e regras de negócio.

## Fora de Escopo

- fora_de_escopo

## Critérios de Aceitação

- [x] UX
      **Dado que** a pessoa acesse o iSUS
      **Quando** ela clica no banner da Oficina na Home do iSUS
      **então** ela consegue acessar uma área para marcar sua presença durante o evento

## Observações
https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=7886%3A8700

**Comment by RaniGub** [comment]
@ericsonmoreira boa tarde, havia conversado com a Laysa sobre essa issue na segunda-feira (13/05), não tenho certeza se ela lhe passou. Está quase finalizada, falta a imagem do banner, cabeçalho e ícone. Enquanto isso, você já pode visitar o figma e adequar a tarefa. É basicamente a mesma da frequência da Residência, mas ligeiramente mais simples.

**Comment by RaniGub** [comment]
Figma atualizado, falta só uma regra sobre abrir o site no view ou no navegador, estou conversando com o @uira

**Comment by RaniGub** [comment]
Imagem cabeçalho
![cabeçalho_Oficina_ISUS_411](https://user-images.githubusercontent.com/79097920/173896399-f7637253-513c-4606-a3ee-c5b7de803c56.jpg)

Imagem banner
![Banner_Oficina_ISUS_380](https://user-images.githubusercontent.com/79097920/173896684-423e95f6-37ad-4d5b-914f-690a56b70281.jpg)
 
O Corner Radius 8 da imagem do banner tá aplicada só no figma. Se precisarem deixo aqui também.

**Comment by ericsonmoreira** [comment]
@RaniGub estou vendo o figma. Mas pelo que a Laysa havia me passado, essas oficina não obedece a mesma regra de negócio que exite para aquela parte de frequência dos cursos da tela de Residência. Estou certo? Se for esse o caso, precisamos nos reunir para obtermos mais detalhes das regras de negócio.

**Comment by ericsonmoreira** [comment]
@RaniGub Coloquei alguns questionamentos no Figma. Dá uma olhadinha lá 🥺 (por favor...)

Valeu 🥇

**Comment by RaniGub** [comment]
Oi @ericsonmoreira respondi lá, falta só uma indicação sobe a abertura do site, falo logo mais pra vc.

**Comment by RaniGub** [comment]
Link do site irá abrir no navegador @ericsonmoreira
