### ISSUE TITLE
Adicionar em nossa documentação o passo à passo para gerar um .apk do app 

### ISSUE THREAD

**Issue by ericsonmoreira** [EscolaDeSaudePublica/isus-app#764]
## 🚀 Objetivo

**Como** pessoa testadora do iSUS
**Quero** instalar o iSUS no meu device antes dele estar disponível nos ambientes de testes das lojas de apps
**Para** poder testar em ambientes que não sejam o de produção

## Contexto

Uma das maneiras de testar um app é fazer esse teste em ambientes seguros e que não interfiram no ambiente de produção para não poluir nos ambiente com informações que não são reais ou interessantes. 

Porém, não é possível criar uma versão nova nos ambientes de testes das lojas que não seja a de produção. Devido a isso, a maneira que encontramos para que outros envolvidos, não desenvolvedores, possam testar o app antes dele estar disponível nas lojas de apps das plataformas é gerar um arquivo para que o app possa ser instalado no device da pessoa.   

Essa `issue` trata de adicionar na documentação dos desenvolvedores o passo à passo para gerar esse arquivo instalador (.apk para Android). 

## Escopo

- [ ] Criar uma documentação do passo à passo para gerar o `.apk` do app. 

## Fora de Escopo

- Novas funcionalidades

## Observações

> Sem critérios de aceitação. Apenas para melhorar nossa documentação.

**Comment by fpontef** [comment]
Segue documento: [Gerar_Bundle_Android_(APK)_com_ENVFILE_de_Desenvolvimento](https://app.zenhub.com/files/258529270/3c6e7f33-d373-4a01-bdb9-69effec74f42/download)
Com as seguintes seções:
- Gerar o APK instalável via gradlew
- Instalar no Emulador ou dispositivo reconhecido via ADB
- Gerar o AAB e instalar o APK via react-native
