### ISSUE TITLE
Permitir a busca dos usuarios no app

### ISSUE THREAD

**Issue by Junior-Shyko** [EscolaDeSaudePublica/isus-app#78]
Ícone a baixo

![Captura de tela de 2020-05-18 15-14-51](https://user-images.githubusercontent.com/7341117/82246031-5e638000-991a-11ea-826b-8e70728be364.png)

**Comment by victorMagalhaesPacheco** [comment]
PR: https://github.com/EscolaDeSaudePublica/isus-app/pull/93

**Comment by caetanooliveira** [comment]
victor vc permitiu a busca só na tela de manejo ou também na de sobre como comentamos na reuniao?

**Comment by caetanooliveira** [comment]
Critério de Aceite:

Permitir busca:
Dado que entro em Manejo Clínico e Sobre iSUS
Quando clico no item de busca
Posso escrever palavras
E ao escrever as três primeiras letras
Devem começar a aparecer conteúdos relacionados

Resultados:
Dado que escrevo “protocolo” na busca
Quando olho a lista de resultados
Ele retorna todos conteúdos do app que contenham “protocolo” no título

**Comment by victorMagalhaesPacheco** [comment]
@caetanooliveira foi adicionado o redirecionamento apenas na página de manejo clínico.

**Comment by caetanooliveira** [comment]
sera que mantemos nesse card o ajuste das outras telas ou criamos um novo? o que tu prefere?

**Comment by victorMagalhaesPacheco** [comment]
Melhor criar um novo card, pois esse já foi teoricamente foi finalizado na versão de lançamento para master hoje (ios e android).

**Comment by caetanooliveira** [comment]
certo
