### ISSUE TITLE
Estilizar Busca e Descrição da busca

### ISSUE THREAD

**Issue by Junior-Shyko** [EscolaDeSaudePublica/isus-app#79]
### **Tela de busca**

- [x] Tirar esse arredondamento das imagens, pq em todo o app elas estão sem e é bom manter esse padrão

- [x] Diminuir a margem do texto na direita pra ficar igual a margem da imagem, mais perto do fim da tela

- [x] Troca a cor do texto no header pra branco, pra melhorar a legibilidade 

- [x] Tira aquele botão de buscar dalí e coloca pro teclado, no lugar do enter

### **Descrição de busca**

- [x] Usar o componente genérico de descrição de conteúdo.

Colocar a estilização do figma: 
https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/mockup?node-id=112%3A0

**Comment by Junior-Shyko** [comment]
Atualmente está assim:
![Captura de tela de 2020-05-18 15-20-55](https://user-images.githubusercontent.com/7341117/82246514-36285100-991b-11ea-86bf-703f6dbef609.png)

**Comment by matheuscpl** [comment]
Teclado com esse comportamento:
![Screenshot_20200520-120639](https://user-images.githubusercontent.com/64148308/82472948-423d1b80-9a9f-11ea-9e7a-0654c30d0209.png)

**Comment by caetanooliveira** [comment]
Nota: 
Manter funcionamento que já está ativo em Educação.
Notas de estilo:
-Tirar esse arredondamento das imagens, pq em todo o app elas estão sem e é bom manter esse padrão 
- Diminuir a margem do texto na direita pra ficar igual a margem da imagem, mais perto do fim da tela 
- Troca a cor do texto no header pra branco, pra melhorar a legibilidade 
- Tira aquele botão de buscar Dalí e coloca pro teclado, no lugar do enter
- Trocar o texto que está ‘Buscar’ por ‘Buscar artigos’

**Comment by caetanooliveira** [comment]
Junior, adicionei a parte de troca do texto buscar que, tu podes validar com o matheus campelo se é esse o texto novo mesmo.

**Comment by matheuscpl** [comment]
**Atualização:** O texto de "Nenhuma informação encontrada" vai ficar pra situação em que realmente não houver resultado de busca.
Este, que se encontra na página inicial da busca será substituído por "Busque por conteúdos em Educação Permanete e Pesquisas Cientifícas."
![Busca](https://user-images.githubusercontent.com/64148308/82501527-cc02de00-9acb-11ea-830b-67e2680f15a0.png)
