### ISSUE TITLE
Mensagem de AppTrakinkgTransparency não está aparecendo nos dispositivos iSO versão 15.5

### ISSUE THREAD

**Issue by ericsonmoreira** [EscolaDeSaudePublica/isus-app#799]
## 🚀 Objetivo

**Como** pessoa usuária do **iSUS** dona de um dispositivo **iPhone** com **iSOS 15.5**
**Quero** poder confirmar/negar o uso de meus dados referentes à politica **AppTrakingTransparency**
**Para** compartilhar ou não das informações de uso do app

## Contexto

No envio da atual versão do app (3.22.4), depois de ajustarmos a mensagem de pedido de uso das informações de uso do app pelo usuário (vide issue #797) a app store recusou novamente a nova versão com a seguinte justificativa:

Thank you for your resubmission. Upon further review, we identified an additional issue that needs your attention. See below for more information.

If you have any questions, we are here to help. Reply to this message in App Store Connect and let us know. 

Guideline 2.1 - Information Needed

We're looking forward to completing our review, but we need more information to continue. Your app uses the AppTrackingTransparency framework, but we are unable to locate the App Tracking Transparency permission request when reviewed on iOS 15.5.

Next Steps

Please explain where we can find the App Tracking Transparency permission request in your app. The request should appear before any data is collected that could be used to track the user.

If you've implemented App Tracking Transparency but the permission request is not appearing on devices running the latest OS, please review the available documentation and confirm App Tracking Transparency has been correctly implemented.

If your app does not track users, update your app privacy information in App Store Connect to undeclare tracking. You must have the Account Holder or Admin role to update app privacy information.

Percebemos pela mensagem que o problema ocorre na versão 15.5 do iOS.

Essa issue se refere a atividade de corrigir esse problema para que possamos requisitar novamente a revisão da versão 3.22.4 do iSUS pela app store. 

## Escopo

- [x] Correção de bug para iOS 15.5 que não mostra a requisição de permissão de `apptrackingtransparency`
- [x] Reenvio do pedido de revisão da versão 3.22.4 do iSUS para a app store

## Fora de Escopo

- Novas funcionalidades

## Critérios de Aceitação

- [x] Mensagem no iOS 15.5
      **Dado que** instalo o app em um dispositivo com iOS versão 15.5
      **Quando** abro o app pela primeira vez
      **então** a mensagem de permissão de envio de informações de uso do app deve aparecer 

## Observações

> Esse já é um problema recorrente. Aconteceu na versão 15.4 do iOS. Acreditamos que será necessário a mudança da biblioteca que gerencia essa permissão pelos usuários. 

> [Política de apptrackingtransparency da app store](https://developer.apple.com/documentation/apptrackingtransparency)

**Comment by RaniGub** [comment]
Bom dia @ericabpinho. Acho que temos uma camada de narrativas aqui antes do Design. Vc pode alinhar com o @ericsonmoreira antes das telas serem disponibilizadas?

**Comment by ericsonmoreira** [comment]
@RaniGub de quais telas vc está falando?

**Comment by RaniGub** [comment]
@ericsonmoreira acho que acabei me confundindo aqui. Tinha feito uma leitura antes da daily e imaginei que seria necessário criar uma tela com o texto de concordância, quando na verdade já existe e não aparecia na AS. Por isso acionei o time de narrativas @ericabpinho. Mas a tarefa apareceu em nossa caixa de entrada, qual a requisição com o time de design?

**Comment by ericsonmoreira** [comment]
@RaniGub acho que era pra definir qual a mensagem exibir. Atualmente está assim: $(PRODUCT_NAME) requisita sua permissão para rastrear alguns dados a fim de promover uma melhor experiência no aplicativo. Essas informações são usadas para provermos conteúdos personalizados de acordo com seu perfil e para obter informações de quais conteúdos são mais acessados para que possamos prover uma melhor experiência.
