### ISSUE TITLE
Criar tela Caminho não encontrado

### ISSUE THREAD

**Issue by ericsonmoreira** [EscolaDeSaudePublica/isus-app#802]
## 🚀 Objetivo

**Como** usuária do iSUS
**Quero** ser redirecionado para uma tela de `Caminho não encontrado`
**Para** não causar um erro fatal durante o uso do app

## Contexto

Uma das coisas que pode acontecer durante nosso flow de atualizações das informações que são exibidas no iSUS é quando temos um banner que redireciona para uma tela interna no app. Como os banners podem ser adicionados com muita facilidade, pode acontecer de um banner novo tentar redirecionar para um tela interna do app que ainda não existe ou, até mesmo, por alguma fala, colocarmos um banner com um caminho errado, etc... Nesses casos, vai acontecer um erro fatal e o app fecha. Causando uma triste experiência ao usuário.

Uma maneira de resolver isso seria criar uma tela de `Caminho não encontrado` para o caso do usuário tentar acessar uma tela que ainda não exista no app. 

## Escopo

- [x] Desenvolver UI/UX da tela
![404](https://user-images.githubusercontent.com/64148308/184348974-29b50556-8839-4a0b-a89d-e1445fc5111e.png)

- [x] A tela deve ter avisos de que a tela não foi encontrada e que pode ser por causa do app estar desatualizado
- [x] A tela deve ter um botão para redirecionar o usuário para a loja do aplicativo para que ele possa ser atualizado, caso seja necessário.

## Fora do escopo

- Telas externas ao app.

## Critérios de Aceitação

- [x] Caminho não encontrado
      **Dado que** a pessoa usuária estiver usando o app
      **Quando** tentar acessar uma tela que não existe no app.
      **então** A tela de "Caminho não encontrado" de ser exibida

- [ ] Redirecionar para loja de aplicativos
      **Dado que** a pessoa usuária estiver na tela Caminho não encontrado
      **Quando** clicar no botão de redirecionamento para à loja
      **então** loja de apps correspondente devera aparecer

## Observação
PROTÓTIPO:  https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=8149%3A8837

ILUSTRAÇÃO: ![undraw_no_data_re_kwbl](https://user-images.githubusercontent.com/64148308/184349104-f23c926b-4d44-4f3c-aaa1-bf6fb4c5f5b3.svg)

**Comment by matheuscpl** [comment]
@ericsonmoreira Add aqui a UX da issue, qualquer coisa só falar 😉

**Comment by ericsonmoreira** [comment]
Valeu @matheuscpl 👍🏻
