### ISSUE TITLE
Verificar e resolver no OneSignal a expiração do certificado 31/12/2022

### ISSUE THREAD

**Issue by vicmagpac** [EscolaDeSaudePublica/isus-app#821]
**Contexto**

Recebemos um aviso via OneSignal sobre o restringimento do envio de notificações para o iSUS pela plataforma. Por exemplo, os novos "alertas" não estão sendo recebidos por pessoas usuárias de dispositivos Apple. Acessamos a área de configuração e aparece a mensagem de "certificados expirados em 31/12/2022".

**Comment by ericsonmoreira** [comment]
Realmente, o certificado havia expirado. Renovamos o certificado `.p12`.

![Captura de tela 2023-01-06 154636.png](https://images.zenhubusercontent.com/6107e6f995403630490497bf/17faff9f-442d-4038-878c-14b737740983)

Certificado válido até 05/02/2024
