### ISSUE TITLE
Realizar lançamento diário para play store e app store

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/isus-app#84]
Requisitos
- [x] Branch principal master
- [x] Todas as alterações devem ser lançadas diariamente de 17h até 22h.

Releases 19/05
Issues: #74 #75 #40 #43 

- [x] 19/05/2020 Android
- [x] 19/05/2020 iOS
- [x] 20/05/2020 Android
- [x] 20/05/2020 iOS
- [x] 21/05/2020 Android
- [x] 21/05/2020 iOS
- [x] 22/05/2020 Android
- [x] 22/05/2020 iOS
- [x] 25/05/2020 Android
- [x] 25/05/2020 iOS
- [x] 29/05/2020 Android
- [x] 29/05/2020 iOS
- [x] 31/05/2020 Android
- [x] 31/05/2020 iOS
- [x] 01/06/2020 Android
- [x] 01/06/2020 iOS
- [x] 02/06/2020 Android (2.5.1)
- [x] 02/06/2020 iOS
- [x] 03/06/2020 Android (2.6.0)
- [x] 03/06/2020 iOS
- [x] 03/06/2020 Android (2.6.1)
- [x] 03/06/2020 iOS
- [x] 04/06/2020 Android (3.0.2)
- [x] 04/06/2020 iOS
- [x] 05/06/2020 Android (3.0.4)
- [x] 05/06/2020 iOS
- [x] 08/06/2020 Android (3.0.5)
- [x] 08/06/2020 iOS
- [x] 10/06/2020 Android (3.0.6)
- [x] 10/06/2020 iOS
- [x] 11/06/2020 Android (3.1.1)
- [x] 11/06/2020 iOS
- [x] 12/06/2020 Android (3.1.2)
- [x] 12/06/2020 iOS
- [x] 15/06/2020 Android (3.1.3)
- [x] 15/06/2020 iOS (3.1.3)
- [x] 17/06/2020 Android (3.1.4)
- [x] 17/06/2020 iOS (3.1.5)
- [x] 19/06/2020 Android (3.1.5)
- [x] 19/06/2020 iOS (3.1.6)
- [x] 22/06/2020 Android (3.1.7)
- [x] 22/06/2020 iOS (3.1.7)
- [x] 24/06/2020 Android (3.1.9)
- [x] 24/06/2020 iOS (3.1.9)
- [x] 26/06/2020 Android (3.1.10)
- [x] 26/06/2020 iOS (3.1.10)
- [x] 29/06/2020 Android (3.1.11)
- [x] 29/06/2020 iOS (3.1.11)
- [x] 02/07/2020 Android (3.2.0)
- [x] 02/07/2020 iOS (3.2.0)
- [x] 08/07/2020 Android (3.3.0)
- [x] 08/07/2020 iOS (3.3.0)
- [x] 09/07/2020 Android (3.3.1)
- [x] 09/07/2020 iOS (3.3.1)
- [x] 13/07/2020 Android (3.3.2)
- [x] 13/07/2020 iOS (3.3.2)
- [x] 16/07/2020 Android (3.3.3)
- [x] 16/07/2020 iOS (3.3.3)
- [x] 17/07/2020 Android (3.4.0)
- [x] 17/07/2020 ios (3.4.0)
- [x] 20/07/2020 Android (3.5.0)
- [x] 20/07/2020 Ios (3.5.0)
- [x] 22/07/2020 Android (3.5.2) - codePush
- [x] 22/07/2020 Ios (3.5.2) - codePush
- [x] 23/07/2020 Android (3.6.0)
- [x] 23/07/2020 Ios (3.6.0)
- [x] 23/07/2020 Android (3.6.1)
- [x] 23/07/2020 Ios (3.6.1)
- [x] 23/07/2020 Android (3.6.2) - codePush
- [x] 23/07/2020 Ios (3.6.2) - codePush
- [x] 23/07/2020 Android (3.7.0)
- [x] 23/07/2020 Ios (3.7.0)

**Comment by ItaloRod** [comment]
Obs.: 
- Abrir release para atualizar a master segundo a develop.
- Alterar a versão no arquivo ```package.json``` , o ```versionName``` e ```versionCode``` em ```android/app/build.gradle```.

**Comment by victorMagalhaesPacheco** [comment]
Lançamento:  Android (3.0.2)

**Comment by victorMagalhaesPacheco** [comment]
Lançamento android 3.0.5 (teste interno).

**Comment by victorMagalhaesPacheco** [comment]
Lançamento android 3.1.0 (teste interno).

**Comment by victorMagalhaesPacheco** [comment]
Lançamento android 3.1.2 (teste interno).

**Comment by victorMagalhaesPacheco** [comment]
Lançamento android 3.1.3 (teste interno).

**Comment by victorMagalhaesPacheco** [comment]
Lançamento android 3.1.4 (teste interno).

**Comment by uira** [comment]
@victorMagalhaesPacheco Tá faltando as mudanças nesse comentário.... importante resumir

**Comment by victorMagalhaesPacheco** [comment]
Lançamento android 3.1.5 (teste interno).
Alterações:
- troca a url do pdf do manejo clínico

**Comment by victorMagalhaesPacheco** [comment]
Lançamento android 3.1.7 (teste interno).
Alterações:
- Estilizado o header, colocando condição de tamanho de tela
- Alteração no drawer menu
- Colocado estilo no menu lateral e colocado limitação de caracteres do titulo da webview

**Comment by victorMagalhaesPacheco** [comment]
Lançamento android 3.1.9 (teste interno).
Alterações:

 -  “Adicionada a paginação das buscas”

**Comment by victorMagalhaesPacheco** [comment]
Lançamento android 3.1.10 (teste interno).
Alterações:

- Atualização e refatoração manejo

**Comment by victorMagalhaesPacheco** [comment]
Lançamento android 3.1.11 (teste interno).
Alterações:

Feedback por onesignal

**Comment by victorMagalhaesPacheco** [comment]
Lançamento android 3.2.0 (teste interno).
Alterações:

- Implementação codePush (android e ios)
- Adicionar tratamento de erro no anexo da imagem

**Comment by ItaloRod** [comment]
Lançamento android 3.3.0 (teste interno).
Alterações:
* Permitir usuário baixar conteúdos de educação e pesquisa

**Comment by ItaloRod** [comment]
Lançamento Android e iOS 3.3.1 (teste interno).
Alterações:

    Atualização do manejo Clínico

**Comment by victorMagalhaesPacheco** [comment]
Lançamento Android 3.3.2 (teste interno e beta).
Alterações:

- notificação iOS Webviews
- notificação banner manejo

**Comment by victorMagalhaesPacheco** [comment]
Lançamento Android 3.3.2 (teste interno e beta).
Alterações:
-  Troca do botão da telemedicina pelo do feedback

**Comment by ItaloRod** [comment]
Lançamento 3.4.0 (teste interno de ambas as plataformas).
Alterações:

    Sinaliza o usuário onde ouve atualizacoes do manejo clínico #180

**Comment by victorMagalhaesPacheco** [comment]
Lançamento 3.5.0 (teste interno de ambas as plataformas).
Alterações: barra inferior para visualizar versão do manejo clinico

**Comment by ItaloRod** [comment]
Lançamento 3.6.0 (Teste interno ).
Alterações: 
* Permite agora que usuários emitem um alerta de falta de EPI em sua unidade de saúde;
* Novas atualizações para o manejo clínico, serão notificadas;
* Correção de bugs e melhorias;

**Comment by ItaloRod** [comment]
Lançamento 3.6.1 (Teste interno).
Alterações:

* Correção campo e-mail no fale conosco 
* Correção da abertura do teclado no fale conosco

**Comment by ItaloRod** [comment]
Lançamento 3.6.1 (Teste interno em ambas as plataformas) - CodePush.
Alterações:

* Permitir compartilhar o link de acesso ao iSUS através do aplicativo .
* Grava  o endereço de email depois do primeiro Feedback do Fale conosco.

**Comment by ItaloRod** [comment]
Lançamento 3.7.0 (Teste interno em ambas as plataformas).
Alterações:

* Adicionada a tela de informações do SUS no Ceará.
* Ajustes no topo e no feedback da tela de Fale conosco e do Alerta de EPI
* Correção de problema no carregamento de links do manejo clínico.
