### ISSUE TITLE
Desabilitar chatbot fullscreen no mobile

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/isus-app#87]
TÍTULO
Desabilitar chatbot fullscreen no mobile.

EU QUERO
Realizar o acesso dos serviços via webview dentro do aplicativo e ao acessar o conteúdo, não apararer o chatbot em fullscreen.

PARA
Acessar o conteúdo especificado sem distrações como é o caso do chatbot que automaticamente sobrepõe todo o conteúdo.

OBSERVAÇÕES
Essa alteração é diretamente no plugin do chatbot no wordpress.

**Comment by uira** [comment]
Retirando código do [Body do Divi](https://coronavirus.ceara.gov.br/wp-admin/admin.php?page=et_divi_options):

````
<!-- Chatbot -->
<script>
  WebChat.default.init({
    selector: "#webchat",
    initPayload: "start",
    channelUuid: 'f4ef120d-0b56-47f3-872d-dcdf73f6ee7d',
    host: 'https://new.push.al',
    socketUrl: "https://socket.push.al",
    title: "Plantão Coronavírus",
    showFullScreenButton: true,
    inputTextFieldHint: "Escreva aqui...",
    openLauncherImage: 'https://ilhasoft-webchat.s3-eu-west-1.amazonaws.com/ceara/sig_ceara2.png',
    profileAvatar: 'https://ilhasoft-webchat.s3-eu-west-1.amazonaws.com/ceara/sig_ceara2.png',
	tooltipPayload: "start",
    tooltipDelay: 1800,
	  
	  params: {
	  images: {
		  dims: {
			  width: 300,
			  height: 200
		  }
	  },
	  storage: "local"
	}
  })

  function isMobile() {
    try { 
        document.createEvent("TouchEvent"); 
        return true; 
    } catch(e) { 
        return false; 
    }
  }
  function openChat() {
    if (!WebChat.isOpen() && !isMobile()) {
        WebChat.open();
    }else{
        WebChat.close();
    }
	   
  }

WebChat.open();
	
	if (document.getElementById("webchat-clique-aqui")) {
	    document.getElementById("webchat-clique-aqui").addEventListener("click", function () {
            WebChat.toggle()
        })	
	}
	
	if (document.getElementById("webchat-icon-clique-aqui")) {
	    document.getElementById("webchat-icon-clique-aqui").addEventListener("click", function () {
            WebChat.toggle()
        })	
	}

</script>
````

**Comment by uira** [comment]
@wforte88 agora que o chatbot está desabilitado, são dois grupos de demandas:
## 1. Customizar chatbot
- [ ] Configuração para habilitar apenas em áreas/páginas específicas;
- [ ] Otimização do CSS e javascript para não abrir sozinho

## 2. Habilitar
- [ ] Habilitar na Home (abrir APENAS mediante clique no banner ou na "bolinha" que NÃO DEVE abrir sozinha em NENHUMA HIPÓTESE)
- [ ] Habilitar na Home e Páginas internas do Cidadão

**Comment by wforte88** [comment]
@victorMagalhaesPacheco @Junior-Shyko @jacsonp Reabilitei o código do chat no Theme Builder para poder desabilitar a exibição no mobile e habilitar apenas nas páginas do Cidadão. Contudo, o código deixou de responder e o chatbot não está carregando de forma alguma. Poderiam me ajudar a ver se é algo com o js?
Local: Divi > Theme Builder > Cabeçalho Global > Módulo Chatbot
Utilizar visualização em wireframe para ver o bloco.
![wireframe](https://user-images.githubusercontent.com/21333612/82546618-c4285580-9b2e-11ea-9ecd-8016d512b10e.png)
