### ISSUE TITLE
Permitir usuário ler novos conteúdos do Wordpress - Android

### ISSUE THREAD

**Issue by caetanooliveira** [EscolaDeSaudePublica/isus-app#88]
**Objetivo:**
Gerar alerta para novos conteúdos do Wordpress

**Contexto:**
Para cada novo projeto (post) cadastrado no Wordpress, do lado das configurações do projeto na área administrativa do wordpress, aparece um botão de "Enviar notificação", caso habilitado essa opção, o Onesignal envia as notificações para os clients, que hoje em dia são somente os navegadores. Deveríamos adicionar os apps como clients no OneSignal também. Os apps ainda não têm disponível o Minha Saúde, deixaremos os alertas de conteúdos desse "menu" de fora. 

**Nota 1:** 
Deverão ser alertados via push notification os usuários, toda vez que um novo conteúdo for gerado no Wordpress para os temas: Educação, Pesquisa Científica, Serviços e Covid-19. Deve ser enviado um push-notification e gerar um alerta no app.

**Alcance:**
android

**Fora de Escopo:**
Gerar alerta dentro do app

**Critérios de Aceite:**
(Gerar alerta Minha Saúde)
Quando há um novo post dos portais Educação, Pesquisa Científica, Serviços e Covid-19
e o cadastrador decide "enviar notificação"
o usuário recebe um push notification

Quando o usuário clica no push notification
Dado que é um conteúdo de educação
Ele pode visualizá-lo dentro do app

(Não gerar alerta Minha Saúde)
Quando há um novo post dos portal Minha Saúde 
e o cadastrador decide "enviar notificação"
**não** gera um push no dispositivo do usuário

(Manter funcionamento web)
Quando há um novo post dos portal Minha Saúde, Educação, Pesquisa Científica, Serviços e Covid-19
e o cadastrador decide "enviar notificação"
gera um alerta pros navegadores

**Comment by matheusbernardes19** [comment]
Descobrimos hoje pelo seguinte artigo que que não é possível testar push notifications em emuladores, celulares físicos são necessários: https://hackernoon.com/send-push-notifications-via-onesignal-by-building-a-react-native-app-a-how-to-guide-pyag322r

Com isso, conseguimos cadastrar o meu celular Android como celular de teste no One Signal e enviamos uma notificação de teste com sucesso:

![WhatsApp Image 2020-05-22 at 18 57 38](https://user-images.githubusercontent.com/65406096/82712900-98f15380-9c5f-11ea-81c5-a86ea8e5ac61.jpeg)

**Comment by matheusbernardes19** [comment]
Durante a configuração do app para utilizar o serviço do One Signal, tivemos um erro relacionado a ["multidex" no Android](https://developer.android.com/studio/build/multidex)

Resolvemos esse erro mudando a propriedade `minSdkVersion` do arquivo `android/build.gradle` de `16` para `21`. Se deixarmos a versão mínima permitida do SDK em 21, o erro some. Porém, se quisermos manter em `16`, teremos que aplicar as [mudanças descritas neste tutorial](https://developer.android.com/studio/build/multidex).

Então eu queria levar essa questão aqui para saber se manter a versão mínima em 16 é mesmo necessária ou não, até que ponto isso poderia (ou não) afetar a disseminação do aplicativo.

**Comment by amaurymeireles** [comment]
Esse card vai englobar so o push notification. A tela de alerta sera englobada em outro card
