### ISSUE TITLE
Implementar tela de busca

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/isus-app#9]
TÍTULO
Implementação tela de busca

EU QUERO
Realizar uma busca de todos os projetos com um determinado termo

PARA
Ajudar no processo de acompanhamento de informações sobre covid19.

OBSERVAÇÕES
Ao acessar o aplicativo, o usuário pode acessar a tela de busca dos projetos.

Endpoint: https://apiisus.inova.esp.br/api/projetos?search=termo

**Comment by matheuscpl** [comment]
Assim como estava especificado no layout no frame "Busca", esta é a tela de busca. Se houver algum impedimento em relação ao framework usado pode falar comigo no slack ou telegram 👍 
![Busca](https://user-images.githubusercontent.com/64148308/82333455-2103fe80-99bd-11ea-8185-22308e903061.png)

**Comment by victorMagalhaesPacheco** [comment]
Como está o andamento dessa atividade? Faltando algum teste no ios ou android?
