### ISSUE TITLE
Ajustar os certificados para Build a Loja no iOS

### ISSUE THREAD

**Issue by ItaloRod** [EscolaDeSaudePublica/isus-app#94]
EU QUERO
Ajustar os certficados e perfis para o build das lojas no site da AppleStore Connect. 

PARA
que o desenvolvedor possa utilizar somente um perfil e somente os seus respectivos certificados (Desenvolvimento e Distribuição)

Atualmente cada desenvolvedor que fazia o deploy para o iOS, gera um Provisioning Profile e dois certificados (Desenvolvimento e Distribuição). Essa organização gera muitos desses elementos e acaba confundindo o desenvolvedor novo durante o deploy. O Objetivo é unificar o perfil e os certificados para todos os desenvolvedores.

Épico #232 necessário para facilitar novos devs poderem realizar deploy do app

**Comment by kurjes** [comment]
@ItaloRod o cenário continua o mesmo? Se sim  tratar como dívida técnica e priorizar junto ao time, talvez trazer novamente a discursão sobre o deploy automatizado

**Comment by ItaloRod** [comment]
> @ItaloRod o cenário continua o mesmo? Se sim tratar como dívida técnica e priorizar junto ao time, talvez trazer novamente a discursão sobre o deploy automatizado

Preciso conversar com o @cairano  sobre o processo de deploy automatizado, visto que ele implementou parte do iOS. Podemos trazer a tona ao realizar a configuração. Para tal preciso me reunir com ele antes para verificarmos.

**Comment by kurjes** [comment]
A prioridade é alta mas não existe visibilidade se ainda se faz necessário, @ItaloRod vai dar visibilidade a medida que a tarefa de deploy automatizado andar.

**Comment by daianefreira** [comment]
Issue fechado sem desenvolvimento, pois conforme validação realizada com Italo nao fazia mais sentido.
