### ISSUE TITLE
Permitir usuário Salvar PDF do Manejo Clínico

### ISSUE THREAD

**Issue by caetanooliveira** [EscolaDeSaudePublica/isus-app#95]
Objetivo:
Permitir usuário Salvar PDF do Manejo Clínico

Faz parte das iniciativas Disponibilizar Conteúdos Offline

Contexto:
Muitos profissionais do interior não tem acesso à internet todo o tempo e há a hipótese de que ter os conteúdos offline para download facilite seu acesso ao manejo. O objetivo é permitir que o usuario faça donwload de uma versão no seu celular para ter disponível e poder inclusive encaminhar para outras pessoas.

Fora de escopo:
Permitir visualização do Manejo Clínico offline DENTRO DO APP

Validar com UX como disponibilizaremos a ação de "salvar em pdf"

Critério de Aceite:
Dado que visualizo o Manejo Clínico
Quando clico no Manejo
Tenho a opção "Salvar em PDF"

Dado que salvo em PDF
Quando abro o arquivo
Tenho o Manejo Clínico disponível no meu dispositivo.

**Comment by caetanooliveira** [comment]
@matheuscpl quando puder adicionar aqui a parte do salvar em PDF, fica pronto.

**Comment by matheuscpl** [comment]
O botão para a funcionalidade de 'salvar em pdf' ficará logo abaixo ao título do Manejo (assim como a função de compartilhar presente nos artigos)

![Screenshot_51](https://user-images.githubusercontent.com/64148308/82566706-b258a980-9b52-11ea-8889-608cede93443.png)

**Comment by ItaloRod** [comment]
@matheuscpl  Você poderia me enviar o PDF que será anexado?

**Comment by matheuscpl** [comment]
Link do PDF no site coronavirus: https://coronavirus.ceara.gov.br/wp-content/uploads/2020/05/11.05-Manejo-Cl%C3%ADnico-Mobile-1.pdf

Arquivo: 
[11.05-Manejo-Clínico-Mobile-1.pdf](https://github.com/EscolaDeSaudePublica/isus-app/files/4668246/11.05-Manejo-Clinico-Mobile-1.pdf)
