### ISSUE TITLE
Permitir usuário que dê feedback ao iSUS

### ISSUE THREAD

**Issue by caetanooliveira** [EscolaDeSaudePublica/isus-app#98]
Objetivo:
Permitir usuário que dê sugestões e/ou suporte ao aplicativo

Contexto:
Ainda não há um campo para dar suporte ao usuário em seu uso e receber feedbacks mais frequentes no app. Essa opção deve ser incluída no menu lateral. Todos os campos são obrigatórios.

Escopo: 
- Desenvolver tela de suporte com campos:
    - Email
    - Tipo de feedback
    - Texto 

Nota:
Ver telas no figma
Em situação inicial o botão enviar está cinza e inativo
O radar button está com sugestão selecionado

Fora de Escopo:
- Anexar imagem
- pop up pro usuário

Alcance:
Sistemas: Android e IOS
Menus lateral e tela de Feedback

Critério de Aceite: 
Dado que eu entre no app iSUS
Quando clico no menu lateral
Posso ver e clicar em sugestão e suporte.

Dado que estou em Sugestão e Suporte
Quando eu decido a categoria: 'sugestão' 
e que escrevo um feedback: 'manejo clínico poderia ser também impresso' 
com meu email 'coliveira@thoughtworks.com' consigo apertar “enviar”
surge uma snack bar com mensagem de sucesso.

Dado que abro a caixa de entrada do feedback.isus@esp.ce.gov.br 
Ver categoria: 'sugestão' 
Posso ler o feedback: 'manejo clínico poderia ser também impresso' 
do usuário: 'coliveira@thoughtworks.com'

Dado que o usuário não preencheu algum dos três campos
Quando tenta clicar em enviar
O botão está cinza 
e surge um snackbar com a mensagem de que falta preencher um campo obrigatório.

Dado que o usuário preencheu os 3 campos
Quando o botão
Ele está verde.

**Comment by matheuscpl** [comment]
Como deve ser a interface do feedback:
![FEEDBACK](https://user-images.githubusercontent.com/64148308/82672236-7ab33580-9c16-11ea-9846-28d617547fde.png)

Importante olhar o figma pra alinhar sobre o comportamento dos feedbacks: https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/mockup?node-id=0%3A1

Qlqr dúvida me chama

**Comment by ItaloRod** [comment]
@victorMagalhaesPacheco  Poderia colocar a URL de acesso da API da do feedback?

**Comment by victorMagalhaesPacheco** [comment]
@mauricioholanda1 

Endpoint: https://apiisus.inova.esp.br/api/feedback
Method HTTP: POST
Dados obrigatórios: categoria, email, texto
